#!/bin/bash
# R268 — build needleji: (24) EKIPA — STANJE EKIPE PDF (team-tab — FRESH
# /api/users, route NIČ; mini-vrstica state-oka; legenda pariteta) + R267/
# R266/R265/R264/R263/R262/…/R227 regresije (parent: r267-build-needles.sh viri).
set -u
cd /home/z/my-project
OUT=/tmp/r268-build-chunks
mkdir -p "$OUT" && rm -f "$OUT"/*.js 2>/dev/null

find .next/static/chunks -name '*.js' -type f | while read -r f; do
  cp "$f" "$OUT/$(echo "$f" | md5sum | cut -c1-12)-$(basename "$f")"
done
echo "  čankov: $(ls "$OUT"/*.js 2>/dev/null | wc -l)"

FAIL=0
need_static() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "OK   : $2"; else echo "MISS : $2  (needle: $1)"; FAIL=1; fi
}
must_miss() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "HIT  : $2  (needle: $1 — NE SME BITI!)"; FAIL=1; else echo "OK   : $2 (odsoten)"; fi
}

echo "--- R268 ekipa-stanje PDF (klient) ---"
need_static "Izvozi pregled stanja ekipe kot PDF" "R268 pill aria"
need_static "Pregled stanja ekipe kot pravi PDF — statusi računov, vloge, življenjski cikl (celotna ekipa)" "R268 pill title"
need_static "EKIPA — STANJE EKIPE" "R268 PDF glava"
need_static "Pregled stanja ekipe prenešen v PDF" "R268 toast title"
need_static "Ni vpisanih članov ekipe" "R268 fail-closed toast"
need_static "Pregled stanja se izvozi, ko je vpisan prvi član ekipe." "R268 fail-closed toast opis"
need_static "Ekipa-stanje-" "R268 filename prefix"
need_static "ekipaStanjePregled" "R268 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "clanBeseda" "R268 sklanjatev EN VIR (toast + sklep + mini)"
need_static "GET /api/users → HTTP" "R268 FRESH fetch ISTEGA endpointa (R244–R267 precedens)"
need_static "Odgovora /api/users ni mogoče prebrati" "R268 fail-verbose DTO pruning"
need_static "manjkajoč id v odgovoru API-ja" "R268 DTO pruning identiteta"
need_static "manjkajoč lifecycle v odgovoru API-ja" "R268 DTO pruning lifecycle"
need_static "Ekipa (viden seznam):" "R268 F2 mini-vrstica (state-oka)"
need_static "Povabilo poteklo" "R268 KPI akcija (RED)"
need_static "Zaklenjenih" "R268 KPI akcija (RED)"
need_static "Čaka aktivacijo" "R268 KPI čakanje (AMBER)"
need_static "(akcija — povabila v zraku)" "R268 sklep akcija čakanja"
need_static "(akcija — pošlji novo aktivacijsko povezavo)" "R268 sklep akcija potečenih"
need_static "(akcija — varnostni pregled)" "R268 sklep akcija zaklepov"
need_static "(zgodovinska cona — offboarding zaključen)" "R268 sklep zgodovinska cona"
need_static "(referenčni pregled — celotna ekipa, tudi deaktivirani računi)" "R268 sklep resnica"
need_static "vir = /api/users (resnica pravic users.read)" "R268 sklep vir"
need_static "PDF = celotna ekipa (trenutna resnica ob kliku — FRESH /api/users, ne zastarel state)" "R268 legenda pill pariteta"
echo "--- R267 ponudbe-spomniki PDF (regresija — R267 ŽIVO na produ dokazan) ---"
need_static "Izvozi pregled spomnikov ponudb kot PDF" "R267 pill aria"
need_static "PONUDBE — SPOMNIŠKI PREGLED" "R267 PDF glava"
need_static "Ni vpisanih ponudb" "R267 fail-closed toast"
need_static "ponudbeSpomnikiPregled" "R267 ENA izpeljava"
need_static "GET /api/projects → HTTP" "R267 FRESH fetch ISTEGA endpointa"
need_static "Spomniki (viden seznam):" "R267 F2 mini-vrstica"
need_static "(referenčni pregled — VSE ponudbe, tudi podpisane)" "R267 sklep resnica"
need_static "vir = /api/projects (resnica vloge — polna resnica, ne samo viden seznam)" "R267 sklep vir"
need_static "PDF/CSV = VSE ponudbe (tudi podpisane — polna resnica) · prikazani seznam CSV = samo odprte prvih 12" "R267 legenda pill pariteta (R331 medija razlaga — ŠIRŠA resnica, ISTA pill družina)"
echo "--- R266 oprema-cikel PDF (regresija) ---"
need_static "Izvozi pregled življenjskega cikla opreme kot PDF" "R266 pill aria"
need_static "OPREMA — ŽIVLJENJSKI CIKL" "R266 PDF glava"
need_static "Ni vpisane opreme" "R266 fail-closed toast"
need_static "opremaCikelPregled" "R266 ENA izpeljava"
need_static "GET /api/equipment → HTTP" "R266 FRESH paginirani fetch"
need_static "nad mejo paginacije vira (MAX_OFFSET)" "R266 tiha rezina prepovedana"
need_static "Cikl (viden seznam):" "R266 F2 mini-vrstica"
need_static "(referenčni pregled — VSA oprema)" "R266 sklep resnica"
need_static "PDF = življenjski cikl VSE opreme (pregledi · kalibracije · statusi — polna resnica, ne samo viden seznam)" "R266 legenda pill pariteta"
echo "--- R265 projekti-termini PDF (regresija) ---"
need_static "Izvozi pregled projektov in terminov kot PDF" "R265 pill aria"
need_static "PROJEKTI — TERMINI PREGLED" "R265 PDF glava"
need_static "Ni vpisanih terminov" "R265 fail-closed toast"
need_static "projektiTerminiPregled" "R265 ENA izpeljava"
need_static "GET /api/schedules → HTTP" "R265 FRESH fetch ISTEGA endpointa"
need_static "od tega s planirano montažo" "R265 sklep resnica"
need_static "· Projekti = projekti × termini (pokritost po projektih)" "R265 legenda append"
echo "--- R264 dobavitelji-pozicija PDF (regresija) ---"
need_static "Izvozi pozicijo dobaviteljev kot PDF" "R264 pill aria"
need_static "DOBAVITELJI — POZICIJA CEN" "R264 PDF glava"
need_static "Ni vpisanih cen" "R264 fail-closed toast"
need_static "dobaviteljiPozicijaCen" "R264 ENA izpeljava"
need_static "· Pozicija = dobavitelji × najnižja per artikel · Brez alternative = samo ena ponudba" "R264 legenda append"
echo "--- R263 stranke-pokritost PDF (regresija) ---"
need_static "Izvozi pokritost opomnikov kot PDF" "R263 pill aria"
need_static "STRANKE — OPOMNIŠKA POKRITOST" "R263 PDF glava"
need_static "Pokritost opomnikov:" "R263 F2 mini-vrstica"
need_static "· Pokritost = stranke × opomnikStatus (slepe pike = brez datuma)" "R263 legenda append"
echo "--- R262/R261/R260/R259/R258/R257/R256/R255 + starejše regresije ---"
need_static "Izvozi pokritost zaloge in osnutkov kot PDF" "R262 pill aria"
need_static "ZALOGA — OSNUTEK POKRITOST" "R262 PDF glava"
need_static "Pokritost osnutka:" "R262 F2 mini-vrstica"
need_static "Izvozi račune po projektih kot PDF" "R261 pill aria"
need_static "RAČUNI PO PROJEKTIH" "R261 PDF glava"
need_static "\"Najhitrejši rok\",\"Največji popust\"" "R260 CSV glava (minified)"
need_static "children:\"najhitrejši rok\"" "R260 žig najhitrejši rok"
need_static "· CSV nosi segmentacijo (najhitrejši rok · največji popust)" "R260 legenda append"
need_static "Povprečni rok" "R259 KPI 4 label"
need_static "Izvozi dobičkonosnost projektov kot PDF" "R258 pill aria"
need_static "DOBIČKONOST PO PROJEKTIH" "R258 PDF glava"
need_static "Izvozi naročila kot PDF" "R257 pill aria"
need_static "NAROČILA — PREGLED" "R257 PDF glava"
need_static "Izvozi tedenski pregled montaž kot PDF" "R256 pill aria"
need_static "TEDENSKI VOZNI RED MONTAŽ" "R256 PDF glava"
need_static "Izvozi vozni red montaž kot PDF" "R255 pill aria"
need_static "VOZNI RED MONTAŽ" "R255 PDF glava"
need_static "Ni vidnih terminov montaže" "R255 fail-closed toast"
need_static "to-roksal-navy-soft" "R255 navy-soft žeton"
need_static "Izvozi koledar pregledov kot PDF" "R253 pill aria"
need_static "Izvozi potekle opomnike kot PDF" "R252 bulk pill aria"
need_static "Izvozi prihodke kot PDF" "R250 pill aria"
need_static "Moja vloga in dovoljenja" "R240 meni + dialog"
need_static "CENIK MATERIALA" "R244 PDF glava"
need_static "Brez dobavitelja (" "R227 žig aria"
must_miss "to-[#2a3f5f]" "must_miss to-[#2a3f5f]"
must_miss "accent-[#f59e0b]" "must_miss accent-[#f59e0b]"
must_miss "bg-[#f7f9ff]" "must_miss bg-[#f7f9ff]"
echo "NEEDLE FAIL=$FAIL (R268 ×24 novih + R267 ×9 + R266 ×9 + R265 ×7 + regresije)"
exit $FAIL
