#!/bin/bash
# R271 — build needleji: (26) ZAPISNIK — STANJE PRED PREDAJO PDF (punch-list —
# FRESH /api/punch?projectId, route NIČ; mini-vrstica state-oka; legenda
# pariteta; EN VIR PUNCH_STATUS_LABELS R158) + R270/R269/R268/R267/R266/R265/
# R264/R263/R262/…/R227 regresije (parent: r270-build-needles.sh viri).
# AWK STRUKTURNA PREVERBA (r270 lekcija 2 needleji-v-loopu → lažno zeleno).
set -u
cd /home/z/my-project
OUT=/tmp/r271-build-chunks
mkdir -p "$OUT" && rm -f "$OUT"/*.js 2>/dev/null

# --- AWK strukturna preverba: needle-klici ZNOTRAJ while/find-loop telesa ALI
# PRED need_static()/must_miss() definicijo = lažno zeleno. Oba števca = 0. ---
STRUCT=$(awk '
  /^need_static\(\)/      { infn=1; needdef=1; next }
  /^must_miss\(\)/        { infn=1; next }
  infn && /^\}/           { infn=0; next }
  infn                    { next }
  infn==0 && /^find /     { loop=1; next }
  infn==0 && loop==1 && /^done$/ { loop=0; next }
  infn==0 && loop==1 && (/^need_static / || /^must_miss /) { c1++; next }
  infn==0 && !needdef && (/^need_static / || /^must_miss /) { c2++; next }
  END { print (c1+0) "/" (c2+0) }
' "$0")
echo "=== Z-STRUCT: needleji v loopu / pred definicijo = $STRUCT (mora biti 0/0) ==="
[ "$STRUCT" = "0/0" ] || { echo "STRUKTURNA NAPAKA — abort"; exit 1; }

find .next/static/chunks -name '*.js' -type f | while read -r f; do
  cp "$f" "$OUT/$(echo "$f" | md5sum | cut -c1-12)-$(basename "$f")"
done
echo "  čankov: $(ls "$OUT"/*.js 2>/dev/null | wc -l)"

FAIL=0
need_static() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "OK   : $2"; else echo "MISS : $2  (needle: $1)"; FAIL=1; fi
}
must_miss() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "HIT  : $2  (needle: $1 — NE SME BITI!)"; FAIL=1; else echo "OK   : $2 (odsoten)"; fi
}
echo "--- R271 zapisnik-stanje PDF (klient — NOVO) ---"
need_static "Izvozi pregled stanja zapisnika kot PDF" "R271 pill aria"
need_static "Stanje zapisnika kot pravi PDF — VSE točke zapisnika (tudi rešene)" "R271 pill title"
need_static "ZAPISNIK — STANJE PRED PREDAJO" "R271 PDF glava"
need_static "Stanje zapisnika prenešeno v PDF" "R271 toast title"
need_static "Ni točk prejemnega zapisnika" "R271 fail-closed toast"
need_static "Stanje zapisnika se izvozi, ko je vpisana prva točka projekta." "R271 fail-closed toast opis"
need_static "Zapisnik-stanje-" "R271 filename prefix"
need_static "punchZapisnikPregled" "R271 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "tockaBeseda" "R271 sklanjatev (toast + mini)"
need_static "PUNCH_STATUS_LABELS" "R271 STATUS EN VIR IMPORT R158 (NI zasegane kopije)"
need_static "GET /api/punch → HTTP" "R271 FRESH fetch ISTEGA endpointa (R244–R270 precedens)"
need_static "Odgovora /api/punch ni mogoče prebrati" "R271 fail-verbose DTO pruning"
need_static "manjkajoč createdAt v odgovoru API-ja" "R271 DTO pruning createdAt"
need_static "Zapisnik (viden seznam):" "R271 F2 mini-vrstica (state-oka)"
need_static "Napak" "R271 KPI akcija (RED)"
need_static "Odprtih" "R271 KPI akcija (AMBER)"
need_static "Rešenost" "R271 KPI Σ (rešenih/vseh %)"
need_static "(akcija — predaja ne more potekti z odprto napako)" "R271 sklep akcija napak"
need_static "(akcija — čaka rešitev)" "R271 sklep akcija odprtih"
need_static "(Σ rešenih / vseh točk)" "R271 sklep rešenost resnica"
need_static "statusi = ISTA besedila kot CSV izvoz (PUNCH_STATUS_LABELS EN VIR)" "R271 sklep EN VIR resnica"
need_static "(referenčni pregled — VSE točke zapisnika, tudi rešene)" "R271 sklep resnica"
need_static "vir = /api/punch?projectId (resnica dostopa do projekta)" "R271 sklep vir"
need_static "PDF = VSE točke zapisnika (tudi rešene — polna resnica, ne samo viden seznam)" "R271 legenda pill pariteta"
need_static "Ni izbranega projekta" "R271 gate toast (podatek-scope)"

echo "--- R270 inventura-pregled PDF (regresija — R270 ŽIVO na produ dokazan) ---"
need_static "Izvozi inventurni pregled premoženja kot PDF" "R270 pill aria"
need_static "Inventurni pregled premoženja kot pravi PDF — VSA zalogovna premoženja (FRESH ob kliku)" "R270 pill title"
need_static "INVENTURA — PREMOŽENJSKI PREGLED" "R270 PDF glava"
need_static "celotno skladišče — VSA premoženja" "R270 glava podnaslov"
need_static "Inventurni pregled premoženja prenešen v PDF" "R270 toast title"
need_static "Ni vpisanih artiklov" "R270 fail-closed toast"
need_static "Inventurni pregled se izvozi, ko je vpisan prvi artikel zaloge." "R270 fail-closed toast opis"
need_static "Inventura-pregled-" "R270 filename prefix"
need_static "inventuraPregled" "R270 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "artikelBeseda" "R270 sklanjatev (toast + mini)"
need_static "kolicinaNiz" "R270 FORMAT EN VIR IMPORT R262 (NI zasegane kopije)"
need_static "GET /api/inventory → HTTP" "R270 FRESH fetch ISTEGA endpointa (R244–R269 precedens)"
need_static "Odgovora /api/inventory ni mogoče prebrati" "R270 fail-verbose DTO pruning"
need_static "premiki (_count.movements) morajo biti ne-negativno celo število" "R270 DTO pruning premiki strict (R227 strogost)"
need_static "Inventura (viden seznam):" "R270 F2 mini-vrstica (state-oka)"
need_static "Pod minimumom" "R270 KPI akcija (RED)"
need_static "Največji manjka" "R270 KPI 5 (največji deficit + enota)"
need_static "(akcija — naroči pred naslednjo porabo)" "R270 sklep akcija pod-minimumom"
need_static "(točno na meji — naslednja poraba pusti pod)" "R270 sklep pozornost na-meji"
need_static "(zdrava zaloga)" "R270 sklep zdrava cona"
need_static "nizka zaloga (≤ minimum — čip zaloge)" "R270 sklep R219 čip pariteta"
need_static "(vsi zabeleženi premiki — obrat skozi skladišče" "R270 sklep obrat resnica"
need_static "iskreno nič" "R270 sklep brez-premikov poimenovana veja"
need_static "(referenčni pregled — VSA zalogovna premoženja, tudi artikli brez premikov)" "R270 sklep resnica"
need_static "vir = /api/inventory (resnica zaloge — FRESH ob kliku, ne viden seznam filtrov)" "R270 sklep vir"
need_static "PDF = VSA zalogovna premoženja (tudi artikli brez premikov — polna resnica, ne samo viden seznam filtrov)" "R270 legenda pill pariteta"
echo "--- R269 meritve-teren PDF (regresija) ---"
need_static "Izvozi terenski pregled meritev kot PDF" "R269 pill aria"
need_static "Terenski pregled meritev kot pravi PDF — VSE meritve projekta (tudi arhivirane)" "R269 pill title"
need_static "MERITVE — TERENSKI PREGLED" "R269 PDF glava"
need_static "Terenski pregled meritev prenešen v PDF" "R269 toast title"
need_static "Ni vpisanih meritev" "R269 fail-closed toast"
need_static "Terenski pregled se izvozi, ko je vpisana prva meritev projekta." "R269 fail-closed toast opis"
need_static "Meritve-teren-" "R269 filename prefix"
need_static "meritevTerenPregled" "R269 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "osnutekBeseda" "R269 sklanjatev žeton (mini)"
need_static "meritvePovzetekBeseda" "R269 sklanjatev EN VIR R203 (toast + mini)"
need_static "GET /api/measurements → HTTP" "R269 FRESH fetch ISTEGA endpointa (R244–R268 precedens)"
need_static "arMetadata ni razumljen kot JSON objekt (pokvaren vir)" "R269 DTO pruning arMetadata fail-verbose"
need_static "Meritve (viden seznam):" "R269 F2 mini-vrstica (state-oka)"
need_static "(akcija — pregled in potrditev)" "R269 sklep akcija osnutkov"
need_static "(pripravljeno za pripravo izdelave)" "R269 sklep resnica potrjenih"
need_static "(referenčni pregled — VSE meritve projekta, tudi arhivirane)" "R269 sklep resnica"
need_static "vir = /api/measurements?projectId (resnica dostopa do projekta)" "R269 sklep vir"
need_static "PDF = VSE meritve projekta (tudi arhivirane — polna resnica, ne samo viden seznam filtrov)" "R269 legenda pill pariteta"
echo "--- R268 ekipa-stanje PDF (regresija) ---"
need_static "Izvozi pregled stanja ekipe kot PDF" "R268 pill aria"
need_static "EKIPA — STANJE EKIPE" "R268 PDF glava"
need_static "Ni vpisanih članov ekipe" "R268 fail-closed toast"
need_static "Pregled stanja se izvozi, ko je vpisan prvi član ekipe." "R268 fail-closed toast opis"
need_static "Ekipa-stanje-" "R268 filename prefix"
need_static "ekipaStanjePregled" "R268 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "clanBeseda" "R268 sklanjatev EN VIR (toast + sklep + mini)"
need_static "GET /api/users → HTTP" "R268 FRESH fetch ISTEGA endpointa (R244–R267 precedens)"
need_static "manjkajoč lifecycle v odgovoru API-ja" "R268 DTO pruning lifecycle"
need_static "Ekipa (viden seznam):" "R268 F2 mini-vrstica (state-oka)"
need_static "(akcija — povabila v zraku)" "R268 sklep akcija čakanja"
need_static "(akcija — pošlji novo aktivacijsko povezavo)" "R268 sklep akcija potečenih"
need_static "(akcija — varnostni pregled)" "R268 sklep akcija zaklepov"
need_static "(zgodovinska cona — offboarding zaključen)" "R268 sklep zgodovinska cona"
need_static "(referenčni pregled — celotna ekipa, tudi deaktivirani računi)" "R268 sklep resnica"
need_static "vir = /api/users (resnica pravic users.read)" "R268 sklep vir"
need_static "PDF = celotna ekipa (trenutna resnica ob kliku — FRESH /api/users, ne zastarel state)" "R268 legenda pill pariteta"
echo "--- R267 ponudbe-spomniki PDF (regresija) ---"
need_static "Izvozi pregled spomnikov ponudb kot PDF" "R267 pill aria"
need_static "PONUDBE — SPOMNIŠKI PREGLED" "R267 PDF glava"
need_static "Ni vpisanih ponudb" "R267 fail-closed toast"
need_static "ponudbeSpomnikiPregled" "R267 ENA izpeljava"
need_static "GET /api/projects → HTTP" "R267 FRESH fetch ISTEGA endpointa"
need_static "Spomniki (viden seznam):" "R267 F2 mini-vrstica"
need_static "(referenčni pregled — VSE ponudbe, tudi podpisane)" "R267 sklep resnica"
need_static "vir = /api/projects (resnica vloge — polna resnica, ne samo viden seznam)" "R267 sklep vir"
need_static "PDF/CSV = VSE ponudbe (tudi podpisane — polna resnica) · prikazani seznam CSV = samo odprte prvih 12" "R267 legenda pill pariteta (R331 medija razlaga — ŠIRŠA resnica, ISTA pill družina)"
echo "--- R266 oprema-cikel PDF (regresija) ---"
need_static "Izvozi pregled življenjskega cikla opreme kot PDF" "R266 pill aria"
need_static "OPREMA — ŽIVLJENJSKI CIKL" "R266 PDF glava"
need_static "Ni vpisane opreme" "R266 fail-closed toast"
need_static "opremaCikelPregled" "R266 ENA izpeljava"
need_static "GET /api/equipment → HTTP" "R266 FRESH paginirani fetch"
need_static "nad mejo paginacije vira (MAX_OFFSET)" "R266 tiha rezina prepovedana"
need_static "Cikl (viden seznam):" "R266 F2 mini-vrstica"
need_static "(referenčni pregled — VSA oprema)" "R266 sklep resnica"
need_static "PDF = življenjski cikl VSE opreme (pregledi · kalibracije · statusi — polna resnica, ne samo viden seznam)" "R266 legenda pill pariteta"
echo "--- R265 projekti-termini PDF (regresija) ---"
need_static "Izvozi pregled projektov in terminov kot PDF" "R265 pill aria"
need_static "PROJEKTI — TERMINI PREGLED" "R265 PDF glava"
need_static "Ni vpisanih terminov" "R265 fail-closed toast"
need_static "projektiTerminiPregled" "R265 ENA izpeljava"
need_static "GET /api/schedules → HTTP" "R265 FRESH fetch ISTEGA endpointa"
need_static "od tega s planirano montažo" "R265 sklep resnica"
need_static "· Projekti = projekti × termini (pokritost po projektih)" "R265 legenda append"
echo "--- R264 dobavitelji-pozicija PDF (regresija) ---"
need_static "Izvozi pozicijo dobaviteljev kot PDF" "R264 pill aria"
need_static "DOBAVITELJI — POZICIJA CEN" "R264 PDF glava"
need_static "Ni vpisanih cen" "R264 fail-closed toast"
need_static "dobaviteljiPozicijaCen" "R264 ENA izpeljava"
need_static "· Pozicija = dobavitelji × najnižja per artikel · Brez alternative = samo ena ponudba" "R264 legenda append"
echo "--- R263 stranke-pokritost PDF (regresija) ---"
need_static "Izvozi pokritost opomnikov kot PDF" "R263 pill aria"
need_static "STRANKE — OPOMNIŠKA POKRITOST" "R263 PDF glava"
need_static "Pokritost opomnikov:" "R263 F2 mini-vrstica"
need_static "· Pokritost = stranke × opomnikStatus (slepe pike = brez datuma)" "R263 legenda append"
echo "--- R262/R261/R260/R259/R258/R257/R256/R255 + starejše regresije ---"
need_static "Izvozi pokritost zaloge in osnutkov kot PDF" "R262 pill aria"
need_static "ZALOGA — OSNUTEK POKRITOST" "R262 PDF glava"
need_static "Pokritost osnutka:" "R262 F2 mini-vrstica"
need_static "Izvozi račune po projektih kot PDF" "R261 pill aria"
need_static "RAČUNI PO PROJEKTIH" "R261 PDF glava"
need_static "\"Najhitrejši rok\",\"Največji popust\"" "R260 CSV glava (minified)"
need_static "children:\"najhitrejši rok\"" "R260 žig najhitrejši rok"
need_static "· CSV nosi segmentacijo (najhitrejši rok · največji popust)" "R260 legenda append"
need_static "Povprečni rok" "R259 KPI 4 label"
need_static "Izvozi dobičkonosnost projektov kot PDF" "R258 pill aria"
need_static "DOBIČKONOST PO PROJEKTIH" "R258 PDF glava"
need_static "Izvozi naročila kot PDF" "R257 pill aria"
need_static "NAROČILA — PREGLED" "R257 PDF glava"
need_static "Izvozi tedenski pregled montaž kot PDF" "R256 pill aria"
need_static "TEDENSKI VOZNI RED MONTAŽ" "R256 PDF glava"
need_static "Izvozi vozni red montaž kot PDF" "R255 pill aria"
need_static "VOZNI RED MONTAŽ" "R255 PDF glava"
need_static "Ni vidnih terminov montaže" "R255 fail-closed toast"
need_static "to-roksal-navy-soft" "R255 navy-soft žeton"
need_static "Izvozi koledar pregledov kot PDF" "R253 pill aria"
need_static "Izvozi potekle opomnike kot PDF" "R252 bulk pill aria"
need_static "Izvozi prihodke kot PDF" "R250 pill aria"
need_static "Moja vloga in dovoljenja" "R240 meni + dialog"
need_static "CENIK MATERIALA" "R244 PDF glava"
need_static "Brez dobavitelja (" "R227 žig aria"
must_miss "to-[#2a3f5f]" "must_miss to-[#2a3f5f]"
must_miss "accent-[#f59e0b]" "must_miss accent-[#f59e0b]"
must_miss "bg-[#f7f9ff]" "must_miss bg-[#f7f9ff]"
echo "NEEDLE FAIL=$FAIL (R271 ×26 novih + R270 ×25 + R269 ×18 + R268 ×17 + R267 ×9 + R266 ×9 + R265 ×7 + R264 ×5 + R263 ×4 + regresije)"
exit $FAIL
