#!/bin/bash
# R282 — build needleji: (1) SEGMENT PRODUKT REFERENCE (issue #16 §3 —
# profile/color/material/handrail/posts/configuration aditivna v1, U1–U6:
# matrika U1–U6 + razmejitev kontrakt vs. business; verzija ostane 1);
# (2) MANDATORY STIL — tip badge title ×10 + kot badge title (hover parity);
# (3) R279/R278/R277/… regresije (parent: r279-build-needles.sh).
# + R277/R276/R275/R274/R273/…/R227 regresije (parent: r278-build-needles.sh).
# AWK STRUKTURNA PREVERBA (r270 lekcija 2 needleji-v-loopu → lažno zeleno).
set -u
cd /home/z/my-project
OUT=/tmp/r282-build-chunks
mkdir -p "$OUT" && rm -f "$OUT"/*.js 2>/dev/null

# --- AWK strukturna preverba: needle-klici ZNOTRAJ while/find-loop telesa ALI
# PRED need_static()/must_miss() definicijo = lažno zeleno. Oba števca = 0. ---
STRUCT=$(awk '
  /^need_static\(\)/      { infn=1; needdef=1; next }
  /^must_miss\(\)/        { infn=1; next }
  infn && /^\}/           { infn=0; next }
  infn                    { next }
  infn==0 && /^find /     { loop=1; next }
  infn==0 && loop==1 && /^done$/ { loop=0; next }
  infn==0 && loop==1 && (/^need_static / || /^must_miss /) { c1++; next }
  infn==0 && !needdef && (/^need_static / || /^must_miss /) { c2++; next }
  END { print (c1+0) "/" (c2+0) }
' "$0")
echo "=== Z-STRUCT: needleji v loopu / pred definicijo = $STRUCT (mora biti 0/0) ==="
[ "$STRUCT" = "0/0" ] || { echo "STRUKTURNA NAPAKA — abort"; exit 1; }

find .next/static/chunks .next/server -name '*.js' -type f | while read -r f; do
  cp "$f" "$OUT/$(echo "$f" | md5sum | cut -c1-12)-$(basename "$f")"
done
echo "  čankov: $(ls "$OUT"/*.js 2>/dev/null | wc -l)"

FAIL=0
need_static() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "OK   : $2"; else echo "MISS : $2  (needle: $1)"; FAIL=1; fi
}
must_miss() {
  if grep -rqF -- "$1" "$OUT" 2>/dev/null; then echo "HIT  : $2 (needle: $1 — NE SME BITI!)"; FAIL=1; else echo "OK   : $2 (odsoten)"; fi
}
echo "--- R282 MANDATORY — F2 sync mini-vrstica + akcijski žig (issue #16 §10, V3) ---"
need_static "Sync (viden seznam): " "R282 mini-vrstica glava (števec sync metadata — EN VIR filteredMeasurements)"
need_static "sinhroniziranih · " "R282 mini segmenti (sinhroniziranih/čakajoči/konfliktov/napak)"
need_static "Konflikt — osveži bazo in ponovi sync" "R282 akcijski žig (konflikti > 0 — obstoječi /api/sync razreši)"
need_static "Sinhronizacijsko stanje vidnega seznama (issue #16 §10)" "R282 mini hover title (provenance — NI sync resnica)"
echo "--- R281 sync metadata (issue #16 §10 — kontrakt, server chunks, V1–V6) ---"
need_static "session-level sync blok opcijsko" "R281 matrika razširitev žig (izrečno — V1 aditivna v1)"
need_static "razmejitev provenance vs. protocol" "R281 V3 razmejitev žig (opazovano stanje klienta — NIKOLI sync resnica)"
need_static "V1–V6" "R281 matrika V-serija (izrečno)"
need_static "syncState" "R281 sync.syncState wire polje (V2 — zaprt besednjak čakalnega vrsta)"
need_static "baseRevision" "R281 sync.baseRevision wire polje (shema /api/sync — ENA resnica o mejah)"
need_static "syncRevision" "R281 sync.syncRevision wire polje (echo — nazadnje viden serverState)"
need_static "tombstone" "R281 sync.tombstone wire polje (V4 — false = izrecno NE grobnica)"
echo "--- R281 MANDATORY STIL — sync žig title ×4 + tombstone note (hover parity) ---"
need_static "Sinhronizacijsko stanje: Sinhronizirano" "R281 sync žig title SYNCED"
need_static "Sinhronizacijsko stanje: V čakalni vrsti" "R281 sync žig title PENDING"
need_static "Sinhronizacijsko stanje: Konflikt" "R281 sync žig title CONFLICT"
need_static "Sinhronizacijsko stanje: Napaka" "R281 sync žig title ERROR"
need_static "tombstone — grobnico potrdi /api/sync" "R281 tombstone note (title append — iskrena razlaga)"
need_static "Sync metadata (opazovano stanje klienta" "R281 TooltipContent (NI sync resnica — pariteta)"
echo "--- R280 produkt reference (issue #16 §3 — kontrakt, U1–U6) ---"
need_static "segments[].profile/color/material/handrail/posts/configuration" "R280 matrika razširitev žig (izrečno — U1 aditivna v1)"
need_static "razmejitev kontrakt vs. business" "R280 U3 razmejitev žig (provenance — NIKOLI business resnica)"
need_static "U1–U6" "R280 matrika U-serija (izrečno)"
echo "--- R280 MANDATORY STIL — tip badge title ×10 + kot badge title (hover parity) ---"
need_static "Vrsta meritve: Razdalja" "R280 tip badge title RAZDALJA"
need_static "Vrsta meritve: Višina" "R280 tip badge title VISINA"
need_static "Vrsta meritve: Kot — izmerjen kot v stopinjah" "R280 tip badge title KOT"
need_static "Vrsta meritve: Nagib" "R280 tip badge title NAGIB"
need_static "Vrsta meritve: Globina" "R280 tip badge title GLOBINA"
need_static "Vrsta meritve: Premer" "R280 tip badge title PREMER"
need_static "Vrsta meritve: Segment" "R280 tip badge title SEGMENT"
need_static "Vrsta meritve: Vogal" "R280 tip badge title KOT_VOGAL"
need_static "Vrsta meritve: Kot stopnice" "R280 tip badge title KOT_STOPNISCE"
need_static "Vrsta meritve: Stebriček/Palica" "R280 tip badge title STEBR"
need_static " se ne označuje — označujem samo odstopanja" "R280 kot badge title (odstopanja — verbatim; ° = 90\\xb0 v chunku)"
echo "--- R279 photo/GLB povezave (issue #16 §9 — kontrakt, regresija) ---"
need_static "photoIds" "R279 segments[].photoIds wire polje (T1 — aditivna v1)"
need_static "modelIds" "R279 segments[].modelIds wire polje (T1 — aditivna v1)"
need_static "nič osirotelih referenc" "R279 superRefine fail-closed žig (T3 — referenčna integriteta)"
need_static "T1–T5" "R279 matrika razširitev žig (izrečno)"
echo "--- R279 MANDATORY STIL — segmentId Badge title (issue #16 §1) ---"
need_static "stabilen segmentId" "R279 Badge title (identiteta preživi re-anchor/offline/migracijo)"
echo "--- R278 start/end koordinati + per-segment quality (issue #16 §3 — regresija) ---"
need_static "startMm" "R278 segments[].startMm wire polje (Q1–Q6 — aditivna v1)"
need_static "endMm" "R278 segments[].endMm wire polje (Q1–Q6 — aditivna v1)"
need_static "Q1–Q6/S1–S6" "R278 matrika razširitev žig (Q+S serija izrečno — R277+R278)"
echo "--- R278 MANDATORY STIL — vir pill title ×3 (hover parity) ---"
need_static "Vir podatkov: Ročni vnos" "R278 vir pill title MANUAL (izpeljan na strežniku — klient ne more ponarejati)"
need_static "Vir podatkov: Foto-CV" "R278 vir pill title PHOTO_CV"
need_static "Vir podatkov: AR-Depth" "R278 vir pill title ARCORE_DEPTH"
echo "--- R277 segment kot (regresija — LIVE na produ potrdil r278-prod-qa) ---"
echo "--- R277 segment kot (issue #16 §3 — kontrakt, server chunks) ---"
need_static "angleDeg" "R277 segments[].angleDeg wire polje (P1 — aditivna v1)"
need_static "LOCAL_NORMALIZED" "R277 P2 frame referenca (azimut od +X — LOCAL_NORMALIZED ostaja canonical)"
need_static "AR_CONTRACT_VALIDACIJA" "R277 P5 fail-closed koda (null/NaN/Infinity/tipografija → zavrnitev)"
echo "--- R277 terenski PDF verzija+vir (issue #16 §6 — 10 stolpcev) ---"
need_static "\"Verzija\",\"Vir\"" "R277 PDF 10-stolpčna glava (minified — WYSIWYG)"
need_static "verzija = veriga korekcij" "R277 sklep — veriga poimenovana"
need_static "nastalo pred verzioniranjem" "R277 legacy '—' iskren odpad (sklep)"
need_static "Ročni vnos/Foto-CV/AR-Depth" "R277 sklep vir poimenovane oznake"
need_static "vir mora biti eden izmed " "R277 fail-closed neznani vir (TypeError — templ. stat. del)"
need_static "verzija mora biti pozitivno celo število ALI null" "R277 fail-closed pokvarjena verzija (tab preverba)"
echo "--- R276 zgodovina verzij meritev (regresija — ŽIVO na produ dokazan) ---"
need_static "NI PONOVNO IZRAČUNANO — dokumenti/BOM ustvarjeni pred to verzijo ostajajo na predhodni meri; ponovni izračun je zgoda lastnika" "R276 O7 odvisniRezultati (IZREČNO iskren — nič lažnega recalculated)"
need_static "MEASUREMENT_VERSION" "R276 audit akcija (O6 — kaj se je spremenilo)"
need_static "Predhodna meritev ne obstaja" "R276 O4 fail-closed 404"
need_static "Predhodna meritev pripada drugemu projektu — verzija mora ostati znotraj istega projekta" "R276 O4 fail-closed 400 (veriga ne prečka projektov)"
need_static "Arhivirane meritve ni mogoče popraviti z novo verzijo" "R276 O4 fail-closed 409 (arhiv se ne popravlja postrani)"
need_static "Predhodnik že ima naslednika — verzija je enojna veriga brez razvejanja" "R276 O4 fork 409 (P2002 → čist 409, ZERO-MUTACIJA)"
need_static "Napaka pri branju zgodovine verzij" "R276 verzije GET 500 žig (fail-verbose)"
need_static "Zgodovina verzij — korekcije NE prepišejo obstoječih mer, dodajo novo verzijo" "R276 UI panel glava (WYSIWYG kanon)"
need_static "Popravljanje verzije: „" "R276 UI korekcijski pas (obrazec)"
need_static "Shranjevanje ustvari NOVO verzijo v" "R276 UI pas resnica (nova verzija, predhodnik ostane)"
need_static "Popravi — ustvari novo verzijo (obstoječa ostaja v zgodovini)" "R276 UI Popravi tooltip"
need_static "Shrani kot novo verzijo" "R276 UI gumb (korekcijski način)"
need_static "Aktivna verzija: ni (zadnja verzija je arhivirana — nikoli padec nazaj na starejšo)." "R276 UI O5 iskrena praznina"
need_static "Odvisni rezultati (BOM/dokumenti) nastali pred novejšo verzijo se NE izračunajo samodejno." "R276 UI O7 resnica (brez lažnega re-preračuna)"
need_static "Foto-CV" "R276 vir oznaka PHOTO_CV (unikatna žica — pariteta labels EN VIR)"
need_static "AR-Depth" "R276 vir oznaka ARCORE_DEPTH"
must_miss "JE PONOVNO IZRAČUNANO" "must_miss lažni re-preračun (O7 — NIKOLI recalculated: true)"
echo "--- R275 zlati fixture + mini razložljivost (regresija — ŽIVO na produ dokazan) ---"

need_static "Inventura (viden seznam) = kar uporabnik vidi po čipih/tipu; FRESH PDF = VSA zalogovna premoženja. pod minimumom = akcija naročila, na meji = pozor." "R275 inventura mini title (hover razložljivost)"
need_static "Vrednost (viden seznam) = ISTI izračun kot PDF KPI + toast (WYSIWYG). Σ — pomeni: nič artiklov nima trenutno veljavne cene — nič ni ocenjeno (brez demo cene)." "R275 vrednost mini title (Σ — iskrena praznina poimenovana)"
need_static "cursor-help" "R275 cursor-help na mini (hover signal)"
echo "--- R274 AR skupni kontrakt (issue #17 §A/§B/§D — NOVO, server chunks) ---"
need_static "ARCORE_DEPTH" "R274 source enum ARCORE_DEPTH (issue #17 B)"
need_static "PHOTO_CV" "R274 source enum PHOTO_CV (issue #17 B)"
need_static "LOCAL_NORMALIZED" "R274 canonical coordinate frame (issue #17 A)"
need_static "TWO_POINT_SCALE" "R274 kalibracijski model enum (issue #17 A)"
need_static "MARKER_PLATE" "R274 kalibracijski model MARKER_PLATE (issue #17 A)"
need_static "AR_CONTRACT_VERSION_UNSUPPORTED" "R274 žična koda nepodprte verzije (issue #17 D)"
need_static "AR_CONTRACT_VERZIJA_MANJKA" "R274 žična koda manjkajoče verzije (issue #17 D — contractVersion obvezen)"
need_static "AR_CONTRACT_VALIDACIJA" "R274 žična koda validacije (strict — neznana polja zavrnjena, D)"
need_static "Neveljaven AR skupni kontrakt" "R274 route 400 žig (B: napaka payload-a ne spremeni projekta)"
need_static "contractVersion" "R274 obvezno verzijo polje (D + sibling sync gate)"
echo "--- R274 sync-pogodbeni gate (sibling delo istega issue-ja — NOVO) ---"
need_static "Nepodprta pogodbena verzija" "R274s per-item zavrnitev neznane verzije (fail-closed)"
need_static "noben zapis ni bil uporabljen" "R274s per-item sporočilo — nič izgubljeno (minified-varen)"
echo "--- R273 zaloga-vrednost PDF (klient — NOVO) ---"
need_static "Izvozi pregled vrednosti zaloge kot PDF" "R273 pill aria"
need_static "Pregled vrednosti zaloge kot pravi PDF — VSA zalogovna premoženja s trenutno veljavnimi cenami (FRESH ob kliku)" "R273 pill title"
need_static "ZALOGA — PREMOŽENJSKA VREDNOST" "R273 PDF glava"
need_static "Pregled vrednosti zaloge prenešen v PDF" "R273 toast title"
need_static "Pregled vrednosti zaloge se izvozi, ko je vpisan prvi artikel zaloge." "R273 fail-closed toast opis"
need_static "Zaloga-vrednost-" "R273 filename prefix"
need_static "zalogaVrednostPregled" "R273 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "preveriVrednostArtikel" "R273 fail-closed preverba artikla"
need_static "preveriVrednostBest" "R273 fail-closed preverba best vnosa"
need_static "stevecCen (_count.prices) mora biti ne-negativno celo število" "R273 DTO pruning števec strict (R227 strogost)"
need_static "bestPrice mora biti končno ne-negativno število" "R273 DTO pruning best strict (R264 pariteta)"
need_static "bestPerMaterial" "R273 JOIN vir (API resnica)"
need_static "GET /api/material-prices → HTTP" "R273 FRESH fetch drugega vira"
need_static "best cena brez ujemajočega artikla" "R273 ORPHAN best fail-closed (R264 precedens)"
need_static "Vrednost (viden seznam):" "R273 F2 mini-vrstica (state-oka + bestCene)"
need_static "Artiklov" "R273 KPI 1 (NAVY)"
need_static "Σ vrednost" "R273 KPI 2 (NAVY, '—' pri zCeno 0)"
need_static "Največja" "R273 KPI 3 (NAVY, poimenovana)"
need_static "Pretečenih" "R273 KPI 4 (AMBER samo > 0)"
need_static "Brez cene" "R273 KPI 5 (AMBER samo > 0)"
need_static "(samo artikli z veljavno trenutno ceno — z ceno " "R273 sklep Σ resnica"
need_static "(vse vpisane cene pretečene — vpisati novo veljavno ceno)" "R273 sklep pretečena akcija (kondicionalna)"
need_static "(vrednost NI ocenjena — iskrena resnica)" "R273 sklep brez-cene resnica (kondicionalna)"
need_static "(samo trenutno veljavne cene — API resnica veljavnostDo null; pretečene NISO vključene)" "R273 SEMANTIČNA ODLOČITEV veljavnost (sklep EN VIR)"
need_static "(referenčni pregled — VSA zalogovna premoženja, tudi artikli brez veljavne cene)" "R273 sklep resnica"
need_static "vir = /api/inventory + /api/material-prices (resnica zaloge IN cen)" "R273 sklep dva vira"
need_static "PDF = polna denarna resnica skladišča (FRESH /api/inventory + /api/material-prices ob kliku — samo trenutno veljavne cene; ne zastarel state)" "R273 legenda pill pariteta"
echo "--- R272 nagibi-teren PDF (regresija — R272 ŽIVO na produ dokazan) ---"
need_static "Izvozi terenski pregled nagibov kot PDF" "R272 pill aria"
need_static "Terenski pregled nagibov kot pravi PDF — VSI nagibi projekta (tudi označeni neveljavni)" "R272 pill title"
need_static "NAGIBI — TERENSKI PREGLED" "R272 PDF glava"
need_static "Terenski pregled nagibov prenešen v PDF" "R272 toast title"
need_static "Ni vpisanih nagibov" "R272 fail-closed toast"
need_static "Terenski pregled nagibov se izvozi, ko je vpisan prvi odčitek projekta." "R272 fail-closed toast opis"
need_static "Nagibi-teren-" "R272 filename prefix"
need_static "nagibiTerenPregled" "R272 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "nagibBeseda" "R272 sklanjatev (toast + mini)"
need_static "smerLabel" "R272 SMER EN VIR IMPORT R157 (R272 EXPORT — R262 precedens)"
need_static "GET /api/slopes → HTTP" "R272 FRESH fetch ISTEGA endpointa (R244–R271 precedens)"
need_static "Odgovora /api/slopes ni mogoče prebrati" "R272 fail-verbose DTO pruning"
need_static "manjkajoč id v odgovoru API-ja" "R272 DTO pruning identiteta"
need_static "kotStopinje mora biti končno število" "R272 DTO pruning kot strict (CSV R157 pravila)"
need_static "Nagibi (viden seznam):" "R272 F2 mini-vrstica (state-oka)"
need_static "Največji kot" "R272 KPI obseg (NAVY)"
need_static "Povprečni kot" "R272 KPI Σ (NAVY)"
need_static "Neveljavnih" "R272 KPI DB resnica (AMBER samo > 0)"
need_static "(obseg odstopanja — absolutna vrednost)" "R272 sklep največji resnica"
need_static "(Σ |kot| / št. odčitkov)" "R272 sklep povprečni resnica"
need_static "(označeni sumljivi odčitki — DB resnica)" "R272 sklep kondicionalna neveljavni"
need_static "smer = ISTA preslikava kot CSV izvoz (smerLabel EN VIR" "R272 sklep EN VIR resnica"
need_static "(referenčni pregled — VSI nagibi projekta, tudi označeni neveljavni)" "R272 sklep resnica"
need_static "vir = /api/slopes?projectId (resnica dostopa do projekta)" "R272 sklep vir"
need_static "PDF = VSI nagibi projekta (tudi označeni neveljavni — polna resnica, ne samo viden seznam)" "R272 legenda pill pariteta"
need_static "Brez projekta" "R272 gate toast (podatek-scope)"
echo "--- R271 zapisnik-stanje PDF (regresija — R271 ŽIVO na produ dokazan) ---"
need_static "Izvozi pregled stanja zapisnika kot PDF" "R271 pill aria"
need_static "Stanje zapisnika kot pravi PDF — VSE točke zapisnika (tudi rešene)" "R271 pill title"
need_static "ZAPISNIK — STANJE PRED PREDAJO" "R271 PDF glava"
need_static "Stanje zapisnika prenešeno v PDF" "R271 toast title"
need_static "Ni točk prejemnega zapisnika" "R271 fail-closed toast"
need_static "Stanje zapisnika se izvozi, ko je vpisana prva točka projekta." "R271 fail-closed toast opis"
need_static "Zapisnik-stanje-" "R271 filename prefix"
need_static "punchZapisnikPregled" "R271 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "tockaBeseda" "R271 sklanjatev (toast + mini)"
need_static "PUNCH_STATUS_LABELS" "R271 STATUS EN VIR IMPORT R158 (NI zasegane kopije)"
need_static "GET /api/punch → HTTP" "R271 FRESH fetch ISTEGA endpointa (R244–R270 precedens)"
need_static "Odgovora /api/punch ni mogoče prebrati" "R271 fail-verbose DTO pruning"
need_static "manjkajoč createdAt v odgovoru API-ja" "R271 DTO pruning createdAt"
need_static "Zapisnik (viden seznam):" "R271 F2 mini-vrstica (state-oka)"
need_static "Napak" "R271 KPI akcija (RED)"
need_static "Odprtih" "R271 KPI akcija (AMBER)"
need_static "Rešenost" "R271 KPI Σ (rešenih/vseh %)"
need_static "(akcija — predaja ne more potekti z odprto napako)" "R271 sklep akcija napak"
need_static "(akcija — čaka rešitev)" "R271 sklep akcija odprtih"
need_static "(Σ rešenih / vseh točk)" "R271 sklep rešenost resnica"
need_static "statusi = ISTA besedila kot CSV izvoz (PUNCH_STATUS_LABELS EN VIR)" "R271 sklep EN VIR resnica"
need_static "(referenčni pregled — VSE točke zapisnika, tudi rešene)" "R271 sklep resnica"
need_static "vir = /api/punch?projectId (resnica dostopa do projekta)" "R271 sklep vir"
need_static "PDF = VSE točke zapisnika (tudi rešene — polna resnica, ne samo viden seznam)" "R271 legenda pill pariteta"
need_static "Ni izbranega projekta" "R271 gate toast (podatek-scope)"

echo "--- R270 inventura-pregled PDF (regresija — R270 ŽIVO na produ dokazan) ---"
need_static "Izvozi inventurni pregled premoženja kot PDF" "R270 pill aria"
need_static "Inventurni pregled premoženja kot pravi PDF — VSA zalogovna premoženja (FRESH ob kliku)" "R270 pill title"
need_static "INVENTURA — PREMOŽENJSKI PREGLED" "R270 PDF glava"
need_static "celotno skladišče — VSA premoženja" "R270 glava podnaslov"
need_static "Inventurni pregled premoženja prenešen v PDF" "R270 toast title"
need_static "Ni vpisanih artiklov" "R270 fail-closed toast"
need_static "Inventurni pregled se izvozi, ko je vpisan prvi artikel zaloge." "R270 fail-closed toast opis"
need_static "Inventura-pregled-" "R270 filename prefix"
need_static "inventuraPregled" "R270 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "artikelBeseda" "R270 sklanjatev (toast + mini)"
need_static "kolicinaNiz" "R270 FORMAT EN VIR IMPORT R262 (NI zasegane kopije)"
need_static "GET /api/inventory → HTTP" "R270 FRESH fetch ISTEGA endpointa (R244–R269 precedens)"
need_static "Odgovora /api/inventory ni mogoče prebrati" "R270 fail-verbose DTO pruning"
need_static "premiki (_count.movements) morajo biti ne-negativno celo število" "R270 DTO pruning premiki strict (R227 strogost)"
need_static "Inventura (viden seznam):" "R270 F2 mini-vrstica (state-oka)"
need_static "Pod minimumom" "R270 KPI akcija (RED)"
need_static "Največji manjka" "R270 KPI 5 (največji deficit + enota)"
need_static "(akcija — naroči pred naslednjo porabo)" "R270 sklep akcija pod-minimumom"
need_static "(točno na meji — naslednja poraba pusti pod)" "R270 sklep pozornost na-meji"
need_static "(zdrava zaloga)" "R270 sklep zdrava cona"
need_static "nizka zaloga (≤ minimum — čip zaloge)" "R270 sklep R219 čip pariteta"
need_static "(vsi zabeleženi premiki — obrat skozi skladišče" "R270 sklep obrat resnica"
need_static "iskreno nič" "R270 sklep brez-premikov poimenovana veja"
need_static "(referenčni pregled — VSA zalogovna premoženja, tudi artikli brez premikov)" "R270 sklep resnica"
need_static "vir = /api/inventory (resnica zaloge — FRESH ob kliku, ne viden seznam filtrov)" "R270 sklep vir"
need_static "PDF = VSA zalogovna premoženja (tudi artikli brez premikov — polna resnica, ne samo viden seznam filtrov)" "R270 legenda pill pariteta"
echo "--- R269 meritve-teren PDF (regresija) ---"
need_static "Izvozi terenski pregled meritev kot PDF" "R269 pill aria"
need_static "Terenski pregled meritev kot pravi PDF — VSE meritve projekta (tudi arhivirane)" "R269 pill title"
need_static "MERITVE — TERENSKI PREGLED" "R269 PDF glava"
need_static "Terenski pregled meritev prenešen v PDF" "R269 toast title"
need_static "Ni vpisanih meritev" "R269 fail-closed toast"
need_static "Terenski pregled se izvozi, ko je vpisana prva meritev projekta." "R269 fail-closed toast opis"
need_static "Meritve-teren-" "R269 filename prefix"
need_static "meritevTerenPregled" "R269 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "osnutekBeseda" "R269 sklanjatev žeton (mini)"
need_static "meritvePovzetekBeseda" "R269 sklanjatev EN VIR R203 (toast + mini)"
need_static "GET /api/measurements → HTTP" "R269 FRESH fetch ISTEGA endpointa (R244–R268 precedens)"
need_static "arMetadata ni razumljen kot JSON objekt (pokvaren vir)" "R269 DTO pruning arMetadata fail-verbose"
need_static "Meritve (viden seznam):" "R269 F2 mini-vrstica (state-oka)"
need_static "(akcija — pregled in potrditev)" "R269 sklep akcija osnutkov"
need_static "(pripravljeno za pripravo izdelave)" "R269 sklep resnica potrjenih"
need_static "(referenčni pregled — VSE meritve projekta, tudi arhivirane)" "R269 sklep resnica"
need_static "vir podatkov = /api/measurements?projectId (resnica dostopa do projekta)" "R269 sklep vir"
need_static "PDF = VSE meritve projekta (tudi arhivirane — polna resnica, ne samo viden seznam filtrov)" "R269 legenda pill pariteta"
echo "--- R268 ekipa-stanje PDF (regresija) ---"
need_static "Izvozi pregled stanja ekipe kot PDF" "R268 pill aria"
need_static "EKIPA — STANJE EKIPE" "R268 PDF glava"
need_static "Ni vpisanih članov ekipe" "R268 fail-closed toast"
need_static "Pregled stanja se izvozi, ko je vpisan prvi član ekipe." "R268 fail-closed toast opis"
need_static "Ekipa-stanje-" "R268 filename prefix"
need_static "ekipaStanjePregled" "R268 ENA izpeljava (KPI + tabela + sklep + toast + mini)"
need_static "clanBeseda" "R268 sklanjatev EN VIR (toast + sklep + mini)"
need_static "GET /api/users → HTTP" "R268 FRESH fetch ISTEGA endpointa (R244–R267 precedens)"
need_static "manjkajoč lifecycle v odgovoru API-ja" "R268 DTO pruning lifecycle"
need_static "Ekipa (viden seznam):" "R268 F2 mini-vrstica (state-oka)"
need_static "(akcija — povabila v zraku)" "R268 sklep akcija čakanja"
need_static "(akcija — pošlji novo aktivacijsko povezavo)" "R268 sklep akcija potečenih"
need_static "(akcija — varnostni pregled)" "R268 sklep akcija zaklepov"
need_static "(zgodovinska cona — offboarding zaključen)" "R268 sklep zgodovinska cona"
need_static "(referenčni pregled — celotna ekipa, tudi deaktivirani računi)" "R268 sklep resnica"
need_static "vir = /api/users (resnica pravic users.read)" "R268 sklep vir"
need_static "PDF = celotna ekipa (trenutna resnica ob kliku — FRESH /api/users, ne zastarel state)" "R268 legenda pill pariteta"
echo "--- R267 ponudbe-spomniki PDF (regresija) ---"
need_static "Izvozi pregled spomnikov ponudb kot PDF" "R267 pill aria"
need_static "PONUDBE — SPOMNIŠKI PREGLED" "R267 PDF glava"
need_static "Ni vpisanih ponudb" "R267 fail-closed toast"
need_static "ponudbeSpomnikiPregled" "R267 ENA izpeljava"
need_static "GET /api/projects → HTTP" "R267 FRESH fetch ISTEGA endpointa"
need_static "Spomniki (viden seznam):" "R267 F2 mini-vrstica"
need_static "(referenčni pregled — VSE ponudbe, tudi podpisane)" "R267 sklep resnica"
need_static "vir = /api/projects (resnica vloge — polna resnica, ne samo viden seznam)" "R267 sklep vir"
need_static "PDF/CSV = VSE ponudbe (tudi podpisane — polna resnica) · prikazani seznam CSV = samo odprte prvih 12" "R267 legenda pill pariteta (R331 medija razlaga — ŠIRŠA resnica, ISTA pill družina)"
echo "--- R266 oprema-cikel PDF (regresija) ---"
need_static "Izvozi pregled življenjskega cikla opreme kot PDF" "R266 pill aria"
need_static "OPREMA — ŽIVLJENJSKI CIKL" "R266 PDF glava"
need_static "Ni vpisane opreme" "R266 fail-closed toast"
need_static "opremaCikelPregled" "R266 ENA izpeljava"
need_static "GET /api/equipment → HTTP" "R266 FRESH paginirani fetch"
need_static "nad mejo paginacije vira (MAX_OFFSET)" "R266 tiha rezina prepovedana"
need_static "Cikl (viden seznam):" "R266 F2 mini-vrstica"
need_static "(referenčni pregled — VSA oprema)" "R266 sklep resnica"
need_static "PDF = življenjski cikl VSE opreme (pregledi · kalibracije · statusi — polna resnica, ne samo viden seznam)" "R266 legenda pill pariteta"
echo "--- R265 projekti-termini PDF (regresija) ---"
need_static "Izvozi pregled projektov in terminov kot PDF" "R265 pill aria"
need_static "PROJEKTI — TERMINI PREGLED" "R265 PDF glava"
need_static "Ni vpisanih terminov" "R265 fail-closed toast"
need_static "projektiTerminiPregled" "R265 ENA izpeljava"
need_static "GET /api/schedules → HTTP" "R265 FRESH fetch ISTEGA endpointa"
need_static "od tega s planirano montažo" "R265 sklep resnica"
need_static "· Projekti = projekti × termini (pokritost po projektih)" "R265 legenda append"
echo "--- R264 dobavitelji-pozicija PDF (regresija) ---"
need_static "Izvozi pozicijo dobaviteljev kot PDF" "R264 pill aria"
need_static "DOBAVITELJI — POZICIJA CEN" "R264 PDF glava"
need_static "Ni vpisanih cen" "R264 fail-closed toast"
need_static "dobaviteljiPozicijaCen" "R264 ENA izpeljava"
need_static "· Pozicija = dobavitelji × najnižja per artikel · Brez alternative = samo ena ponudba" "R264 legenda append"
echo "--- R263 stranke-pokritost PDF (regresija) ---"
need_static "Izvozi pokritost opomnikov kot PDF" "R263 pill aria"
need_static "STRANKE — OPOMNIŠKA POKRITOST" "R263 PDF glava"
need_static "Pokritost opomnikov:" "R263 F2 mini-vrstica"
need_static "· Pokritost = stranke × opomnikStatus (slepe pike = brez datuma)" "R263 legenda append"
echo "--- R262/R261/R260/R259/R258/R257/R256/R255 + starejše regresije ---"
need_static "Izvozi pokritost zaloge in osnutkov kot PDF" "R262 pill aria"
need_static "ZALOGA — OSNUTEK POKRITOST" "R262 PDF glava"
need_static "Pokritost osnutka:" "R262 F2 mini-vrstica"
need_static "Izvozi račune po projektih kot PDF" "R261 pill aria"
need_static "RAČUNI PO PROJEKTIH" "R261 PDF glava"
need_static "\"Najhitrejši rok\",\"Največji popust\"" "R260 CSV glava (minified)"
need_static "children:\"najhitrejši rok\"" "R260 žig najhitrejši rok"
need_static "· CSV nosi segmentacijo (najhitrejši rok · največji popust)" "R260 legenda append"
need_static "Povprečni rok" "R259 KPI 4 label"
need_static "Izvozi dobičkonosnost projektov kot PDF" "R258 pill aria"
need_static "DOBIČKONOST PO PROJEKTIH" "R258 PDF glava"
need_static "Izvozi naročila kot PDF" "R257 pill aria"
need_static "NAROČILA — PREGLED" "R257 PDF glava"
need_static "Izvozi tedenski pregled montaž kot PDF" "R256 pill aria"
need_static "TEDENSKI VOZNI RED MONTAŽ" "R256 PDF glava"
need_static "Izvozi vozni red montaž kot PDF" "R255 pill aria"
need_static "VOZNI RED MONTAŽ" "R255 PDF glava"
need_static "Ni vidnih terminov montaže" "R255 fail-closed toast"
need_static "to-roksal-navy-soft" "R255 navy-soft žeton"
need_static "Izvozi koledar pregledov kot PDF" "R253 pill aria"
need_static "Izvozi potekle opomnike kot PDF" "R252 bulk pill aria"
need_static "Izvozi prihodke kot PDF" "R250 pill aria"
need_static "Moja vloga in dovoljenja" "R240 meni + dialog"
need_static "CENIK MATERIALA" "R244 PDF glava"
need_static "Brez dobavitelja (" "R227 žig aria"
must_miss "TODO-R282" "R282 — brez razvojnih ostankov"
must_miss "TODO-R281" "R281 — brez razvojnih ostankov"
must_miss "TODO-R280" "R280 — brez razvojnih ostankov"
must_miss "TODO-R279" "R279 — brez razvojnih ostankov"
must_miss "to-[#2a3f5f]" "must_miss to-[#2a3f5f]"
must_miss "accent-[#f59e0b]" "must_miss accent-[#f59e0b]"
must_miss "bg-[#f7f9ff]" "must_miss bg-[#f7f9ff]"
echo "NEEDLE FAIL=$FAIL (R282 ×4 novih; R281 ×13; R280 ×15; R279 ×5 + R278 ×6 + R277 ×9 + R276 ×15 + R275 ×3 + R274 ×13 + R273 ×27 + R272 ×25 + R271 ×26 + R270 ×25 + R269 ×18 + R268 ×17 + R267 ×9 + R266 ×9 + R265 ×7 + R264 ×5 + R263 ×4 + regresije)"
exit $FAIL
