#!/usr/bin/env python3
"""R289: append worklog vnos (tri-sekcijski kanon) — NE prepiše obstoječe
vsebine (samo pripne za `---` ločilom)."""
VSEBINA = '''
---

## R289 — ISKREN PRESEŽEK V ZVONČKU + PRVI PRAVI 2-TAB CROSS-TAB E2E (P1-c, odprt od R272+ — ZAPRT) — worklog i9
### Status / ocena (R289 konec)
- HEAD: R289 (ta commit) — vse zeleno lokalno; produ na R288 buildu (r288-prod-qa.sh EXIT=0 potrjen na ZAČETKU runde — build 2026-09-29T17:00:49.601Z > R288 push 17:00:27Z, deploy ~22 s; R288 LIVE needleji ×8 ['aria-label":"Iskren presežek signalov' NI — R288 needleji: roksal:select-crm + izbranaStrankaId + onStrankaIzbranaObravnavana + PRESKOCI + ODPRI + CAKAJ + 'Poudarjeno iz zvončka (opomnik)' + 'border-roksal-amber/60 bg-roksal-amber/5'] + R287/R286/R285/R284/R283/R282/R281/R280/R278/R279/R277/R276/R274/R272/R271/R269/R240/R227 regresije ŽIVO + Z1b verzije 404 + Z1c zvonček [desc ŽIVO, 0 opomnikov na spot — iskrena praznina] + Z3 v99 gate — ZERO-MUTACIJA). R289 push sproži deploy — potrditev = PRVA naloga R290 (r289-prod-qa iz r288 vzorca).
- GitHub issues: brez novih (#14–#17 nespremenjene; dev-dokazljivi del izčrpan — ostanki lastniške akcije). P1-f opomnik BULK ŽE ZAPRT (potekli-opomniki-pdf R252 — preverjeno v kodni bazi, NE ponovljen). R289 vzame (c) 2-tab cross-tab E2E (odprt od R272+) + NOV family-wide presežek (iskrena vrzel: 7 signalnih družin tiho capa — 9. zamujena dobava / 7. opomnik bi izginil brez žigona).
### Cilji / izvedene spremembe / verifikacija
- FOCUS — ISKREN PRESEŽEK (S1–S5 zapisane pred razvojem): S1 EN VIR (isti validacijski sprehod kot vrstice — presežek NE more divergirati); S2 ENA vstavitvena točka (role="note" POVZETEK pod seznamom — pogojna, ne-klikljiva, brez lažnih affordance; title izrecno pove, kje je celotna resnica); S3 fail-closed (reset ob load/omrežni napaki; atomarno z items — nikoli mešanih stanj); S4 (c) CROSS-TAB E2E kot dokaz; S5 stil samo žetoni (border-border/60 + bg-muted/40 + text-muted-foreground + text-roksal-ink + tabular-nums — 0 novih hex).
- NOV lib izvoz src/lib/opomnik-zvonek.ts: opomnikZvonekPresezek(vhodi, max=6) — presežek = veljavni − prikazani; INTERNAL izvleček opomnikZvonekNosilci (javno vedenje opomnikZvonekVrstice IDENTIČNO — R287 ×15 pinov ščiti); pokvareni vnosi NE štejejo (nikoli napihnjenega alarma); TypeError na ne-seznamu (ISTA družina R287); max<0 = pariteta vrstic (slice(0,0) → vsi presežek); danas NE potreben (štetje ne odvisi od datuma).
- notification-center.tsx: PresezekVrstica { kategorija, st } + presezki state + dodajPresezek helper + 6 komponentnih družin wire-anih z ISTIMI filtriranimi seznami (Nizka zaloga 8, Brez dobavitelja 8, Današnje montaže 8, Follow-upi 6, Zapadli računi 6, Zamujene dobave 8) + opomniki prek liba (CRM opomniki +N); setPresezki ATOMARNO z setItems; catch → setPresezki([]); UI note blok z aria-label="Iskren presežek signalov" (poimenovana regija) + 'Presežek: kategorija +N · …' (tabular-nums); badge/pečat semantika NESPREMENJENA (presežek = dopolnitev, ne zamenjava).
- (c) CROSS-TAB E2E — PRVIČ z agent-browser TABS (tab new/close/<id>): Z0 TAB A baza (0 vrstic + note NIČ + pečat A1 + bazni fetch števec) → SEED 9 (8 POTEKEL + 1 AKTIVEN) → Z1 TAB B PRIČA (tab new — NOV zavihek, ISTA seja): 6 vrstic + 'Presežek: CRM opomniki +3' ŽIVO (mount fetch) → Z2 AKTIVACIJA tab t1 (bring-to-front) → REALNI visibilitychange/focus dogodki → useRefetchOnFocus → delta /api/crm = 2 (notification-center + crm-tab — obe površini) → 6 vrstic + '+3' + pečat SPREMENJEN (A2≠A1) = CROSS-TAB PROPAGACIJA DOKAZANA → Z3 restore r289 + seed r287 (2 opomnika) + dispatch (po 32 s rate-limit oknu): 2 vrstici + note IZGINILA (pogojni kanon ŽIVO — note samo ko >cap) → Z4 restore ×2 + fp bajtnato identičen (r289 + r287) — ZERO-MUTACIJA.
- TESTI +17 (3896/3896, 216): NOV r289-opomnik-presezek.test.ts ×17 — lib ×10 (0/≤max/>max/izrecen max/EN VIR divergenca/pokvareni NE štejejo/mešani statusi/TypeError/determinizem/max<0 pariteta) + strazar ×7 (6 družin wiring/opomniki lib call/atomarnost+catch reset/pogojni UI/ne-klikljivost/žetoni+0 hex/r287 pini). PIN posodobljen z ohranjeno namero: r287 EN VIR uvoz (razširjen z opomnikZvonekPresezek — komentar v testu).
- SKRIPTE: r288-prod-qa.sh (NOVA — PRVA naloga R289, r287 vzorec + R288 needleji ×8 + TODO-R288 must_miss) + r289-build-needles.sh (R289 ×8: aria-label + 'Presežek:' + title + 4 kategorije + 'kategorija' ključ; TODO-R289 must_miss; Z-STRUCT 0/0) + r289-run-smoke.sh + r289-db-e2e.cjs (seed-presezek/restore/fp — 9 strank e2e-r289-%) + r289-e2e-browser.sh (2-tab: H/Z0/S/Z1/Z2/Z3/Z4) + gen-r289-needles.py. README ×2 (3879→3896; 215→216).
- VERIFIKACIJA: tsc 0 · eslint 0 · vitest 3896/3896 (216) · build ✓ · r289-build-needles FAIL=0 (R289 ×8 + R288 ×8 + R287 ×10 + R286 ×8 + R285 ×11 + R284 ×16 + … + regresije + must_miss; 359 OK; Z-STRUCT 0/0) · r289-run-smoke ✓ (health/200/307/403 CSRF · port sproščen) · E2E ŽIVO EXIT=0 ČISTI TEK (Z0 baza → S seed → Z1 TAB B [6 + +3] → Z2 AKTIVACIJA [delta 2 + 6 + +3 + pečat A2≠A1] → Z3 [2 vrstici + note NIČ] → Z4 ODTIS BAJTNATO IDENTIČEN). Kontrakt NIČ; /api/sync NIČ; Measurement SDK / BOM / pricing / geometry core NIČ; OgrajaVizija nič; brez sheme; 0 novih hex.
### Lekcije (R289)
- (1) **ASCII kanon 4. generacija**: tudi IZOŽENA imena funkcij iz lib-a NE preživijo minifierja v UVOZNEM modulu (lokalna vezava) — opomnikZvonekPresezek MISS na 1. teku; stabilni so SAMO prop/objektni ključi ('kategorija') + JSX attr literali + hyphenated attr ključi kot STRING ključi ('"aria-label":"…"' — ne 'aria-label="…"').
- (2) **Headless tab vidnost je LEN**: po tab close ostane ozadje 'hidden' do eksplicitne AKTIVACIJE (agent-browser tab <id> = bring-to-front) — REALNI visibilitychange/focus dogodki potem sprožijo useRefetchOnFocus (delta 2 brez synthetic dispatcha); R173 synthetic dispatch = rezerva.
- (3) **Rate-limit FOKUS_MIN_INTERVAL_MS = 30 s**: zaporedni refetch testi (Z2 → Z3) MORAJO izrecno počakati okno, sicer je dispatch brezploden (Z3 6 vrstic stale na 1. teku).
- (4) eval CLI dvojno JSON kodiranje ('\\"…\\"') — bash preverbe z tr -d '"\\\\' + substring matche, NE raw json.loads (r229 python-parser lekcija za nove oblike).
- (5) Seed raba: r289-db-e2e.cjs NOV (9 strank) — r287 seed ×2 ostane za regresijo (Z3) in dokaz pogojnega kanona (note IZGINILA).
### Nerešeno / tveganja / prioritete za naslednjo rundu (R290)
- 🔴 **PRVA naloga R290: potrditi R289 na produ** — iz r288-prod-qa.sh vzorca zgenerirati r289-prod-qa.sh (EPOCH build-guard > R289 push časa; R289 LIVE needleji ×8: '"aria-label":"Iskren presežek signalov"' + 'Presežek:' + 'Iskren presežek — zvonček prikazuje najpomembnejše vrstice' + 'Današnje montaže' + 'Follow-upi' + 'Zapadli računi' + 'Zamujene dobave' + 'kategorija'; R288/R287 regresije; Z1b verzije 404; Z1c zvonček pogojni DOM probe + NOV Z1d presežek note pogojni probe [spot: note NIČ — iskrena praznina]; Z3 v99 gate).
- 🟠 R290 opcijski viri: aria-hidden mega-diff (P1-d, 629 mest — codemod + izjeme-audit); e2e-lib migracija starih skript (P1-b, 25+); RBAC ogledalo ostanki (P1-e — SKLADIŠČE/API-ključ pogledi); CSRF vezba (ZADNJI, samo z blagoslovom); deep-link/presežek evalvacija po lastniški rabi.
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3,5 tedna) — obvestiti lastnika (enajstič zapisano; NE pozabiti).
'''
with open('/home/z/my-project/worklog.md', 'a', encoding='utf-8') as f:
    f.write(VSEBINA)
print('worklog R289 append OK')
