#!/usr/bin/env python3
# R293 — worklog append (tridelni žig — kanon R172+; append-only).

DODATEK = '''---

## R293 — DOBIČKONOST PO PROJEKTIH CSV (24. člen izvozne družine) + MARŽNI RAZGLED strip (MANDATORY STIL) — worklog i13
### Status / ocena (R293 konec)
- HEAD: R293 (ta commit) — vse zeleno lokalno; **produ na R292 buildu 2026-09-29T19:55:24.467Z — DEPLOY ZAOSTANEK IZČERPAN: build ~31 s po R292 pushu 19:54:53Z (po treh generacijah zamika R290/R291 — ESKALACIJA iz R292 REŠENA brez 4. zapisa; lokalni buildi vsi ✓, kanon ponovno zdrav)**. ✅ PROD QA (PRVA naloga runde): r292-prod-qa.sh EXIT=0 — PRVIČ POLNI LIVE needle dokaz R290+R291+R292 SKUPAJ: LOGIN ✓ (poskus 2) · Z1 OPOMBA (meritve UI MONTER skoping — pogojni kanon r277) · Z1b verzije ruta 404 + 'Meritev ne obstaja' ŽIVO · Z1c zvonček ŽIVO prazna kopija [iskrena praznina] · Z1d presežek note NIČ [iskrena praznina] · Z2 44 čankov: R292 ×8 + R291 ×8 + R290 ×8 + R289/R288/R287/R286/R285/R284/R283/R282/R281/R280/R278/R279/R277/R276/R240/R227 needleji VSI LIVE OK + must_miss ×9 (TODO-R284..R292) · Z3 v99 sync gate ŽIVO (fail-closed, ZERO-MUTACIJA).
- GitHub issues (API, lastniški token): #14–#17 NESPREMENJENE [0 komentarjev, updated 2026-09-28] — dev-dokazljivi del izčrpan (R287 sklep); #1 updated 2026-09-29T18:47:30Z = lastniški body edit (determinizem epopeja — repozitorij to doktrino že izvaja). R293 vzame naravnega družinskega naslednika: CSV brat DOBIČKONOST PO PROJEKTIH PDF R258 (14. člen brez CSV brata — WYSIWYG bratje kanon R284→R285/R291/R292).
- Sinhronizacija: lastniški token AKTIVEN na remote (push dry-run 'Everything up-to-date' pred rundom); README usklajen (×2 v rundi: 3997→4018; 220→221) — zahteva lastnika 'sinhroniziraj readme kode' izpolnjena.
- Spot portfel sprememba (E2E odkritje): spot zdaj ima 1 račun (IZDAN, 893.04 EUR, brez projekta ob E2E teku → strip sklep ŽIVO) — Z0n/Z0o pogojni kanon še vedno prazna veja (PLACAN-only), Z0p dobičkonost (IZDAN+PLACAN) PRVIČ ŽIVA podatekovna veja.
### Cilji / izvedene spremembe / verifikacija
- FOCUS (P1–P8 zapisane pred razvojem): P1 EN VIR — vhod liba = presek { vrste, povzetek } (ISTI rezultat dobicikonostPoProjektih kot PDF brat R258 IN strip — lib NE računa znova, WYSIWYG po konstrukciji, vzorec R291); primitivne izpeljave UVOŽENE: znesekNiz (EXPORT iz PDF brata — R293 ena-besedna sprememba, ISTI strojni kanon zneskov) + projektBeseda (UVOŽENA iz projekti-termini-pdf — R265 lekcija: sklanjatev NIKOLI zasegana); P2 fail-closed ×~10 z indeksom krivca (ne-objekten presek / ne-polje vrste / pokvarjena vrsta: projekt, prihodki-stroški ≥ 0 [denarna tokova], marža KONČNA [SME biti negativna — izpeljana resnica], marža = prihodki − stroški TOČKOVNA izpeljava preverba [isti FP operaciji], marzaOdstotek finite|null, števci celo ≥ 0 / pokvaren povzetek / pokvaren now ×3); P3 determinizem — now KOT parameter, vrstice v ISTEM vrstnem redu kot vhod (MARŽA ASC je bratova sort — lib NE preureja; f(množica) R248/R250/R252/R253); P4 ravninska resnica PDF tabele — 7 stolpcev VERBATIM autoTable head, zneski znesekNiz, % toFixed(1) ALI '—' (NIKOLI izmišljen 0 %), števci String; meta kanon R172/R291/R292 (ločilna + Obseg + Projektov + Prihodki + Stroški + Marža + POGOJNE ×5 [Negativnih marž — iskren alarm / Storniranih / Osnutkov (izključeni iz prihodkov) / Računov brez projekta z vsoto EUR / Naročil brez projekta z vsoto EUR (izključeni iz preseka)] + Izvoženo ob ISO); P5 PRAZEN PRESEK = veljaven CSV (glava + meta iskrne ničle; brez-projektni odpad poimenovan, če prisoten) — komponenta pri 0 računov IN 0 naročil NEOBJAVLJA datoteke (ISTI gate kot brat R258); P6 ENA izpeljava sklep dobicikonostSklep = strip + toast (WYSIWYG); P7 MANDATORY STIL — MARŽNI RAZGLED strip NA ZASLONU (vodja pregled; do zdaj dobičkonostna resnica SAMO v PDF): MARŽA ASC akcijski red, NEGATIVNA marža rdeča text-roksal-red (PDF RED bold pariteta, NIKOLI utišana), mini tir |marža| / maxMarza × 100 (ISTO merilo za VSE, bg-roksal-navy/30 + bg-roksal-red/40, aria-hidden, hover title 'N % najvišje marže (po absolutni vrednosti)' — izpeljava izrečena), '—' % stolpec, iskrena praznina 'Ni projektov v preseku — dobičkonost se izriše ob prvem računu ali naročilu.', legenda PREDPONA append '· CSV = ista resnica kot PDF' (R258/R261 resnica bajtno ohranjena — substring-parna lekcija), 0 novih hex; P8 gumb VEDNO viden (R232/P1-k kanon; FileSpreadsheet aria-hidden; press-scale; focus ring) + dvoklik guard + disabled parity (brat: loading || dobicikonostCsvVTeku).
- MANDATORY FUNKCIJA: NOV lib src/lib/dobicikonost-projekti-csv.ts (BOM + '\\n' + citiraj vzorec vodja-csv; DOBICIKONOST_PROJEKTI_CSV_GLAVA ×7 izvožena; marzaOdstotekNiz ENA izpeljava % resnice; dobicikonostSklep — sklanjatev projektBeseda + EUR resnice; filename 'Dobicikonost-projektov-<stamp>.csv' — brat PDF imena, samo pripona ločuje) + vodja-dashboard žičenje: dobicikonostVhodi memo (DTO pruning EN VIR — stara inline preslikava v R258 handlerju IZBRISANA, R290 vzorec; r258 pini dobicikonostPoProjektih(racuni, allOrders) + buildDobicikonostPdfDoc(racuni, allOrders, { now }) NEZMENJANA) + dobicikonostIzpeljava memo (presek ENA izpeljava za strip + CSV + PDF toast) + handleDobicikonostCsv (ISTI gate kot brat; ENA now za CSV + ime — lekcija R121/R235; uspešni toast = dobicikonostSklep; fail-verbose catch 'Izvoz CSV ni uspel' destructive) + maxMarza memo. r180 lucide-blok pin posodobljen z OHRANJENO namero (FileSpreadsheet v ISTEM bloku — History pečat ostaja; R291 vzorec).
- TESTI +21 (4018/4018, 221): NOV r293-dobicikonost-projekti-csv.test.ts ×21 (lib ×14: glava ×7 VERBATIM, EN VIR uvozi [znesekNiz export brata + projektBeseda + brez ponovnega računa], ravninska resnica + MARŽA ASC NEZMENJAN, % '—' null resnica, NEGATIVNA marža VERBATIM + iskren alarm meta, BOM/\\n/brez CR, meta vrstice + vrstni red indeksi, pogojne ×5 obeh smeri [racunovBrezProjekta šteje VSE brez-projektne — vsota samo izdane+plačane], prazen presek veljaven ×8 vrstic, determinizem bajtno + drug now, f(množica) premešan bajtno ENAK, sklep sklanjatev 1/2/5 + točen niz, fail-closed ×~10, filename; strazar ×7: EN VIR memo + stara preslikava izbrisana + r258/r261 pini intact, gumb VEDNO viden + guard + parity, fail-closed PREJ + ENA now, uspešni toast = sklep + fail-verbose, strip žetoni + aria + % izpeljava + maxMarza, legenda PREDPONA + pripona, hex baseline + bratje čisti).
- SKRIPTE: r292-prod-qa.sh (PRVA naloga — polni LIVE teki, 44 čankov) + gen-r293-skripte.py (izpeljava r293-build-needles/run-smoke/e2e iz r292 vzorcev; pozicijska popravka R292 bloka [blind-rename lekcija — 8 oznak + glava + TODO-R292 vračilo] + preverba blokovnega vrstnega reda R293→R292→R291) + r293-build-needles.sh (R293 ×8: gumb aria/title + fail-closed toast + uspešni toast + strip aria + % title + iskrena praznina + meta Obseg lib čanek; TODO-R293 own) + r293-run-smoke.sh + r293-e2e-browser.sh (NOV Z0p: MARŽNI RAZGLED strip probe [vrstice/tirje/sklep/praznina pogojni kanon] + DOBIČKONOST CSV pogojni kanon — toast pri 0/0 ALI bajtna capture; Z0o oznake relabel R292).
- LEKCIJE: (1) **Response.text() STRIJE vodilni BOM** (fetch spec UTF-8 decode) — eb_csv_capture (Response.text vzorec) NE more dokazati BOM; spot zdaj ima podatek → Z0p prva REALNA capture (350 B) ponesla napako na dan; dokaz = RAW bajti (b.arrayBuffer: EF BB BF) + TextDecoder za vsebino — Z0n/Z0o do zdaj VEDNO prazna veja, zato past nevidena; (2) **hex baseline pini štejejo TUDI komentarje** (r225/r261 regex čez celotno datoteko) — komentar 'baseline #1d2b3e' povišal števec 1→2 = lažno rdeče; pravilo: NIČ hex literalov v komentarjih (tudi 'baseline' omembe); (3) test pričakovanja IZ koda, ne iz spomina — statusi naročil DOBLJENO/POTRJENO/POSLANO (ne izmišljeni PREJETO/NAROCENO/VP_SKLADISCU), racunovBrezProjekta šteje VSE brez-projektne vnose (vsota EUR samo izdane+plačane), meta tail indeksi = pogojna resnica (ločilna dokazana strukturno, ne pozicijsko); (4) blind-rename lekcija pozicijsko implementirana v gen-r293 (R292 blok oznake + TODO-R292 vračilo + blokovni vrstni red assert) — past se NE ponovi v 4. generaciji; (5) dobičkonost (IZDAN+PLACAN) in prihodki-meseci (samo PLACAN) sta RAZLIČNI resnici — spot 893.04 EUR IZDAN viden v stripu, NE v Z0m mesecih (obe pravilni, definicije izrečene v legendi).
- VERIFIKACIJA: tsc 0 · eslint 0 · vitest 4018/4018 (221) · build ✓ · r293-build-needles FAIL=0 (R293 ×8 + R292 ×8 + R291 ×8 + R290 ×8 + R289/R288/… regresije ×~354 + must_miss; Z-STRUCT 0/0) · r293-run-smoke ✓ (health 200 + db ok / login 200 / PWA 307 / 403 CSRF fail-closed · port sproščen) · E2E ŽIVO EXIT=0 ČIST TEK (Z0p MARŽNI RAZGLED ŽIVO [1 vrstica + 1 aria-hidden tir + sklep '1 projekt · prihodki 893.04 EUR · stroški 0.00 EUR · marža 893.04 EUR · negativnih marž 0'] + Z0p CSV ŽIVO bajtno [350 B, BOM efbbbf RAW dokaz, glava '"Projekt","Prihodki (EUR)","Stroški (EUR)","Marža' …] → Z0z → Z0y → Z0m → Z0n → Z0o → Z1/Z1r/Z1s/Z1m → Z2 → Z2b/Z2z PDF → Z2x/Z2y CSV → Z3 panel → Z4 pilli → Z5 temna → RESTORE → ODTIS BAJTNATO IDENTIČEN r276+r281+r283+r287 — ZERO-MUTACIJA). Kontrakt NIČ; /api/sync NIČ; Measurement SDK / BOM / pricing / geometry core NIČ; OgrajaVizija nič; brez sheme; 0 novih hex. README ×2 (3997→4018; 220→221). 🆕 Skripte: r292-prod-qa.sh, gen-r293-skripte.py, r293-build-needles.sh, r293-run-smoke.sh, r293-e2e-browser.sh.
### Nerešeno / tveganja / prioritete za naslednjo rundu (R294)
- 🔴 **PRVA naloga R294: potrditi R293 na produ** — r293-prod-qa.sh (iz r292-prod-qa vzorca; EPOCH guard > R293 push časa; R293 ×8 LIVE needleji + R292/R291/R290 ×8 regresije; Z1b; Z1c/Z1d; Z3). **DEPLOY ZAOSTANEK IZČERPAN (R292 build ~31 s po pushu — kanon zdrav); pričakovano R293 build v kanonskem oknu (~30 s–40 min).**
- 🟠 R294 opcijski viri: (b) e2e-lib migracija ostalih starih skript (25+); RBAC ogledalo ostanki (SKLADIŠČE/API-ključ — fixture znižanih pravic); 'izvozi' družina naslednji brat: koledar pregledov CSV (brat PDF R253); deep-link/presežek evalvacija po lastniški rabi; CSRF vezba (ZADNJI, samo z lastniškim blagoslovom).
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3,5 tedna) — obvestiti lastnika (petnajstič zapisano; NE pozabiti).
'''

with open('/home/z/my-project/worklog.md', 'a', encoding='utf-8') as f:
    f.write(DODATEK)
print('worklog appended: R293 tridelni žig')
