#!/usr/bin/env python3
# R294 — worklog append (tridelni žig — kanon R172+; append-only).

DODATEK = '''---

## R294 — ISSUE #1 AVTOMATIZACIJA AUDIT (skener + pregled + meritve) + DETERMINIZEM POPRAVKI (wind demo/survey-pdf/locale jedra) — worklog i14
### Status / ocena (R294 konec)
- HEAD: R294 (ta commit) — vse zeleno lokalno; **produ ŠE VEDNO na R292 buildu (19:55:24.467Z) — R293 push 20:46:30Z ~1 h brez deploya → 🔴 ESKALACIJA LASTNIKU POTRJENA (4. zapis): r293-prod-qa.sh EXIT=0 stale veja — stale build zdrav (Z1b verzije 404 + Z3 v99 gate + R289–R292 needleji ŽIVO); R293 pilli must_miss izpuščen iz stale veje (Vercel skew protection lahko streže R293 čanke R292 page-u po pushu — vrstno ranljivo; avtoritativni detektor = EPOCH build-guard)**. R290/R291 deployana, R292 ŽIVO (polni LIVE needle dokaz v R293 rundi).
- **LASTNIŠKA DIREKTIVA: "nadaljuj na prvi issue"** — FOCUS = issue #1 (Professional automation / determinizem): prebran CELOTEN issue (7.738 znakov); izhodiščna analiza 'Kaj bom RAZVIL' → (a) skener determinizma kot VGRAJEN gate (ni obstajal), (b) pregled po območjih + AI izjava (dokumentacija NI obstajala), (c) meritve zmogljivosti (NI obstajale), (d) POPRAVKI dejanskih nedeterminizmov, ki jih je skener našel (wind demo Math.random ×7!, survey-pdf new Date ×2, crm-csv toLocale, termini localeCompare, 8 izvoznih jeder z ICU klici).
- ISSUES (API): #14–#17 nespremenjene; #1 = runda FOCUS (lastniški body edit 18:47:30Z vključuje AGENT STARTUP RULE: 'RAZVOJ > QA', 'prepoved mikro-rund' — ta runda sledi: skener + popravki + dokumentacija = razvoj, testi = dokaz).
- Sinhronizacija: token aktiven (push dry-run OK pred rundom); R293 predan prek infra cron commita af61a20 (drevo bajtno identično žigu — potrjeno z git diff).
### Cilji / izvedene spremembe / verifikacija
- FOCUS (P1–P8 zapisane pred razvojem): P1 NOV lib src/lib/avtomatizacija-audit.ts — EN VIR strojna resnica: AVTOMATIZACIJA_AUDIT (11 območij issue #1 §1–§11, klasifikacija DETERMINISTICNO/SDK/SKRIPTA/AI_OPCIJSKO/AI_ZAHTEVANO, implementacija/dokaz POTI — strazar dokazuje, da datoteke obstajajo — 'tabela ne sme sanjati') + AI_KANDIDATI ×3 (vsi izrecno 'NE-IMPLEMENTIRANO — kandidat (nič povezano)' — nič lažne prevare) + PREPOVEDANI_VZORCI (AI gostitelji, Math.random, Date.now, toLocale*, localeCompare, new Date()) + AVTOMATIZACIJA_IZJEME (20 vnosov, vsak z obveznim razlogom — fail-closed); P2 odstraniKomentarje = comment/string/REGEX-aware lexer (vrstična struktura ohranjena 1:1); LEKCIJE v kodi: komentarji se preverijo PRED nizi (backtick v // komentarju odprl lažni niz), regex literali (/"/g) MORAJO biti prepoznani (hevuristika prejšnjega žetona + ključne besede), sicer se stanje pokvari za vse nadaljnje vrstice; P3 SEAM pravilo: privzete vrednosti parametrov (now: Date = new Date() / ?? new Date() / = Date.now()) = dokumentiran kanon (line-lokalni offset — LEKCIJA: m.index je dokumentni, NE vrstični offset); P4 pregledajAvtomatizacijo → Kršitve z indeksom krivca (pot:vrstica + okoli 120 znakov), determinizem f(množica); P5 skener preskoči svojo datoteko (definicija vzorcev); P6 NOV docs/automacija-audit.md (pregled + AI izjava 'AI kot odvisnost: NIČ' + kandidati + skener + meritve + R294 popravki) — pripet na lib s strazarjem; P7 MANDATORY STIL: MARŽNI RAZGLED strip bogatejši — per vrstica števca 'N r · M n' (PDF tabela stolpca Računov/Naročil NA ZASLONU; hover title izrečena resnica; 0 novih hex); P8 popravki iz skenerja (spodaj).
- POPRAVKI (skener je našel REALNE nedeterminizme — 'implement the practical parts'): (1) wind-service.ts — demo vetrični vzorec Math.random ×7 (hranil je isSafeForInstallation!) → fiksne iskrene vrednosti (8.5/11.5 m/s, SW, 18°, opis izrecno 'Demo (brez živih podatkov — nastavi OPENWEATHER_API_KEY)' — nič lažne vremenske resnice); (2) survey-pdf.ts — new Date() ×2 + toLocaleDateString → now: Date KOT parameter + buildSurveyPdfDoc/generateSurveyPdf split (bajtni determinizem dokazljiv; caller site-survey-tab poda now); (3) crm-csv.ts — formatDatum fallback toLocaleDateString → string rezanje (isti kalendarček v vsakem pasu); (4) termini-prikaz.ts — localeCompare izenačba → navadno < po UTF-16 (R245/R250 kanon); (5) IZVOZNA JEDRA ×8 (audit-csv, boss-report-pdf, document-pdf, ekipa-csv, nagibi-csv, punch-csv, termini-csv, zaloga-povzetek) — ICU klici → EN VIR čisti formati v csv-export.ts: slDatum ('DD. MM. YYYY'), slUra ('HH:MM'), slDatumKratko ('D. M. YYYY'), formatSlDecimalno (vejica + tisočilec, ICU prag 5 mest — 10000 → 10.000, 9999 → 9999), MESCI_SL — BAJTNO ISTI izpisi (ICU resnica node 24 sl-SI; paritetni testi), document-pdf posebej kritičen (SHA-256 → object storage).
- TESTI +43 (4061/4061, 222): NOV r294-avtomatizacija-audit.test.ts ×20 (lexer ×5: backtick v komentarju, blok čez vrstice, URL v nizu varen, regex z navedki, vrstice 1:1; skener ×5: AI gostitelj zaznan, komentar omenja vzorec NI kršitev, seam privzeta vrednica vs const assignment, fail-closed izjeme, determinizem reda; REALNO drevo ×3: skener nad celotnim src/lib = 0 kršitev, AI kandidati vsi NE-implementirani, tabela referencira samo obstoječe datoteke ×11 območij + izjeme z razlogi; docs pin ×2; meritve ×4: dobičkonost 3500 vnosov < 200 ms [izmerjeno ~10 ms] + tedenski razgled+CSV 500 < 200 ms [~9 ms] + prihodki 3000 < 150 ms [~4 ms] + ICU pariteta formatov bajtno) + obstoječi suite zelen (vsi ICU zamenjave bajtno identične — nič pinned izpisa ni premaknjen).
- SKRIPTE: gen-r294-prodqa.py (r293-prod-qa iz r292 vzorca — EPOCH guard > R293 push, R293 ×8 LIVE blok, pozicijska popravka R292 oznak + TODO-R292 vračilo + stale veja prestrukturirana [R290/R291/R292 pilli = LIVE needs v stale buildu; R293 must_miss izpuščen — skew protection lekcija] + logistics dispatch v stale veji) + r293-prod-qa.sh + r294-audit-pregled.ts (CLI dokaz skena) + r294-locale-kodemod.py (mehanske output-identične zamenjave ×8 jeder).
- LEKCIJE: (1) **lexer zaporedje stanj je ključno** — komentarji PRED nizi (backtick v // komentarju — 'podpičje (`;`)') in regex literali (/"/g) MORAJO biti prepoznani, sicer lažni nizi pokvarijo vse nadaljnje vrstice (skener je lažno报告al 141 'kršitev' — po popravku 0); (2) **m.index je dokumentni NE vrstični offset** — seam preverba potrebuje line-lokalni pred (lastIndexOf('\\n') + 1); (3) ICU sl-SI tisočilec šele pri 5 celoštevilčnih mestih (minimumGroupingDigits=2: 10000 → 10.000, 9999 → 9999) — formatSlDecimalno prag; (4) hex pini štejejo komentarje (R293 lekcija ponovno potrjena — nova strip komentarja brez hex literalov); (5) stale veja prod-qa: pill-level must_miss je vrstno ranljiv po pushu (Vercel skew protection) — avtoritativni detektor = EPOCH build-guard; (6) test pričakovanja IZ koda: statusi naročil/terminov iz STATUSI registrov, TIPI iz prihodki-pdf (RACUN, ne 'STORITEV'), dokaz datoteke prek ls PRED fiksacijo (2× napačno ime dokaza).
- VERIFIKACIJA: tsc 0 · eslint 0 · vitest 4061/4061 (222) · build ✓ · r293-build-needles FAIL=0 (R293 ×8 + regresije ×~354; Z-STRUCT 0/0) · r293-run-smoke ✓ (health 200 + db ok / login 200 / PWA 307 / 403 CSRF fail-closed · port sproščen) · E2E ŽIVO EXIT=0 ČIST TEK (Z0p MARŽNI RAZGLED ŽIVO [1 vrstica + r/n žetoni] + Z0p CSV ŽIVO bajtno [350 B, BOM RAW] → Z0z → Z0y → Z0m → Z0n → Z0o → Z1/Z1r/Z1s/Z1m → Z2 → Z2b/Z2z PDF → Z2x/Z2y CSV → Z3 → Z4 → Z5 temna → RESTORE → ODTIS BAJTNATO IDENTIČEN r276+r281+r283+r287 — ZERO-MUTACIJA). Kontrakt NIČ; /api/sync NIČ; Measurement SDK / BOM / pricing / geometry core NIČ; OgrajaVizija nič; brez sheme; 0 novih hex. README ×2 (4018→4061; 221→222). 🆕 Skripte: gen-r294-prodqa.py, r293-prod-qa.sh, r294-audit-pregled.ts, r294-locale-kodemod.py. 📄 NOV docs/automacija-audit.md (pripet na lib).
### Nerešeno / tveganja / prioritete za naslednjo rundu (R295)
- 🔴 **PRVA naloga R295: potrditi R294 na produ** — r294-prod-qa.sh (iz r293-prod-qa vzorca; EPOCH guard > R294 push časa; R294 nima lastnih LIVE needlejev [stilska dopolnitev stripa + popravki determinizma — r293 needleji pokrijejo strip]; R293 ×8 + R292/R291/R290 regresije; Z1b; Z1c/Z1d; Z3). **ESKALACIJA AKTIVNA (4. zapis): produ stale od 20:46:30Z — R293+R294 se deplotata SKUPAJ, ko se Vercel zbudi; lastnik MORA preveriti Vercel dashboard (deploy stuck/limit — isti vzorec kot R290–R292 zamik; lokalni buildi vsi ✓).**
- 🟠 R295 opcijski viri (issue #1 nadaljevanje): skener razširjen na src/components (prikazni sloj — sedaj izven obsega); route handlerji (I/O meje — stena ura po definiciji, vredno pregleda ali ima katera ruta truth-kernel del); AI kandidati evalvacija po lastniški rabi; 'izvozi' družina: koledar pregledov CSV (brat PDF R253); e2e-lib migracija (25+); CSRF vezba (ZADNJI, samo z lastniškim blagoslovom).
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3,5 tedna) — obvestiti lastnika (šestnajstič zapisano; NE pozabiti).
'''

with open('/home/z/my-project/worklog.md', 'a', encoding='utf-8') as f:
    f.write(DODATEK)
print('worklog appended: R294 tridelni žig')
