#!/usr/bin/env python3
# R341 — worklog tri-delni append (po KOLIZIJI #14 supersediciji)
V = "/home/z/my-project/worklog.md"
VSEBINA = """

## R341 — 2026-10-01 (cron tick 202610011930 nadaljevanje po KOLIZIJI #14; ⚠️ 14. potrditev LEKCIJE 1: vzporedna lastniška seja je oddala R340 [4da09b9, 11:53:39Z — measurements FAZA 4 + calculator cut-list + profileLabels → shared + VALIDATE residual migracija + qa-round.sh TSV kanon] MED mojim delom — moja runda preimenovana R340→R341 po kanonu KOLIZIJE #4/R323/#13; njihov R340 = pristala resnica [git reset --hard origin/main], moja delta re-aplicirana na njihovo postavitev — vsi trije moji prispevki DOKAZANO edinstveni [njihov tree: modeLabelMap ×6 še vedno, new Blob ×1 še vedno, val 26 title odsoten]; njihov QA KONSOLIDACIJA kanon SPOŠTOVAN: moji r340-* derive skripti ×12 NISO pristali [ostanejo v stash@{0} kot zgodovina, vzorec /tmp/r338-staging] — namesto njih `scripts/qa-needles/r341.tsv` register v NJIHOVEM novem formatu; dev: kalkulator FAZA 3 [EN VIR modeLabels] + 65. člen issue #1 [zgodovina CSV → kanon toCsv] + MANDATORY STIL val 26 [hover parity zgodovina izračunov])

### Status / ocena (R340 konec [njihov] → R341 zagon [moja re-aplikacija])
- HEAD ob zagonu moje seje: `cf395e9` (R339) — synced, drevo čisto (adoption protokol; STALE povzetek iz prejšnje seje trdil R318/48. člen PDF izvoz — disk/git resnica: R318–R339 VSE pristalo); moja runda najprej razvita lokalno, ob pripravi na commit `git fetch` razkril **KOLIZIJO #14**: `4da09b9` (njihov R340) pristal 11:53:39Z
- Odločitev po kanonu (precedens KOLIZIJA #4/R323/#13): njihov R340 = SUPERSEDIRAJUČI (pristal prvi, celovit: dekompozicija + migracija + nov QA kanon); moja lokalna izvedba [vse v delovnem drevesu, NE commitirana] → stash `r341-moja-delta-pred-supersedicijo` → `git reset --hard origin/main` → delta re-aplicirana na njihovo postavitev
- **Edinstvenost delta dokazana** (disk resnica na njihovem tree): `modeLabelMap` ×6 [3 defs + 3 usages — njihov cut-list/profileLabels premik teh NI posobil], ročni CSV `new Blob` ×1 še vedno, val 26 title odsoten — NIČ supersedicije vsebine, čista renumeracija
- Postavitev razlike: njihov calculator-tab 4828 vrstic [cut-list.ts + profileLabels → shared]; po moji re-aplikaciji 4796 [−32: modeLabelMap dedup −36, 65. člen +2 neto [kanon krajši od ročnega plesa], val 26 +5]

### Cilji / izvedene spremembe / verifikacija
- **PRVA NALOGA (R340 dodelitev, izvedena PRED kolizijo)**: r339-prod-qa.sh POST-commit (grep čistost prej PASS) → **ESKALACIJA veja EXIT=0**: stale build `10:42:53.179Z` < R339 meja `11:24:40Z` — ZDRAV (Z2 needleji R276→R337 ŽIVO + ZERO must_miss + Z3 v99 sync gate ŽIVO ZERO-MUTACIJA; ESKALACIJA LASTNIKU: Vercel dashboard — deploy stuck/limit; kanon R280/R284: naslednji zeleni deploy nosi R290+…+R340+R341 SKUPAJ)
- **NJIHOV R340 QA dolg PORAVNAN po njihovi R341 instrukciji** ("qa-round.sh 340 e2e/smoke"): `qa-round.sh 341 e2e` EXIT=0 [delegacija na r339-e2e-browser.sh legacy anchor] + `qa-round.sh 341 smoke` ✓ [R341 SMOKE KONEC] — njihove iskrene meje [samo needles] zaprte na združenem stanju
- **FAZA 3 dekompozicija kalkulator — EN VIR `modeLabels`** (re-aplicirano na 4da09b9, fail-closed zam — 1. poskus ujel podniz-dvojni števec [6-presledkovni vzorec ⊂ 14-presledkovnega], popravljen pricakuj=2 — LEKCIJA R340 1 podkrepljena): 3× podvojen inline `Record<CalcMode, string>` (getCurrentKeyResult / addToHistory / Save-Calculation onClick — vsi trije bloki bajtno identični) → EN VIR `export const modeLabels` v `calculator/shared.ts` (+18 vrstic z R341 komentarjem; VERBATIM pari; SOSEDITELJSKO z njihovim profileLabels — brez konfliktov) + tab: uvoz ×1, `modeLabels[mode]` ×3, **0 `modeLabelMap` ostankov**; dogovor z modeTabs oznakami IDENTIČEN (isti niz 10 parov — testiran)
- **65. člen issue #1 (IZVOZI družina) — zgodovina izračunov CSV → kanon**: ročno sestavljanje (lastno citiranje + `\\n` + ročna BOM + blob/anchor/revoke ples — ZADNJI ročni CSV v kalkulatorju) → EN VIR `toCsv(headers, rows)` (R136: BOM + podpičje + CRLF + RFC 4180 csvField) + `downloadCsvText` (R296 mehanika); glave ×7 / vrstice ×7 / ime `roksal-zgodovina-YYYY-MM-DD.csv` / toasti / prazna-guardo VSE NESPREMENJENI; **iskren presledek obnašanja: `\\n` → CRLF**; 0 `new Blob`/`createObjectURL`/`uFEFF` ostankov v tabu
- **MANDATORY STIL val 26 — hover parity zgodovine izračunov** (vzorec R280/R281/R339): prstni odtis badge `title="Prstni odtis izračuna — verzija formule in hash vhodov za reproducibilnost (R150)"` + `cursor-help`; vnosni gumb zgodovine `title={`${entry.modeLabel} — ${entry.keyResult}`}` (hover parity z aria-label; gumb brez cursor-help — klikljivost); **0 novih hex**; vodja NI urejen → val 24/23 pini ostanejo
- **vitest r341 ×27** (3 NOVI datoteki, preimenovani iz r340-* po koliziji + interno R340→R341): `r341-calc-faza3` ×9 [EN VIR ×1 + 0 inline defs + 0 modeLabelMap + uvoz/uporabe ×3 + izčerpnost 10 ključev bijekcija + dogovor z modeTabs + snapshod + VERBATIM pari + r339 postavitev nedotaknjena] · `r341-zgodovina-csv` ×8 [uvoz + okno klica + 0 ročnih ostankov + glave/vrstice VERBATIM + guarda + toCsv kanon enota + downloadCsvText delegacija na viru] · `r341-stil-val26` ×10 [badge title/cursor-help + gumb title + cursor-help ×1 točno + 0-hex + obrnjene regresije val 25/24 [focus-visible:ring-roksal-amber/50 ×12 — disk resnica]/val 23/press-scale + register]
- **`scripts/qa-needles/r341.tsv`** (NOVI kanon — needleji kot PODATEK, njihov format iz r340.tsv): need_static ×1 [val 26 badge title — edini nov minifikacijo-preživeči niz te runde] + must_miss TODO-R341 ×1; **iskrena omejitev pokritosti** (vzorec njihove r340.tsv): modeLabels oznake obstajajo tudi v modeTabs [isti niz po konstrukciji] in 65. člen NESPREMENI vidno površino po namenu — pokritost = tsc + vitest r341 ×27 + E2E regresija; moji r340-* derive skripti ×12 NISMO pristali (supersedicija po kanonu — stash@{0} zgodovina)
- **VERIFIKACIJA NA ZDRUŽENEM STANJU (vsa ZELENA)**: tsc **0** · eslint **0** (5 dotaknjenih) · vitest **4851/4851 (292; njihov 4824/289 + mojih +27/+3)** — NIČ stale pinov [njihov r172 shift 6640→6525 ostane veljaven — moja delta NE sega v measurements; vsi val-registri preživijo] · build svež EXIT=0 (rm -rf .next; max-old-space 2560) · `qa-round.sh 341 needles` **VSE OK** [R341 register: val 26 needle ŽIV v kalkulator čanku + TODO-R341 must_miss + delegirana veriga r339→…→R227] · `qa-round.sh 340 needles` **VSE OK** [njihov register preživi mojo delta — railing-diagram ×3 + Z-line ŽIVO] · `qa-round.sh 341 smoke` ✓ (**R341 SMOKE KONEC**; login=200; fail-closed ovojnice 400 ŽIVO) · **`qa-round.sh 341 e2e` EXIT=0** [delegacija r339-e2e-browser.sh: Z0be [1737 bajtov FULL] + Z0bd/Z0bc/Z0bb ŽIVO; **ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana**] · README ×4 (4851/292 ×3 + R341 bullet s kolizijskim narativom)
- LEKCIJE R341: (1) **KOLIZIJA #14 = 14. potrditev LEKCIJE 1** — fetch PRED pripravo commita je kolizijo ujel ŠE PRED commitom [njihov 4da09b9 pristal 11:53:39Z, moj commit bi bil ~12:0x]; brez fetcha → ADD/ADD konflikti na calculator-tab/shared + dvojna R340 generacija; (2) **fail-closed zam tudi pri RE-APLIKACIJI** — podniz-dvojni števec [6 ⊂ 14 presledkov] bi tiho zamenjal obe znački z napačnim pričakovanjem; count-first je rešil; (3) **nov QA kanon spoštovan od samega zaloma** — ko vzporedna seja uvede nov vzorec [TSV register namesto 11 derive skriptov], nova delta sledi NOVEMU vzorcu, ne staremu [r341.tsv namesto r341-build-needles.sh]; (4) stash kot supersedijska zgodovina [vzorec r338-staging] — nič izgubljeno, vse rekonstruirljivo; (5) njihove iskrene meje [e2e/smoke ne pognani] so zakonita naloga naslednje runde — poravnane na združenem stanju
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ (njihova dekompozicija nedotaknjena); OgrajaVizija nič; **brez sheme** [njihova VALIDATE migracija ostaje njihova resnica — je ne ponavljam ne spreminjam; moja delta = samo app-layer + testi]; 0 novih hex (val 26 = title + cursor-help); NIČ FNV soli

### Nereseno / tveganja + prioritete R342
- ⏳ **Deploy PENDING**: R338+R339+R340+R341 čakajo na zeleni Vercel deploy — kanon R280/R284: naslednji zeleni deploy nosi VSE generacije (R290+…+R341); R342 prva naloga = `qa-round.sh 341 prod-qa` POST-commit re-run (NOVI kanon; pričakuj LIVE vejo ob zelenem deployu; LEKCIJA R337 6: interpretacija ŠELE po 2. teku) + delegirana veriga
- ⚠️ **KOLIZIJSKA VROČINA ostaja**: 14 kolizij v zgodovini; fetch-first PRED dev + fetch pred commitom/pushom = obvezna protokola; vzporedne seje tečejo ŠE VEDNO (njihov R340 je prišel ~40 min za mojim zagonom)
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3.5 tedna) — obvestiti lastnika (znova zapisano v R341; 45. zapis)
- R342 kandidati: **kalkulator FAZA 4** [template/history orkestracija → use-calc-history hook; calculate*ClientSide dispatcherji → calculator/calculations.ts] ALI **measurements FAZA 5** [preveri kolizije najprej — vzporedne seje so tam bile ×2] ALI **qa-needles registri za zgodovinske runde** [r3xx.tsv vzvratno — NIZKA prioriteta, kanon pravi da se NE ustvarjajo vzvratno] ALI **e2e-lib dedup** [veliko, previdno] — vedno z fetch-first protokolom + novim TSV kanonom za needleje
- ISSUE #1: 65 členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA, prepoved mikro-rund]
"""
with open(V, "a", encoding="utf-8") as f:
    f.write(VSEBINA)
print("worklog R341 appended; lines:", sum(1 for _ in open(V, encoding='utf-8')))
