#!/usr/bin/env python3
# r345-worklog-append.py — tri-section append za R345 (append-only, kanon).
import sys

TXT = """
## R345 — 2026-10-01 (cron tick 202610012345; nadaljevanje po R344 QA-IZVEDBENI rundi; adoption protoklov je ujel STALE SUMMARY CHAIN: povzetek je trdil HEAD=R318/`608e125`, disk resnica = R344/`4bfb97a` synced 0/0 — 26-rundni zaostanek v povzetku, stale-summary korekcija #42; razvoj: kalkulator FAZA 5 [dispatch logika 10 načinov → calculator/calculations.ts, args objekti — vzorec R325] + MANDATORY STIL val 28 [parity zaglavij zgodovine/predlog])

### Status / ocena
- HEAD ob zagonu: `4bfb97a` (R344) — synced 0/0, drevo čisto; fetch-first izveden PRED dev (LEKCIJA 1, 17. raba; KOLIZIJSKA vročina 16 kolizij ostaja)
- **PRVA NALOGA (R344 dodelitev) IZVEDENA v celoti**: (a) `qa-round.sh 343 prod-qa` re-run **EXIT=0 LIVE veja** [footer === R339 PROD QA — R290+…+R339 ŽIVO SKUPAJ ===; Z2 vsi needleji ŽIVO + Z3 v99 gate ŽIVO ZERO-MUTACIJA]; (b) **ERA PREVERBA r343.tsv — NOV kanonski skript `scripts/r345-era-harvest.sh`** [žetev 62/62 produkcijskih čankov iz prod-qa teka → grep -rqF po registru]: **R343 val 27 needle ŽIVO NA PRODU** [chunk_045] + must_miss TODO-R343 čisto + era kontrole R340 ×1 in R341 val 26 ŽIV → **produ = R339+R340+R341+R342+R343 ŽIVO SKUPAJ** [R343 deploy POTRJEN, ⏳ Deploy PENDING iz R343 ZAPRT]; iskren samo-ulov: prva verzija skripta je imela IZMISLJEN kontrolni needle za R341 — popravljen na resničnega iz r341.tsv PRED tek (no fabricated data)
- Okoljski reset peskovnika odkrit med verigo: prisma client izgubljen (57 testnih datotek FAIL `Cannot find module '.prisma/client/default'`), .env spran na SQLite placeholder, roksal_dev prazna baza — popolni reparacijski protokol izveden (glej LEKCIJE)

### Cilji / izvedene spremembe / verifikacija
- **FAZA 5 — NOV `calculator/calculations.ts` (279 vrstic)**: dispatch logika 10 načinov izluščena VERBATIM iz taba z args objekti (vzorec R325 pdf-exports; dve družini: ovonični railing/anchoring/wind vračajo `CalcEngineeringResult<T>` NEPREMENJEN — komponenta loči !ok → setEngineeringErrors / ok → setLastFingerprint + set*Result; guard načini baluster/angled/material/compliance/cnc/windLocation/glass vračajo `T | null` — komponenta samo set*Result); parsanje, guard pogoji in klici čistih jeder so čist premik; jedra NESPREMJENA (hard rule)
- **EN VIR veriga dispatchev**: prej 2× podvojen if/else blok (handleCalculate + auto-calc useEffect) → 1 pomožnica `izvediIzracunZaAktivniNacin()` + 2 klica [isti vrstni red, isti klici]; import čistost: run*V1 blok + 7 izračunskih funkcij odstranjeni iz taba (tipi OSTANEJO — useState parametri); `calculator-tab` 4.771 → 4.643 vrstic (−128 + val 28)
- **MANDATORY STIL val 28 — parity zaglavij zgodovine/predlog** (vzorec R291/R293 a11y + val 25–27 title parity): Izvozi CSV → title="Izvoz zgodovine izračunov kot CSV datoteka"; Počisti (zgodovina) → aria-label="Počisti zgodovino izračunov" + title="Pobriši celotno zgodovino izračunov" [bralniki zaslonov slišita dvoumno "Počisti" ×2 — zgodovina ALI predloge]; Počisti vse (predloge) → aria-label="Počisti vse predloge" + title="Pobriši vse shranjene predloge"; **0 novih hex**
- **vitest r345 ×26 (2 NOVI datoteki)**: r345-calc-faza5 ×17 [ovonični načini ×4 (rail-v1/anch-v1/wind-v1 + fail-closed !ok veja) + guard načini ×7 (vsak guard + vsak uspeh) + determinizem FULL bajtno + žičenje (uvozni blok + tanke ovojnice) + EN VIR veriga (1 definicija + 2 klica) + jedra IZVEN taba + calculations.ts 0-hex + FAZA 4 regresija] + r345-stil-val28 ×9 [3 parity pari z okni okoli onClick + 0-hex okna + obrnjene regresije val 27 (badge title)/val 26 (prstni odtis + cursor-help ×1)/val 24 (ring ×12 + press-scale)/val 25 (measurements) + R291/R293 vnosni gumb nedotaknjen]
- **`scripts/qa-needles/r345.tsv`** (kanon R340–R344): need_static ×5 [vsi val 28 nizi] + must_miss TODO-R345; iskrena omejitev: FAZA 5 = premik bajtno identičnih teles → NI edinstvenega needleja za SAM premik [pokritost = tsc + vitest ×17 + E2E regresija]
- **README disk resnica**: števci testov ×3 (4870/294 → 4896/296) + vrstična tabela `calculator-tab.tsx` 4.796 → 4.643 + faza 1+2+3+4+5 + R345 bullet [R342 lekcija: stale tabela po lastni rundi — wc -l preverba izvedena]
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND)**: tsc **0** · eslint **0 (FULL)** · vitest **4896/4896 (296 datotek)** = R344 baza 4870/294 + mojih +26/+2 · build svež EXIT=0 [po rm -rf .next; max-old-space 2560] · `qa-round.sh 345 needles` **VSE OK** [celotna veriga R227→…→R339 + union registri r340–r345; val 28 needleji ŽIVO v čankih, TODO čisto] · `qa-round.sh 345 smoke` **EXIT=0** [login 200 + CSRF 403 + ovojnice ×3 → 400 + port sproščen] · `qa-round.sh 345 e2e` **EXIT=0** [Z0ax→Z0be vsi ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana]
- LEKCIJE R345: (1) **pesek-reset reparacijski protokol** [nadgradnja R344 incidenta v protokol]: prisma client izgubljen → `npx prisma generate`; .env spran → restore po .env.example konvenciji `postgresql://roksal:roksal@localhost:5433/roksal_dev`; baza prazna → `bun run db:deploy` (migracije) + `node prisma/seed.cjs` (bazni podatki vključno WPC-120-A) + `bunx tsx tools/create-admin.ts ci@roksal.si …` (smoke fixture); VSE dokumentirane poti, NIČ improvizacije; (2) **`[m` prikazni artefakt orodja**: doslovnost `[m` v izhodu Bash orodja je POJEDENA (ANSI reset interpretacija) — `const [mode,` se prikaže kot `const ode,` → lažni alarm pokvarjene datoteke; disk resnica = `grep -c` + `git show | diff` (blob vs delovno drevo IDENTIČNO) — datoteka NIKOLI bila pokvarjena; prihodnje: sum na korozijsko preverbo NIKOLI ne potrduj po prikazu, vedno grep -c/git; (3) **pipeline `$?` past ×2**: `cmd | tail; echo $?` da tail-ov izhod, ne ukaza — SMOKE_EXIT=0 je bil napačno branje; kanon: `cmd > log 2>&1; echo $?` [fail-verbose, ne tiho]; (4) izvozna skripta era preverbe je zdaj KANONSKA (`r345-era-harvest.sh`) — prihodnje runde jo klonirajo z novim registrom; (5) vitest števec raste tudi z okoljsko reparacijo — 57 FAIL datotek z 0 testi je bilo signal clienta, ne regresije kode
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement/kalkulator jedro NIČ [dispatch premik čistih klicev]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 28 = title/aria atributi); NIČ FNV soli

### Nereseno / tveganja + prioritete R346
- ✅ **Deploy LIVE**: R339+R340+R341+R342+R343 na produ [era dokaz r345-era-harvest.sh]; **R344 [QA-only] + R345 [FAZA 5 + val 28] čakata naslednji zeleni deploy** — R346 prva naloga = `qa-round.sh 345 prod-qa` re-run + era preverba r345.tsv [val 28 needleji ×5 ŽIV pričakuj ob zelenem deployu; TODO-R345 čisto]
- ⚠️ **KOLIZIJSKA VROČINA: 16 kolizij** — fetch-first PRED dev + pred commitom/pushom obvezen; rev-list count PRED dev (LEKCIJA 1)
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3.5 tedna) — obvestiti lastnika (49. zapis)
- R346 kandidati: **kalkulator FAZA 6** [collectCurrentInputs/applyInputs → calculator/inputs.ts z args objekti — isti vzorec; preveri kolizije najprej] ALI **measurements FAZA 5** ALI **e2e-lib dedup** [veliko, previdno] — vedno z fetch-first + TSV kanonom
- ISSUE #1: 65 členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA]
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R350
"""

with open("worklog.md", "a", encoding="utf-8") as f:
    f.write(TXT)

n = sum(1 for _ in open("worklog.md", encoding="utf-8"))
print(f"OK: worklog zdaj {n} vrstic")
