#!/usr/bin/env python3
# R348 — worklog append (kanon r341/r343/r345-worklog-append.py: python
# append z eksplicitnim UTF-8, NIKOLI overwrite).
import io

SEKCIJA = """## R348 — 2026-10-02 (cron tick 202610020200; nadaljevanje po R347; razvoj: measurements FAZA 5 [EN VIR gradnja starejše družine CSV izvozov → measurements/izvoz-csv.ts; 4 stale telesa + 15 inline escapes + 4 inline BOM izginili] + MANDATORY STIL val 31 [a11y parity izvozne družine meritev — 5 gumbov aria/title + ring])

### Status / ocena
- HEAD ob zagonu: `a0e2c24` (R347) — synced 0/0, drevo čisto; fetch-first izveden PRED dev (LEKCIJA 1, 20. raba) in pred commitom
- **PRVA NALOGA (R347 dodelitev) IZVEDENA**: `qa-round.sh 347 prod-qa` re-run **EXIT=0 ob 1. teku** (brez deploy-swap epizode — LEKCIJA R347 1 kanon `agent-browser close --all` pred tekom upoštevan): LIVE veja [EPOCH prod build 17:24:29.646Z > R339 meja 11:24:40], Z2 vsi needleji ŽIVO [R290+…+R346 veriga], Z3 v99 sync gate ŽIVO (fail-closed, ZERO-MUTACIJA)
- **ISKRENO — era preverba r347.tsv (val 30 needleji ×4) NI IZVEDENA**: R347 deploy **ŠE NI pristal** — prod build nepremičen `17:24:29.646Z` (R346 era) celotno rundu (18:04 → 18:40Z), medtem ko je R347 commit `17:58:21Z`; anomalija 45+ min [kanon: 21 s od commita do builda — R346 dokaz]; vzrok NEZNAN (ni dostopa do Vercel dashborda — hard rule read-only inventory); **prenese se na R349 prvo nalogo** (R347+R348 bosta pristala SKUPAJ — en deploy glave repa)
- agent-browser QA: `/prijava` [→ /login] pravilno renderan (naslov, forma E-pošta/Geslo/Prijava, namig create-admin), **0 konzolnih error/opozoril**; close --all kanon po koncu

### Cilji / izvedene spremembe / verifikacija
- **FAZA 5 — NOV EN VIR `measurements/izvoz-csv.ts` (93 vrstic; vzorec kalkulator FAZA 5–7 / R325 pdf-exports)**: `csvEsc` (podvajanje navedkov — 15 inline kopij `(x || '').replace(/"/g, '""')` izginilo iz taba), `csvDokument` (BOM + zaglavje + LF — 4 inline kopije `\\uFEFF + header + \\n + rows.join` izginile), `MERITVE_CSV_HEADER` + `zgradiMeritveVrstice` (17-stolpčni P1 kontrakt — **stale telesi handleExportCSV ≡ handleBulkExportCSV sta bila bajtno identična 2. resnici** [~20 vrstic ×2]; zdaj 1 gradnik, vhodni seznam = klicateljeva resnica: vse ALI samo izbrane); **4 × inline Blob prenos → kanon `downloadCsvText`** (R171/R296; MIME `text/csv;charset=utf-8;` izgubi navlečno piko — VSEBINA datoteke bajtno ista, dokumentirano); `measurements-tab` 6.702 → 6.652 (−50; LEKCIJA R347 2 potrjena: stale kopije dihajo v function telesih ×4); izvozni datumi ostanejo `toISOString().slice(0, 10)` VERBATIM (družinska konsistenznost z R186 klicateljem izvoziMeritveCsv; UTC-vs-lokalni obrobni primer dokumentiran — nič tiho); stebri/audit vrstični gradniki ostanejo lokalni (1 potrošnik — brez podvajanja)
- **MANDATORY STIL val 31 — a11y parity izvozne družine meritev** (vzorec R291/R293 + val 25–30): 5 gumbov dobi `aria-label` + `title` [CSV vse meritve / PDF pregled / bulk CSV izbrane / zgodovina CSV (shadcn Button) / steber-table CSV]; 3 gola `<button>` + steber-table dobi izrecen `focus-visible:ring-2 focus-visible:ring-roksal-navy/40` — **LEKCIJA R346 (val 8 stražar) 2. potrditev ŽIVO**: `r317-stil-val8` stražar je ustavil NOVI aria gumb zgodovine brez izrecnega ringa v družinskem skenu → ring dodan v istem commitu (kanon dela, NI prilagajanja stražarja); **0 novih hex**
- **stale testi = del kontrakta** (iskreno, kanon R347): (a) `r172-dark-spots` vrstični prst `6525 → 6475` [13. premik; zgodovina v komentarju: FAZA 5 −50 nad prstom]; (b) `r317-stil-val8` stražarjeva 2 faila → odpadena z ringom na kodi (nikoli z oslabitvijo stražarja)
- **vitest r348 ×26 (2 NOVI datoteki)**: `r348-meritve-faza5` ×18 [osnovna vrstica z realnimi labeli (RAZDALJA/POTRJENA/beton/słDatumKratko '1. 10. 2026') + multi-unit stolpci + NECITIRAN zadnji datum stolpec (VERBATIM) + fallbacki + podlaga surova vrednost + csvEsc + determinizem ×2 + EN VIR dokaz (vsota delov = celota) + MERITVE_CSV_HEADER bajtno + csvDokument BOM struktura + 0-hex + stale-izginili (new Blob ×0, inline escape ×0, inline BOM ×0, stale header iz taba izginil) + žičenje (zgradiMeritveVrstice ×2 klica, csvDokument ×4, csvEsc ×5, downloadCsvText ×6) + R186 regresija + steber-table a11y] + `r348-stil-val31` ×8 [5 parity skupin z okni + 0-hex + obrnjene regresije R186/R269/R284/R285 vodje + val 30/28 kalkulator]
- **`scripts/qa-needles/r348.tsv`** (python write z \\t — LEKCIJA R346 1 proaktivna; awk NF=3 preverba čisto): need_static ×5 [val 31 aria nizi — novi minifikacijo-preživeči stringi] + must_miss TODO-R348; FAZA 5 = unifikacija → NI edinstvenega needleja za SAM premik (iskrena omejitev: pokritost = tsc + vitest ×18 + E2E)
- **README disk resnica**: števci testov ×3 (4940/300 → 4966/302) + vrstična tabela `measurements-tab.tsx` 6.702 → 6.652 + faza 1+2+3+4+5 + R348 bullet
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL)** · vitest **4966/4966 (302 datoteki)** = R347 baza 4940/298 + mojih +26/+2 − 0 · build svež **EXIT=0** [rm -rf .next; max-old-space 2560; ×2 teka — 2. po ring popravku, kanon "veriga na končni viri"] · `qa-round.sh 348 needles` **VSE OK** [Z-STRUCT-REG r348: 5 need_static ŽIVO + must_miss čisto; veriga R227→…→R339 + union registri r340–r348; 846 OK čank] · `qa-round.sh 348 smoke` **EXIT=0** · `qa-round.sh 348 e2e` **EXIT=0** [Z0ax→Z0be ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana]
- LEKCIJE R348: (1) **pipeline `$?` past — 3. potrditev, tokrat VLASTNA**: `npx tsc | tail; echo $?` je izpisal tail-ov izhodni kod 0, medtem ko je tsc GLASNO odpovedal TS2353 — kanon `cmd > log 2>&1; echo $?` ponovno vpeljan v reflex (R345 lekcija ×2, zdaj ×3); (2) **testni fixtureji = SAMO polja kontrakta**: MeritveVrsticaVhod nima `id` — fixture je nosil izmišljeni `id: 'm1'` (LEKCIJA R347 4 varianta: preveri kontrakt, ne ugibaj); (3) **zadnji stolpec 17-stolpčnega kontrakta je NECITIRAN datum** — asercija `endsWith(',1. 10. 2026')`, ne `toContain('"…')`; (4) **counting asercije štejejo VSE pojavitve** (import + opis komentar + klici — MERITVE_CSV_HEADER ×4, ne ×2) ali izrecno štejejo samo klicne parene
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement/kalkulator jedro NIČ [unifikacija klicev + download mehanika; CSV gradniki bajtno NESPREMENJENI]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 31 = aria/title/ring razredi); NIČ FNV soli; diff: 4 datoteke spremenjene + 5 novih [71 insercij / 98 delecij]

### Nereseno / tveganja + prioritete R349
- ⏳ **R347 deploy PENDING na produ** (40+ min ob zaključku runde): prod build nepremičen `17:24:29.646Z` kljub R347 commitu `17:58:21Z` — anomalija vs. kanon 21 s; če ostane stale → **LASTNIK preveri Vercel dashboard** (mogoča vrsta čakanja / pavza / limit na računu); lokalni build R348 EXIT=0 — koda NI vzrok
- **R349 prva naloga = `qa-round.sh 348 prod-qa` re-run + DVOJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5)** [pričakuj OBA era ŽIV ob zelenem deployu — R347+R348 pristaneta SKUPAJ; NOV kanonski skript r349-era-harvest.sh [klon r347-era-harvest; register razširjen na oba registra] pričakovan]
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3,5 tedna) — obvestiti lastnika (52. zapis)
- R349 kandidati: **measurements FAZA 6** [handleZapisniListCsv/handleTerenPdf/handleZapisniListPdf — preveri kolizije + stale sken TUDI inline JSX blokov — LEKCIJA 2] ALI **e2e-lib dedup** [veliko, previdno] ALI **kalkulator FAZA 8** [ostanki: PDF export wraps? preveri kolizije] — vedno z fetch-first + TSV kanonom
- ISSUE #1: 65 členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA]
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R350

"""

with io.open("/home/z/my-project/worklog.md", "a", encoding="utf-8") as f:
    f.write(SEKCIJA)
print("worklog R348 appended")
