#!/usr/bin/env python3
# r349-worklog-append.py — R349 sekcija (三段式; append-only — kanon).
SEKCIJA = """
## R349 — 2026-10-02 (cron tick 202610020247; nadaljevanje po R348; razvoj: measurements FAZA 6 [EN VIR fetch + fail-verbose DTO pruning terenskih izvozov → NOV measurements/teren-vnosi.ts; 3 stale telesa R269/R284/R285 → 1 gradnik z dialektnim stikalom zKotom] + MANDATORY STIL val 32 [a11y parity akcijskih gumbov meritev + izrecen ring])

### Status / ocena
- HEAD ob zagonu: `afea754` (R348) — synced 0/0, drevo čisto; fetch-first izveden PRED dev (LEKCIJA 1, 21. raba) in pred commitom (čist push, 0 kolizij tej rundi)
- **PRVA NALOGA (R348 dodelitev) IZVEDENA v celoti**: (a) `qa-round.sh 348 prod-qa` re-run **EXIT=0 ob 1. teku** [LIVE veja — EPOCH meja R339; Z2 vsi needleji ŽIVO (R290+…+R339 veriga); Z3 v99 sync gate ŽIVO fail-closed ZERO-MUTACIJA]; (b) **DVOJNA era preverba — NOV kanonski skript `scripts/r349-era-harvest.sh`** [klon r347-era-harvest; OBA registra r347+r348 v ENEM obhodu; žetev 62/62 čankov]: **EXIT=2 — R347+R348 ŠE NI NA PRODU (deploy PENDING — pričakovana veja)**: val 30 ×4 + val 31 ×5 vsi MISS, must_miss TODO-R347/R348 čisto, era kontrole R340/R341/R343/R345 ŽIV; (c) **ISKRENO — deploy anomalija traja**: prod build nepremičen `2026-10-01T17:24:29.646Z` (R346 era) celotno rundu (18:49 → 19:20Z), R347 commit `17:58:21Z` (~80 min stale ob zaključku runde), R348 commit `18:47:18Z`; vzrok NEZNAN (ni dostopa do Vercel dashborda — hard rule read-only inventory); **prenese se na R350 prvo nalogo** (R347+R348+R349 bodo pristali SKUPAJ — en deploy glave repa)
- agent-browser QA: `/prijava` [→ /login] pravilno renderan (naslov, forma E-pošta/Geslo/Prijava, namig create-admin, "Zgrajeno 01.10.2026 ob 19:24:29" = R346 era build — konsistentno s PENDING deployem), **0 konzolnih error/opozoril**; close --all kanon

### Cilji / izvedene spremembe / verifikacija
- **FAZA 6 — NOV EN VIR `measurements/teren-vnosi.ts` (132 vrstic; vzorec FAZA 5/R348 + kalkulator FAZA 5–7)**: `pruneMeritveTerenVrstice` (fail-verbose DTO pruning — ENA kopija prej 3 stale teles; **stale telesi R284 ≡ R285 bajtno identična razen komentarjev — diff dokazal PRED premikom**) + `fetchMeritteTerenVnosi` → kanon `fetchMeritveTerenVnosi` (FRESH fetch /api/measurements?projectId + credentials + res.ok razlog + ne-polje TypeError — R244–R268 precedens); dialektno stikalo `zKotom` nosi OBA bajtna kontrakta EKSPLICITNO (nič tihega): **R269 false** = DTO brez kotStopinje ključa (spread pojavni vzorec `...(opcije.zKotom ? { kotStopinje: kot } : {})`) + brez kot validacije (stale handler ga NI poznal — pokvaren kot ne zlomi terenskega pregleda) ALI **R284/R285 true** = kotStopinje prvorazredni stolpec + validacija + legacy arMetadata.kot fallback (R283 m1/m2 dialekt); tab = samo žičenje: 3 await klici (×1 false + ×2 true); vsak handler ohrani LASTNO UI resnico (dvoklik guard, brez-projekta toast, prazen-seznam toast z lastnim besedilom, uspešni/fail toast, finally); `measurements-tab` 6.653 → 6.448 (−205: stale telesa −218, uvozi +4, val 32 +13; **LEKCIJA R347 2 potrjena ×3: stale kopije dihajo v function telesih**); orotveli `type MeritveTerenVnos` uvoz odstranjen (eslint bi ujel); stale sken inline JSX blokov: createObjectURL ×0, inline escape ×0, inline BOM ×0 (FAZA 5 že čisto)
- **MANDATORY STIL val 32 — a11y parity AKCIJSKIH gumbov, kjer vidno besedilo NE razlaga akcije** (vzorec R291/R293 + val 25–31): (1) predloga meritev apply → `aria-label="Naloži predlogo meritev: {naziv}"` + title (parity val 29 kalkulator); (2) hitro dodajanje ×2 (osnovne + napredne mapi) → `aria-label="Nova meritev: {tip}"` + title (parity R203); (3) glavna enota preklop → `aria-label="Nastavi glavno enoto: {enota}"` + title (parity R186); (4) stopnična predloga load → `aria-label="Naloži stopnično predlogo: {naziv}"` + title; vsi 4 skupini dobi izrecen `focus-visible:ring-2 focus-visible:ring-roksal-navy/40` **V ISTEM commitu** (LEKCIJA R346 val 8 stražar kanon; amber/50 register ostane zaklenjen v vodji ×11); **0 novih hex**
- **stale testi = del kontrakta** (iskreno, kanon r341/r346/r348): (a) `r269` okno handler → EN VIR žičenje (`fetchMeritveTerenVnosi(selectedProject, { zKotom: false })`) + okno na modulu (fetch/HTTP/ne-polje/prune stringi preusmerjeni na teren-vnosi.ts); (b) `r277` 3 komponentne trditve (verzija/vir DTO) → modul + žičenje toContain; (c) `r172` prst 6475 → 6271 (14. premik; zgodovina v komentarju: FAZA 6 −204 nad prstom)
- **vitest r349 ×26 (2 NOVI datoteki)**: `r349-meritve-faza6` ×18 [oba dialekta (ključ izostane/prisoten) + legacy fallback SAMO pri true + fail-verbose VERBATIM ×8 napak (id/createdAt/fizikalni/verzija/vir/kotStopinje/arMetadata ×3) + arMetadata toleranca (null/undefined/'' → default null) + status fallback EN VIR + determinizem OBA dialekta + fetch wrapper ×3 (URL+credentials / HTTP 503 razlog / ne-polje / happy path) + EN VIR dokaz (await klici ×1+×2, 0 stale kopij — `const vrstice = data as` izginil) + kontraktna EKSPLICITNOST + 0-hex] + `r349-stil-val32` ×8 [4 parity skupine z okni + 0-hex + obrnjena regresija val 31 (5 aria: 4 v tabu + steber-table v measurements/ mapi — iskren lokacijski popravek; niz v r348.tsv je need_static na buildu, vir je v komponenti) + val 30 kalkulator]
- **LEKCIJE R349**: (1) **oxc parse "Unterminated string" lahko pomeni MOJO tipkarjsko napako** — zaključni `'` napačno zapisan kot `` ` `` (Write orodje ni krivo); minimalna replika z `rolldown/experimental transformSync` izolirala napako na 2 vrstici; bisect-prefix metaoda LAŽE pri nepopolnih funkcijah (EOF napake so pričakovane) — išči specifični "Unterminated string"; (2) **oknoMed do_ marker je EKSKLUZIVEN** — okno, ki se konča TOČNO na iskani niz, niz NE vsebuje (uporabi marker, ki je PO aserciranem nizu — npr. `</button>`, `truncate`, `<Icon`); (3) **template literal aria v viru vsebuje ${...}** — needle = STATIČNI predponi del (minifikacija ohrani kos kot string literal — r349.tsv ×8 ŽIVO na buildu potrjeno); (4) **komentarji vsebujejo iste nize kot klici** — štej `await ` klice ali izrecno loči (LEKCIJA R348 4 2. potrditev)
- **`scripts/qa-needles/r349.tsv`** (python write z eksplicitnim \\t — LEKCIJA R346 1; awk NF=3 preverba čisto): need_static ×8 [val 32 statični predponi deli/diskriminatorni celoti — ×8 ŽIVO v build čankih] + must_miss TODO-R349; FAZA 6 = premik teles → NI edinstvenega needleja za SAM premik (iskrena omejitev: pokritost = tsc + vitest ×18 + E2E regresija)
- **README disk resnica**: števci testov ×3 (4966/302 → 4992/304) + vrstična tabela `measurements-tab.tsx` 6.652 → 6.448 + faza 1+2+3+4+5+6 + R349 bullet + **R348 vstavljanje popravljeno**: orotveli R347 verifikacijski rep (2 vrstici za R348 bulletom) vrnjen na svoje mesto v R347 bullet (iskren README higienski popravek — artefakt R348 vstavljanja)
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL)** · vitest **4992/4992 (304 datoteki)** = R348 baza 4966/302 + mojih +26/+2 − 0 · build svež **EXIT=0** [rm -rf .next; max-old-space 2560] · `qa-round.sh 349 needles` **VSE OK** [Z-STRUCT-REG r349: 8 need_static ŽIVO + must_miss čisto; veriga R227→…→R339 + union registri r340–r349; 872 OK čank] · `qa-round.sh 349 smoke` **EXIT=0** · `qa-round.sh 349 e2e` **EXIT=0** [Z0ax→Z0be ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana]
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement/kalkulator jedro NIČ [unifikacija klicev; CSV/PDF gradniki bajtno NESPREMENJENI]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 32 = aria/title/ring razredi); NIČ FNV soli; diff: 5 datotek spremenjenih + 7 novih [94 insercij / 269 delecij tracked]

### Nereseno / tveganja + prioritete R350
- ⏳ **R347+R348 deploy ŠE VEDNO PENDING na produ** (~80 min R347 ob zaključku runde): prod build nepremičen `17:24:29.646Z` (R346 era) — anomalija vs. kanon 21 s; če ostane stale → **LASTNIK preveri Vercel dashboard** (mogoča vrsta čakanja / pavza / limit na računu); lokalni build R349 EXIT=0 — koda NI vzrok
- **R350 prva naloga = `qa-round.sh 349 prod-qa` re-run + TROJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5) IN `r349.tsv` (val 32 ×8)** [pričakuj VSE tri era ŽIV ob zelenem deployu — R347+R348+R349 pristajo SKUPAJ; kanonski skript r350-era-harvest.sh [klon r349-era-harvest; register razširjen na tri registre] pričakovan]
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3,5 tedna) — obvestiti lastnika (53. zapis)
- R350 kandidati: **measurements FAZA 7** [ostanki: kopirajMeritvePovzetek + audit/steber gradniki — preveri kolizije + stale sken TUDI inline JSX blokov — LEKCIJA 2] ALI **kalkulator FAZA 8** [ostanki: PDF export wraps? preveri kolizije] ALI **e2e-lib dedup** [veliko, previdno] — vedno z fetch-first + TSV kanonom
- ISSUE #1: 65 členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA]
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R350
"""

with open('/home/z/my-project/worklog.md', 'a', encoding='utf-8') as f:
    f.write(SEKCIJA)
print('worklog R349 sekcija dodana')
