#!/usr/bin/env python3
# r350-worklog-append.py — R350 tridelni append (kanon r349-worklog-append.py).
# Append-only: vsebina gre NA KONEC worklog.md (nikoli overwrite).
import datetime

SEKCIJA = """
---
## R350 — MEASUREMENTS FAZA 7 (ostanki starejše izvozne družine EN VIR + seznam PDF gradnik) + MANDATORY STIL val 33

### Stanje / ocena ob prevzemu (adoption protokol — git resnica, ne povzetek verige)
- HEAD = `5660dfe` (R349) PRISPEL, drevo čisto, 0 neprispelega — operativna runda = **R350** (tick `202610020330`, 03:30 +08:00, Job 413422). Povzetek verige je bil STALE (trdil R317) — adoption protokol prevzel.
- **PRVA NALOGA iz R349 izpolnjena**: (1) `qa-round.sh 349 prod-qa` re-run **EXIT=0 ob 1. teku** [LIVE veja — EPOCH meja R339; Z2 vsi needleji ŽIVO; Z3 v99 gate ZERO-MUTACIJA]; (2) **NOV kanonski skript `r350-era-harvest.sh`** [TROJNA era preverba — VSI trije registri r347+r348+r349; žetev 62/62 čankov]: **EXIT=2** — R347+R348+R349 ŠE VEDNO NI NA PRODU [vsi 17 val 30/31/32 need_static MISS; must_miss čisto; era kontrole R340/R341/R343/R345 ŽIV] — ISKRENO: prod build še nepremičen `17:24:29.646Z` (R346 era); R347 commit `17:58:21Z` je ob zaključku runde stal ~92 min — anomalija traja (vzrok neznan; ni dostopa do Vercel dashborda, hard rule read-only).
- **agent-browser QA**: `/prijava` → redirect `/login` pravilno renderan [R logotip, e-pošta + geslo, Prijava, build žig = "Zgrajeno 01.10.2026 ob 19:24:29 (Europe/Ljubljana)" = 17:24:29Z R346 era — KONSISTENTEN z EPOCH]; 0 resničnih konzolnih errorjev [rAF warning = benigni 3D viewer ostanki pred redirectom]; 404 pri časovnem oknu pred redirectom = prehodna stran, ne bug. Brez bugov → development-first (issue #1 AGENT STARTUP RULE).

### Cilji / spremembe / verifikacija
- **FAZA 7 — ostanki starejše izvozne družine EN VIR** (vzorec FAZA 5/R348 + FAZA 6/R349 + kalkulator FAZA 2/R325):
  - `measurements/izvoz-csv.ts` razširitev (94 → 158 vrstic): **STEBRI_CSV_HEADER + zgradiStebriVrstice** (8-stolpčni R156 per-segment kontrakt; em-dash '—' za brez-razmik VERBATIM) + **ZGODOVINA_CSV_HEADER + zgradiZgodovinaVrstice** (6-stolpčni LOKALNI zgodovina kontrakt) — oba vrstična gradnika VERBATIM iz taba (prej inline `.map()` telesa). **Kolizija preverjena in zavrnjena**: `lib/audit-csv.ts` (R162) = SISTEMSKA revizijska sled (Uporabnik/Vloga/E-pošta/IP kontrakt) — druga družina, NE kolizija.
  - **NOV `measurements/pdf-seznam.ts`** (196 vrstic; vzorec R325 pdf-exports + **r269 build/generate razcep**): `buildSeznamPdfDoc` (čist gradnik — 85-vrstični inline jsPDF blok [glava navy + povzetek 7 vrstic + autoTable 9 stolpcev + noga] izluščen iz taba — ZADNJI veliki inline izvozni gradnik) + `exportSeznamPdf` (tanki wrapper; guard + toasti + ime datoteke ostanejo klicateljeva resnica). **ENA eksplicitna odstopka od VERBATIM (iskreno, kanon r269/document-pdf R121 — 100% determinizem)**: `doc.setCreationDate(izvozenoOb)` + `doc.setFileId(FNV-1a)` — trailer /ID je sicer jsPDF NAKLJUČEN [diagnoza: 2 teka iste vhoda → razlika @8715 samo v /ID hex]; čista JS FNV-1a, **NOVI soli 0xd9–0xdc** [register: do sedaj najvišji 0xd8; LEKCIJA: ista semena v dveh modulih NE smejo dati isti ID]. Glifna resnica helvetica (č/š/ž prek WinAnsi ne renderirajo) = OBSTOJEČA — izven FAZA kontrakta; kandidat R351 prek registerSloPdfFonts vzorca r269.
  - Determinizem: povzetek številke = klicateljeva izpeljava (totalLength/avgHeight/stSegmentov/najdalsaDolzinaMm/totalArea/statusCounts — ISTA resnica kot KPI kartice WYSIWYG); `izvozenoOb: Date` = vhod (noga + CreationDate).
  - Tab: uvozi posodobljeni (csvEsc odpadel — nič več direktnih klicev), handleExportStebriCSV + handleExportAuditCSV zdaj `csvDokument(HEADER, zgradiVrstice(seznam))` ENOVRSTIČNO, handleExportPDF 85 → 20 vrstic žičenja; `measurements-tab` 6.448 → **6.386** (−62: stale telesa −~50 + PDF blok −85 + uvozi/komentarji + val 33 +73).
- **MANDATORY STIL val 33 — a11y parity skupinske akcije / izbira** (bulk orodna vrstica): 4 brata **Izberi vse / Počisti / Kopiraj / Izbriši izbrane** dobi aria-label + title + izrecen focus ring navy/40 **V ISTEM commitu** (LEKCIJA R346 kanon; parity val 31 brata 'Izvozi izbrane CSV' v ISTI vrstici; 'Kopiraj' = vidno besedilo NE razlaga CILJA). 0 novih hex (navy/40 = obstoječi token).
- **VITEST r350 ×29** (2 NOVI datoteki): `r350-meritve-faza7` ×21 [stebri/zgodovina realni labeli + fallbacki + csvEsc RFC 4180 + determinizem + header bajtni kontrakti + kolizija-dokaz + buildSeznamPdfDoc bajtni determinizem (enak vhod = enak; drug izvozenoOb = drugačen) + %PDF- magija + prazen seznam dovoljen v gradniku + wrapper IME=klicatelj + VERBATIM dokaz (literali v modulu, IZGINILI iz taba) + stale-izginili + žičenje counting ×4 [LEKCIJA R349: import + komentar + klic] + FAZA 5/6 regresija + 0-hex + TODO čisto] + `r350-stil-val33` ×8 [4 parity skupine + strukturni dokaz aria↔ring v istem bloku + 0-hex + obrnjena regresija val 31/32].
- **Stale testi = del kontrakta (iskreno, z zgodovino v komentarju)**: (1) r348 žičenje csvEsc 5 → 0 v tabu + modul ≥3 (15. premik prsta-združljiv zapis; zgodovina 14. premik r172 v R349); (2) r172 prst 6271 → **6209** z R350 zgodovino [LEKCIJA R330 veriga nadaljevana].
- **Register + README disk resnica**: `scripts/qa-needles/r350.tsv` [9 need_static = PDF glava 'ROKSAL — Seznam meritev' (modul string literal) + val 33 ×8 statičnih aria/title nizov + must_miss TODO-R350; python write z \\t; awk NF=3 čisto] + README: števci ×3 (4992/304 → 5021/306) + tabela 6.448 → 6.386 faza 1..7 + R350 bullet.
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL, npm run lint)** · vitest **5021/5021 (306 datotek)** = R349 baza 4992/304 + mojih +29/+2 − 0 [1. tek 1 fail = r172 prst stale → 15. premik → zeleno] · build svež **EXIT=0** [rm -rf .next; max-old-space 2560] · `qa-round.sh 350 needles` **VSE OK** [9 need_static ŽIVO + must_miss čisto; veriga R227→…→R339 + union registri r340–r350; 882 OK čank] · `qa-round.sh 350 smoke` **EXIT=0** · `qa-round.sh 350 e2e` **EXIT=0** [Z0ax→Z0be ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement/kalkulator jedro NIČ [izvozni gradniki = premik teles + 2 eksplicitni deterministični izboljšavi dokumentirani; CSV/PDF izvozi vsebinsko bajtno enaki]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 33 = aria/title/ring token razredi); NOVI FNV soli 0xd9–0xdc (registrirana — jedro nič).

### Nereseno / tveganja + prioritete R351
- ⏳ **R347+R348+R349 deploy ŠE VEDNO PENDING na produ** (~92+ min R347 ob zaključku te runde): prod build nepremičen `17:24:29.646Z` (R346 era) — anomalija vs. kanon 21 s traja čez tri commita [R347 17:58Z → R348 → R349 19:27Z]; TROJNA era preverba EXIT=2 (17 need_static MISS, must_miss čisto, starejše era kontrole ŽIV — žeteva zdrava). Lokalni build R350 EXIT=0 — koda NI vzrok. **LASTNIK: preveri Vercel dashboard** (čakalna vrsta / pavza / limit; hard rule read-only — ne morem diagnosticirati dalje).
- **R351 prva naloga = `qa-round.sh 350 prod-qa` re-run + ŠTIRIJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5) IN `r349.tsv` (val 32 ×8) IN `r350.tsv` (val 33 ×9)** [pričakuj VSE štiri era ŽIV ob zelenem deployu — R347+R348+R349+R350 pristajo SKUPAJ; kanonski skript r351-era-harvest.sh [klon r350-era-harvest; 4 registri, ≥26 need_static] pričakovan].
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3,3 tedna) — obvestiti lastnika (54. zapis).
- R351 kandidati: **helvetica → registerSloPdfFonts v pdf-seznam.ts** (r269 vzorec — popravi č/š/ž glife v seznam PDF; ENA vsebinska sprememba izvoza, ločena runda) ALI **measurements FAZA 8** [sken: ostanki inline JSX blokov + audit/steber handlerji ostanki — preveri kolizije] ALI **e2e-lib dedup** [veliko, previdno] — vedno z fetch-first + TSV kanonom.
- ISSUE #1: 65+ členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R351.
"""

with open('worklog.md', 'a', encoding='utf-8') as f:
    f.write(SEKCIJA)

print(f"worklog.md appended ({len(SEKCIJA.splitlines())} vrstic)")
