#!/usr/bin/env python3
# r351-worklog-append.py — R351 tridelni append (kanon r350-worklog-append.py).
# Append-only: vsebina gre NA KONEC worklog.md (nikoli overwrite).
SEKCIJA = """
---
## R351 — pdf-seznam GLIFNI POPRAVEK (helvetica → registerSloPdfFonts, r269 vzorec) + MANDATORY STIL val 34 (filter čipi a11y parity)

### Stanje / ocena ob prevzemu (adoption protokol — git resnica, ne povzetek verige)
- HEAD = `b33eecf` (R350) PRISPEL, drevo čisto, 0 neprispelega — operativna runda = **R351** (tick `202610020409`, 04:00 +08:00, Job 413422).
- **PRVA NALOGA iz R350 izpolnjena**: (1) `qa-round.sh 350 prod-qa` re-run **EXIT=0 ob 1. teku** [LIVE veja — EPOCH meja R339; Z0–Z3 vsi ŽIVO]; (2) **NOV kanonski skript `r351-era-harvest.sh`** [ŠTIRIJNA era preverba — VSI štirje registri r347+r348+r349+r350; žetev 62/62]: **EXIT=2** — R347+R348+R349+R350 ŠE VEDNO NI NA PRODU [val 30 ×4 + val 31 ×5 + val 32 ×8 + val 33 ×8 MISS — SKUPAJ 25 MISS; must_miss ×4 čisto; era kontrole R340/R341/R343/R345 ŽIV] — ISKRENO: prod build še nepremičen `17:24:29.646Z` (R346 era); anomalija vs. kanon 21 s traja čez PET commitov [R347 17:58Z → R348 → R349 19:27Z → R350 19:59Z]; vzrok neznan (ni dostopa do Vercel dashborda, hard rule read-only).
- **NOVO ODKRITIE (iskreno)**: needle 'ROKSAL — Seznam meritev' iz r350 registra je bil ŽIV v harvestu — ker string obstaja v tabu ŽE PRED R350 (stari inline PDF gradnik ga je nosil) → NI R350 era-diskriminator (prisotnost = OK, era-trditev = netočna); popravljenega opisa NI tiho urejal — dokumentirano tu + v r351.tsv komentarju (r350 register ostane kot prisnostni needle). Enako NI diskriminator za R351 font spremembo: 'RobotoSl-Regular.ttf' je v measurements čankih ŽE od R269 (lib/meritve-teren-pdf uvaža pdf-sl-font).
- **agent-browser QA**: `/login` pravilno renderan [R logotip + forma E-pošta/Geslo required + Prijava]; 0 resničnih konzolnih errorjev. Brez bugov → development-first (issue #1 AGENT STARTUP RULE).

### Cilji / spremembe / verifikacija
- **GLIFNI POPRAVEK — `measurements/pdf-seznam.ts` (197 → 205 vrstic; r269 vzorec)**: standard helvetica (WinAnsi) NI nosil č/š/ž [glava 'ROKSAL — Seznam meritev', povzetek 'Število meritev', tabela 'Dolžina/Višina/Kot/Datum' — vsi pokvarjeni v izvozu] → **registerSloPdfFonts(doc)** (Roboto subset latin-ext, 23 KB na varianto, base64 lib/pdf-sl-font-data) + 4 × setFont Roboto [glava bold/normal + povzetek bold/normal; autoTable podeduje trenutni font — tabela sedaj Roboto]. **ENA vsebinska sprememba izvoza — iskreno dokumentirana** (R350 komentar je jo naznanil kot kandidata; izvoženi PDF se SPROTI spremeni — vgrajeni fonti + pravilni glifi), determinizem čist [enak vhod = bajtno enak; registerSloPdfFonts idempotenten na dokumentu; b64 konstante = statični modul].
- **GLIFNA ZMOGLJIVOST — bajtni dokaz**: `/FontFile2` (vgrajen TrueType) v izhodu — standard-14 helvetica PDF NIMA vgrajenih tokov [diagnoza: npx tsx 2-teka; FontFile2 prisoten, determinizem EQUAL true]. ROBUSTNOST r350 strukture: FNV soli 0xd9–0xdc + VERBATIM literali + wrapper IME=klicatelj NESPREMENJENI.
- **MANDATORY STIL val 34 — a11y parity filter čipi družina** (measurements-tab): status čipi ×4 [Vse/Osnutek/Potrjena/Arhivirana] dobi **aria-pressed={isActive}** [REALNO toggle stanje — bralnik zaslona pove pritisnjeno/ne-pritisnjeno] + aria-label `Filtriraj po statusu: ${label} (${count})` + title `Pokaži meritve statusa ${label} (${count})` + izrecen ring navy/40 **V ISTEM commitu**; Foto mere pill dobi aria-pressed={fotoFilterActive} + NOV aria-label 'Foto mere filter: prikaži samo meritve zajete na foto zavihku' + ring (title pariteta ostane). 0 novih hex. `measurements-tab` 6.386 → 6.391 (+5: 4 × aria/title vrstice + ring širi obstoječi className).
- **VITEST r351 ×18** (2 NOVI datoteki): `r351-pdf-font` ×10 [vir: import+klic PRED prvo setFont (pozicijski dokaz iNew<iReg<iFont) + 4 × Roboto counting + 0 × helvetica setFont + komentar zgodovina; determinizem čist z Roboto ×2; FontFile2 glifni dokaz; %PDF- magija + prazen seznam; wrapper NESPREMENJEN; VERBATIM literali + FNV soli regresija; družinska konsistenznost r269 [ISI registerSloPdfFonts v meritve-teren]] + `r351-stil-val34` ×8 [status čipi aria-pressed + template prefixi + ring struktura; foto pill aria-pressed + NOV aria + ring; 0-hex; obrnjena regresija val 31/33].
- **Stale test = del kontrakta**: r172 prst 6209 → **6214** z R351 zgodovino (val 34 +4 vrstice nad prstom) [LEKCIJA R330 veriga; 16. zapis prsta]. LEKCIJA: predlagaj +4 → dejansko +5 — ŠTEJ VRSTICE iz diska, ne ugibaj (2. tek popravil).
- **Register + README disk resnica**: `scripts/qa-needles/r351.tsv` [3 need_static = val 34 statični predponi deli/celoti + must_miss TODO-R351; python write z \\t; awk NF=3 čisto; komentarji dokumentirajo NE-diskriminatornost 'ROKSAL — Seznam meritev' + 'RobotoSl-Regular.ttf'] + README: števci ×3 (5021/306 → **5039/308**) + tabela 6.386 → 6.391 + R351 bullet.
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL, npm run lint)** · vitest **5039/5039 (308 datotek)** = R350 baza 5021/306 + mojih +18/+2 − 0 [1. tek 1 fail = r172 prst stale → 16. zapis → zeleno; 2. tek 2. fail = prst +4 → dejansko +5 → 3. tek zeleno] · build svež **EXIT=0** [rm -rf .next; max-old-space 2560] · `qa-round.sh 351 needles` **VSE OK** [3 need_static ŽIVO + TODO-R351 čisto; veriga R227→…→R339 + union registri r340–r351; 886 OK čank] · `qa-round.sh 351 smoke` **EXIT=0** · `qa-round.sh 351 e2e` **EXIT=0** [Z0ax→Z0be ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement/kalkulator jedro NIČ [pdf-seznam = glifni poprav dokumentiran; CSV gradniki NESPREMENJENI]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 34 = aria-pressed/aria/title/ring token razredi); NIČ novih FNV soli (0xd9–0xdc regresija potrjena).

### Nereseno / tveganja + prioritete R352
- ⏳ **R347+R348+R349+R350 deploy ŠE VEDNO PENDING na produ** (~2,2 h R347 ob zaključku te runde): prod build nepremičen `17:24:29.646Z` (R346 era) — anomalija čez PET commitov; ŠTIRIJNA era preverba EXIT=2 (25 need_static MISS, must_miss ×4 čisto, starejše era kontrole ŽIV — žeteva zdrava 62/62). Lokalni build R351 EXIT=0 — koda NI vzrok. **LASTNIK: preveri Vercel dashboard** (čakalna vrsta / pavza / limit; hard rule read-only — ne morem diagnosticirati dalje).
- **R352 prva naloga = `qa-round.sh 351 prod-qa` re-run + PETERIJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5) IN `r349.tsv` (val 32 ×8) IN `r350.tsv` (val 33 ×9) IN `r351.tsv` (val 34 ×3)** [pričakuj VSE pet era ŽIV ob zelenem deployu — R347–R351 pristajo SKUPAJ; kanonski skript r352-era-harvest.sh [klon r351; 5 registrov, ≥29 need_static] pričakovan].
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3,2 tedna) — obvestiti lastnika (55. zapis).
- R352 kandidati: **measurements FAZA 8** [sken: ostanki inline JSX blokov + status cycle / zgodovina toggle handler ostanki — fetch-first + kolizije] ALI **helvetica glifni poprav za druge inline PDF-e** [sken kateri ostali izvozi še standardni font — fetch-first] ALI **e2e-lib dedup** [veliko, previdno] — vedno z TSV kanonom.
- ISSUE #1: 65+ členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R352.
"""

with open('worklog.md', 'a', encoding='utf-8') as f:
    f.write(SEKCIJA)

print(f"worklog.md appended ({len(SEKCIJA.splitlines())} vrstic)")
