#!/usr/bin/env python3
# r352-worklog-append.py — R352 tridelni append (kanon r351-worklog-append.py).
# Append-only: vsebina gre NA KONEC worklog.md (nikoli overwrite).
SEKCIJA = """
---
## R352 — kalkulator pdf-exports GLIFNI POPRAVEK (helvetica → registerSloPdfFonts, r269/R351 vzorec) + MANDATORY STIL val 35 (dialog Shrani a11y parity)

### Stanje / ocena ob prevzemu (adoption protokol — git resnica, ne povzetek verige)
- HEAD = `47cc75b` (R351) PRISPEL, drevo čisto, 0 neprispelega — operativna runda = **R352** (tick `202610020435`, 04:30 +08:00, Job 413422).
- **PRVA NALOGA iz R351 izpolnjena**: (1) `qa-round.sh 351 prod-qa` re-run — **1. tek FAIL (transient: masa need_static MISS ob LIVE EPOCH žigu = omrežni flake pri žetvi čankov; zapisano iskreno), 2. tek EXIT=0** [LIVE veja — prod build `2026-10-01T20:35:08.778Z`; Z2 vsi needleji ŽIVO; Z3 v99 gate ZERO-MUTACIJA; footer `=== R339 PROD QA — R290+…+R339 ŽIVO SKUPAJ ===`]; (2) **NOV kanonski skript `r352-era-harvest.sh`** [PETERIJNA era preverba — VSI pet registr r347+r348+r349+r350+r351; žetev 62/62; ≥29 need_static]: **EXIT=0 ob 1. teku** — R347 val 30 (×4) + R348 val 31 (×5) + R349 val 32 (×8) + R350 val 33 (×9) + R351 val 34 (×3) **VSE ŽIVO NA PRODU**; must_miss ×5 čisto; era kontrole R340/R341/R343/R345 ŽIV.
- ⭐ **DEPLOY ANOMALIJA REŠENA**: prod build skočil s stale `17:24:29.646Z` (R346 era) → **`2026-10-01T20:35:08.778Z`** > R351 commit `20:34:48Z` (20 s — kanon!). Vseh PET zaporednih commitov (R347–R351, 17:58Z–20:34Z) je pristalo SKUPAJ v enem deployu 20:35:08Z — backlog zbrisan; agent-browser build žig 'Zgrajeno 01.10.2026 ob 22:35:08 (Europe/Ljubljana)' KONSISTENTEN.
- **agent-browser QA**: `/prijava` rendera 404 ZA autentificirano sejo — **NI bug**: proxy 307 → `/login?next=/prijava` velja samo za anonimne [curl dokaz: 307 brez piškotka], agent-browser pa nosi ŽIVO httpOnly sejo `spot-r165@roksal.si` (MONTER, /api/auth dokaz) → proxy spusti → neobstoječa ruta → korekten 404 (redirectCount=0, pravilno vedenje; v skladu z R350 opazbo). `/login` anonimno ✓; `/` (vizualizacija) ✓; Meritve tab ✓ [Field Manager v2.5, iskren prazen seznam brez projektov, laser status]; 0 resničnih konzolnih errorjev. Brez bugov → development-first (issue #1 AGENT STARTUP RULE).

### Cilji / spremembe / verifikacija
- **GLIFNI POPRAVEK — `calculator/pdf-exports.ts` (+56/−29 po numstatu; r269/R351 vzorec)**: standard helvetica (WinAnsi) NI nosil č/š/ž — VSEH **29 setFont mest × 5 gradnikov** [predloga vrtanja / materialni list / razrezni list CNC / vetrno poročilo / steklena balustrada] je nosilo pokvarjene glife ['Širina palice', 'Število palic (z rezervo)', 'Število letvev (top+bottom)', 'Širina reza', 'Število profilov', 'Število' tabelna glava, 'Akontacija — ob naročilu' ...] → **registerSloPdfFonts(doc)** ×5 (po new jsPDF, pred prvo setFont; idempotentno) + setFont Roboto (15 bold + 14 normal; autoTable podeduje — didParseCell fontStyle bold pade na Roboto bold). **ENA vsebinska sprememba izvoza — iskreno dokumentirana** (glava modula: izvoženi PDF-i se SPROTI spremenijo — vgrajeni fonti + pravilni šumniki; vsebina/izračuni NESPREMENJENI; časovni žigi new Date/Date.now = OBSTOJEČA klicateljeva resnica tega modula — izven R350/R351 build/generate kontrakta, NI regresija). Kalkulator jedro (@/lib/calculator) NIČ — modul je render plast R325.
- **GLIFNA ZMOGLJIVOST — bajtni dokaz v testih**: `/FontFile2` (vgrajen TrueType) v izhodu exportBalusterPdf + exportGlassPdf — standard-14 helvetica NIMA vgrajenih tokov; getFontList: Roboto normal+bold registrirana.
- **MANDATORY STIL val 35 — a11y parity dialog "Shrani" bratov** (vidno besedilo 'Shrani' NE razlaga CILJA — LEKCIJA R346 kanon: aria-label akcija+cilj + title + izrecen ring navy/40 V ISTEM commitu): (1) logistika razpored `Shrani nov razpored [v proizvodnjo]` (ring ŽE od val 30); (2) logistika ekipa `Shrani novo ekipo [v proizvodnjo]` + **NOV ring**; (3) logistika oprema `Shrani novo opremo [v zalogo opreme]` (ring ŽE od val 32); (4) materialna inteligenca dobavitelj `Shrani novega dobavitelja [v register dobaviteljev]` + **NOV ring**. 0 novih hex. LEKCIJA JSX: `{/* komentar */}` je NEVELJAVEN znotraj `&& ( )` izraznega oklepaja — komentar pred pogojni blok (1. poskus → takoj popravljeno; tsc 0).
- **VITEST r352 ×18** (2 NOVI datoteki): `r352-kalkulator-font` ×10 [vir: import + 5 × registerSloPdfFonts + pozicije PER gradnik (iNew<iReg<iFont v vsakem segmentu) + 0 × helvetica + counting 15/14 + zgodovina komentar + VERBATIM regresija glave/toasti/ime datoteke; GLIFNA ZMOGLJIVOST na ujetih dokumentih (Baluster + Glass: %PDF- + FontFile2 + getFontList) + GLIFNA STABILNOST ×2 teka + družinska konsistenznost 3 potrošniki ENEGA modula [teren r269 + seznam R351 + kalkulator R352] + jedro NIČ dokaz [lib/calculator NE uvaža pdf-exports]] + `r352-stil-val35` ×8 [4 bratje aria/title + ring struktura v ISTEM bloku + 0-hex + obrnjena regresija val 33/34]. **LEKCIJA jsPDF 4.x**: konstruktor dodeli `save` kot INSTANČNO own property [senči podrazredno metodo; NI niti === API.save] — spyOn(jsPDF.API,'save') vrne 'property not defined', podrazred-override se ne kliče; rešitev = vi.mock('jspdf') s podrazredom, ki po super() piše čez instančno save (ujem brez prenosa; pravi konstruktor + pravi autoTable + pravi output). Stranski učinek 2. (pokvarjenega) teka: 8 testnih PDF-ov v repo rootu — **izbrisanih**, NI commitanih.
- **Register + README disk resnica**: `scripts/qa-needles/r352.tsv` [8 need_static = val 35 statične aria/title celote (NOVI nizi = era-diskriminatorji) + must_miss TODO-R352; awk NF=3 čisto; komentar dokumentira NE-diskriminatornost glifnega popravka (registerSloPdfFonts v čankih ŽE od R269)] + README: števci ×3 (5039/308 → **5057/310**) + R352 bullet [glifni popravek + val 35 + vitest + LEKCIJA jsPDF].
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** (×2: po val 35 urejanjih + na končnih virih) · eslint **0 (FULL, npm run lint)** · vitest **5057/5057 (310 datotek)** = R351 baza 5039/308 + mojih +18/+2 − 0 [EXIT=0 ob 1. teku — brez stale testov] · build svež **EXIT=0** [rm -rf .next; max-old-space 2560] · `qa-round.sh 352 needles` **VSE OK** [8 need_static ŽIVO + TODO-R352 odsoten; strukturna preverba registra 9 vrstic; veriga R227→…→R339 + union registri r340–r352] · `qa-round.sh 352 smoke` **EXIT=0** [ovojnice 400 + { error } — ISTA EN VIR] · `qa-round.sh 352 e2e` **EXIT=0** [Z0ax→Z0be ŽIVO + ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; kalkulator jedro NIČ [pdf-exports = render plast, glifni poprav dokumentiran; @/lib/calculator uvozni kontrakt NESPREMENJEN]; measurement jedro NIČ; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 35 = aria/title/ring token razredi); NIČ novih FNV soli.

### Nereseno / tveganja + prioritete R353
- ✅ Deploy anomalija REŠENA (R347–R351 ŽIVO na produ, PETERIJNA era preverba EXIT=0) — ni več lastnikove akcije; Vercel dashboard ni več blokator.
- **R353 prva naloga = `qa-round.sh 352 prod-qa` re-run + ŠESTIJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5) IN `r349.tsv` (val 32 ×8) IN `r350.tsv` (val 33 ×9) IN `r351.tsv` (val 34 ×3) IN `r352.tsv` (val 35 ×8)** [pričakuj VSE šest era ŽIV — R352 pride na produ sam; kanonski skript r353-era-harvest.sh [klon r352; 6 registrov, ≥37 need_static] pričakovan].
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3,2 tedna) — obvestiti lastnika (56. zapis).
- R353 kandidati: **helvetica glifni popravek za preostale inline PDF-e** [sken: reference-gallery.tsx ×6 + post-signature-panel.tsx + signature-quote.tsx + floor-plan-tab.tsx — fetch-first, kateri nosijo č/š/ž] ALI **measurements FAZA 8** [ostanki inline JSX + handlerji — fetch-first + kolizije] ALI **e2e-lib dedup** [veliko, previdno] — vedno z TSV kanonom.
- ISSUE #1: 65+ členov izpolnjenih (Deliverables 7/7 ✓); issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- Arhiv: lokalni branch `r249-moja-delta` [49c77c7] — NIKOLI pushati; brisati lahko po R353.
"""

with open('worklog.md', 'a', encoding='utf-8') as f:
    f.write(SEKCIJA)

print(f"worklog.md appended ({len(SEKCIJA.splitlines())} vrstic)")
