#!/usr/bin/env python3
# r360-worklog-append.py — R360 worklog vnos (kanon: python append, nič ne
# prepisujemo — lepo na konec, po R359 sekciji).
VNOS = """
---
Task ID: R360
Agent: Super Z (cron tick 1a0d7c0831c23029-cron-agent-loop-202610021045, Job 413422)
Task: R360 — prva naloga (prod-qa re-run prek r359-prod-qa-retry.sh + TRIJESTIJNA era preverba r347–r359) + agent-browser QA + stil val 43 + feature (QA-infra hardening 2. val — kanon porabljen) + verifikacija + commit

Stanje / ocena:
- ADOPTION: `git log` pokazal HEAD = **ce2a444 (R359)**, drevo čisto (povzetek pogajanj spet STAREN — kanon "vedno git log" ponovno potrjen). Operativna runda = **R360**, tick 202610021045.
- **PRVA NALOGA iz R359 izpolnjena**: (1) `r359-prod-qa-retry.sh 359` — **prod-qa ZELEN ob poskusu 1** (retry ovoj kanon porabljen prvič v produkciji — transient kategorija R358+R359 s kanonom zdravljena); (2) **NOV kanonski skript `r360-era-harvest.sh`** [klon r359; TRIJESTIJNA era preverba — 13 registrov r347–r359; ≥59 need_static = 4+5+8+9+3+8+4+3+3+3+3+3+3; hash rezolucija podedovana]: **EXIT=0 ob 1. teku** — vseh TRIJEST er ŽIVO NA PRODU; 57 need_static ŽIVO DIREKTNO + 2 R353 prek hash rezolucije [a0911d4a403ebc43.js + e1e0545d5e5cc274.js HTTP 200 — pričakovano, leno čanki]; ⭐ **R359 val 42 vsi 3 needleji ŽIVO DIREKTNO** [chunk_026] → R359 deploy potrjen v celoti; must_miss ×13 čisto; era kontrole R340/R341/R343/R345 ŽIV.
- **agent-browser QA** (`scripts/r360-qa-spot.sh`, spot-r167 prijava — e2e-lib kanon; demo IZKLOPLJEN R127; **kolektor ŠELE PO prijavi — LEKCIJA R358 spoštovana**): prijava OK (poskus 2) → kolektor **0 errorjev** čez vse dispatche. **⭐ SPOT-PROBE HARDENING aplikiran V SEJI (kandidat 4)**: fiksna spanja → poll do znane glave; **1. tek pokazal prešibek ankor** — 'Meritve' matcha že tab bar (poskus 1 = pred renderjem vsebine: niProjektov lažno false), 'Field Manager' pride PRED lazy sekcijo (katalog/aiRaba/csvPills lažno 0); **re-probe `r360-qa-spot2.sh` z NAJZAKASNEJŠIMI ankorji** ('Ni projektov' / 'AI raba'): niProjektov=true (iskrena praznina — FAZA 11 gumbi projekt-scoped pravilno skriti), verzijeToggleRing=3, glava+katalogPillAria+katalogPillVidno+aiRaba ŽIVO, csvPills=9, funkcij ŽIVO → **NI bugov, le 2 probe nepreciznosti (dokumentirani)**; zvonček odpri/zapri OK; development-first.

Cilji / spremembe / verifikacija:
- **Fetch-first sken kandidatov** (iskreno): (a) **FAZA 13 sken** — GET/verzije + portal klaster: 6 fetchi v measurements-tabu (projects L598 raw-set, measurements L627+L672 normalizeMeasurements [2 isti-endpoint brata v STRUKTURNO različnih funkcijah — nested z early-returns vs standalone effect], verzije L1006 z validacijskim strojem, ar-snapshots L2761 z empty-toast strojem, photos L2992 z find-strojem) = **5 različnih endpointov, 5 oblik odgovorov, 5 state strojev**; portal [token]/page: 0 client fetchi (server-rendered) → **FAZA 13 NI utemeljena** (LEKCIJA R352/R359: heterogeni viri, vsiljena abstrakcija ne za šalo; 3. isti-endpoint klic bi utemeljil EN VIR naloziMeritveZaProjekt — zabeleženo za prihodnost); (b) e2e-lib dedup odložen 5.čič; (c) register-retirement kanon = lastniška odločitev (AGENT NE menja zamrznjenih registrov); (d) **spot-probe hardening — aplikiran v QA skriptih + dokumentiran** (glej QA sekcija).
- **FEATURE — QA-infra hardening 2. val: KANON PORABLJEN** (zaključek R359 hardening loka): (1) `r360-era-harvest.sh` žetev faza ZAMENJANA s klicem kanonskega `scripts/qa-harvest.sh` (retry ×3 determinističen backoff + parcialna-žeteva guard min 30 + fail-closed vhodi; R359: "prihodnje era-harvest skripte ga lahko pokličejo namesto lastnega inline curla (r360+)") — **DEMO ×2: 60/60 čankov, 0 failov, 0 retry-jev, EXIT=0** (CDN zdrav; retry zdaj vseeno varuje era preverbo pred transientom R358/R359 vzorca) + **guard demo EXIT=1** (neobstoječa URL datoteka — fail-closed); (2) spot-probe poll kanon v `r360-qa-spot.sh` + `r360-qa-spot2.sh` (lebdeči ankor resnica — glej QA sekcija); zamrznjeni r339 NI mutiran.
- **MANDATORY STIL val 43 — a11y resnica računovodskih akcij družine** (LEKCIJA R346 kanon; 0 novih hex; 9 gumbov × 1 datoteko invoice-manager.tsx; **VSE SPREMEMBE DODATNE — starejši aria/title nizi byte-identični**): (1) 'Izdaj' → NOVI aria 'Izdaj račun — status iz osnutka v izdan' + NOVI title 'Potrdi izdajo računa — status se spremeni v izdan; neuspeh vrne prejšnje stanje' (iskrena rollback resnica — optimistic update + rollback L557) + ring kanon; (2) 'Briši' → NOVI aria 'Trajno izbriši osnutek računa' + NOVI title 'Trajno izbriši osnutek računa — brisanje ni možno razveljaviti' (deleteInvoice je PRAVI DELETE — toast 'Osnutek brisan'; za razliko od bulk meritev arhiviranja je tu beseda 'trajno' UTEMELJENA) + ring kanon; (3) 'Plačan' → NOVI aria 'Označi račun kot plačan' + NOVI title (rollback resnica) + ring kanon; (4) 'Opomnik' → ring PARITETA (roksal-red/40 + ring-2 + offset-2; aria/title template literala byte-identična); (5) 'Storno' → NOVI aria 'Storniraj račun — drugi klik potrdi' (dvoklik resnica) + NOVI title 'prvi klik prikaže potrditev, drugi klik stornira (3 s okno)' + ring PARITETA (rdeči žig ohranjen); (6) 'Uredi' → NOVI aria 'Uredi osnutek računa' + NOVI title 'Uredi osnutek — osnutek se odstrani, dialog zapolni polja; shranjevanje ustvari nov račun' (iskrena posledica onClick: deleteInvoice + setDialogOpen) + ring kanon (bil BREZ ringa); (7) 'PDF' → NOVI aria 'Prenesi račun kot PDF' + NOVI title + ring kanon; (8) 'QR' + (9) 'XML' → ring PARITETA (aria/title ZAMRZNJENA — 'UPN QR koda za plačilo', 'eRačun XML (eSlog 2.1 / EN 16931)', 'Prenesi eRačun XML'). aria/title PO onClick (r241 strukturni regex zahteva className→onClick sosednost — vrstni red JSX props je prost, resnica ostane).
- **Stale pini shiftani V ENI rundi** (2 pina, 2 testne datoteke): **r241 'Briši zahteva invoices.create'** — stari className pin → NOVI ring kanon + aria/title (test ime nosi zgodovino: 'stale pin shiftan val 43 (R360, precedens R334/R355–R359)'); **r236 'app glavni fokus'** — stari Izdaj className pin → NOVI ring kanon (komentar z zgodovino). Proaktiven sken ujel r241; r236 ujel 1. polni vitest tek — LEKCIJA (2) zapisana.
- **VITEST r360 ×10** (1 NOVA datoteka): `r360-stil-val43` ×10 [7 blokov A–G strukturno + (H) zamrznjen hex seznam — 3 × QR barvni par '#1d2b3e'/'#ffffff' = EDINI hex v datoteki, '0 novih' dokazan s ŠTETJEM ne z null + (I) obrnjena regresija val 41/42 + (J) 7 enoličnih era-diskriminatorjev ×1]. Tek 1: 6 fail = enosmerna test okna (ring je PRED onClick, aria/title PO — okno mora pokrivati obe smeri) + 0-hex null pričakovanje → okna dvosmerna (Math.max(0, z-400)) + hex seznam zamrznjen → zeleno.
- **Register + README disk resnica**: `scripts/qa-needles/r360.tsv` [3 need_static = val 43 NOVI nizi (era-diskriminatorji, vsak točno ×1 v virih — preverjeno rg -F) + must_miss TODO-R360; python write z \\t (gen-r360-tsv.py); NF=3 čisto [awk lažni alarm na komentar glavi — vrstni red pogojev v awk izrazu, ne datoteka]] + README: števec 5173/323 → **5183/324** + R360 bullet (TRIJESTIJNA + FAZA 13 NI utemeljena + val 43 + hardening 2. val + spot poll kanon).
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL, npm run lint)** · vitest **5183/5183 (324 datotek)** = R359 baza 5173/323 + mojih +10/+1 − 0 [tek 1: 1 fail = stale pin r236 — shiftan V ENI rundi; tek 2 zeleno] · build svež **EXIT=0** [rm -rf .next; max-old-space-size 2560] · `qa-round.sh 360 needles` **VSE OK** [3 need_static ŽIVO + TODO-R360 odsoten; veriga R227→…→R339 + union registri r340–r360] · `qa-round.sh 360 smoke` **EXIT=0** [ovojnice 400 + { error } — ISTA EN VIR] · `qa-round.sh 360 e2e` **EXIT=0** [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · `r360-era-harvest.sh` **EXIT=0 ×2** [TRIJESTIJNA + kanonska žeteva] · **leak-check čist** [git grep ghp_[A-Za-z0-9]{36} → nič; žeton izključno v remote URL-ju] · **r172 prst 6051 potrjen iz diska** [val 43 ni premaknil measurements-tab — žetonska obroba na vrstici 6051 potjena; 22. zapis NI potreben — prst se ne zapise, ko se ne premakne].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 43 = render plast a11y v invoice-manager; FAZA 13 sken brez migracije]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex (val 43 = title/aria/ring žetonski razredi; hex seznam v datoteki zamrznjen); NIČ novih FNV soli.

Nereseno / tveganja + prioritete R361:
- ✅ Deploy zdrav (R359 ŽIVO na produ — TRIJESTIJNA preverba zeleno ob 1. teku; prod-qa retry kanon ZELEN ob poskusu 1); ni lastnikove akcije.
- ⚠️ **Iskrenost dolg (owner-level, ostaja)**: bulk trigger title 'Trajno izbriši' vs arhivira resnica — pinan v zamrznjenem r350.tsv; potreben register-retirement kanon (lastniška odločitev). Val 43 je pokazal KONTRAST: 'Briši' pri računih je pravi DELETE — beseda 'trajno' je tam utemeljena; pri meritvah arhiviranja ni. Iskrenost dolg ostaja odprt.
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3 tedne) — obvestiti lastnika (64. zapis).
- **R361 prva naloga = `qa-round.sh 360 prod-qa re-run` (prek `r359-prod-qa-retry.sh 360`) + ŠTIRINAJSTIJNA era preverba `r347.tsv` (val 30 ×4) IN `r348.tsv` (val 31 ×5) IN `r349.tsv` (val 32 ×8) IN `r350.tsv` (val 33 ×9) IN `r351.tsv` (val 34 ×3) IN `r352.tsv` (val 35 ×8) IN `r353.tsv` (val 36 ×4) IN `r354.tsv` (val 37 ×3) IN `r355.tsv` (val 38 ×3) IN `r356.tsv` (val 39 ×3) IN `r357.tsv` (val 40 ×3) IN `r358.tsv` (val 41 ×3) IN `r359.tsv` (val 42 ×3) IN `r360.tsv` (val 43 ×3)** [pričakuj VSE štirinajst er ŽIV ob zelenem deployu — R360 pride na produ sam; kanonski skript r361-era-harvest.sh [klon r360 — zEJ Z qa-harvest.sh porabo; 14 registrov, ≥62 need_static] pričakovan].
- R361 kandidati: **FAZA 13 — 3. isti-endpoint klic** [L627+L672 normalizeMeasurements brata; 3. klic (če se pojavi) utemelji EN VIR naloziMeritveZaProjekt — LEKCIJA R352 prag] ALI **e2e-lib dedup** [veliko, previdno — 6.čič odloženo] ALI **ring parity val 44: ostale družine** [velik dolg: logistics-tab 36/1, inventory-tab 23/1, material-intelligence-tab 26/0, crm-tab 13/4 navy40 brez offset-2 — IZBERI 1 datoteko × 1 družina, proaktiven pin sken OBVEZEN: rg stari class nizi + aria po VSEH testih PRED 1. tekom] ALI **register-retirement kanon predlog** [lastniška odločitev — samo dokumentirati, ne izvajati] — vedno z fetch-first + TSV kanonom.
- ISSUE #1: vsa sprejemna merila ✓; 65+ členov izpolnjenih; issue ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- LEKCIJE R360: (1) **poll ankor = NAJZAKASNEJŠI znani element** — 'Meritve' matcha tab bar, 'Field Manager' pride pred lazy sekcijo; ankor mora biti PRAZNINA oz. zadnja lazy sekcija ('Ni projektov', 'AI raba'); spot 1. tek lažno nižje vrednosti NI bil bug, bil je prehiter probe (iskrenost: re-probe obvezna ob sumu); (2) **proaktiven stale-pin sken mora vključevati STARE CLASS NIZE, ne samo nova imena** — r241 (aria/title imena) ujet proaktivno, r236 (stari class niz) šele ob 1. teku; rg 'stari_niz' po vseh testih, ki berejo datoteko, PRED 1. vitest tekom; (3) **enosmerna test okna so krhka ob JSX prop vrstnem redu** — ring je PRED onClick, aria/title PO (r241 regex sosednost); okno vedno dvosmerno: slice(Math.max(0, z-400), z+400); (4) **'0 novih hex' na datoteki s prejšnjimi hexi = zamrzni seznam** — šteješ in pinataš NAJDIŠČA resnico (3 × QR par), ne pričakuješ null; (5) **transient kategorija = kanon porabljen v praksi** — r359-prod-qa-retry.sh 359 ZELEN ob poskusu 1 ob 1. uporabi; hardening, ki se NE porabi, je le papir.
"""

with open("/home/z/my-project/worklog.md", "a", encoding="utf-8") as f:
    f.write(VNOS)

print("APPEND OK — R360 vnos na koncu worklog.md")
