#!/usr/bin/env python3
# r369-worklog-append.py — R369 delovni dnevnik (adopcija + polna re-verifikacija).
# Varnost: samo APPEND (preveri, da se datoteka konča z znanim repom R368),
# potem doda R369 sekcijo. Fail-closed: čekiraj znak, sicer abort.

ENTRY = """
---
Task ID: R369 (Job 413422, tick 1a0d7c0831c23029-cron-agent-loop-202610021800)
Agent: Super Z (cron tick 202610021800, Job 413422) — ADOPCIJA + POLNA RE-VERIFIKACIJA
Task: R369 — runda izvedena in commitirana v prejšnji seji (gateway auto-commit 962aaf4, tick ~202610021558), ki je POGASILA PRED worklog vnosom in pushem; ta seja je ADOPCIRALA drevo, NEZAVISNO re-verificirala CELOTNO verifikacijsko verigo (vse zeleno), dopisala ta vnos in PUSHALA. Vsebina runde: prva naloga (prod-qa re-run prek r359-prod-qa-retry.sh 368 + DVAINDVJSETIJNA era preverba r347–r368) + val 51 POST-deploy verifikacija (amber površine, spot-r167/14) + MANDATORY STIL val 52 (ring OBLIKOVNA pariteta navy+ink PARIŠKIH vrstic) + FEATURE (e2e-lib dedup 9. val — eb_sonda_red_stetje).

Stanje / ocena (adopcija):
- ADOPTION: `git log` pokazal HEAD = **962aaf4** (gateway auto-commit '72fb6b84-…-cron', 2026-10-02 09:58:47 UTC = 17:58:47 +08:00) NAD 686c379 (R368); drevo čisto; `origin/main..HEAD` = 1 (NI pushano). Worklog vnos R369 NI obstajal → prejšnja seja je umrla po commitu, pred handoverjem. **ADOPCIJSKI PROTOKOL**: vse trditve commita obravnavane kot NEPREVERJENE → celotna verifikacijska veriga PONOVO zagnana v tej seji (spodaj) — nič zaupano, vse izmerjeno.
- **Inventar commita (17 datotek, +968/−14)**: scripts/r369-era-harvest.sh [DVAINDVJSETIJNA — 22 registrov r347–r368, ≥93 need_static = 89 + 4] · scripts/r369-census.py [per-barvni census VSEH focus-visible:ring- družin, kanon R368 generaliziran] · scripts/r369-val52-apply.sh [determinističen perl s fail-closed števci] · scripts/r369-qa-spot.sh [spot-r167/14] · scripts/r369-trio-identity.py [per-blok md5 dokaz] · scripts/r369-ink-probe.py · scripts/r369-register-write.py · scripts/r369-readme-update.py · scripts/qa-needles/r369.tsv [4 need_static ×10/×1/×1/×1 + TODO-R369 must_miss] · scripts/e2e-lib.sh [+26: eb_sonda_red_stetje] · src: termini-card ×6 + bottom-nav ×2 + notification-center ×3 + quick-actions-fab ×1 [val 52] · NOVA testna datoteka r369-stil-val52.test.ts [×5, 252 vrstic] · r167-termini-filtri-dark.test.ts [1 PIN SHIFT {0,400}→{0,430} z žigom] · README [števec 5229/332 → 5234/333 + R369 bullet].
- **PRVA NALOGA iz R368 izpolnjena + v tej seji RE-VERIFICIRANA**: (1) `r359-prod-qa-retry.sh 368` — **prod-qa ZELEN ob poskusu 1 FOREGROUND** [RE-VERIFIKACIJA v tej seji: ZELEN ob poskusu 1; README zabeleži, da sta 2 poskusa detachanega nohup teka v prejšnji seji ubila okolje — proces kill, NI skriptnega faila; kanon ostaja FOREGROUND]; (2) `r369-era-harvest.sh` — **DVAINDVJSETIJNA era preverba EXIT=0 ob 1. teku** [RE-VERIFIKACIJA: EXIT=0 ob 1. teku]: vseh **22 er ŽIVO NA PRODU**; ⭐ **R368 val 51 vsi 4 needleji ŽIVO DIREKTNO** (chunk_045/chunk_014/chunk_026/chunk_018) → val 51 deploy potrjen v celoti; 2 R353 needleja prek HASH REZOLUCIJE (a0911d4a403ebc43.js + 1085983bcb110e2c.js, HTTP 200 + niz prisoten); must_miss ×22 čisto; era kontrole R340/R341/R343/R345 ŽIV.
- **val 51 POST-deploy verifikacija RE-VERIFICIRANA** (`scripts/r369-qa-spot.sh`, spot-r167/14; mounted + className LOČENO — LEKCIJA R365 (4); prijava OK ob poskusu 2 — transient, iskreno): **12 MONTIRANIH amber površin z offset-2** — inclinometer 'Vklopi libelo' 1/1/1 (mounted/amber50/offset2 — permission idle), obvestilne kartice **10/10** (Sheet odprt — demo NI prazen; L748 amber/60), viz ročaj 1/1 (demo način); pogojne iskreno NEmontirane z vrati iz vira (photo kategorija/debelina/orodja — 'Ni fotografij', fotoPrazninaRazlog true; measurements amber/40 ×0 — mera foto/cenovni kontekst; kanon r277); top-bar iskalnik white/60 + ring-offset-0 = **dokumentirana gosta površina ŽIVO** (iskalnikWhite60O0 1); navy pariteta **27/27/0** (eb_sonda_navy_stetje 2. uporaba — val 47/49 stabilnost); **kolektor 0 errorjev**.

Cilji / spremembe / verifikacija (runda val 52 + feature — commitirano v 962aaf4, struktura re-verificirana v tej seji):
- **MANDATORY STIL val 52 — ring OBLIKOVNA pariteta navy+ink PARIŠKIH vrstic** (svetlo+temno dvojčki na ISTIH elementih; per-barvni split kanon: navy = val 43–49 površinsko, red = val 50, amber = val 51, navy+ink pari = val 52; **BARVNI ŽIGI bajtno nespremenjeni** — shape-only runda): disk resnica prek `scripts/r369-census.py` [RE-POGNAN v tej seji: roksal-ink/40 skupaj=12 {'O2': 12} — razcep = 0 POTRJEN; roksal-amber/50 18/18 O2 — val 51 nedotaknjen; navy/40 skupaj=249 {'O2': 184, 'O1': 8, 'NONE': 54, '?INTERP': 3} — gap 65]: **12 × EN ` focus-visible:ring-offset-2` TIK ZA `focus-visible:ring-roksal-navy/40`** — offset žeton je TEMA-NEODVISEN, pokrije svetlo navy/40 IN temno ink/40 varianto ISTEGA elementa (kanon R368 notification L748 'EN offset pokrije svetlo+temno'); termini-card ×6 (L336/L352/L398/L417/L431/L442), bottom-nav ×2 (L123/L186), notification-center ×3 (L855/L881/L940), quick-actions-fab ×1 (L92); needle multiplicita RE-PREVERJENA z grep -o v tej seji: N1 ×10 / N2 ×1 / N3 ×1 / N4 ×1 — točno kot registrirano; **2 namerni izjemi dokumentirani** (iskreno, ne tiho — LEKCIJA R366 (5)): ui/* kit ring/50 ×14 (shadcn ring-[3px] fokus jezik — drugačen sistemski sloj) + top-bar white/60 + ring-offset-0 ×3 (namerna gosta površina — iskalni gumb); navy gap 77 → 65 (točno 12 parov rešenih; ostali navy rep = val 53+ kandidat, iskreno).
- **Stale-pini: 1 PIN SHIFTAN** — r167 okenski kvantifikator {0,400}→{0,430} z žigom [PIN SHIFT R369 val 52]: val 52 je vstavil 28 znakov v className 'Samo moje' gumba (okno 380→408, headroom 430); **PRED-skan sosledja ga NI ulovil — ulov ga je FULL vitest v tek 1 prejšnje seje; LEKCIJA: stale-pin PRED-skan mora enumerirati VSE okenske kvantifikatorje nad tarčnimi datotemi, ne samo sosledja**; r167 sosledja ink/40 preživita (vstavljanje ZA navy/40), r214 števca navy/40=2 + ink/40=2 (bottom-nav) nespremenjena, r268 = team-tab izven tarče, r361 (E) = crm-tab izven tarče [RE-PREVERBA vitest FULL v tej seji: 5234/5234 zeleno — pini stabilni].
- **FEATURE — e2e-lib dedup 9. val: `eb_sonda_red_stetje`** (rdeči trio byte-identičen ×2 v zamrznjenem r368-qa-spot.sh A/C — per-blok md5 03c8497dc9baf54c87e78a7dcb6f8ad8 nad 449 bajti, potrjeno prek python r369-trio-identity.py; skrajšani 2-poljni par byte-identičen ×3 — md5 640fec6de79293af75c9b021268b8a15 nad 278 bajti — prag LEKCIJE R352 (×3) IZENAČEN; precedens proaktivnega kanona pri ×2: eb_sonda_status_chipi R367, LEKCIJA R362 (3)): kanonizirana OBLIKA = **POLNI trio 3-poljni eval** (B-okrnjena 2-polja oblika se NE kanonizira — 2 polja izgubita BrezOffset resnico); regex /ring-red-\\d+\\// ohranjen natanko iz inline blokov (rdeči žetoni heterogeni: red-400/50, red-400/60, red-500, red-600/40 — regex je INLINE resnica); dispatch + poll ostanejo ločena kanona; V REPu ENOVRSTIČNI IIFE eval — r231 invariant; **zamrznjeni spot skripti NI mutirani** — kanon R361–R368. **Poraba ob 1. uporabi v r369-qa-spot.sh V ISTI rundi** (kanon ne sme biti papir): rdeči 0/0/0 na inclinometru — iskrena praznina.
- **VERIFIKACIJSKA VERIGA — celotna, PONOVO zagnana v tej seji (ADOPCIJA, na končno vire)**: tsc **0** · eslint **0 (FULL, `npm run lint`)** · vitest **5234/5234 (333 datotek)** = R368 baza 5229/332 + mojih +5/+1 − 0 [tek 1 prejšnje seje: 1 fail = r167 okenski pin → shift V ISTI rundi; tek 2 zeleno; ta seja: FULL tek zeleno] · build svež **EXIT=0** [rm -rf .next; max-old-space-size 2560] · `qa-round.sh 369 needles` **VSE OK** [4 need_static ŽIVO v svežem buildu + TODO-R369 odsoten; veriga R227→…→R339 + union registri r340–r369] · `qa-round.sh 369 smoke` **EXIT=0** [ovojnice 400 + { error } — ISTA EN VIR] · `qa-round.sh 369 e2e` **EXIT=0** [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · `r369-era-harvest.sh` **EXIT=0** [DVAINDVJSETIJNA] · `r359-prod-qa-retry.sh 368` **ZELEN ob poskusu 1** · `r369-qa-spot.sh` **ZELEN** [spot-r167/14; kolektor 0 errorjev] · **leak-check čist** [git grep ghp_[A-Za-z-0-9]{36} → 0 na HEAD; žeton izključno v remote URL-ju].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 52 = render plast a11y className-only v 4 render datotekah]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex; NIČ novih FNV soli.

Neresno / tveganja + prioritete R370:
- ✅ Deploy zdrav (R368 ŽIVO na produ — DVAINDVJSETIJNA preverba zeleno; val 51 POST-deploy potrjen z 12 montiranimi amber površinami; val 52 needles ŽIVO v lokalnem svežem buildu); ni lastnikove akcije.
- ⚠️ **val 52 produkcijska verifikacija = R370**: r369.tsv 4 needleji ŽIVO v lokalnem buildu; na produ še STARI razredi (deploy R369 še ni potekel/izveden ob zaključku te seje — preveriti `git log origin/main` + Vercel po pushu v NASLEDNJI rundi, ne v tej). R370 pričakuje: era preverba 4/4 ŽIVO + spot re-proba navy+ink pariških površin (termini-card 'Samo moje' — pogojen z myUserId prijavo; notification-center vrstice — pogojene s seznamom; bottom-nav glavni zavihki — VEDNO montirani; quick-actions-fab — montiran; **vse sonde naj SPET poročajo mounted + className LOČENO**, LEKCIJA R365 (4)).
- ⚠️ **Iskrenost dolg (owner-level, ostaja)**: bulk trigger title 'Trajno izbriši' vs arhivira resnica — pinan v zamrznjenem r350.tsv; potreben register-retirement kanon (lastniška odločitev). NI blokiral.
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3 tedne) — obvestiti lastnika (73. zapis; datum nespremenjen — iz R368 (72.) izpeljano).
- **R370 prva naloga** = `qa-round.sh 369 prod-qa re-run` [prek `r359-prod-qa-retry.sh 369`] + **TRIINDVJSETIJNA era preverba r347–r369** [23 registrov, ≥97 need_static = 93 + 4 — pričakuj VSE ŽIVO; 2 R353 needleja še naprej pričakovana prek hash rezolucije; kanonski skript `r370-era-harvest.sh` [klon r369; 23 registrov, ≥97 need_static] pričakovan].
- R370 kandidati: **ring parity val 53 — preostali navy rep** [census: navy/40 gap 65 = NONE ×54 + O1 ×8 + ?INTERP ×3 — PRED odločitvijo per-vrstična triaža iz diska: koliko NONE je NE-focus ali NE-gumb površine (querySelectorAll 'main button' resnica spotov mora ostati skladna); O1 ×8 = offset-1 normalizacija kandidati (precedens val 47/49); ?INTERP ×3 = interpolirani className — preskočiti ali ročno] ALI **vodja-lupina/tab bar 9 ostanki** [VES-dokument BrezOffset=9 iz spot-r167/11 — per-površinski števec + aria vzorci PRED odločitvijo] ALI **e2e-lib dedup 10. val** [iskreno: NI identificiranega kandidata ob ×2/×3 — dokumentirati in IZPUSTITI če ni ponovitve (kanon R368: material B-proba ×1 = NI prag)] — vedno z fetch-first + TSV kanonom + stale-pin PRED-skanom (**RAŠIRJEN: enumerate VSE okenske kvantifikatorje {0,N} nad tarčnimi datotemi — LEKCIJA R369**; okenske dolžine + grep -o pojavitve).
- ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- LEKCIJE R369: (1) **gateway auto-commit lahko vsebuje CELOTO verificirano rundo brez worklog vnosa in pusha** — adopcija = NEZAUPANJE: celotno verifikacijsko verigo PONOVO pognati in vsak števec neodvisno potrditi (ta seja: vse zeleno, 0 popravkov potrebnih — najboljši možen izid adopcije); (2) **stale-pin PRED-skan mora enumerirati VSE okenske kvantifikatorje** nad tarčnimi datotemi — sosledja-skan je ulovil r167 sosledja, NI pa okna {0,400}; FULL vitest je edini zanesljiv mrežni skan (LEKCIJA R368 (6) razširjena na okna); (3) **detachan nohup teka lahko UBJE okolje** (proces kill) — prod-qa kanon ostaje FOREGROUND (prejšnja seja, README bullet; potrjeno v praksi); (4) **census generalizacija kanona je poceni in se izplača** — r369-census.py (iz r368-census.py) je pokril VSE družine in odkril navy+ink par strukturo, ki handover ni predvidel (handover je predlagal ink kot SAMOSTOJNO družino; disk je pokazal PARISKE vrstice z navy — LEKCIJA R364 (4) spet); (5) **tema-neodvisen offset žeton pokrije svetlo+temno par** — ENA substitucija na pariško vrstico namesto dveh (kanon R368 L748 formaliziran v val 52 kanon).
"""

path = "/home/z/my-project/worklog.md"
with open(path, "r", encoding="utf-8") as f:
    src = f.read()

GUARD = "števec vedno po koncu, ne po načrtu."
if not src.rstrip().endswith(GUARD):
    raise SystemExit("FAILOVEDANO: worklog rep ni znan R368 rep — abort")

if "Task ID: R369 (" in src:
    raise SystemExit("FAILOVEDANO: R369 vnos že obstaja — abort")

if not src.endswith("\n"):
    src += "\n"
src += ENTRY
with open(path, "w", encoding="utf-8") as f:
    f.write(src)
print("OK: R369 vnos dodan")
