#!/usr/bin/env python3
# r370-worklog-append.py — R370 delovni dnevnik. Fail-closed: preveri znani
# rep R369 vnosa, potem APPEND. Samo en vnos (guard na 'Task ID: R370 (').

ENTRY = """
---
Task ID: R370 (Job 413422, tick 1a0d7c0831c23029-cron-agent-loop-202610021821)
Agent: Super Z (cron tick 202610021821, Job 413422)
Task: R370 — prva naloga (prod-qa re-run prek r359-prod-qa-retry.sh 369 + TRIINDVJSETIJNA era preverba r347–r369 prek NOVega kanonskega skripta r370-era-harvest.sh) + val 52 POST-deploy verifikacija (navy+ink pariške površine, spot-r167/15 + re-proba) + agent-browser QA + MANDATORY STIL val 53 (ring OBLIKOVNA pariteta navy/40 OFFSET-1 REP — normalizacija 1→2) + FEATURE (QA-infra hardening 3. val — r370-window-scan.py, LEKCIJA R369 (2) formalizirana; e2e-lib dedup 10. val ISKRENO IZPUŠČEN) + verifikacija + commit

Stanje / ocena:
- ADOPTION: `git log` pokazal HEAD = **2628e52 (R369 adopcija)**, drevo čisto, `origin/main..HEAD` prazen (gateway auto-commit NI prisoten). Operativna runda = **R370**, tick 202610021821.
- **PRVA NALOGA iz R369 izpolnjena**: (1) `r359-prod-qa-retry.sh 369` — **prod-qa ZELEN ob poskusu 1 FOREGROUND**; (2) **NOV kanonski skript `r370-era-harvest.sh`** [klon r369 prek NOVEga python orodja r370-era-clone.py z 10 fail-closed žigi — 1. teek kloniranja je GLASNO abortiral na 2 napačno pričakovanih števcih žigov [`r370-resolucija-` = 2 (izhod -o + grep vhod), ostanek 'dvaindvajsete' v novi glavi LEGITIMEN] → popravljene pričakovane vrednosti V ISTI rundi, transformacija NIKOLI spremenjena; TRIINDVJSETIJNA era preverba — 23 registrov r347–r369, ≥97 need_static = 93 + 4, vsota potrjena iz diska prek python [(347,4)…(369,4)]]: **EXIT=0 ob 1. teku** — vseh TRIINDVJSET er ŽIVO NA PRODU; ⭐ **R369 val 52 vsi 4 needleji ŽIVO prek HASH REZOLUCIJE** (3abf34ececedd8ff.js + dc5a9c95ae97123a.js, HTTP 200 + niz prisoten) → val 52 deploy potrjen v celoti; 2 R353 needleja še naprej prek hash rezolucije; must_miss ×23 čisto; era kontrole R340/R341/R343/R345 ŽIV.
- **val 52 POST-deploy verifikacija** (`scripts/r370-qa-spot.sh`, spot-r167/15 + `scripts/r370-spot-reprobe.sh`; mounted + className LOČENO — LEKCIJA R365 (4); prijava OK ob poskusu 2 — transient, iskreno): **bottom-nav 9/9/9/0** (navy40/ink40/offset2/brezOffseta — VEDNO montirane pariške vrstice; **znani 'vodja-lupina/tab bar 9 ostanki' kandidat iz R368 handoverja REŠEN z val 52** — skenira se iz seznama R371 kandidatov); Sheet kartice navy/40 **51/51** z offset-2 + 'Označi vse kot prebrano' 1/1 (vrata neprebrana>0 ŽIVO); FAB sprožilec ŽIVO (item L92 vrata: meni odprt — prva sonda tekla PREZGODAJ, glej LEKCIJA (6)); termini pari **4/4/0** (vrstica L336/352/398/417/431/442 žive v demo podatkih); **D2 DOKAZ**: edini navy/40-BrezOffset gumb na dashboardu = 'Izvozi CSV' L1678 = shadcn Button + brand barvni override = **val 52 namerna izjema #1** (kit ring-[3px] fokus jezik) — NI val 54 gap kandidat po doktrini izjem; **kolektor 0 errorjev** v obeh sejah; sonde: eb_sonda_navy_stetje 3. uporaba + eb_sonda_red_stetje 2. uporaba. **NI runtime bugov → development-first.**
- **Fetch-first sken + odločitev**: census iz diska (r369-census.py RE-POGNAN): navy/40 gap 65 = NONE ×54 + O1 ×8 + ?INTERP ×3 → **val 53 = O1 ×8 normalizacija** (precedens val 47/49/51); dedup 10. val kandidat: python skan r370-dedup-scan.py nad r365–r369 spot skriptami — **13 eval blokov, 13 unikatnih, 0 ponovitev ≥2 → ISKRENO IZPUŠČEN** (kanon R368).

Cilji / spremembe / verifikacija:
- **MANDATORY STIL val 53 — ring OBLIKOVNA pariteta navy/40 OFFSET-1 REP, normalizacija 1→2** (per-barvni split kanon: navy = val 43–49 + val 52 pari, red = val 50, amber = val 51, navy O1 rep = val 53; **BARVNI ŽIGI bajtno nespremenjeni** — shape-only runda): census PRED {'O2': 184, 'O1': 8, 'NONE': 54, '?INTERP': 3} gap 65 → PO **{'O2': 192, 'O1': 0, 'NONE': 54, '?INTERP': 3} gap 57 — O1 razcep = 0**; **8 vrstic × 4 datoteke** (calculator L4382, dashboard L2666, invoice L1045/L1061/L1182, vodja L1274/L1290/L1306 — VSE focus-visible gumbi); substitucija **DOLŽINSKO NEVTRALNA** (poln žeton 27→27 znakov) = 0 okenskih premikov; NONE ×54 + ?INTERP ×3 ISKRENO izven (val 54+ triaža — D2 dokaz zgoraj: prvi 'NONE' kandidat iz spotov je kit override = izjema #1); in-place = **0 novih vrstic** (4489/3188/1722/2199 — wcLinije kanon); **0 novih hex** (16/0/6/1 = HEAD); aria/title ZAMRZNJENI (ring-only — val 44–52 precedens). Apply prek `scripts/r370-val53-apply.sh` (fail-closed per-datoteka PRED števci) + `scripts/r370-pins-shift.py` (6 shiftov, vsak točno 1 pojavitev, sicer abort).
- **Stale-pini: 6 SHIFTOV V ISTI RUNDI** z žigi [PIN SHIFT R370 val 53]: (1) r236-dobavitelji-pdf.test.ts L276 toContain navy/40 offset-1" → offset-2" + žig komentar; (2) r236-build-needles L47 CSV pill → offset-2 [LEGACY, proaktiven — kanon R368 r244-prod-qa]; (3) r236-build-needles L49 Prejem → offset-2 [**ŽE ZASTAREL PRED R370** — green-50+navy/40 živi na logistics L2417 z offset-2; osvežen na disk resnico]; (4) r236-build-needles L48 Izdaj/Plačan → vmesni outline-none+ring-2 segment dodan [**ŽE ZASTAREL PRED R370** — disk L1319/L1339]; (5) r237-build-needles L43 dashboard L2666 → offset-2; (6) r237-prod-core L64 CSV pill → offset-2 [LEGACY, proaktiven]. Preživetja potrjena v testu (C): r366 (C) not.toContain bere r242 TEST datoteko (0 × ring-offset-1 še vedno), r364 (A) MERITVE offset-1 = 0, r368/r369 (A) iteracije nedotaknjene.
- **NAJDBA (QA-integriteta)**: legacy build-needle skripti r227–r339 so **IZVEN trenutne needles faze** (qa-round needles = TSV registri r340+ SAMO — potrjeno z grepom skozi /tmp/r370-needles-full.log: ni klica r236-build) → njihovi zastareli needleji so bili NEVIDNO zastareli; r236-build-needles na svežem buildu je imel **2 MISS** (Izdaj/Plačan + Prejem) kljub 'VSE OK' verigi. Oba osvežena na disk resnico V ISTI RUNDI → po osvežitvi r236-build **0 MISS** + r237-build **0 MISS** na svežem buildu. Odlaga ostalih legacy skript = lastniška odločitev (register-retirement kanon).
- **Register + README disk resnica**: `scripts/qa-needles/r370.tsv` [4 need_static, vsi ×1 per-datoteka grep -rlF (LEKCIJA R368 (6) precizirana: cat brez ločila laže) in **×0 v HEAD 2628e52** (fetch-first git grep -F GLASNO potrjeno prek python); N1 calculator 'hover:opacity-80 … offset-2', N2 dashboard 'bg-roksal-navy … h-9 … offset-2', N3 invoice L1182 'text-2xs font-medium press-scale … offset-2', N4 dashboard rep 'navy/40 offset-2 transition-colors'; **2 izpuščena kandidata DOKAZANA v testu**: vodja niz = material ×8 (R242 press-scale pariteta — className-only ne diskriminira ere), invoice pill niz = crm ×1; must_miss TODO-R370; python validacija NF=3 čisto] + README: števec **5234/333 → 5239/334** + R370 bullet VSTAVLJEN kot CELOTO z python PRED val 44 sidrom (LEKCIJA R366 (3) kanon; preverba vrstnega reda 45→…→53→44 — val 44 zgodovinski append na koncu odseka, disk resnica).
- **FEATURE — QA-infra hardening 3. val: `scripts/r370-window-scan.py`** (LEKCIJA R369 (2) FORMALIZIRANA — stale-pin PRED-skan kot ORODJE): enumerira VSE okenske kvantifikatorje {0,N}/{M,N} v testih, ki berejo tarčne datoteke, požene vsak regex nad disk vsebino (MATCH/NO-MATCH + okna) + delta-mode simulacija vstavitve; **65 okenskih regexov enumeriranih (per-tarčna enumeracija — test čez 2 tarči se šteje 2×), 0 preozkih, PRED in PO apply** — 1. uporaba V ISTI rundi (kanon ne sme biti papir). **e2e-lib dedup 10. val ISKRENO IZPUŠČEN** — dokaz ponovno izračunan V TESTU (E): 13 blokov / 13 unikatnih md5 / Set.size = 13.
- **VITEST r370 ×5** (1 NOVA datoteka `r370-stil-val53.test.ts`): (A) PARITETA guard offset-1 = 0 v 4 tarčah + navy/40 števci 4/9/10/4 + offset-2 1/2/10/4 + žigi + in-place; (B) era-diskriminatorji ×1/×1/×1/×1 per-datoteka + 2 izpuščena kandidata dokazana (material ×8 / crm ×1) + 'Izvozi CSV' L1678 kit-override dokaz; (C) 6 shiftov (novi prisotni, stari odsotni) + preživetja (r242 TEST, MERITVE); (D) 0 novih hex 16/0/6/1 + aria/title ZAMRZNJENI; (E) orodje ŽIVO + 65 re-enumeriranih V TESTU (per-tarčna semantika) + dolžinska nevtralnost (27/27, rep 13/13) + dedup izpust dokaz (13/13/0) + era klon kanon (REG_W + prag 97 + TRIINDVJSETIJNA). **Tek 1: 3 faila** = (a) žig 'LEKCIJA' vs disk 'LEKCIJE' niz, (b) re-enumeracija dedupirana 53 namesto per-tarčna 65, (c) dolžina polnega žetona 27 namesto repa 13 [moja aritmetika] — vsi popravljeni V ISTI rundi; **tek 2 zeleno 5/5**; + TS1501 /gs flag past → [\\s\\S]*? (target < es2018).
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL, `npm run lint`)** · vitest **5239/5239 (334 datotek)** = R369 baza 5234/333 + mojih +5/+1 − 0 [tek 2 zeleno] · build svež **EXIT=0** [rm -rf .next; max-old-space-size 2560] · `qa-round.sh 370 needles` **VSE OK, 0 MISS** [4 need_static ŽIVO v svežem buildu + TODO-R370 odsoten; veriga R227→…→R339 + union registri r340–r370 z 6 shiftanimi pini] + legacy osvežena: r236-build **0 MISS**, r237-build **0 MISS** · `qa-round.sh 370 smoke` **EXIT=0** [ovojnice 400 + { error } — ISTA EN VIR] · `qa-round.sh 370 e2e` **EXIT=0** [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana] · `r370-era-harvest.sh` **EXIT=0** [TRIINDVJSETIJNA, ob začetku runde] · `r359-prod-qa-retry.sh 369` **ZELEN ob poskusu 1** · `r370-qa-spot.sh` + re-proba **ZELENA** [kolektor 0 errorjev] · **leak-check čist** [git grep ghp_[A-Za-z0-9]{36} → 0 na HEAD; žeton izključno v remote URL-ju].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 53 = render plast a11y className-only v 4 render datotekah]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex; NIČ novih FNV soli.

Neresno / tveganja + prioritete R371:
- ✅ Deploy zdrav (R369 ŽIVO na produ — TRIINDVJSETIJNA preverba zeleno; val 52 POST-deploy potrjen prek hash rezolucije + montirani DOM dokazi bottom-nav/Sheet/termini); ni lastnikove akcije.
- ⚠️ **val 53 produkcijska verifikacija = R371**: r370.tsv 4 needleji ŽIVO v lokalnem buildu; na produ še STARI razredi. R371 pričakuje: era preverba 4/4 ŽIVO (delno prek hash rezolucije — chunki se bodo zamenjali) + spot re-proba navy O1-rep površin (calculator izvozni gumbi — pogojeni z izračuni; dashboard Izvozi CSV — VEDNO montiran [kit override — offset ostaja 0 po izjemi #1!]; invoice CSV/PDF pilli — pogojeni z računi; vodja statusni gumbi — pogojeni; **vse sonde naj SPET poročajo mounted + className LOČENO**, LEKCIJA R365 (4); pričakuj večino iskreno NEmontiranih v demo praznini — kanon r277 z razlogom iz vira).
- ⚠️ **Legacy build-needle skripti r227–r339 IZVEN verige** — ostali legacy needleji so lahko ŠE zastareli (samo r236/r237 osvežena ob dotiku val 53); popolna Legacy needle revija ALI uradni register-retirement = lastniška odločitev. NI blokiral (trenutna veriga = TSV registri r340+).
- ⚠️ **Iskrenost dolg (owner-level, ostaja)**: bulk trigger title 'Trajno izbriši' vs arhivira resnica — pinan v zamrznjenem r350.tsv; potreben register-retirement kanon (lastniška odločitev). NI blokiral.
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3 tedne) — obvestiti lastnika (74. zapis; datum nespremenjen — iz R369 (73.) izpeljano).
- **R371 prva naloga** = `qa-round.sh 370 prod-qa re-run` [prek `r359-prod-qa-retry.sh 370`] + **STIRIINDVJSETIJNA era preverba r347–r370** [24 registrov, ≥101 need_static = 97 + 4 — pričakuj VSE ŽIVO; 2 R353 needleja prek hash rezolucije; kanonski skript `r371-era-harvest.sh` [klon r370; 24 registrov, ≥101] pričakovan] + val 53 POST-deploy verifikacija [navy O1-rep površine spot — mounted + className LOČENO].
- R371 kandidati: **ring parity val 54 — navy NONE triaža** [54 vrstic per-vrstična klasifikacija iz diska: shadcn-kit override (izjema #1 doktrina — D2 dokaz) vs resnični brand gumbi brez offseta; pričakuj manjšo gap ostalost; orodje r370-window-scan.py kanon razširljiv na NONE sken] ALI **?INTERP ×3 triaža** [roksal-catalog/punch-list interpolirani className — ročno ali iskreno preskočiti] ALI **e2e-lib dedup 11. val** [iskreno: NI kandidata ob ×2/×3 po r370-dedup-scan.py — izpustiti če ni ponovitve] — vedno z fetch-first + TSV kanonom + stale-pin PRED-skanom prek r370-window-scan.py (okenske dolžine + grep -rlF pojavitve per datoteko).
- ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- LEKCIJE R370: (1) **legacy build-needle skripti (r227–r339) so IZVEN trenutne needles verige** — njihovi zastareli needleji so bili NEVIDNO zastareli (r236 L48/L49 že pred R370); needles faza = TSV registri r340+ SAMO; legacy needleje osvežiti ob dotiku ALI uradno upokojiti (lastniška odločitev); (2) **per-tarčna enumeracija je kanon orodja** — test čez 2 tarči se šteje 2× (53 dedupirano ≠ 65 per-tarčno); in-test replika mora upoštevati ISTO semantiko kot orodje (LEKCIJA R364 (4) precizirana na enumeracijsko semantiko); (3) **cat brez ločila laže multiplicito** — sosednji .tsx brez končne noveline skrije nize (grep -rlF per datoteka = kanon; LEKCIJA R368 (6) precizirana); (4) **poln žeton ≠ rep** — 'focus-visible:ring-offset-N' = 27 znakov, 'ring-offset-N' = 13; dolžinsko-nevtralni dokaz na polnem žetonu; (5) **era-needle potrebuje ×0 v HEAD** — niz, ki ga nosi tudi druga datoteka (material ×8 / crm ×1), NI era diskriminator; vitest per-datoteka guard pokrije ostale; (6) **spot sonde brez dispatch/poll poročajo lažno praznino** — A-section r370-qa-spot tekla pred montažo (nav 0), re-proba z dispatch+wait 9/9/9/0 (LEKCIJA R360 poll kanon potrjena: vsaka površinska sonda rabi dispatch + pocakaj); (7) **TS1501: /s flag pod targetom < es2018** — [\\s\\S]*? = re.S semantika brez flaga; pipe v bash skrije exit kodo ($? = tail) — exit kode meriti BREZ pip.
"""

path = "/home/z/my-project/worklog.md"
with open(path, "r", encoding="utf-8") as f:
    src = f.read()

GUARD = "(5) **tema-neodvisen offset žeton pokrije svetlo+temno par** — ENA substitucija na pariško vrstico namesto dveh (kanon R368 L748 formaliziran v val 52 kanon)."
if GUARD not in src.rstrip():
    raise SystemExit("FAILOVEDANO: worklog rep ni znan R369 rep — abort")

if "Task ID: R370 (" in src:
    raise SystemExit("FAILOVEDANO: R370 vnos že obstaja — abort")

if not src.endswith("\n"):
    src += "\n"
src += ENTRY
with open(path, "w", encoding="utf-8") as f:
    f.write(src)
print("OK: R370 vnos dodan")
