#!/usr/bin/env python3
# r371-worklog-append.py — R371 delovni dnevnik. Fail-closed rep-guard R370.

ENTRY = """
---
Task ID: R371 (Job 413422, tick 1a0d7c0831c23029-cron-agent-loop-202610021918)
Agent: Super Z (cron tick 202610021918, Job 413422)
Task: R371 — prva naloga (prod-qa re-run prek r359-prod-qa-retry.sh 370: ZELEN ob poskusu 2 — 1. teek transient, 10. runda zapored, iskreno + STIRIINDVJSETIJNA era preverba r347–r370 prek NOVega kanonskega skripta r371-era-harvest.sh) + val 53 POST-deploy verifikacija (navy O1-rep površine, spot-r167/16 + vodja-identify) + agent-browser QA + MANDATORY STIL val 54 (ring OBLIKOVNA pariteta navy/40 NONE TRIAŽA — 13 surovih brand vrstic dobi offset-2; BRAND GUMB pariteta ZAKLJUČENA — milestone val 43–54) + FEATURE (r371-none-triage.py orodje) + e2e-lib dedup 11. val ISKRENO IZPUŠČEN + verifikacija + commit

Stanje / ocena:
- ADOPTION: `git log` pokazal HEAD = **76fd98d (R370)**, drevo čisto, `origin/main..HEAD` prazen (gateway auto-commit NI prisoten). Operativna runda = **R371**, tick 202610021918.
- **PRVA NALOGA iz R370 izpolnjena**: (1) `r359-prod-qa-retry.sh 370` — **prod-qa ZELEN ob poskusu 2** (1. teek transient — retry kanon PRAVIČNO porabljen, 10. runda zapored, iskreno poročano); (2) **NOV kanonski skript `r371-era-harvest.sh`** [klon r370 prek NOVEga python orodja r371-era-clone.py; STIRIINDVJSETIJNA era preverba — 24 registrov r347–r370, ≥101 need_static = 97 + 4, vsota potrjena iz diska prek python [(347,4)…(370,4)]]: **EXIT=0 ob 1. teku** — vseh ŠTIRIINDVJSET er ŽIVO NA PRODU; ⭐ **val 53 vsi 4 needleji ŽIVO DIREKTNO** (chunk_043/chunk_028/chunk_037) → val 53 deploy potrjen v celoti; 2 R353 needleja prek hash rezolucije; must_miss ×24 čisto; era kontrole R340/R341/R343/R345 ŽIV.
- **val 53 POST-deploy verifikacija** (`scripts/r371-qa-spot.sh`, spot-r167/16 + `scripts/r371-vodja-identify.sh`; VSAKA površina z dispatch + pocakaj — LEKCIJA R370 (6) aplicirana; prijava OK): **vodja izvozni pilli 3/3 offset-2 ŽIVO** (aria 'Izvozi …' — L1274/1290/1306), invoice racuniCsv **1/1** + prihodkiPdf **1/1** + meseciCsv iskreno NEmontiran (vrata `meseciPovzetek.ok` — prihodki po mesecih iz demo podatkov ni mogoče razčleniti — kanon r277 z razlogom iz vira), calculator zgodovina **1/1** (Zgodovina izračunov trigger), dashboard 'Izvozi prikazane projekte v CSV' kit override ŽIVO (offset **NAMERNO 0** — izjema #1, dokumentirano ŽIVO), **D2-dokaz 2**: 4. navy/40 BrezOffset 'Izvozi *' gumb = **sistem-zdravje-card L204 kit override** (shadcn Button + brand override — disk dokaz, izjema #1); sonde: eb_sonda_navy_stetje 4. uporaba + eb_sonda_red_stetje 3. uporaba; **kolektor 0 errorjev**. **NI runtime bugov → development-first.**

Cilji / spremembe / verifikacija:
- **MANDATORY STIL val 54 — ring OBLIKOVNA pariteta navy/40 NONE TRIAŽA** (per-barvni split kanon: navy = val 43–49 + val 52 pari + val 53 O1 rep + val 54 NONE triaža, red = val 50, amber = val 51; **BARVNI ŽIGI bajtno nespremenjeni** — shape-only runda): disk resnica prek NOVega orodja **`scripts/r371-none-triage.py`** (element klasifikacija z nazaj-hodom do 15 vrstic do '<Button'/'<button'/'<Input'/'<Link'/div — LEKCIJA R364 (4) = KODA ne oči): navy/40 NONE ×54 = **KIT ×35** (shadcn Button + brand override — **NAMERNA izjema #1** iz val 52, offset po dizajnu 0) + **RAW ×13** (val 54 tarče) + **INPUT ×2** (dashboard L1623 + roksal-catalog L95 — iskalni vnosi, NE gumbi — iskreno izven, lastni fokus jezik) + **CMP ×5** (DropdownMenu/Command/Card — lastni fokus jezik, izven) + deal-pipeline L219 (drag handle cn() — NE gumb, izven). **13 vrstic × 10 datotek** dobi ` focus-visible:ring-offset-2` TIK ZA navy/40 (audit-trail L249/L310, calculator L860/L4439, dashboard L1628/L1756, inclinometer L341, inline-inclinometer L131, inline-kotomer L185, steber-table L69, photo L2370, punch-list L531, rate-limit L226; 2 tarči = census ?INTERP template → O2). Apply prek `scripts/r371-val54-apply.py` (fail-closed: vsaka vrstica preverjena po (datoteka, št. vrstice, navy/40 prisoten, ring-offset ODSOTEN, točno 1 žeton) PRED vstavitvijo). Census PRED {'O2': 192, 'NONE': 54, '?INTERP': 3} gap 57 → PO **{'O2': 205, 'NONE': 43, '?INTERP': 1} gap 44 — vsi 44 = DOKUMENTIRANI namerni (35 KIT + 2 INPUT + 5 CMP + 1 drag) → navy/40 BRAND GUMB pariteta ZAKLJUČENA (razcep na brand gumboh = 0; MILESTONE val 43–54)**. Substitucija DODAJA 27 znakov (insert); in-place = **0 novih vrstic** (344/4489/3188/599/2684/748/315/268/420/169); **0 novih hex** (0/16/0/0/12/0/0/0/8/0 = HEAD); aria/title ZAMRZNJENI (ring-only — val 44–53 precedens).
- **Stale-pini: 2 ŠTEVEC PIN SHIFTA** [PIN SHIFT R371 val 54] — r370-stil-val53.test.ts (A) offset-2 števec **calculator 1→3** (L860/L4439) + **dashboard 2→4** (L1628/L1756), z žigom v it() opisu: val 54 je dodala offset na NOVIH surovih vrsticih ISTIH datotek, ki jih r370 guard šteje. **Ulov s FULL vitestom (tek 1), NE s pre-skanom** — okno-scan orodje preverja okenske kvantifikatorje, NE števčnih guardov; LEKCIJA (7). Okenski/handler/must_miss pini: **0 shiftov** — r370-window-scan.py delta +27 = 0 preozkih (65/65), r317 must_miss needle (polni niz 'h-8 px-2 transition-colors hover:text-roksal-ink focus-visible:ring-roksal-navy/40') še odsoten, r348 steber toContain preživi, r346 line-okno preživi, r271/r272/r268 handler pini nedotaknjeni.
- **Register + README disk resnica**: `scripts/qa-needles/r371.tsv` [4 need_static, vsi ×1 per-datoteka grep -rlF in **×0 v HEAD 76fd98d** (fetch-first git grep -F -- GLASNO potrjeno prek python): N1 audit-trail chip 'rounded-full border px-2 py-0.5 … offset-2', N2 calculator 'p-1 rounded-md hover:bg-secondary/60 … offset-2', N3 dashboard 'top-1/2 -translate-y-1/2 … offset-2', N4 calculator zgodovina rep 'navy/40 offset-2 focus-visible:border-roksal-navy/40'; izpuščeni kandidati dokumentirani: punch-list L531 template compile rep, inline close brata ×2 (enak niz v 2 datotekah — veljaven a kanon 4 needleje/rundo; vitest (A) pokrije), ostale 6 tarč prek vitest (A) guard; must_miss TODO-R371; NF=3 čisto] + README: števec **5239/334 → 5244/335** + R371 bullet kot CELOTO z python PRED val 44 sidrom (red 45→…→54→44 — disk resnica) + **higienski popis**: roundski bullet je v 1. verziji vseboval naključne CJK znake ('向往') — odkrito in popravljeno V ISTI rundi (perl/python preverba → 0).
- **FEATURE — `scripts/r371-none-triage.py`** (val 54 orodje): element klasifikacija vseh navy/40 brez-offset vrstic (nazaj-hod do 15 vrstic; KIT/RAW/INPUT/LINK/CMP/DIV) — PRED-triaža iz diska, nič ročnih oči; **1. uporaba V ISTI rundi** (kanon ne sme biti papir). **e2e-lib dedup 11. val ISKRENO IZPUŠČEN** — dokaz ponovno izračunan V TESTU (E): 13 blokov / 13 unikatnih md5 / 0 ponovitev ≥2 (kanon R368).
- **VITEST r371 ×5** (1 NOVA datoteka `r371-stil-val54.test.ts`): (A) PARITETA guard — vseh 13 tarč nosi offset-2 TIK ZA navy/40 + in-place + hex/aria/title per datoteka (10 datotek); (B) era-diskriminatorji ×1/×1/×1/×1 + ne-tarčni dokazi (sistem-zdravje-card kit override + 2 INPUT brez offseta); (C) stale-pini ČIST (r317 polni must_miss odsoten + r348 steber + r346 line-okno + amber ×2 nespremenjena + handler pini) **+ 2 števec shifta v r370 (A) z žigom**; (D) census klasa dokaz (punch template 'offset-2 ${' — LEKCIJA R361; inclinometer template vrstica; navy žigon vsota 32); (E) orodja ŽIVO (none-triage + apply fail-closed + window-scan delta + dedup izpust dokaz 13/13/0 + era klon 24. register). **Tek 1: 2 faila** = (a) preširok must_miss sosledni assert [krajša sosledja živi na KIT vrstici L262 — polni r317 needle edini pravi], (b) r346 okno char-based naprej-usmerjeno zgreši className PRED aria-jem [r346 kanon je LINE-okno i-8..i+6] — vsi popravljeni V ISTI rundi; **tek 2 zeleno 5/5**; nato FULL vitest ulovil še r370 (A) števec (2 shifta zgoraj) → ponovni FULL tek **5244/5244 zeleno**.
- **VERIFIKACIJSKA VERIGA (celotna, FOREGROUND, na KONČNI viri)**: tsc **0** · eslint **0 (FULL, `npm run lint`)** · vitest **5244/5244 (335 datotek)** = R370 baza 5239/334 + mojih +5/+1 − 0 · build svež **EXIT=0** [rm -rf .next; max-old-space-size 2560] · `qa-round.sh 371 needles` **VSE OK, 0 MISS** [4 need_static ŽIVO + TODO-R371 odsoten; veriga R227→…→R339 + union registri r340–r371] · `qa-round.sh 371 smoke` **EXIT=0** [ovojnice 400 + { error } — ISTA EN VIR] · `qa-round.sh 371 e2e` **EXIT=0** [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA dokazana] · `r371-era-harvest.sh` **EXIT=0** [STIRIINDVJSETIJNA, ob začetku runde] · `r359-prod-qa-retry.sh 370` **ZELEN ob poskusu 2** · `r371-qa-spot.sh` + `r371-vodja-identify.sh` **ZELENA** [kolektor 0 errorjev] · **leak-check čist** [git grep ghp_[A-Za-z0-9]{36} → 0 na HEAD; žeton izključno v remote URL-ju].
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 54 = render plast a11y className-only v 10 render datotekah]; OgrajaVizija nič; **brez sheme** (ZERO-MUTACIJA E2E); 0 novih hex; NIČ novih FNV soli.

Neresno / tveganja + prioritete R372:
- ✅ Deploy zdrav (R370 ŽIVO na produ — STIRIINDVJSETIJNA preverba zeleno; val 53 POST-deploy potrjen DIREKTNO na vseh 4 needlejih + montirani DOM dokazi vodja/invoice/calculator); ni lastnikove akcije.
- ⚠️ **val 54 produkcijska verifikacija = R372**: r371.tsv 4 needleji ŽIVO v lokalnem buildu; na produ še STARI razredi. R372 pričakuje: era preverba 4/4 ŽIVO (delno prek hash rezolucije) + spot re-proba 13 surovih vrstic (audit-trail dialog vrata: zgodovina odprta; dashboard iskanje: vnos ≠ prazno → clear ŽIVO; calculator zgodovina vrstica vrata: shranjen izračun; punch/inclinometer PDF vrata; **vse sonde naj SPET poročajo mounted + className LOČENO**, LEKCIJA R365 (4) + dispatch+poll VSAKA — LEKCIJA R370 (6)).
- ⚠️ **Legacy build-needle skripti r227–r339 IZVEN verige (ostaja)** — samo r236/r237 osvežena (R370); popolna revija ALI register-retirement = lastniška odločitev. NI blokiral.
- ⚠️ **Iskrenost dolg (owner-level, ostaja)**: bulk trigger title 'Trajno izbriši' vs arhivira resnica — pinan v zamrznjenem r350.tsv; potreben register-retirement kanon (lastniška odločitev). NI blokiral.
- ⏰ **roksal-fallback-db POTEČE 2026-10-25** (~3 tedne) — obvestiti lastnika (75. zapis; datum nespremenjen — iz R370 (74.) izpeljano).
- **R372 prva naloga** = `qa-round.sh 371 prod-qa re-run` [prek `r359-prod-qa-retry.sh 371`] + **PETINDVJSETIJNA era preverba r347–r371** [25 registrov, ≥105 need_static = 101 + 4 — pričakuj VSE ŽIVO; 2 R353 needleja prek hash rezolucije; kanonski skript `r372-era-harvest.sh` [klon r371; 25 registrov, ≥105] pričakovan] + val 54 POST-deploy verifikacija [13 surovih brand vrstic spot — mounted + className LOČENO; dispatch+poll VSAKA površina].
- R372 kandidati: **?INTERP ×1 preostala** [roksal-catalog L110 KIT template chip — kit override doktrina ali ročen offset; census preverba] ALI **INPUT/LINK/CMP fokus-jezik doktrina** [2 iskalna vnosa + 5 CMP + top-bar — usklajena doktrina 'lastni fokus jezik' zapisana v register ALI lastniška odločitev o offsetu na inputih] ALI **nov stil val 55 — red/40 družina** [census: red/40 gap 22 = NONE ×20 + O1 ×2 — per-vrstična triaža iz diska prek r371-none-triage.py EXTENZIJE (generalizacija na poljuben žeton) PRED odločitvijo] — vedno z fetch-first + TSV kanonom + stale-pin PRED-skanom prek r370-window-scan.py **+ ŠTEVEC guard sken čez stil teste prejšnjih valov** (LEKCIJA (7)).
- ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
- LEKCIJE R371: (1) **klon-kanon preverbe morajo ločiti PRED-pogoje (vhodni rep) od POST-pogojev (novi žigi)** — TODO-R370 ne sme biti v must seznamu r370-klona (še ne obstaja v viru); (2) **legitimen ostanek stare ere-besede v NOVI glavi** [triindvajsete preverbe R370] — žig pričakovan natančen; 2. ponovitev istega vzorca iz R370 klon lekcije (LEKCIJA R362 (3) kanon pri ponovitvi); (3) **era-needle grep z vodilnim pomnilnikom rabi `--`/`-e`** [top-1/2 -translate… je lažno padel kot grep opcija]; (4) **must_miss assert = POLNI needle niz** — krajša sosledja laže živi na KIT vrsticah z ISTO sosledjem [L262 h-7]; (5) **okenski kanon r346 je LINE-based [i-8..i+6]** — char-based naprej-usmerjena replika zgreši className PRED aria-jem; replika = ISTA semantika kot original (LEKCIJA R364 (4) precizirana); (6) **dispatch+poll na VSAKI spot površini** — LEKCIJA R370 (6) aplicirana: 4/4 površine ŽIVO brez lažne praznine (razen iskrenih vrat meseciCsv); (7) **okno-orodje NE vidi ŠTEVČNIH guardov** — stale-pin pre-skan mora vključiti tudi ŠTEVCE (offset-2 per datoteka) iz stil testov prejšnjih valov nad ISTIMI datotekami; FULL vitest je ulovil, pre-skan ne (razširitev LEKCIJE R369 (2) na števce); (8) **CJK revizija roundskih besedil** — roundski bullet je nosil naključne '向往' znake; popis V ISTI rundi + preverba (rg CJK range) pred commitom.
"""

path = "/home/z/my-project/worklog.md"
with open(path, "r", encoding="utf-8") as f:
    src = f.read()

GUARD = "(5) **tema-neodvisen offset žeton pokrije svetlo+temno par** — ENA substitucija na pariško vrstico namesto dveh (kanon R368 L748 formaliziran v val 52 kanon)."
if GUARD not in src:
    raise SystemExit("FAILOVEDANO: worklog rep ni znan — abort")
# R370 vnos je bil dodan po R369 — rep je zdaj R370 LEKCIJE (7): pipe skrije exit kodo
if "exit kode meriti BREZ pip." not in src:
    raise SystemExit("FAILOVEDANO: R370 rep manjka — abort")
if "Task ID: R371 (" in src:
    raise SystemExit("FAILOVEDANO: R371 vnos že obstaja — abort")

if not src.endswith("\n"):
    src += "\n"
src += ENTRY
with open(path, "w", encoding="utf-8") as f:
    f.write(src)
print("OK: R371 vnos dodan")
