#!/usr/bin/env python3
# r379-worklog-append.py — R379 fail-closed append v worklog.md
# DVA vnosa: (1) ADOPCIJSKI vnos R378 [njihova poslovna runda 73d57b0 —
# worklog vnos NI obstajal, LEKCIJA R369 (1) ponovitev; vsebina IZ IHOVEGA
# commit sporočila, GLASNO označena kot adopcija], (2) moj R379 vnos.
# Guard = rep R377 vnosa (disk resnica — njihov vnos je izpuščen!).
import sys, pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")
GUARD = "R378 kandidati: 1. window-scan generalizacija [FIXED-STRING needle pini iz r340+ registrov + slice-okna — LEKCIJA R377 (4) zaprta z orodjem] ALI era-harvest needle→ruta mapping stolpec [preciznejši server dokaz]; 2. e2e-lib dedup 16. val [po kanonu le ob novih ×3 ponovitvah]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA]."

R378_ADOPCija = """---
Task ID: R378
Agent: vzporedna lastniška runda (73d57b0) — ADOPCIJSKI vnos dopisan v R379 (worklog vnos NI obstajal v commitu — LEKCIJA R369 (1) ponovitev; vsebina iz njihovega commit sporočila)
Task: R378 — PROIZVODNA + AS-INSTALLED DOMENA (issue #13, korak R167 iz §9 + §10) — KOLIZIJA #20 [njihova številka; moja QA runda preimenovana R377→R378→(sedaj)R379]

Work Log (POVZETEK iz njihovega commit sporočila 73d57b0 — ni v moji rundi generiran):
- (1) ProductionOrder [§10 nalog NAD ODOBRENIM BOM; statusni stroj v src/lib/production-orders.ts EN VIR: PLANNED→RELEASED→IN_PRODUCTION→QC→PRODUCED→READY_FOR_INSTALLATION + izidi REWORK/REJECTED/SCRAPPED/REPLACED — vsak izid ZAHTEVA razlog; prepovedani robovi dokumentirani; PLANNED→RELEASED napolni approvedById/approvedAt]; (2) ProductionOrderLine [snapshot BOMLine; remainingQty STREŽNIŠKO izračunan — klientov total NE sprejet; invarianti rejected ≤ produced (400), produced+scrapped ≤ planned (409)]; (3) ProductionOperation [statusni stroj PLANNED→IN_PROGRESS→DONE|FAILED + FAILED→PLANNED; DONE terminalen]; (4) InstallationRecord [§9 'tretja resnica' VERZIONIRANA @@unique([projectId, versionNumber]); DRAFT→POTRJENO terminalno; bomVersionId RESTRICT; vezave ponovna uporaba SetNull]; (5) InstallationRecordLine [bomLineId NULL = vgrajeno IZVEN BOM iskreno; internalSku SNAPSHOT strežniško PREPISAN (LAŽNI-SKU test); installedQty > 0; dvojen NE-NULL bomLineId zavrnjen]; (6) MEJA ZAKLEPA R167: ustvarjanje po zaklepu 409, izvedba teče naprej; monter na zaklenjenem 403 od RBAC; (7) §9 KOLIČINSKA VERIGA v GET /api/bom/procurement [additivno]: producedQty = Σ VSIH nalogov, installedQty = Σ SAMO POTRJENIH zapisov (DRAFT ne šteje — test izrecno); NEVEZANA → NULL nikoli ničle; (8) API rute hišnega vzorca: POST/GET/PATCH /api/production + /api/installation-records ×3; (9) §10 STRAŽAR GEOMETRIJE iz VIRA modula; (10) production-orders.ts čisto jedro + production-store.ts transakcijska plast [EN VIR + auditInTx]; (11) migracija 20261005080000_r378_production_domain [5 tabel, CHECK ×VSE VALIDATED, brez seeda — iskreno §8]. PIN SHIFT-i: r191 val2 48/63→52/67 handlerjev + r308 88→92 route datotek. SANDBOX: roksal_dev rebuildan iz nič do r378 + seed + CI users.
- Njihova VERIFIKACIJA (iz commit sporočila): vitest 5417/5417 (350) POLN TEK 1 zelen [r378-production-orders ×23 + r378-production-store ×15 + r378-installation-records ×10 + r378-quantity-chain ×6 + r376-bom-procurement PIN SHIFT] · build svež EXIT=0 · 4 needleji ŽIVI v .next/server+static · qa-round.sh 378 needles EXIT=0 · fetch-first ×0 v HEAD aea8720 · leak-check čist.
- NJIHOVE LEKCIJE (iz commit sporočila): (1) ozadnji delegirani agent ujame kolizijo tudi ko glavni agent vidi timeout; (2) parsed.data.action discriminant se ne ohrani za destrukturiranje v isti stavku — lokalna const; (3) vrata v PLASTI imajo VRSTNI RED; (4) monter na zaklenjenem projektu = 403 od RBAC; (5) SIDRA testni fixture globalno unikaten — suite ga mora pobrisati; (6) stale staged kopije po prekinitvi — prepiši z zadnjo preverjeno različico.

Stage Summary:
- KOLIZIJA #20 [20. potrditev]: vzporedna lastniška QA R377 [aea8720] pristala med njihovim delom → preimenovana R377→R378. Njihov README števec je ostal ZASTAREL (disk 5363/346, commit trdi 5417/350) — popravljen v R379. Njihov worklog vnos NI obstajal — ta adopcijski vnos dopisan v R379 (GLASNO označen kot povzetek iz commit sporočila — NI moja runda, NI moje vrednotenje njihove vsebine).
- Kontrakt NIČ; SDK/BOM/pricing/geometry core NIČ [njihova produkcija ni moja površina]; OgrajaVizija nič; brez sheme sprememb s strani QA [njihova shema = njihova poslovna odločitev]. ⏰ roksal-fallback-db POTEČE 2026-10-25 (81. zapis).
"""

R379 = """---
Task ID: R379
Agent: Super Z (AI runda, Job 413422, tick 202610030215)
Task: R379 (preimenovana iz R378 po KOLIZIJI #21) — prva naloga (prod-qa re-run 377 + ENAINTRIDESIJNA era preverba r347–r377 + val 58 POST-deploy verifikacija) + MANDATORY STIL val 59 + FEATURE window-scan generalizacija + re-aplikacija po koliziji + DVAINTRIDESIJNA era preverba + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD aea8720 (R377) — KOLIZIJA #20: NI (ob startu); delovno drevo čisto; worklog R377 vnos = handover (prebran celoten).
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 377` — **ZELEN ob poskusu 1** (15. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **ENAINTRIDESIJNA era preverba** (31.) `r378-era-harvest.sh` [31 registrov r347–r377, ≥126 = 125 + 1, vsota IZ DISKA; generiran prek `era-clone.py --src-round 377 --expected-total 126 --dst-round 378 --dst-label "R378 val 59" --dst-chain-seg "IN r376.tsv ×4 IN r377.tsv val 58 ×1 na"`]: **EXIT=0 ob 1. teku** (in ponovitev EXIT=0 — determinizem) — **115 ŽIVO DIREKTNO + 11 rezolucij ŽIVO** [6 hash + 5 SERVER: r374 price-book + r376 BOM ×4]; **r371 NASLEDNICA ŽIVO (chunk_028)**; ⭐ **val 58 needle ŽIVO DIREKTNO** (chunk_028) → **val 58 deploy POTRJEN v celoti**; must_miss ×31 čisto.
- ⭐ **LEKCIJA R379 (1) — era-clone.py PODNIZ-HROŠČA** [orodje ujelo SVOJO hroščo, fail-closed NI zapisal outputa]: POST preverba 'expected 0' starih era besed lažno pozitivna — slovenska sestavljena številska beseda vsebuje PREJŠNJO kot podniz (ENAINTRIDESIJNA ⊃ TRIDESIJNA, ENAINTRIDESETIH ⊃ TRIDESETIH, enaintrideset ⊃ trideset); 31. preverba = PRVI prehod v INTRIDESIJNA družino (22→30 prehodov brez podnizov → hrošča spala); poprava: `stej()` z LEVO črkovno mejo `(?<![A-Za-zŠČŽščž])` za 4 stare-era vzorce; 2. tek EXIT=0.
- PRVA NALOGA (C): **val 58 POST-deploy spot** `r379-qa-spot.sh` (spot-r167/22; mounted + className LOČENO, dispatch+poll VSAKA, kolektor 0 errorjev): (A) bazna resnica — PRAZNO iskanje → 'Počisti iskanje projektov' **0 montiranih** (kanon r277; sidroCsv=1); (B) fill → **MONTIRAN 1 + VSEH 5 needle klas = 1** [transition-colors, ring-2, navy/40, offset-2, rounded — LOČENO]; (C) **PRAVI klik OK** (Playwright trusted event, scrollintoview) → vrednost '' + **od-montiran 0** — funkcionalni dokaz v OBEH smereh; (D) navy sonda 5/4/1 [BrezOffset=1 = znana kit izjema #1], red sonda 0; (E) kolektor 0.
- ⭐ **LEKCIJA R379 (2) — eb_zapri_vodic RACE** [disk resnica sledenja]: vodič se pokaže ŠELE ~10s+ PO prijavi (hidracija + dynamic chunk ssr:false + setTimeout 1000 v OnboardingWrapper, page.tsx L641 pogojni `activeTab !== 'viz'`) — stara ×3 takojšnja klik streljala PRED mountom → vodič ODPRT celo sejo → ozadje `fixed inset-0 z-[100] bg-black/60` (pointer-events auto) **BLOKALO VSE PRAVE klike** [eval sonde niso prizadele — NEZAZNANO v vseh prejšnjih spot rundah]; v1 popravka (poll ×8) imela LAŽNO POZITIVNI 'zaprto-dokaz' (vodič še NI bil odprt) → **v2 = 2-fazni deterministični post-pogoj**: faza 1 okno pojavitve 45s (ozadje ALI storage='true'), faza 2 dokaz šele `ozadje=0 IN storage='roksal_onboarding_done'='true'` (handleSkip VEDNO piše storage PRED zaprtjem); fail-closed return 1 GLASNO [klicatelji zamrznjenih tokov vračila NE preverjajo — disk resnica]; na lokalnem e2e strežniku se vodič ne hydrira v 45s → iskren warning, tokovi zeleni.
- **DISK RESNICA (najdba)**: search bar na začetnem scroll položaju **POD fixed bottom-nav (z-50)** na 577px viewportu — pravi klik na 'Počisti iskanje' zahteva scrollintoview (pravi uporabnik scrolla — ni app-bug; spot počne ISTO).
- ⭐ **LEKCIJA R379 (3) — PRIKAZNI ARTIFAKT #2** [precedens R369 r369-census.py 'lineax(0…)']: onboarding-tour.tsx L127 prikazan kot `}, andleNext, …])` (manjka `[h`) — TS scanner dokazal BAJTNATO resnico `}, [handleNext, handlePrev, handleSkip])` — tsc EXIT=0 resnica; NIČ 'popravljenega' (fail-closed vs fantom).
- MANDATORY STIL **val 59 — red/40 offset-2 PARITETA**: disk census `r379-census.sh` [5 družin A–E; rdeča 25 vrstic = O2 11 + NONE 14; amber/50 100%; E(navy brez dark-ink) = 0]; **14 × INS ' focus-visible:ring-offset-2' TIK ZA 'focus-visible:ring-roksal-red/40'** (ciljni kanon = val 43 RED_KANON; val 52 pairing kanon generaliziran na rdečo; 8 datotek: dashboard ×5 [L1914/2059/2185/2491/2635], floor-plan ×1 [L1731], inventory ×1 [L1740], quote-followup ×1 [L641], roksal-catalog ×1 [L201], sessions-dialog ×2 [L316/348], termini-card ×1 [L474], top-bar ×2 [L261/268]; +28 znakov/vrstico, in-place 0 novih vrstic); **r372 val 55 izjema #1 RESOLVANA** (top-bar CMP ×2 + dashboard KIT L1914); `r379-val59-apply.py` fail-closed [scan→14, apply 14, subn==plan, in-place dokaz, idempotenca 0]; `r379-stil-val59.test.ts` **×6 it ZELENO** [(A) pariteta + zamrznjeni števci, (B) KANON == red per datoteka, (C) ostanek 0 čez vse roksal, (D) era-diskriminatorji, (E) obrnjena regresija val 55 N1–N4 + val 58 + amber 100%, (F) družina 25/25]; r372 (D)/(E) **PIN SHIFT R379 val 59 / EVOLVED** žigi [(D) o2 11→25, none 14→0; (E) klasifikacijska replika OBRNJENA na RED+O2 = {KIT:12, CMP:2, RAW:1} — L1987 = RAW nativni (val 55 SUB tarča)].
- ⭐ **LEKCIJA R379 (4) — eslint require()**: nov test uporabljal `require('node:fs')` → @typescript-eslint/no-require-imports ×3 — statičen `import { readFileSync, readdirSync }` V ISTI rundi. **LEKCIJA R379 (5) — python with-blok indetacija**: register write ValueError 'I/O operation on closed file' — zanka ZUNAJ `with` bloka; delna datoteka izbrisana, popravljeno.
- FEATURE **`r379-window-scan.py` — 8. generalizacija QA orodij** [formalizacija LEKCIJE R377 (4)]: **DEL 1** regex okenski kvantifikatorji nad 8 tarčami (53 regexov; delta-simulacija) + **DEL 2 NOVO: FIXED-STRING needle pini IZ REGISTROV r340–r379** (vsak grep -F nad src/; 147/147 ŽIVIH po re-aplikaciji — evolucija/izbris needleja ujet TUKAJ, ne šele v vitestu/era harvestu) + **DEL 3 NOVO: slice-okna detekcija** (17 vzorcev); delta 28 → 0 preozkih EXIT=0.
- ⭐ **KOLIZIJA #21 [21. potrditev, kanon KOLIZIJE #4/R323/#13–#20]**: push REJECTED — origin/main premaknjen aea8720→**73d57b0** (njihova poslovna R378 PROIZVODNA DOMENA, issue #13 korak R167) MED mojim delom → moja runda preimenovana **R378→R379** [njihova r378.tsv + r378-*.test.ts ostanejo; moji artefakti preimenovani r378-*→r379-*; val 59 OSTANE val 59 — poslovne runde NE porabijo val, kanon R375]. POSTOPEK: backup branch `r378-ai-delta` → `reset --hard origin/main` → re-aplikacija delta [era-clone.py poprava, e2e-lib.sh v2, r372 PIN SHIFT/EVOLVED, val 59 INS ×14 prek apply (targets iz diska — KOLIZIJA re-apply kanon), preimenovanje VSEH artefaktov + žigov] → prisma generate + `migrate deploy 20261005080000_r378_production_domain` [njihova shema; LEKCIJA R377 (8): shell env URL s fh—— napakami citati — P1012] → **DVAINTRIDESIJNA era preverba** (32.) `r379-era-harvest.sh` [32 registrov r347–r378, ≥130 = 126 + 4]: **EXIT=0** — 115 direktno + 15 resolucij [6 hash + 11 SERVER: r374 + r376 BOM + **njihovi 4 produkcija needleji prek production-store_ts chunka + prod /api/production 401** — njihov deploy ŽIVO]; must_miss ×32 čisto.
- ⭐ **LEKCIJA R379 (6) — era-clone verižni-rep + banner generalizacija (9.)**: statična vzorca `IN r{N}.tsv val M ×4 na` / `IN {label} (×4) ŽIVO NA PRODU` NE ujameta mešanih repov (ročni chain-seg) IN multiplicit ≈ ×1 — regex detekcija DEJANSKEGA segmenta (`IN r{N}.tsv[^#\\n]*? na` oz. `IN {label} (×\\d+) ŽIVO NA PRODU`) z count-checkom == 1; + oznaka konvencija: register vrstica nosi LASTNO oznako datoteke ('R377 val 58', ne 'R378 val 59') — popravljeno v r378-era-harvest.sh (L120 + banner) za veriženje.
- **e2e-lib dedup 16. val ISKRENO IZPUŠČEN** [kanon R368: le ob novih ×3 ponovitvah].
- REGISTER `scripts/qa-needles/r379.tsv` [4 need_static per-datoteka: top-bar CMP par ×2, sessions-dialog par ×2, dashboard KIT par ×2, termini-card ×1 + roksal-catalog ×1 (isti niz); must_miss TODO-R379; NF=3 vsi; **×0 v HEAD 73d57b0 fetch-first GLASNO**]; izpuščeni kandidati dokumentirani [floor-plan/inventory/quote-followup pokriti prek vitest (A)/(C); red-400/60 = druga družina; B/C/A navy gap družine = NASLEDNJI val kandidati].
- README: 5363/346 → **5423/351** [njihov zastarel števec popravljen — disk resnica 5363/346, njihov commit trdi 5417/350; 5423 = 5363 + njihovih 54 + mojih 6; 351 = 346 + 4 + 1] + R379 bullet (njihov R378 bullet žig ohranjen) prek `r379-readme-update.py` fail-closed.
- **ADOPCIJA**: njihov worklog vnos NI obstajal v 73d57b0 → adopcijski vnos R378 dopisan ZGORAJ (povzetek iz njihovega commit sporočila, GLASNO označen — LEKCIJA R369 (1) ponovitev, 2. ponovitev vzorca R374).

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND, na KONČNI viri PO re-aplikaciji KOLIZIJE #21): tsc 0 · eslint 0 (FULL, po require()-popravi) · vitest **5423/5423 (351) FULL GREEN** [= njihova baza 5417/350 + mojih +6/+1 − 0] · build svež rm -rf .next EXIT=0 [na njihovi shemi — prisma generate + migrate deploy] · qa-round.sh 379 needles EXIT=0 [97× FAIL=0; r379.tsv 4 need_static ŽIVO + TODO-R379 odsoten + njihov r378.tsv ŽIVO; UNION r340–r379 + veriga r339→…→R227] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r378-era-harvest EXIT=0 [31st] + r379-era-harvest EXIT=0 [32nd] · r359-prod-qa-retry 377 ZELEN ob poskusu 1 · r379-window-scan EXIT=0 [147/147 needlejev ŽIVIH] · leak-check čist.
- NOVO: scripts/qa-needles/r379.tsv + skripte [r379-era-harvest.sh, r379-qa-spot.sh, r379-census.sh, r379-val59-apply.py, r379-window-scan.py, r379-register-write.py, r379-readme-update.py, r379-worklog-append.py, r379-click-probe.sh (diag), r379-ast-probe.cjs (fantom dokaz), r379-commit-msg.txt] + r379-stil-val59.test.ts [×6] + UREJENO: e2e-lib.sh [eb_zapri_vodic v2], era-clone.py [podniz-hrošča + verižni-rep/banner generalizacija 9.], r372-stil-val55.test.ts [PIN SHIFT/EVOLVED], 8 render datotek [val 59 INS], r378-era-harvest.sh [oznaka konvencija fix], README.
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 59 = render plast a11y className-only v 8 render datotekah]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (81. zapis). ⚠️ njihova nota: žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R380 prva naloga = qa-round.sh 379 prod-qa re-run [prek r359-prod-qa-retry.sh 379] + triintrideseta era preverba r347–r379 [33 registrov, ≥134 = 126 + 4 + 4; prek era-clone.py --src-round 379 --expected-total 134 --dst-label "R380 val 60" [oz. kandidatska val]; pričakuj 134/134 ŽIVO [r379 4 needleji razrešeni ob TEM pushu]] + val 59 POST-deploy verifikacija [4 needleji r379.tsv; vrata: rdeči akcijski gumbi — top-bar odjava CMP meni, sessions-dialog odjava naprave, dashboard rdeči KIT akcije; mounted + className LOČENO].
- R380 kandidati: 1. **B/transition-colors družina** [crm-tab ×12 + dashboard ×3 + cena paneli ×4 + audit ×2 + calculator ×1 + sketch ×1 + vodja ×4 + termini ×4 — KIT vrstice N/A (transition-all iz baze) — nativni <button> triaža po kanonu val 58]; 2. **C/border-pariteta družina** [crm-tab ×13 + dashboard ×7 + bottom-nav ×2 + calculator ×2 + audit ×3 + cena paneli ×4 + safety ×2 + team ×6 + termini ×6 + vodja ×4 + site-survey ×1 + sketch ×1 — r379-census.sh]; 3. A/offset ostanki ×11 [dashboard Input L1623 = izjema #2 zamrznjena]; 4. era-harvest needle→ruta mapping stolpec [preciznejši server dokaz]; 5. e2e-lib dedup 17. val [po kanonu]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""
src = W.read_text(encoding="utf-8")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard (rep R377) najden ×{src.count(GUARD)} ≠ 1 — abort")
if "Task ID: R379" in src or "ADOPCIJSKI vnos dopisan v R379" in src:
    sys.exit("FAILOVEDANO: R379/adopcijski vnos ŽE obstaja — protokol ponovitev, abort")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu datoteke — abort")
W.write_text(src.rstrip("\n") + "\n\n" + R378_ADOPCija + "\n" + R379, encoding="utf-8")
new = W.read_text(encoding="utf-8")
if new.count("Task ID: R378") != 1 or new.count("Task ID: R379") != 1:
    sys.exit("FAILOVEDANO: POST preverba števcev — abort")
if not new.rstrip("\n").endswith("razvoj > QA]."):
    sys.exit("FAILOVEDANO: POST preverba repa — abort")
print(f"OK: R378 (adopcija) + R379 vnosa pripeta; worklog = {len(new)} bajtov")
