#!/usr/bin/env python3
# r381-worklog-append.py — R381 fail-closed append v worklog.md (EN vnos:
# R381; ADOPCIJA NI bila potrebna — njihov R380 vnos je bil v LASTNI rundi
# c63ee37, vzorec R376/R379; KOLIZIJA #22 žig GLASNO).
# Guard = ZADNJA ne-prazna vrstica worklog.md (disk resnica) z GLASNO
# prefix preverbo '- LEKCIJA (build):' — rep njihovega R380 vnosa.
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- LEKCIJA (build): SIGKILL build workerja"):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep njihovega R380 vnosa: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard najden ×{src.count(GUARD)} ≠ 1 — abort")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu datoteke — abort")

VNOS = """---
Task ID: R381
Agent: Super Z (AI runda, Job 413422, tick 202610030400; runda PREIMENOVANA R380→R381 po KOLIZIJI #22)
Task: R381 — prva naloga (prod-qa re-run 379 + TRIINTRIDESIJNA era preverba r347–r379 + val 59 POST-deploy verifikacija) + MANDATORY STIL val 60 (nativni prehod-paritetni zaključek) + REGISTER EVOLUCIJA (3. uporaba) + FEATURE era-ruta-mapa + window-scan 10. generalizacija + KOLIZIJA #22 re-aplikacija + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 9c36c51 (R379) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R379 vnos = handover (prebran celoten). ADOPCIJA ob startu ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 379` — **ZELEN ob poskusu 1** (16. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **TRIINTRIDESIJNA era preverba** (33.) `r380-era-harvest.sh` [33 registrov r347–r379, ≥134 = 126 + 4 + 4, vsota IZ DISKA; generiran prek `era-clone.py --src-round 379 --expected-total 134 --dst-round 380 --dst-label "R379 val 59" --dst-chain-seg "IN r378.tsv ×4 IN r379.tsv val 59 ×4 na"` — oznaka konvencija R379 (6)]: **EXIT=0 ob OBEH tekih** (determinizem) — **val 59 needleji VSI 4 ŽIVO DIREKTNO** [top-bar CMP par chunk_014, sessions-dialog par chunk_031, dashboard KIT par + termini/catalog chunk_028] → **val 59 deploy POTRJEN v celoti**; must_miss ×33 čisto.
- PRVA NALOGA (C): **val 59 POST-deploy spot** `r381-qa-spot.sh` (spot-r167/23; mounted + className LOČENO — LEKCIJA R365 (4); **ZERO-MUTACIJA: NIČ klikov na odjavo/preklic seje** — samo Radix meni/dialog odpiranje po kanonu r186 pointerdown+click): (A) top-bar trigger aria-label="Odjava" → meni odprt → **N1 2/2 rdeča DropdownMenuItema FULL parity** [ring-2, red/40, offset-2, gap-2 — VSI ločeno ×2] + besedili 'Ta naprava'/'Vse naprave (tudi ta)' + Escape → menuitemi 0 (od-montiran dokaz); (B) meni → 'Aktivne seje' → dialog → **47 aktivnih sej: 46 preklici-gumbov (!s.current) + 1 'Odjavi vse ostale naprave' (ostaliCount>0) = 47/47 parity** [press-scale+ring-2+red/40+offset-2 ločeno ×47] + Escape → zaprt — dinamična disk resnica (spot račun kopiči seje iz QA rund; NO revocation executed); (C) dashboard N3 error-retry **iskreno 0** (vrata invError/narocilaError — zdrava seja, kanon r277 + razlog iz vira L1914/L2059); (D) catalog N4 **iskreno 0** (vrata napaka — L50 fetchProfili); navy sonda 10/0/10 [catalog površina — val 52 ne pokriva roksal-catalog navy familije = znan val 53+ kandidat, NE regresija; R379 spot je meril dashboard 5/4/1]; red sonda 0; kolektor **0**; eb_zapri_vodic iskren warning (vodič se na hladnem produ ni hidriral v 45s — v2 fail-closed kanon R379 (2)).
- ⭐ **LEKCIJA R381 (1) — handover kandidat številke = REPVIDLJIVI podniz censusa**: R379 handover je za kandidata B navajal 31 vrstic (tail-visible datoteke zadnje census teke); POLNA disk resnica = **155 navy + 15 red = 170 vrstic** — navedki iz delnega izpisa so NEZANESLJIVI za scoping; pred vsakim apply OBVEZNA sveža element-nivojska triaža (`r381-triaza.py`).
- MANDATORY STIL **val 60 — NATIVNI PREHOD-PARITETNI ZAKLJUČEK**: disk resnica `r381-triaza.py` [element klasifikacija z retrograde tag-walkom: 170 vrstic = **154 × <Button>** (transition-all IZ BAZE ui/button.tsx L8 → N/A, kanon val 58 'KIT nosi transition-all iz baze') + **3 × nativni <button>** + **13 × drugo** = 8 input/textarea/Input (FROZEN izjema #2, kanon R377) + **5 × top-bar DropdownMenuItem** (3 navy + 2 red; ui/dropdown-menu.tsx BREZ transition)]: **11 × INS na 8 vrsticah, in-place 0 novih vrstic** — (a) 3 nativna gumba `INS ' transition-colors' PRED 'focus-visible:ring-2'` (kanon val 58): audit-trail-dialog L310, measurements-tab L4020 ('Naloži stopnično predlogo'), photo-tab L2370 ('Uredi mero') — vsi navy; (b) 5 top-bar meni itemov INS transition-colors (kanon val 58 za ne-Button interaktivne elemente) + 3 navy itemi INORE `INS ' focus-visible:ring-offset-2' ZA navy/40` (**val 52 pairing kanon — meni-notranja pariteta z rdečima sestro, ki sta O2 dobili v val 59**); frozen: input/textarea ×8 nedotaknjeni. `r381-val60-apply.py` fail-closed [SCAN→APPLY→POST→idempotenca: scan 11/11, in-place dokaz, idempotenca 0].
- Stale-pin pre-skan (R369 lekcija 2 kanon): delta ×2 [+18 / +28 konteksta] = **0 preozkih okenskih pinov** + needle pini ŽIVIH + in-place 0 odstopanj.
- ⭐ **REGISTER EVOLUCIJA** (kanon r371 N3 / R377, **3. uporaba** prek `r381-evolucija.py` fail-closed): val 60 INS je evoluiral **r379 needle #1** (top-bar CMP par — ISTA vrstici, ki ju je val 59 prijel) → stara need_static vrstica KOMENTIRANA dobesedno ('# … — EVOLVED R381 val 60: …') + **NASLEDNICA** podatkovna vrstica 'gap-2 transition-colors focus-visible:ring-2 focus-visible:ring-roksal-red/40 focus-visible:ring-offset-2' → **need_static r379 = 4 NESPREMENJEN** (era vsote ≥134 veljavne); NASLEDNICA pride na produ OB TEM pushu (r382 era žetva jo bere ŽIVO); **PIN SHIFT žigi `PIN SHIFT R381 val 60 / EVOLVED`** v r372-stil-val55.test.ts (D) + r379-stil-val59.test.ts (D) [+ nova ×0 asercija stare oblike — pariteta dokazana v OBEH smeri].
- `r381-stil-val60.test.ts` **×6 it ZELENO** [(A) signaturne vrstice per datoteka (audit 1, measurements 5, photo 1, top-bar 5) + zamrznjeni števci vrstice/hex/aria/title, (B) top-bar meni pariteta evolved ×3 navy + ×2 red / stara oblika ×0, (C) nativni gumbi evolved ×1 + pre-val ×0, (D) FROZEN izjema #2 natančni podnizi (inventory ×1+×3, logistics ×3+×1, catalog ×1), (E) obrnjena regresija val 59 KANON ×25 + val 55 N1–N4 + val 58 + amber 100%, (F) vrstični brez-transition števec **170 → 162** (−8 val 60 vrstic)]; ⭐ **LEKCIJA R381 (2) — element vs vrstica disk resnica**: triaža klasifikacija (3 nativni + 8 frozen) se NE preslika 1:1 na vrstične filtre (SIGNATURA vrstice vključujejo že-parirane prejšnjih valov: measurements 5 = 1 val 60 + 4 prej; vrstični brez-transition = 162 ne 8, ker Button vrstice nosijo transition-all šele v renderu) — 3 testna faila ujeta ŠE PRED FULL tekom, popravljena na disk resnico V ISTI rundi.
- FEATURE **`r381-era-ruta-map.py` — needle→RUTA mapping** [handover kandidat 4: preciznejši server dokaz]: za need_static needleje r340–r381 TRI jezika dokaza — (1) ruta-direktno (needle v route-lokalnem .next/server/app fajlu, ruta iz obrnjega app-paths-manifest.json), (2) prek-importa (needle v skupnem server chunku → enostopenjski import pregled route fajlov — iskreno omejitev), (3) probe-ruta (SERVER_PROBE_SPECS: VAR→register→ruta); client-only = 'shared-client-chunk' iskreno. **REZIME (na pred-kolizijskem buildu): /api/price-book 4, /api/installation-records 4, /api/bom/[id] 2, /api/bom/procurement 1, /api/deal-lock 1, /api/calculator 1 + 130 shared-client + 8 shared-server** — r374/r376/r378 server needleji zdaj nosijo IZRECNO rutovo asociacijo; ⭐ **LEKCIJA R381 (3) — regex capture group**: findall '(r\\d+)\\.tsv' ujame 'r374' BREZ '.tsv' → re.search '.tsv' na njem = None; poprava `int(p[1:])` (orodje ujelo SVOJO hroščo — EXIT=1 fail-closed, 3. ponovitev vzorca R379 (1)/R369).
- **`r381-window-scan.py` — 10. generalizacija QA orodij** (naslednik r379 8. generacije, NIKOLI ne mutiran): TARGETS +3 val 60 tarče (audit-trail/measurements/photo), REG window 340–381 (tolerantno na manjkajoče registre — skenljiv PRED in PO pisanju registra), **DEL 4 NOVO: in-place varstvo** (per-tarča vrstični števec PRIČAKOVANE_VRSTICE z diska; odstopanje = EXIT 1).
- **e2e-lib dedup 17. val ISKRENO IZPUŠČEN** [kanon R368: le ob novih ×3 ponovitvah].
- REGISTER `scripts/qa-needles/r381.tsv` [4 need_static per-datoteka: top-bar navy meni evolved ×3 (L239/246/253), audit-trail L310 ×1, measurements L4020 ×1, photo L2370 ×1; vsi 0 v HEAD c63ee37; rdeči evolved par pokrit prek r379 NASLEDNICE — brez duplikata; must_miss TODO-R381; NF=3 vsi] prek `r381-register-write.py` fail-closed [PRED/PO žigi, idempotenca].
- README: 5488/355 → **5494/356** [= njihova baza 5488/355 + mojih +6/+1] + R381 bullet (njihov R380 bullet ohranjen) prek `r381-readme-update.py` fail-closed; ⭐ **LEKCIJA R381 (4) — PO asercija niz**: preverba je iskala napačen žig v bulletu ('R380 prva naloga =' namesto naslednje runde) — fail-closed abort PO zapisu; datoteka bila PRAVILNA, popravljen SKRIPTOV assertion (iskren dokaz: grep disk resnica; 4. ponovitev orodje-lovi-svojo-hroščo).
- ⭐ **KOLIZIJA #22 [22. potrditev, kanon KOLIZIJE #4/R323/#13–#21]**: push REJECTED — origin/main premaknjen 9c36c51→**c63ee37** MED mojim delom: njihova poslovna **R380** [2f5cb30 — issue #13 korak R168 §12 REAL UNITS + DECIMAL: centralna zaokroževalna politika decimal-policy.ts + kanonične enote units.ts + konverzija na Inventarju + 21 Float→Decimal stolpcev + r380.tsv 4 server needleji + r380-*.test.ts ×4] + c63ee37 (njihov worklog vnos v LASTNI rundi — vzorec R376/R379, LEKCIJA R369 (1) izpolnjena S PRIHODOM: brez adopcije) → moja runda preimenovana **R380→R381** [val 60 OSTANE val 60 — poslovne runde NE porabijo val, kanon R375]. POSTOPEK: backup branch `r380-ai-delta` → `reset --hard origin/main` → delta re-aplicirana prek checkouta iz backup brancha [4 render datoteke + r379.tsv EVOLVED + 2 PIN SHIFT testa — njihov commit NI dotaknil mojih 4 render datotek/r379.tsv/testov = čista re-aplikacija] + preimenovanje mojih artefaktov r380-*→r381-* [razen r380-era-harvest.sh — 33rd ostane pod izvirnim imenom, kanon R379/r378-era-harvest.sh] + žigi R380 val 60 → R381 val 60 + **NJIHOV r380.tsv zahteva VARSTVO: moj checkout je nadomestil njihov register → obnovljen iz origin/main GLASNO** → **ŠTIRIINTRIDESIJNA era preverba** (34.) `r381-era-harvest.sh` [34 registrov r347–r380, ≥138 = 134 + 4; generiran prek era-clone.py --src-round 380 --dst-round 381 --dst-label "R380 issue #13 (R168)" --dst-chain-seg "IN r380.tsv ×4 na" --server-probe ×6 incl. "AG|/api/inventory|401"].
- VERIFIKACIJA post-KOLIZIJA: glej Stage Summary (celotna veriga na KONČNI viri).

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND, na KONČNI viri PO re-aplikaciji KOLIZIJE #22): tsc 0 · eslint 0 (FULL) · vitest **5494/5494 (356) FULL GREEN** [= njihova baza 5488/355 + mojih +6/+1] · build svež rm -rf .next EXIT=0 [na njihovi shemi — 21 Float→Decimal] · qa-round.sh 381 needles EXIT=0 [r381.tsv 4 ŽIVO + TODO-R381 odsoten + r379 NASLEDNICA ŽIVO + njihov r380.tsv ŽIVO; UNION r340–r381 + veriga r339→…→R227] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r380-era-harvest EXIT=0 [33rd ×2 — determinizem] + r381-era-harvest EXIT=0 [34th — njihovi 4 needleji ŽIVO] · r381-window-scan EXIT=0 · r381-era-ruta-map EXIT=0 · r359-prod-qa-retry 379 ZELEN ob poskusu 1 · leak-check čist [pravi pattern ghp_[A-Za-z0-9]{30,} ×0 na HEAD].
- NOVO: scripts/qa-needles/r381.tsv + skripte [r381-era-harvest.sh (34.), r381-qa-spot.sh, r381-triaza.py, r381-val60-apply.py, r381-window-scan.py, r381-evolucija.py, r381-era-ruta-map.py, r381-register-write.py, r381-readme-update.py, r381-worklog-append.py, r381-commit-msg.txt] + r381-stil-val60.test.ts [×6] + r380-era-harvest.sh [33rd, ime ohranjeno] + UREJENO: audit-trail-dialog.tsx, measurements-tab.tsx, photo-tab.tsx, top-bar.tsx [val 60 INS], r372-stil-val55.test.ts [PIN SHIFT], r379-stil-val59.test.ts [PIN SHIFT], r379.tsv [EVOLVED+NASLEDNICA], README.
- Kontrakt NIČ (/api/sync); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 60 = render plast a11y className-only v 4 render datotekah; njihova decimal/units produkcija = njihova poslovna odločitev]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (81. zapis). ⚠️ njihova nota: žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R382 prva naloga = qa-round.sh 381 prod-qa re-run [prek r359-prod-qa-retry.sh 381] + petintrideseta era preverba r347–r381 [35 registrov, ≥142 = 138 + 4; prek era-clone.py --src-round 381 --expected-total 142 --dst-label "R381 val 60"; pričakuj 142/142 ŽIVO [r381 4 needleji razrešeni ob TEM pushu; r379 NASLEDNICA ŽIVO]] + val 60 POST-deploy verifikacija [4 needleji r381.tsv; vrata: top-bar meni (pointerdown+click na aria-label="Odjava" trigger — kanon r186; 3 navy itemi 'Zamenjaj geslo'/'Aktivne seje'/'Moja vloga in dovoljenja' zdaj z transition+offset-2), audit-trail dialog razpiranje, measurements stopnične predloge, photo 'Uredi mero'; mounted + className LOČENO; NIČ klikov na odjavo/preklic].
- R382 kandidati: 1. **C/border-pariteta družina** [crm-tab ×13 + dashboard ×7 + bottom-nav ×2 + calculator ×2 + audit ×3 + cena paneli ×4 + safety ×2 + team ×6 + termini ×6 + vodja ×4 + site-survey ×1 + sketch ×1 — POZOR: repvidljivi podnizi ≠ polna disk resnica — LEKCIJA R381 (1): triaža pred apply OBVEZNA]; 2. A/offset ostanki [top-bar navy meni ×3 RESOLVANA z val 60; dashboard Input L1623 = izjema #2 zamrznjena + preostanek — sveža triaža]; 3. era-harvest ruta stolpec INTEGRACIJA v era-clone.py [r381-era-ruta-map.py posamično orodje → vgrajen stolpec]; 4. e2e-lib dedup 18. val [po kanonu — le ob novih ×3 ponovitvah]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

out = src.rstrip("\n") + "\n" + VNOS
if out.count("Task ID: R381") != 1:
    sys.exit("FAILOVEDANO: R381 vnos ×" + str(out.count("Task ID: R381")) + " ≠ ×1 (idempotenca)")
W.write_text(out, encoding="utf-8")
print(f"OK: R381 vnos appendan ({len(VNOS)} bajtov); guard rep njihovega R380 vnosa ohranjen nad novim vnosom")
