#!/usr/bin/env python3
# r382-worklog-append.py — R382 fail-closed append v worklog.md (EN vnos:
# R382; guard = rep R381 vnosa z GLASNO prefix preverbo '- R382 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith('- ⭐ LEKCIJA R382 (1):'):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R381: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R383
Agent: Super Z (AI runda, Job 413422, tick 202610030523; runda PREIMENOVANA R382→R383 po KOLIZIJI #23)
Task: R383 — prva naloga (prod-qa re-run 381 + PETINTRIDESIJNA era preverba r347–r381 + val 60 POST-deploy verifikacija) + MANDATORY STIL val 61 (A/offset + C/border-pariteta zaključek, 168 × INS + dark-fix 134) + REGISTER EVOLUCIJA (4.+5.+6. uporaba) + FEATURE era-clone COMPANION + KOLIZIJA #23 re-aplikacija + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 30f856e (R381) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R381 vnos = handover (prebran). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 381` — **ZELEN ob poskusu 2** (17. runda; poskus 1 = znana transient kategorija R358/R359 harvest curl brez retry — wrapper po kanonu ponovil).
- PRVA NALOGA (B): **PETINTRIDESIJNA era preverba** (35.) `r382-era-harvest.sh` [35 registrov r347–r381, ≥142 = 138 + 4, vsota IZ DISKA; generiran prek era-clone.py --src-round 381 --dst-round 382 --dst-label "R381 val 60" --dst-chain-seg "IN r381.tsv val 60 ×4 na" + **VSEH 8 server-probe spec-ov** — LEKCIJA R381 (5) spec-list ZAMENJAVA]: **EXIT=0 ×2** (determinizem) — 142/142 ŽIVO = 123 direktno + 19 resolucij; **val 60 needleji VSI 4 ŽIVO DIREKTNO** (chunk_015/028/026/045) → **val 60 deploy POTRJEN v celoti**; must_miss ×35 čisto.
- PRVA NALOGA (C): **val 60 POST-deploy spot** `r383-qa-spot.sh` (spot-r167/24; mounted + className LOČENO; ZERO-MUTACIJA — NIČ klikov na odjavo/preklic): (A) top-bar meni (kanon r186) → **N1 navy evolved 3/3 + red evolved 2/2 na PRODU** (vseh 5 tokenov ločeno per item) + stara oblika **0** + Escape → 0 — **meni-notranja pariteta dokazana v OBEH smerih na produ**; **DISK RESNICA: spot račun ima 0 projektov na produ** (CSV aria '(0 projektov)' + prazno stanje — programatska preverba) → (B) audit-trail chevroni, (C) measurements stopnične predloge, (D) photo 'Uredi mero' — **iskreno 0 montiranih** (kanon r277 + razlogi iz virov: vrata = projekt-detajl / stair-form L4006 stairTemplates.length>0 / odprta slika z ≥1 merjenjem; ustvarjanje podatkov = mutacija → NE izvedeno); kolektor **0**; eb_zapri_vodic iskren warning (nehidriran na hladnem produ — v2 kanon).
- ⭐ **LEKCIJA R383 (1) — repvidljivi handover kandidati ≠ disk resnica (2. potrditev)**: R381 handover kandidat 1 (C/border-pariteta) je navajal 52 vrstic — polna triaža `r383-triaza.py` [element + border klasifikacija z retrograde tag-walkom] je dokazala **134 tarč z VIDLJIVIM borderjem** (19 border-class + **115 × <Button variant="outline">** — border IZ BAZE ui/button.tsx) + 78 N/A + A/ostanki 35 (prekrivanje 25). Triaža PRED scopingom = OBVEZNA.
- MANDATORY STIL **val 61 — A/OFFSET + C/BORDER-PARITETA ZAKLJUČEK** (dvostopenjsko): **STEP 1** 34 × INS ' focus-visible:ring-offset-2' TIK ZA navy/40 (val 52 pairing kanon; FROZEN izjema #2 kanon R377: roksal-catalog L95 <Input> izključena) + **STEP 2** 134 × INS ' focus-visible:border-roksal-navy/40' TIK ZA O2 (val 57 kanon R375) — skupaj **168 × INS na ~30 datotekah, in-place 0 novih vrstic**; `r383-val61-apply.py` fail-closed [kontrakt EMBEDDED vrstičnih list (bajtno ujemanje proti ponovni izpeljavi — KOLIZIJA premik = glasen abort), per-vrstica točno 1 sidro, POST closure + in-place + needle-survival].
- ⭐ **LEKCIJA R383 (2) — VAL 57 KANON POPRAVEK: border-pariteta = PAR (light navy + dark ink)**: FULL vitest tek 1 je ujel **39 failov** — **R166 DARK obrobni stražar** (kanon R163–R166: vsak border-roksal-navy/N rabi dark: varianto) je ujel, da STEP 2 vstavlja SAMO light polovico → 13 × R166 kršitev + 26 pins/censusov. **`r383-val61-dark-fix.py`**: 134 × INS ' dark:focus-visible:border-roksal-ink/40' za light (val 57 lastne vrstice NOSIJO par že od R375 — moja implementacija je zamudila polovico kanona). + **PAR-SOROJENEC kanon val 20/21/22**: material L2111 CSV sorojenec (brez borderja — ni S2 tarča) je ostal brez FB → PAR bajtna enakost sorojencev prelomljena → L2111 dopolnjena z FB+dark (135. INS — 'ISTI jezik čez kontekste' je STAREJŠI, močnejši kanon od družinske triaže).
- ⭐ **LEKCIJA R383 (3) — pre-skan MORA teči PRED apply (in po VSEH tarčah)**: delta simulacija je bila IZPUŠČENA pred apply (in r381-window-scan TARGETS je pokrival le 11 val-60 datotek, ne ~30 val-61) — FULL net je ujel posledice; r383-window-scan TARGETS razširjen na **VSEH 61 roksal .tsx** (11. generalizacija). (Iskren popravek README: delta='0 preozkih' trditev je bila zapisana PRED tekom — nedovoljeno; LEKCIJA R381 (4) ponovitev v OBRATNI smeri: nikoli ne zapisuj rezultatov, ki jih še ni.)
- **REGISTER EVOLUCIJA** (kanon r371 N3/R377, **4.+5.+6. uporaba** prek r383-evolucija.py + r383-evolucija2.py fail-closed): val 61 je prelomil **r363 needle** ('…ring-offset-2 active:scale…') + **r364 needle** ('…ring-offset-2\"') → EVOLVED R383 val 61 + NASLEDNICA (števca 4/4 NESPREMENJENA); **dark-fix je prelomil NASLEDNICO r363 + lastna r383 #2/#3** → evolucija2: r363 NASLEDNICA-2 (z dark) + r383 #2/#3 popravljena v živo (register nepushan, GLASNO) + r364 NASLEDNICA dark korekcija; **PIN SHIFT žigi 'PIN SHIFT R383 val 61 / EVOLVED'** v: r372 (C) [szc guard flip + navyO2 4→7], r371 (B) [N4 ×1→×2] + (D) [punch pin evolved + SZC guard flip], r373 (C) [dashboard navy+O2 4→7] + (D) [kat[109] O2 flip], r375 (A)/(B)/(D) [22→27, 25→20, globalno 24→159], r381 (D) [inventory evolved ×2 z dark], r383 (F) [NASLEDNICA-2 + measurements pin z dark], r361 (B)/(D), r366 (C), r242, r267, r317, r174, r241 — **26 pins × 18 testnih datotek + 1 embedded legacy needle**.
- ⭐ **LEKCIJA R383 (4) — needle konvencija: BREZ 'className="' prefixa in BREZ končnega navedka**: prevajalnik ne ohranja JSX navedkov v čankih — r383 #2/#3 z 'className="' prefixom so MISS v buildu kljub ŽIVO v src; popravljeni na gol token rep (kanon r379+ needles brez prefixa). **LEKCIJA R383 (5) — embedded legacy needles (r317-build-needles.sh) so ŽIV del verige**: val 61 je prelomil r317 'site-survey harmoniziran ring' žeton → EVOLVED komentar + razširjen žeton V FROZEN skripti (R166/R317 stražarji so ŽIVO preverjanje, ne zgodovina).
- **FEATURE era-clone COMPANION integracija** (handover kandidat 3): era-clone.py ob generaciji harvesta **AVTOMATSKO generira companion r{dst}-era-ruta-map.py** [klon r{src} vzorca z žigi: HARVEST pot + REG window + opisi; tolerantno preskočen za poslovne runde; fail-closed preverba PRED zapisom obeh datotek]; demonstracija: r382-era-harvest.sh re-generiran **BAJTNATO IDENTIČEN** (determinizem) + r382-era-ruta-map.py companion nastal samodejno; končni tek: **159 needlejev, 32 z rutovo asociacijo** (/api/price-book 8, /api/installation-records 4, /api/inventory 2 …).
- **e2e-lib dedup 18. val ISKRENO IZPUŠČEN** [kanon R368].
- REGISTER `scripts/qa-needles/r383.tsv` [4 need_static: calculator L4396 (S1 vzorec), team L497 + sessions L363 + material-intelligence L456 (S2 vzorci — programatsko verificirana unikatnost); 0 v HEAD 7a92097; must_miss TODO-R383; NF=3] prek `r383-register-write.py` fail-closed.
- README: 5552/360 → **5558/361** [= njihova baza 5552/360 + mojih +6/+1] + R383 bullet (njihov R382 bullet ohranjen) prek `r383-readme-update.py` fail-closed.
- ⭐ **LEKCIJA R383 (6) — api-key-lifecycle flaky v FULL tekih**: 6 failov v FULL runih, 21/21 zeleno samostojno — vzor = živalski postgres procesi od prejšnjih (timeout) runov; pkill + čist teek. NI koda-bug; opažanje dokumentirano za globalSetup diagnozo.
- ⭐ **KOLIZIJA #23 [23. potrditev, kanon KOLIZIJE #4/R323/#13–#22]**: push REJECTED — origin/main premaknjen 30f856e→**7a92097** MED mojim delom: njihova poslovna **R382** [c1bac7b — issue #13 korak R169 §13 CRM LIJAK: Lead + Opportunity + ločeni naslovi stranke + r382.tsv 5 server needlejev + 7a92097 lastni worklog vnos] → moja runda preimenovana **R382→R383** [val 61 OSTANE val 61 — kanon R375]. POSTOPEK: backup branch `r382-ai-delta` → `reset --hard origin/main` → delta re-aplicirana prek checkouta iz backup brancha [4+25 render datotek + r363/r364 EVOLVED + 18 testnih PIN SHIFT — njihov commit NI dotaknil NIČ od mojih površin = čista re-aplikacija] + preimenovanje mojih artefaktov r382-*→r383-* [razen r382-era-harvest.sh (35th) + r382-era-ruta-map.py (COMPANION) — imeni ohranjeni, kanon r378/r379] + žigi R382 val 61→R383 val 61 + **njihov r382.tsv obnovljen iz origin/main** → **ŠESTINTRIDESIJNA era preverba** (36.) `r383-era-harvest.sh` [36 registrov r347–r382, ≥147 = 142 + 5; generiran prek era-clone.py --src-round 382 --dst-round 383 --dst-label "R382 issue #13 (R169)" --dst-chain-seg "IN r382.tsv ×5 na" + 11 spec-ov [8 prejšnjih + AJ|/api/leads|401 + AJ|/api/opportunities|401 + AJ|/api/customer-addresses|401]] + COMPANION r383-era-ruta-map.py avtomatsko.

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND, na KONČNI viri PO re-aplikaciji KOLIZIJE #23): tsc 0 · eslint 0 (FULL) · vitest **5558/5558 (361) FULL GREEN** [= njihova baza 5552/360 + mojih +6/+1] · build svež rm -rf .next EXIT=0 · qa-round.sh 383 needles EXIT=0 [r383.tsv 4 ŽIVO + TODO-R383 odsoten + r363/r364 NASLEDNICA ŽIVO + njihov r382.tsv ŽIVO + r317 EVOLVED žeton ŽIVO; UNION r340–r383 + veriga r339→…→R227] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r382-era-harvest EXIT=0 [35th ×2] + r383-era-harvest EXIT=0 [36th — njihovi 5 needlejev ŽIVO prek server resolucije + CRM rute 401] · r383-window-scan EXIT=0 [159/159] · r383-era-ruta-map EXIT=0 · r359-prod-qa-retry 381 ZELEN ob poskusu 2 · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na HEAD].
- NOVO: scripts/qa-needles/r383.tsv + skripte [r383-era-harvest.sh (36th) + r383-era-ruta-map.py (COMPANION avtomatsko), r383-qa-spot.sh, r383-triaza.py, r383-val61-apply.py, r383-val61-dark-fix.py, r383-window-scan.py, r383-evolucija.py, r383-evolucija2.py, r383-register-write.py, r383-readme-update.py, r383-worklog-append.py, r383-commit-msg.txt] + r383-stil-val61.test.ts [×6] + UREJENO: era-clone.py [COMPANION integracija], ~30 render datotek [val 61 INS], r363.tsv + r364.tsv [EVOLVED+NASLEDNICA], r317-build-needles.sh [EVOLVED žeton], 18 testnih datotek [PIN SHIFT], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 61 = render plast a11y className-only; njihova CRM produkcija = njihova poslovna odločitev]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~2 tedna) — obvestiti lastnika (81. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R384 prva naloga = qa-round.sh 383 prod-qa re-run [prek r359-prod-qa-retry.sh 383] + sedemintrideseta era preverba r347–r383 [37 registrov, ≥151 = 147 + 4; prek era-clone.py --src-round 383 --expected-total 151 --dst-label "R383 val 61" + VSEH spec-ov + nov AK|/api/sync|401 [LEKCIJA R381 (5)]]; pričakuj 151/151 ŽIVO [r383 4 needleji razrešeni ob TEM pushu] + val 61 POST-deploy verifikacija [4 needleji r383.tsv; mounted + className LOČENO; NIČ klikov na odjavo/preklic].
- R384 kandidati: 1. red/40 border-pariteta [navy FB zaključen — rdeča simetrija; sveža triaža obvezna — LEKCIJA R382 (1)]; 2. amber/50 border-pariteta [isti vzorec]; 3. PAR-sorojenci varstvo v triaži [LEKCIJA R382 (2): sorojenec brez borderja dobí FB, če brat nosi]; 4. e2e-lib dedup 19. val [po kanonu]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

out = src.rstrip("\n") + "\n" + VNOS
if out.count("Task ID: R383") != 1:
    sys.exit("FAILOVEDANO: R383 vnos ×" + str(out.count("Task ID: R383")) + " ≠ ×1")
W.write_text(out, encoding="utf-8")
print(f"OK: R382 vnos appendan ({len(VNOS)} bajtov)")
