#!/usr/bin/env python3
# r385-worklog-append.py — R385 fail-closed append v worklog.md (EN vnos:
# R385; guard = rep R384 vnosa z GLASNO prefix preverbo '- R385 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- R385 kandidati: 1."):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R384: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R385
Agent: Super Z (AI runda, Job 413422, tick 202610030915 — peti tick, vsi netekeni ticki združeni v ENO rundo po kanonu)
Task: R385 — prva naloga (prod-qa re-run 384 + OSEMINTRIDESIJNA era preverba r347–r384 + val 62 POST-deploy verifikacija) + MANDATORY STIL val 63 (AMBER/50 border-pariteta, 15 × INS s dark PAR v enem koraku) + FEATURE r166 dark stražar GENERALIZACIJA (vsi barvni FB pari) + REGISTER EVOLUCIJA (7. uporaba: r368 N1) + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD c235e90 (R384) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R384 vnos = handover (prebran). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 384` — **ZELEN ob poskusu 2** (19. runda; poskus 1 = znana transient kategorija R358/R359, retry wrapper po kanonu).
- PRVA NALOGA (B): **OSEMINTRIDESIJNA era preverba** (38.) `r385-era-harvest.sh` [38 registrov r347–r384, ≥155 = 151 + 4, vsota IZ DISKA; generiran prek era-clone.py --src-round 384 --dst-round 385 --expected-total 155 + **VSEH 12 server-probe spec-ov IZRECNO — LEKCIJA R384 (1)**; COMPANION `r385-era-ruta-map.py` nastal samodejno — R383 feature deluje]; **EXIT=0 ×2** (determinizem) — **155/155 ŽIVO** (direktno + hash + 18 server resolucij); must_miss ×38 čisto; era kontrole R340/R341/R343/R345 ŽIVE.
- PRVA NALOGA (C): **val 62 POST-deploy spot** `r385-qa-spot.sh` (spot-r167/25; ZERO-MUTACIJA — NIČ klikov na revoke/odjavo/preklic; dialog zaprt z Escape): (B) top-bar user meni (kanon r186 pointerdown+click) → 'Aktivne seje' → **'Prekliči sejo na napravi' 41/41 MONTIRANO na produ** — vseh 15 tokenov LOČENO per className split (h-7/shrink-0/gap-1/border-roksal-red\\/30/px-2/text-2xs/text-roksal-red/hover:bg-roksal-red\\/10/press-scale/ring-2/red\\/40/O2/FB red 41/41 + dark FB red 41/41); Escape → dialogi 0; (A) dashboard 'Poskusi znova' (L1914/L2059 dvojčka) **iskreno 0** — invError/narocilaError zahtevata padel fetch na produ; ZERO-MUTACIJA: napak ni iskreno sprožiti; needle ŽIVO v buildu = era need_static dokaz (programatsko dokumentirano V zamrznjeni skripti); (C) measurements 'Odstrani osnutek' (L5679) **iskreno 0** — osnutki per-projekt localStorage (roksal_measurement_drafts_<projectId>); spot račun 0 projektov (kanon r277) → brez ključa ni sekcije; semena brez projectId NE možna (draftsKey fail-closed vrže); (D) vodja 'Zamujena dobava' (L2122) **iskreno 0** — DB-gnana resnica stats.zamujeneDobave > 0; 0 projektov; OBE veji iskreno poročani; sonde navy 4/4/0 + red 0 + kolektor **0**.
- MANDATORY STIL **val 63 — AMBER/50 BORDER-PARITETA** (amber simetrija po rdečem zaključku val 62; kanon R385 handover kandidat 1): disk resnica `r385-triaza.py` [**15 tarč z VIDLJIVIM borderjem** = 14 border-class (vodja-dashboard ×13 border-roksal-navy/25 + hover:border-roksal-amber — Button outline CSV izvoz; photo L740 nativni 'border' template-literal) + 1 outline-variant (inclinometer L539); vseh 15 z O2; **3 N/A iskreno izključeni** (inclinometer L433, inventory L1229, photo L1162 — brez borderja in brez sorojenca z FB); **8 IZVEN OBSEGA** — amber/40 pod-družina (dashboard L1749/L1946, measurements L3329/L3478, vodja L2093) + amber/60 (notification L748, photo L2113/L2414) dokumentirana za prihodnja vala, kanon ena-intenziveta-na-val kot red/40 (val 59 offset + val 62 border); 0 anomalij] → **15 × INS ' focus-visible:border-roksal-amber/50 dark:focus-visible:border-roksal-amber/30' TIK ZA O2 na 3 datotekah, in-place 0 novih vrstic**; LEKCIJA R383 (2) v apply: PAR (light + dark) v ENEM koraku; **dark /30 po ISTEM pravilu kot rdeča val 62: sledi družinskemu obstoječemu light+dark border paru z ISTO light intenziveto — audit-trail-dialog L53 'border-roksal-amber/50 dark:border-roksal-amber/30'** (amber ostane amber v temni temi — barva je pomen [nizka zaloga/opozorilo], NI ink — ink je navy nevtralni sorojenec); `r385-val63-apply.py` fail-closed [kontrakt EMBEDDED bajtno ×15, per-vrstica točno 1 sidro, POST closure (negativni lookbehind `(?<!dark:)` — LEKCIJA R384 (2)) + in-place + needle-survival (.tsx+.ts — LEKCIJA R384 (4)); mid-line idempotenca — LEKCIJA R384 (3); ponovni tek = **0 INS dokazan**].
- PRE-SKAN (LEKCIJA R383 (3) — PRED apply, čez VSE tarče): `r383-window-scan.py delta 79 'focus-visible:ring-roksal-amber/50 focus-visible:ring-offset-2'` [točna pozicija — 79 = dolžina vstavka]: **304 okenskih regexov 0 preozkih + 164 needle pinov 0 mrtvih + 133 slice-oknen + 0 vrstičnih odstopanj** → **0 PIN SHIFT napovedano**.
- ⭐ **LEKCIJA R385 (1) — pre-skan NE pokriva POJAVITVENIH (grep -o) era-diskriminator pinov v STAREJŠIH stil testih**: FULL vitest tek 1 ujel **r368-stil-val51.test.ts (B) N1** ['ring-amber/50 offset-2 outline-none' ×1 → 0 — val 63 FB vstavljen MED offset-2 in outline-none na photo L740; r368 = AMBER runda!]; PIN SHIFT V ISTI RUNDI z žigom [PIN SHIFT R385 val 63]: stari adjacency = 0 + NOVA EVOLVED adjacency ['ring-amber/50 offset-2 FB-amber dark-FB outline-none' ×1] — 16/16 ZELENO. Kanon za prihodnost: amber-družinska dela MORAJO pre-skaniati tudi stare amber stil teste (val 51) — navy dela niso ujeta, ker r368 (B) pina SAMO amber diskriminatorje.
- REGISTER EVOLUCIJA (kanon r371 N3/R377, **7. uporaba** prek `r385-evolucija.py` fail-closed): val 63 prelomil **r368.tsv N1 needle** (span čez O2 do outline-none) → EVOLVED R385 val 63 (komentirana vrstica, zgodovina dobesedno) + **NASLEDNICA podatkovna vrstica** [NASLEDNICA ŽIVO v buildu takoj — needles faza OK; na produ OB TEM pushu]; need_static števec r368 = 4 NESPREMENJEN (era vsote veljavne); needles faza ponovno **EXIT=0**.
- **FEATURE R166 DARK STRAŽAR GENERALIZACIJA** (R385 handover kandidat 2): `r385-fb-dark-generalizacija.test.ts` **×5 ZELENO** — (A) it.each per družina: vsaka izvedljiva vrstica z light FB žetonom nosi dark par NA ISTI vrstici [navy→ink/40, red→red/50, amber→amber/30]; (B) globalna pariteta števcev **159/16/15** light==dark (delna aplikacija = glasna regresija); (C) obrnjena regresija: 0 sirot (dark FB brez light polovice); disk resnica ob nastanku: 0 kršitev, 0 sirot. ISTI jezik čez kontekste = starejši močnejši kanon (LEKCIJA R382 (2)), zdaj TRAJNO varovan za VSE tri barvne družine.
- `r385-stil-val63.test.ts` **×6 ZELENO** [(A) PARITETA vzorci FB+dark TIK ZA O2, (B) dark PAR 15/15, (C) N/A 3 bajtno, (D) ostanek 0 + in-place 2199/2684/599, (E) izven-obsega 8 nedotaknjenih + regresija red 16/16 + navy 159/159, (F) bordered-brez-FB 0 + NASLEDNICA navy ŽIVO].
- e2e-lib dedup 19. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r385.tsv` [4 need_static: vodja L1213 ×4 (sorojenci kanon), vodja L1475 ×9 (h-6 izvozi vrstica), photo L740 ×1 (nativni + template literal), inclinometer L539 ×1 (outline-variant); 0 v HEAD c235e90; TODO-R385 must_miss] prek `r385-register-write.py` fail-closed [TSV točno 3 polja, bajtno ŽIVO v src (.tsx+.ts), 0-v-HEAD, need_static=4 usklajeno z era verigo].
- README: 5567/363 → **5578/365** [= R384 baza 5567/363 + mojih +11/+2: stil ×6 + generalizacija ×5] + R385 bullet (njihov R384 bullet ohranjen) prek `r385-readme-update.py` fail-closed.

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL `eslint .`) · vitest **5578/5578 (365) FULL GREEN TEK 2** [tek 1 = 5577/5578 — r368 (B) stale-pin ujet + PIN SHIFT V ISTI RUNDI po kanonu; 0 PIN SHIFT ob PRVEM apply ze pre-skan napovedal 0 za registre, a pojavitveni pin stil testa je bil izven njegovega obsega — LEKCIJA R385 (1)] · build svež rm -rf .next EXIT=0 · qa-round.sh 385 needles EXIT=0 [r385.tsv 4 ŽIVO + NASLEDNICA r368 ŽIVO + TODO-R385 odsoten; Z-STRUCT pokvarjenih 0; UNION r340–r385 + veriga r339→…→R227 VSE ŽIVE] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r385-era-harvest EXIT=0 ×2 [38th — 155/155 ŽIVO] · r383-window-scan delta 79 EXIT=0 [DEL 1–4 čisti] · r359-prod-qa-retry 384 ZELEN ob poskusu 2 · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na HEAD].
- NOVO: scripts/qa-needles/r385.tsv + skripte [r385-era-harvest.sh (38th) + r385-era-ruta-map.py (COMPANION avtomatsko), r385-qa-spot.sh, r385-triaza.py, r385-val63-apply.py, r385-evolucija.py, r385-register-write.py, r385-readme-update.py, r385-worklog-append.py, r385-commit-msg.txt] + r385-stil-val63.test.ts [×6] + r385-fb-dark-generalizacija.test.ts [×5 — FEATURE]; UREJENO: 3 render datotek [val 63 INS ×15: vodja-dashboard, photo-tab, inclinometer-tab], r368.tsv [EVOLVED+NASLEDNICA], r368-stil-val51.test.ts [PIN SHIFT N1], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 63 = render plast a11y className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (81. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R386 prva naloga = qa-round.sh 385 prod-qa re-run [prek r359-prod-qa-retry.sh 385] + devetintrideseta era preverba r347–r385 [39 registrov, ≥159 = 155 + 4; prek era-clone.py --src-round 385 --expected-total 159 + VSEH 12 spec-ov IZRECNO — LEKCIJA R384 (1)]; pričakuj 159/159 ŽIVO [r385 4 needleji razrešeni ob TEM pushu] + val 63 POST-deploy verifikacija [4 needleji r385.tsv; mounted + className LOČENO; NIČ klikov na revoke/odjavo; sessions 'Prekliči' 41/41 vzorec iz spot-r167/25].
- R386 kandidati: 1. amber/40 border-pariteta [pod-družina izven obsega val 63: dashboard L1946, measurements L3478, vodja L2093 — sveža triaža obvezna — LEKCIJA R382 (1); dark par po Družinskem precedensu]; 2. amber/60 border-pariteta [notification L748 — ring par svetlo/temno že obstaja na vrstici; photo L2113/L2414]; 3. e2e-lib dedup 20. val [po kanonu]. ⭐ LEKCIJA R385 (1) upoštevati: amber dela pre-skaniat TUDI r368-stil-val51 (B) pine. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

nov = src.rstrip("\n") + "\n\n" + VNOS
W.write_text(nov, encoding="utf-8")
print("OK: worklog.md — R385 vnos pripet (guard R384 rep potrjen bajtno ×1)")
