#!/usr/bin/env python3
# r386-worklog-append.py — R386 fail-closed append v worklog.md (EN vnos:
# R386; guard = rep R385 vnosa z GLASNO prefix preverbo '- R386 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- R386 kandidati: 1."):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R385: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R386
Agent: Super Z (AI runda, Job 413422, tick 202610031009)
Task: R386 — prva naloga (prod-qa re-run 385 + DEVETINTRIDESIJNA era preverba r347–r385 + val 63 POST-deploy verifikacija) + MANDATORY STIL val 64 (AMBER/40 border-pariteta, 3 × INS s dark PAR v enem koraku — amber simetrija zaključena) + FEATURE O2 pairing stražar GENERALIZACIJA + REGISTER EVOLUCIJA r368 N3 (needle ŽIVO prek L3329 — brez evolucije) + r375 stale-pin EVOLVED + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 666a7cc (R385) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R385 vnos = handover (prebran). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 385` — **ZELEN ob poskusu 1** (20. runda).
- PRVA NALOGA (B): **DEVETINTRIDESIJNA era preverba** (39.) `r386-era-harvest.sh` [39 registrov r347–r385, ≥159 = 155 + 4, vsota IZ DISKA; generiran prek era-clone.py --src-round 385 --dst-round 386 --expected-total 159 + **VSEH 12 server-probe spec-ov IZRECNO — LEKCIJA R384 (1)**; COMPANION `r386-era-ruta-map.py` nastal samodejno]; **EXIT=0 ×2** (determinizem) — **159/159 ŽIVO** (direktno + hash + 18 server resolucij); must_miss ×39 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 63 deploy POTRJEN** (4 needleji r385 razrešeni ob R385 pushu).
- PRVA NALOGA (C): **val 63 POST-deploy spot** `r386-qa-spot.sh` (spot-r167/26; ZERO-MUTACIJA — NIČ klikov na revoke/izvoz/odjavo): (A) vodja 'Izvozi dnevni pregled vodje kot CSV' (L1213) **1/1 MONTIRANO na produ** — vseh 16 tokenov LOČENO per className split (incl. FB amber/50 + dark FB amber/30); (B) vodja 'Izvozi pregled AI rabe kot CSV' CSV pilula (L1475, data-testid ai-raba-csv-pill) **1/1 MONTIRANO** — 17 tokenov incl. dark:border-roksal-ink/25 rep; (C) photo kategorija filtri (L740, aria-pressed ×3) **3/3 MONTIRANO** — 13 tokenov (FB+dark MED O2 in outline-none — template literal); (D) inclinometer 'Poskusi znova naložiti zgodovino nagibov' (L539) **iskreno 0** — historyError ≠ null zahteva padel fetch; ZERO-MUTACIJA: napak ni iskreno sprožiti; needle ŽIVO v buildu = era need_static (programatsko dokumentirano V zamrznjeni skripti); sonde navy 0/0/0 + red 0 (main na teh površinah brez navy/red FB) + kolektor **0**. **SKUPAJ val 63: 5/5 montiranih površin — vzorec ×3 različnih vrst elementov (Button outline nativni, CSV pilula, aria-pressed filtri).**
- MANDATORY STIL **val 64 — AMBER/40 BORDER-PARITETA** (zaključek amber simetrije skupaj z val 63; kanon R386 handover kandidat 1): disk resnica `r386-triaza.py` [**3 tarče** border-class: dashboard L1946 (border-roksal-amber/40 kartica), measurements L3478 (border-roksal-amber/30), vodja L2093 (border-roksal-amber/40 kartica — rdeči dvojček L2122 ima FB že od val 62); vseh 3 z O2; 2 N/A iskreno izključena (dashboard L1749, measurements L3329 — brez borderja + brez sorojenca z FB); 21 IZVEN obsega (amber/50 zaključen val 63 + amber/60 prihodnji val); 0 anomalij; **⭐ dark-polovica lookbehind fix v triaži**: notification L748 'dark:focus-visible:ring-roksal-amber/40' NI član /40 družine — light ring je /60; prvotni substring match jo je lažno ujel kot tarčo → AMBER40_LIGHT regex `(?<!dark:)` — LEKCIJA R384 (2) generalizacija na TRIAŽNO orodje] → **3 × INS ' focus-visible:border-roksal-amber/40 dark:focus-visible:border-roksal-amber/40' TIK ZA O2 na 3 datotekah, in-place 0 novih vrstic**; LEKCIJA R383 (2) v apply: PAR v ENEM koraku; **dark /40 po družinskem precedensu z ISTO intenziveto — crm-tab L811 'dark:border-roksal-amber/40' Card (edini obstoječi dark amber/40 border v kodebazi)**; amber ostane amber v temni temi (NI ink); `r386-val64-apply.py` fail-closed [kontrakt EMBEDDED ×3, per-vrstica 1 sidro, POST closure lookbehind + in-place + needle-survival — **0 mrtvih: r368 N3 needle ŽIVO prek L3329** (grep binarno, register EVOLUCIJA NI potrebna); mid-line idempotenca — ponovni tek **0 INS dokazan**].
- PRE-SKAN (LEKCIJA R383 (3) — PRED apply): `r383-window-scan.py delta 79 'focus-visible:ring-roksal-amber/40 focus-visible:ring-offset-2'` [79 = dolžina vstavka]: **304 okenskih regexov 0 preozkih + 164 needle pinov 0 mrtvih + 133 slice-oknen + 0 vrstičnih odstopanj** → 0 PIN SHIFT za registre napovedano.
- ⭐ **LEKCIJA R386 (1) — lookbehind discipline čez CELE teste**: r386-stil-val64 (D)/(F) substring check `includes('ring-amber/40')` je lažno ujel L748 dark polovico (isti vzorec kot triaža) → popravljeno na AMB40_LIGHT regex `(?<!dark:)`; generalizacija LEKCIJE R384 (2): 'dark: token VSEBUJE light podniz' velja za VSAKODAVNE preverbe (triaža, stil teste, ne samo closure števcev).
- ⭐ **LEKCIJA R385 (1) UPOŠTEVANA (kanon deluje)**: r368-stil-val51 (B) N3 pojavitveni pin ['ring-amber/40 offset-2 outline-none' ×2 = L3329 + L3478] je bil PREDVIDEN in PIN SHIFTAN V ISTI RUNDI [stari adjacency 2→1 — L3329 (N/A) ohrani; EVOLVED adjacency ×1 — L3478 z FB+dark]; žig [PIN SHIFT R386 val 64]. FULL vitest je ujel ŠE EN stari pin, ki ga NITI R385 (1) ni predvidel:
- ⭐ **LEKCIJA R386 (2) — val 57 era 'dokumentirano BREZ sprememb' pine so tudi živi**: r375-stil-val57 (B) je pinil 'amber brez border-paritete' (prva bordered amber/40 vrstica v measurements BREZ FB — disk resnica ob R375) → val 64 je pariral L3478 → assertion obrnjen; EVOLVED z žigom [EVOLVED R386 val 64]: amber bordered zdaj NOSI FB+dark (pozitivna preverba); ime (B) it posodobljeno ('amber EVOLVED R386 val 64'). **Kanon za prihodnost: vsak val MORA pre-skaniati stare stil teste VSEH prejšnjih vals iste družine — ne samo nazadnje runde (r368 val 51 + r375 val 57 oba ujeta).**
- **FEATURE O2 PAIRING STRAŽAR GENERALIZACIJA**: `r386-ring-o2-generalizacija.test.ts` **×5 ZELENO** — (A) it.each per družina: vsaka izvedljiva vrstica z 'focus-visible:ring-2 ring-roksal-{navy|red|amber}/N' nosi O2 — razcep = 0; (B) FROZEN izjema #2 (kanon R377): roksal-catalog L95 <Input> dokumentirana + **TOČNO 1 izjema čez vse roksal** (tihageneralizacija izjem = glasna regresija); (C) globalna števca zamrznjena: navy 237 / red 25 / amber 26 focus-ring vrstic (disk resnica ob nastanku; val 63/64 FB vstavljanja NE dodajajo ring vrstic). Komplement r385-fb-dark-generalizacija — skupaj pokrivata OBE polovici (O2 + dark FB) vseh treh barvnih družin.
- r386-stil-val64.test.ts **×6 ZELENO** [(A) PARITETA 3 tarče FB+dark TIK ZA O2, (B) DARK PAR 3/3 + val 63 15/15 regresija, (C) N/A 2 bajtno, (D) ostanek 0 + in-place 3188/6232/2199, (E) amber/60 3 nedotaknjene + red 16/16 + navy 159/159, (F) bordered-brez-FB 0 + r368 N3 ŽIVO + NASLEDNICA navy ŽIVO].
- KOMPLEMENTARNE EVOLUCIJE (cross-val, z žigi): `r385-fb-dark-generalizacija` **EVOLVED R386 val 64** [amber PAR seznam razširjen 3→4 vnosov (navy + red + amber/50 + amber/40); globalna pariteta 159/16/15+3; sirota preverba na DRUŽINSKI ravni (katerakoli intenziveta, lookbehind) — it.each 3→4 = +1 test]; `r385-stil-val63` (E) **EVOLVED R386 val 64** [3 amber/40 bordered tarče prestavljene iz izven-obsega v EVOLVED z pozitivno FB preverbo; izven obsega ostane amber/60 + brez-border amber/40 vrstici]; `r368-stil-val51` (B) N3 **PIN SHIFT R386 val 64**; `r375-stil-val57` (B) **EVOLVED R386 val 64**.
- e2e-lib dedup 20. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r386.tsv` [4 need_static: dashboard L1946, measurements L3478, vodja L2093, družinski PAR žeton 'focus-visible:border-roksal-amber/40 dark:focus-visible:border-roksal-amber/40' ×3; 0 v HEAD 666a7cc; TODO-R386 must_miss] prek `r386-register-write.py` fail-closed [TSV 3 polja, bajtno ŽIVO v src, 0-v-HEAD, need_static=4 usklajeno z era verigo].
- README: števec 5578/365 → **5590/367** [= R385 baza + mojih +12/+2: r386-stil ×6 + r386-ring-o2 ×5 + it.each razširitev r385-fb-dark +1] + R386 bullet prek `r386-readme-update.py` fail-closed (popravek števca 5589→5590 po dejanski FULL resnici — it.each razširitev je bila podcenjena v prvem zapisu).

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL `eslint .`) · vitest **5590/5590 (367) FULL GREEN TEK 2** [tek 1 = 5589/5590 — r375-stil-val57 (B) stale-pin ujet + EVOLVED V ISTI RUNDI; LEKCIJA R386 (2)] · build svež rm -rf .next EXIT=0 · qa-round.sh 386 needles EXIT=0 [r386.tsv 4 ŽIVO + TODO-R386 odsoten; Z-STRUCT pokvarjenih 0; UNION r340–r386 + veriga r339→…→R227 VSE ŽIVE] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r386-era-harvest EXIT=0 ×2 [39th — 159/159 ŽIVO] · r383-window-scan delta 79 EXIT=0 [DEL 1–4 čisti] · r359-prod-qa-retry 385 ZELEN poskus 1 · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na HEAD].
- NOVO: scripts/qa-needles/r386.tsv + skripte [r386-era-harvest.sh (39th) + r386-era-ruta-map.py (COMPANION avtomatsko), r386-qa-spot.sh, r386-triaza.py, r386-val64-apply.py, r386-register-write.py, r386-readme-update.py, r386-worklog-append.py, r386-commit-msg.txt] + r386-stil-val64.test.ts [×6] + r386-ring-o2-generalizacija.test.ts [×5 — FEATURE]; UREJENO: 3 render datotek [val 64 INS ×3: dashboard-tab, measurements-tab, vodja-dashboard], r368-stil-val51.test.ts [PIN SHIFT N3], r375-stil-val57.test.ts [EVOLVED (B)], r385-fb-dark-generalizacija.test.ts [EVOLVED amber/40 + it.each 3→4], r385-stil-val63.test.ts [EVOLVED (E)], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 64 = render plast a11y className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (81. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R387 prva naloga = qa-round.sh 386 prod-qa re-run [prek r359-prod-qa-retry.sh 386] + štirideseta era preverba r347–r386 [40 registrov, ≥163 = 159 + 4; prek era-clone.py --src-round 386 --expected-total 163 + VSEH 12 spec-ov IZRECNO — LEKCIJA R384 (1)]; pričakuj 163/163 ŽIVO [r386 4 needleji razrešeni ob TEM pushu] + val 64 POST-deploy verifikacija [4 needleji r386.tsv; mounted + className LOČENO; NIČ klikov na revoke/odjavo; vodja + photo vzorci iz spot-r167/26].
- R387 kandidati: 1. amber/60 border-pariteta [ZADNJA amber pod-družina: notification L748 (border-border/60 token + hover amber; ring par svetlo /60 + dark /40 že na vrstici — dark FB kandidat /40 po lastnem ring paru), photo L2113 (border + ring /60 brez dark) — sveža triaža obvezna — LEKCIJA R382 (1)]; 2. plain amber ring ostanki ×4 + mrtev-CSS navy ×20 statistika [sveža triaža, morda zamrznjeno]; 3. e2e-lib dedup 21. val [po kanonu]. ⭐ LEKCIJI R386 (1) + (2) upoštevati: lookbehind čez VSE preverbe + pre-skan stil testov VSEH prejšnjih vals iste družine (r368 + r375 + r385 + r386). ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

nov = src.rstrip("\n") + "\n\n" + VNOS
W.write_text(nov, encoding="utf-8")
print("OK: worklog.md — R386 vnos pripet (guard R385 rep potrjen bajtno ×1)")
