#!/usr/bin/env python3
# r387-worklog-append.py — R387 fail-closed append v worklog.md (EN vnos:
# R387; guard = rep R386 vnosa z GLASNO prefix preverbo '- R387 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- R387 kandidati: 1."):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R386: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R387
Agent: Super Z (AI runda, Job 413422, tick 202610031047 — pet tickov 202610021821/030215/030400/030815/030915 je bilo že pokritih z R386 vnosi; ta tick = R387)
Task: R387 — prva naloga (prod-qa re-run 386 + ŠTIRIDESIJNA era preverba r347–r386 + val 64 POST-deploy verifikacija) + MANDATORY STIL val 65 (AMBER/60 border-pariteta, 2 × INS + 11 × PIN SHIFT zamrznjenih needle skript — amber simetrija TRETJIČ zaključena) + FEATURE FB-BORDER pariteta stražar GENERALIZACIJA (tretji varuh) + EVOLUCIJE r368 (C)/r385 (B)(E)/r386 (B)(E) + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 3969bca (R386) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R386 vnos = handover (prebran; njegov 'R387 prva naloga' + 'R387 kandidati' izvedeni dobesedno). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 386` — **ZELEN ob poskusu 2** (21. runda; poskus 1 = znana transient kategorija R358/R359 — Z2 chunk harvest curl brez retry).
- PRVA NALOGA (B): **ŠTIRIDESIJNA era preverba** (40.) `r387-era-harvest.sh` [40 registrov r347–r386, ≥163 = 159 + 4, vsota IZ DISKA; generiran prek era-clone.py --src-round 386 --dst-round 387 --expected-total 163 + **VSEH 12 server-probe spec-ov IZRECNO — LEKCIJA R384 (1)**; COMPANION `r387-era-ruta-map.py` nastal samodejno]; **EXIT=0 ×2** (determinizem) — **163/163 ŽIVO** (direktno + hash + 18 server resolucij); must_miss ×40 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 64 deploy POTRJEN** (4 needleji r386 razrešeni ob R386 pushu).
- PRVA NALOGA (C): **val 64 POST-deploy spot** `r387-qa-spot.sh` (spot-r167/27; ZERO-MUTACIJA — NIČ klikov na revoke/izvoz/odjavo/filter): (A) dashboard 'Brez dobavitelja' kartica (L1946, aria-label prefix 'Brez dobavitelja (') **1/1 MONTIRANO na produ** — vseh 20 tokenov LOČENO per className split (incl. FB amber/40 + dark FB amber/40); (B) measurements 'Poglej pripadajočo foto mero' (L3478) **iskreno 0** — POGOJNA resnica (isPhoto && photoId; brez foto mer v trenutnem seznamu; ZERO-MUTACIJA: ničesar ne fabricirati; needle ŽIVO v buildu = era need_static); (C) vodja kartica (L2093) **1/1 MONTIRANO** — 20 tokenov; (D) globalni PAR žeton živ na vodja površini; sonde navy 4/4/0 + red 0; kolektor **0**. **SKUPAJ val 64: 2/2 pogojno-možnih površin MONTIRANO + 1 iskreno 0 z razlogom.**
- MANDATORY STIL **val 65 — AMBER/60 BORDER-PARITETA** (ZADNJA amber pod-družina; amber simetrija TRETJIČ zaključena: /50 val 63 + /40 val 64 + /60 val 65; kanon R386 handover kandidat 1): disk resnica `r387-triaza.py` [**2 tarči** border-class: notification L748 (border-border/60 + hover:border-roksal-amber/40; ring par light /60 + dark /40 ŽE na vrstici), photo L2113 (nativni 'border' s pogojnima veja border-roksal-amber/border-white/20 — trajno temna površina bg-roksal-navy, brez dark: variant); obe z O2; 1 N/A iskreno izključen (photo L2414 — brez borderja in brez sorojenca z FB); 0 anomalij] → **2 × INS ' focus-visible:border-roksal-amber/60 dark:focus-visible:border-roksal-amber/40' TIK ZA O2, in-place 0 novih vrstic**; LEKCIJA R383 (2) v apply: PAR v ENEM koraku; **dark /40 po DVEH skladiščih resnice: notification L748 lasten dark ring JE /40 (FB sledi SVOJI ring pari) + crm-tab L811 'dark:border-roksal-amber/40' Card (precedens val 64); /30 je par /50+/30 audit-trail L53 — namenjen /50 družini; /60 NIMA lastnega dark border para v kodebazi → /40 UNIFORMNO za celo družino**; amber ostane amber v temni temi (NI ink); `r387-val65-apply.py` fail-closed [kontrakt EMBEDDED ×2 + **PIN SHIFT ×11 zamrznjenih needle skript v ENEM atomskem koraku** (faza 2, žig [PIN SHIFT R387 val 65]); POST closure lookbehind — LEKCIJA R386 (1); POST in-place; POST needle-survival — 0 mrtvih; ponovni tek = **0 INS / 0 SHIFT dokazan**].
- ⭐ **LEKCIJA R368 KANON (PIN SHIFT V ISTI RUNDI) UPORABLJENA**: notification L748 sosednost 'ring-offset-2 dark:focus-visible:ring-roksal-amber/40' je PINANA v **11 zamrznjenih needle skriptah (r245–r255-build-needles.sh)** — val 65 vstavi FB MED offset-2 in dark ring → brez shifta bi veriga r338→…→R227 (needles faza) lažno failala na produ; PIN SHIFT VSEH 11 V ISTI RUNDI [nov needle vključuje FB+dark par + žig 'PIN SHIFT R368 val 51: offset-2; PIN SHIFT R387 val 65: FB amber/60+dark/40'] + r368-stil-val51 (C) novObv EVOLVED [nov pin ×11 ŽIVO + star = 0]. Pre-skan DEL 2 (164 needle pinov 0 mrtvih) je pokril REGISTRE, ne zamrznjenih skript — preživetje skriptnih pinov je ujel NAČRT (grep r245 pred apply), ne pre-skan: **kanon za prihodnost: pre-skan MORA grepati tudi scripts/*.sh needle spise, ne samo TSV registrów**.
- PRE-SKAN (LEKCIJA R383 (3) — PRED apply): `r383-window-scan.py delta 79 'focus-visible:ring-roksal-amber/60 focus-visible:ring-offset-2'` [79 = dolžina vstavka]: **304 okenskih regexov 0 preozkih + 164 needle pinov 0 mrtvih + 133 slice-oknen + 0 vrstičnih odstopanj** → 0 PIN SHIFT za REGISTRE napovedano (skriptni pini zgoraj).
- ⭐ **LEKCIJA R386 (2) UPOŠTEVANA (pre-skan stil testov VSEH prejšnjih vals iste družine)**: ujeti VSE stale-pini PROAKTIVNO v rundi — FULL vitest tek 1 = **5603/5603 ZELEN brez popravkov** [r385-stil-val63 (E) + r386-stil-val64 (E): L748+L2113 izven-obsega → EVOLVED z pozitivno FB preverbo (L2414 ostaja izven); r386-stil-val64 (B): dark FB amber/40 žeton je DELJEN z amber/60 → 3→5 z SKUPNIM PAR-om light40+light60==dark40; r385-fb-dark-generalizacija: +družina amber/60→dark/40 (it.each 4→5 = +1 test; GLOBALNA PARITETA pricakovano [3,5]/[2,5]; BREZ SIROT svetlobaDružine +ključ 'amber/60' — TypeError pri manjkajočem ključu, ujet lokalno); r368 (A)/(B) ring števci NESPREMENJENI (FB je border žeton — val 51 popis 31/30 vrstic ostaja)]. ⭐ **LEKCIJA R387 (1): tudi LASTEN nov test lahko ima hrošča** — r387-stil-val65 (D) je prvotno štel bordered vrstice BREZ pogoja !includes(FBA60) → lažno 2; popravljeno pred FULL tekom (lokalni tek je ujel).
- **FEATURE FB-BORDER PARITETA STRAŽAR GENERALIZACIJA** (TRETJI varuh; R387 handover kandidat): `r387-fb-border-generalizacija.test.ts` **×6 ZELENO** — (A) it.each per barva (navy/red/amber): vsaka ring-2+O2+border vrstica z light barvnim ringom nosi FB ISTE barve — kršitve 0; (B) števci zamrznjeni: navy 159 / red 16 / amber 20 [/50 ×15 + /40 ×3 + /60 ×2]; (C) obrnjena regresija: 0 sirot (FB border brez ringa iste barve); (D) N/A vrstici (photo L2414, dashboard L1749, measurements L3329) iskreno izven obsega — brez FB in brez borderja (disk resnica). TRIA varuhov sedaj pokrijejo celoten FB jezik: r385 (dark polovica) + r386 (O2 pairing) + r387 (FB-border istobarvnost).
- r387-stil-val65.test.ts **×6 ZELENO** [(A) PARITETA 2 tarči FB+dark TIK ZA O2, (B) DARK PAR 2/2 + regresija 15/15+3+16/16+159/159 + skupni dark:/40 žeton = 5, (C) N/A L2414 bajtno, (D) ostanek 0 + in-place 2684/969, (E) REGRESIJA PIN SHIFT 11/11 nov pin + 0 star, (F) amber/60 ring vrstic = 3 (2 tarči + 1 N/A) + NASLEDNICA navy ŽIVO].
- e2e-lib dedup 21. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r387.tsv` [4 need_static: notification L748 (celoten nov className), photo L2113 (celoten template rep), družinski PAR žeton 'focus-visible:border-roksal-amber/60 dark:focus-visible:border-roksal-amber/40' ×2, seam adjacency 'dark:focus-visible:border-roksal-amber/40 dark:focus-visible:ring-roksal-amber/40' ×1 (dokaz vstavitve MED offset-2 in dark ringom); 0 v HEAD 3969bca; TODO-R387 must_miss] prek `r387-register-write.py` fail-closed [TSV točno 3 polja, bajtno ŽIVO v src (.tsx+.ts), 0-v-HEAD, need_static=4 usklajeno z era verigo].
- README: števec 5590/367 → **5603/369** [= R386 baza 5590/367 + mojih +13/+2: r387-stil-val65 ×6 + r387-fb-border ×6 + it.each razširitev r385-fb-dark +1 — LEKCIJA R386 (it.each ne podcenjevati) UPORABLJENA Vnaprej] + R387 bullet (njegov R386 bullet ohranjen) prek `r387-readme-update.py` fail-closed.

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL `eslint .`) · vitest **5603/5603 (369) FULL GREEN TEK 1 IN TEK 2** [brez stale-pinov — evolucije proaktivno v rundi; LEKCIJA R386 (2) deluje] · build svež rm -rf .next EXIT=0 · qa-round.sh 387 needles EXIT=0 [r387.tsv 4 ŽIVO + TODO-R387 odsoten; Z-STRUCT pokvarjenih 0; UNION r340–r387 + veriga r339→…→R227 VSE ŽIVE — vključno s PIN SHIFTanimi r245–r255] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r387-era-harvest EXIT=0 ×2 [40th — 163/163 ŽIVO] · r383-window-scan delta 79 EXIT=0 [DEL 1–4 čisti] · r359-prod-qa-retry 386 ZELEN ob poskusu 2 · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na src+scripts].
- NOVO: scripts/qa-needles/r387.tsv + skripte [r387-era-harvest.sh (40th) + r387-era-ruta-map.py (COMPANION avtomatsko), r387-qa-spot.sh, r387-triaza.py, r387-val65-apply.py, r387-register-write.py, r387-readme-update.py, r387-worklog-append.py, r387-commit-msg.txt] + r387-stil-val65.test.ts [×6] + r387-fb-border-generalizacija.test.ts [×6 — FEATURE]; UREJENO: 2 render datoteki [val 65 INS ×2: notification-center L748, photo-tab L2113], 11 zamrznjenih needle skript [PIN SHIFT: r245–r255-build-needles.sh], r368-stil-val51.test.ts [EVOLVED (C) novObv], r385-fb-dark-generalizacija.test.ts [EVOLVED amber/60 + PAR mapa + sirote ključ], r385-stil-val63.test.ts [EVOLVED (E)], r386-stil-val64.test.ts [EVOLVED (B)+(E)], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 65 = render plast a11y className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (81. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R388 prva naloga = qa-round.sh 387 prod-qa re-run [prek r359-prod-qa-retry.sh 387] + enainštirideseta era preverba r347–r387 [41 registrov, ≥167 = 163 + 4; prek era-clone.py --src-round 387 --expected-total 167 + VSEH 12 spec-ov IZRECNO — LEKCIJA R384 (1)]; pričakuj 167/167 ŽIVO [r387 4 needleji razrešeni ob TEM pushu] + val 65 POST-deploy verifikacija [4 needleji r387.tsv; mounted + className LOČENO; NIČ klikov na revoke/odjavo; spot vzorci iz spot-r167/27 — POGOJNE resnice (brezDobavitelja > 0; foto mere v seznamu) dokumentirane z iskrenim 0].
- R388 kandidati: 1. plain amber ring ostanki ×4 + mrtev-CSS navy ×20 statistika [sveža triaža; statistika brez vizualnega učinka NE sme biti delana zaradi dela — morda zamrznjeno z dokumentacijo]; 2. dark-only ring pari (notification L748 vzorec light /60 + dark /40) čez druge družine [sveža triaža]; 3. e2e-lib dedup 22. val [po kanonu]. ⭐ LEKCIJE R386 (1)+(2) + R387: lookbehind čez VSE preverbe + pre-skan stil testov VSEH prejšnjih vals iste družine (r368+r375+r385+r386+r387) + pre-skan TUDI zamrznjenih needle skript scripts/*.sh (NE samo TSV registrov) + PIN SHIFT V ISTI RUNDI. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

W.write_text(src + VNOS, encoding="utf-8")
print(f"OK: worklog append R387 ({len(VNOS)} bajtov); guard ohranjen na koncu pred vnosa repom")
