#!/usr/bin/env python3
# r388-worklog-append.py — R388 fail-closed append v worklog.md (EN vnos:
# R388; guard = rep R387 vnosa z GLASNO prefix preverbo '- R388 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- R388 kandidati: 1."):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R387: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R388
Agent: Super Z (AI runda, Job 413422, tick 202610031133 — šest tickov 202610021821/030215/030400/030815/030915/031133 združenih: pet je bilo že pokritih z R386/R387 vnosi; ta tick = R388)
Task: R388 — prva naloga (prod-qa re-run 387 + ENAINŠTIRIDESIJNA era preverba r347–r387 + val 65 POST-deploy verifikacija) + MANDATORY STIL val 66 (HOVER-BARVNA GLADKOST — transition-colors, 21 × INS PRE/PO ankor + PIN SHIFT r211 ×2) + FEATURE ČETRTI STRAŽAR hover gladkost GENERALIZACIJA + EVOLUCIJA r377 (števec) + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 30f9864 (R387) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R387 vnos = handover (prebran; njegov 'R388 prva naloga' + 'R388 kandidati' izvedeni dobesedno). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 387` — **ZELEN ob poskusu 2** (22. runda; poskus 1 = znana transient kategorija R358/R359 — Z2 chunk harvest curl brez retry).
- PRVA NALOGA (B): **ENAINŠTIRIDESIJNA era preverba** (41.) `r388-era-harvest.sh` [41 registrov r347–r387, ≥167 = 163 + 4, vsota IZ DISKA; generiran prek era-clone.py --src-round 387 --dst-round 388 --expected-total 167 + **VSEH 12 server-probe spec-ov IZRECNO — LEKCIJA R384 (1)**; ⭐ **era-clone.py ERA_BESODE GLASNO razširjena na 41** [ENAINŠTIRIDESIJNA] — fail-closed guard je to zahteval (kanon: razširi GLASNO, ne tiho]; COMPANION `r388-era-ruta-map.py` nastal samodejno]; **EXIT=0 ×2** (determinizem) — **167/167 ŽIVO** (direktno + hash + 18 server resolucij); must_miss ×41 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 65 deploy POTRJEN** (4 needleji r387 razrešeni ob R387 pushu).
- PRVA NALOGA (C): **val 65 POST-deploy spot** `r388-qa-spot.sh` (spot-r167/28; ZERO-MUTACIJA — NIČ klikov na revoke/izvoz/odjavo/obvestilne vrstice/označi prebrano): (A) top-bar 'Obvestila' sheet (kanon Radix odpiranje) → notification L748 vrstica **MONTIRANO 10× na produ** — vseh 20 tokenov LOČENO per className split (incl. FB amber/60 + dark FB amber/40 + dark ring /40) + (C) **seam adjacency 10×** 'dark:focus-visible:border-roksal-amber/40 dark:focus-visible:ring-roksal-amber/40' (dokaz vstavitve MED offset-2 in dark ringom); (B) photo STROKES 'Debelina črte' (L2113) **iskreno 0** — POGOJNA resnica (uredjevalnik zahteva odprto fotografijo isPhoto && photoId; ZERO-MUTACIJA: ničesar ne fabricirati; needle ŽIVO v buildu = era need_static); (D) globalni PAR žeton 10×; sonde navy 27/27/0 + red 0; kolektor **0**. **SKUPAJ val 65: MONTIRANO 10× + seam 10× + 1 iskreno 0 z razlogom.**
- MANDATORY STIL **val 66 — HOVER-BARVNA GLADKOST (transition-colors)**: sveža triaža disk resnica `r388-triaza.py` [handover kandidati iskreno ZAMRZNJENI — statistika brez vizualnega učinka NI delana zaradi dela: **plain amber ring ostanki = 9** (semantično stanja: izbor/status/dekoracija — NI pariteta tema), **mrtev-CSS navy = 82** [r388-triaza2.py: focus ring + offset BREZ border širine → border-pariteta bi bila MRTVA CSS; handover ocena ×20 zastarela — disk resnica; R375 je dokumentiral ×25 na svoji površini], **dark-only ring pari = 1** (L748 seed; druge družine izčrpane)]; `r388-triaza3.py` hover-border transition census = 16 hitov — **vseh 16 lažno pozitivnih** [baza nosi transition-all/transition-colors na base vrstici template literala]; `r388-triaza4/5.py` **element-točna triaža** (najdiTag nazaj do odpiralnega taga + pokritost per lastnost bg=background-color/text=color/border=border-color) → 15 realnih + 1 artefakt → **val 66 = 21 × INS ' transition-colors' TIK okoli hover žetona** [PRE anchor ×19: žeton PRED hover; PO anchor ×2: dashboard L2941 + photo L2081 — PRE span PINAN v zamrznjenih prod-qa skriptah r313–r339 + r315-stil-val6 ('text-roksal-amber hover:bg-roksal-amber/25' / 'text-white hover:bg-roksal-amber/90'); PO vstavljanje ohranja span → brez PIN SHIFTa zamrznjenih skript; polni-span pre-skan (pre+hover) ujel vseh 6 pinov], in-place 0 novih vrstic ×8 datotek [**dashboard ×11 — Badge hover:bg družina: Badge cva baza 'transition-[color,box-shadow]' NE pokrije background-color** → Badge vrstice z hover:bg rabijo LASTNO transition-colors (navy/15 ×2, amber/20 ×2, green/20 ×3, red/20 ×4 vključno z L1238/1239 ternary veja) + termini-card ×1 + setup L100 + aktivacija L65 (nativna <Link> CTA) + viz-tab L330 + product-home L147 (mobilni gumbi) + photo ×3 (L1162 <a>, L2081 gumb PO, L2294) + measurements ×2 (Trash2 ikoni L3355/L4036)]; iskrene izključitve dokumentirane [mrtvi hover žetoni: hover:bg == bg ×4 (step-product L275, measurements L5609, sessions-dialog L292, quote-followup L409) + pointer-events-none ×2 (before-after L182/L185) + mrtvi izvozi termini-prikaz ×4 (brez .tsx potrošnika) + notification L811 transition-transform konflikt (aditivni transition-colors bi OVERIRAL transform — NI aditivno rešljiv)]; `r388-val66-apply.py` fail-closed [kontrakt EMBEDDED ×21 (stara vrstica bajtnato) + **PIN SHIFT r211-fail-verbose-detail-strazar.test.ts ×2 v ISTI atomski korak** (kanon R368; L60 s literalnim \\" escape + L70, žig [PIN SHIFT R388 val 66]); POST in-place; idempotenca — ponovni tek = abort 'vrstica ≠ kontrakt' (0 novih INS dokazano); 1. tek abortal NAJPREJ na r211 (nitka escape) pred VSAKO spremembo — fail-closed dokazan tudi na napaki].
- ⭐ **LEKCIJA R388 (1) — element-točna triaža obvezna**: per-vrstični census je lažno pozitiven na DVA načina — (a) className pokončinene vrstice (tag na prejšnji vrstici), (b) cva baza (Button 'transition-all', Badge 'transition-[color,box-shadow]') nosi transition izven vrstica; pokritost se preverja na NIVOU ODPIRALNEGA TAGA (r388-triaza5.py); **counter-pini (številski števci žetonov, npr. r377 'transition-colors ×12') jih span/anchorni pre-skan NE vidi** — FULL vitest tek 1 je mreža; EVOLVED V ISTI RUNDI.
- PRE-SKAN (LEKCIJA R383 (3) — PRED apply): `r388-window-scan.py` [**12. generacija iz r383 — kanon R358 hardening V NOVI skripti; TARGETS +4: setup-client, activation-client, viz-tab, product-home; REG_DO = 387; DEL 4 pričakovane vrstice osvežene**] delta 18 ×9 hover žetonov (navy/15, amber/20, green/20, red/20, amber/90, text-ink, text-amber, amber/25, text-red): **304 okenskih regexov 0 preozkih + 180 needle pinov 0 mrtvih + 133 slice-oknen + 0 vrstičnih odstopanj — EXIT=0 ×9**.
- ⭐ **LEKCIJA R386 (2) UPORABLJENA, ampak NE ZADOSTUJE za counter-pin**: pre-skan polnih spanov (pre+hover) čez src/lib/__tests__ + scripts/*.sh + TSV je ujel vseh 6 groženj — ampak r377-stil-val58 števec 'transition-colors = 12' NE vsebuje hover žetona → FULL vitest **tek 1 = 5618/5619** (1 fail = r377 stale števec 12 → disk 23) → **EVOLVED V ISTI RUNDI** [števec 12→23 z žigom [EVOLVED R388 val 66 +11 PRE anchorjev]]; FULL **tek 2 = 5619/5619 GREEN**.
- **FEATURE ČETRTI STRAŽAR — hover gladkost GENERALIZACIJA**: `r388-hover-gladkost-generalizacija.test.ts` **×10 ZELENO** — (A) globalna kršitev = 0 čez VSE src z element-točno pokritostno logiko (najdiTag + pokritost v TS — zrcali r388-triaza5.py; ZAMRZNJENE izjeme ×11 + 1 finder omejitev material-intelligence L459 iskreno dokumentirana — template literal vrnitev BREZ JSX sidra, dejanska pokritost prisotna prek baze L457); (B) ui-kit bazi zamrznjeni (Button 'transition-all' + Badge 'transition-[color,box-shadow]' — shadcn jezik NI mutiran); (C) it.each per datoteka: val 66 tarče nosijo transition-colors. KOMPLET ŠTIRIH varuhov pokriva celoten stil jezik: r385 (dark FB polovica) + r386 (O2 pairing) + r387 (FB-border istobarvnost) + r388 (transition pokritost).
- r388-stil-val66.test.ts **×6 ZELENO** [(A) PARITETA 21 tarč transition-colors na isti vrstici, (B) CENZUS per datoteka zamrznjen [18/5/12/4/1/1/1/1] + PO spans ×2 ŽIVA, (C) N/A izključitve bajtno [mrtvi žetoni + pointer-events-none + termini-prikaz 5 pojavitev (L47 ima TUDI dark:hover) + L811 konflikt], (D) ZAMRZNJENE STATISTIKE plain 8/navy 36/dark-par 1 v baznem vzorcu [disk resnica celotnega src: 9/82/1], (E) r211 PIN SHIFT regresija novi ×2 + stari 0, (F) in-place vrstični števci ×8 + r387 seam needle ŽIVO].
- e2e-lib dedup 22. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r388.tsv` [4 need_static: setup/aktivacija <Link> CTA **ožji žeton** ('rounded-xl bg-roksal-amber px-5 … shadow-md transition-colors hover:bg-roksal-amber/90' — ker m/[token] measure-client L322 nosi ISTI span ŽE v HEAD = **obstoječ precedens gladkosti**, N1 prvi nabort = 0-v-HEAD fail-closed je ujel), dashboard Badge navy/15 ×2, photo PO anchor dokaz, dashboard red/20 + r211 žig ×4; 0 v HEAD 30f9864; TODO-R388 must_miss] prek `r388-register-write.py` fail-closed [TSV točno 3 polja, bajtno ŽIVO v src, 0-v-HEAD, need_static=4 usklajeno z era verigo — naslednja ≥171].
- README: števec 5603/369 → **5619/371** [= R387 baza + mojih +16/+2: r388-stil-val66 ×6 + r388-hover-gladkost ×10 (2 + 8 it.each — LEKCIJA R386 it.each ne podcenjevati UPORABLJENA)] + R388 bullet (njegov R387 bullet ohranjen) prek `r388-readme-update.py` fail-closed.

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL `eslint .`) · vitest **5619/5619 (371) FULL GREEN TEK 2** [tek 1 = 5618/5619 — r377 stale counter-pin ujet + EVOLVED V ISTI RUNDI; LEKCIJA R388 (1)] · build svež rm -rf .next EXIT=0 · qa-round.sh 388 needles EXIT=0 [r388.tsv 4 ŽIVO + TODO-R388 odsoten; Z-STRUCT pokvarjenih 0; UNION r340–r388 + veriga r339→…→R227 VSE ŽIVE] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r388-era-harvest EXIT=0 ×2 [41st — 167/167 ŽIVO] · r388-window-scan delta 18 ×9 EXIT=0 [DEL 1–4 čisti] · r359-prod-qa-retry 387 ZELEN ob poskusu 2 · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na src+scripts].
- NOVO: scripts/qa-needles/r388.tsv + skripte [r388-era-harvest.sh (41st) + r388-era-ruta-map.py (COMPANION avtomatsko), r388-qa-spot.sh, r388-triaza.py, r388-triaza2.py, r388-triaza3.py, r388-triaza4.py, r388-triaza5.py, r388-val66-apply.py, r388-window-scan.py (12. gen), r388-register-write.py, r388-readme-update.py, r388-worklog-append.py, r388-commit-msg.txt] + r388-stil-val66.test.ts [×6] + r388-hover-gladkost-generalizacija.test.ts [×10 — FEATURE]; UREJENO: 8 render datotek [val 66 INS ×21: dashboard ×11, photo ×3, measurements ×2, termini-card ×1, viz-tab ×1, product-home ×1, setup ×1, aktivacija ×1], r211-fail-verbose-detail-strazar.test.ts [PIN SHIFT ×2 R388 val 66], r377-stil-val58.test.ts [EVOLVED števec 12→23], era-clone.py [ERA_BESODE +41 GLASNO], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 66 = render plast className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (82. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R389 prva naloga = qa-round.sh 388 prod-qa re-run [prek r359-prod-qa-retry.sh 388] + dvainštirideseta era preverba r347–r388 [42 registrov, ≥171 = 167 + 4; prek era-clone.py --src-round 388 --expected-total 171 + VSEH 12 spec-ov IZRECNO — LEKCIJA R384 (1)]; pričakuj 171/171 ŽIVO [r388 4 needleji razrešeni ob TEM pushu] + val 66 POST-deploy verifikacija [4 needleji r388.tsv; mounted + className LOČENO; NIČ klikov na revoke/odjavo; setup/aktivacija <Link> sta PRED prijavo — spot vzorec izklopljenega stanja ali iskreno 0 z razlogom; PO-anchor needle (photo L2081) POGOJNA (odprta fotografija)].
- R389 kandidati: 1. hover-bg gladkost ZAKLJUČEK — hover:bg-roksal na nativnih elementih izven val 66 obsega (step-* čarovnik, mask-editor, viz-tab L143/152/164, product-* ostali, product-projects) [sveža triaža po LEKCIJI R388 (1) element-točno; isti PRE/PO ankor kanon]; 2. notification L811 transition-transform konflikt [property-list nadgradnja 'transition-[transform,color]' — NI aditivno; lasten val z EVOLVED (C)]; 3. e2e-lib dedup 23. val [po kanonu]. ⭐ LEKCIJE R386/R387/R388: lookbehind čez VSE preverbe + pre-skan stil testov VSEH prejšnjih vals iste družine + pre-skan TUDI zamrznjenih needle skript scripts/*.sh + PIN SHIFT V ISTI RUNDI + **counter-pini jih boundary pre-skan NE vidi — FULL vitest tek 1 je mreža; EVOLVED V ISTI RUNDI** + **element-točna triaža (per-vrstični census lažno pozitiven)**. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

nov = src.rstrip("\n") + "\n" + VNOS
if not nov.endswith(VNOS.rstrip("\n") + "\n"):
    sys.exit("FAILOVEDANO: append preverba ni uspela — abort")
W.write_text(nov, encoding="utf-8")
print(f"OK: worklog R388 vnos pripet ({len(VNOS)} bajtov; guard = R387 rep)")
