#!/usr/bin/env python3
# r389-worklog-append.py — R389 fail-closed append v worklog.md (EN vnos:
# R389; guard = rep R388 vnosa z GLASNO prefix preverbo '- R389 kandidati: 1.').
import sys
import pathlib

W = pathlib.Path("/home/z/my-project/worklog.md")

src = W.read_text(encoding="utf-8")
vrstice = [l for l in src.splitlines() if l.strip()]
GUARD = vrstice[-1] if vrstice else ""
if not GUARD.startswith("- R389 kandidati: 1."):
    sys.exit(f"FAILOVEDANO: zadnja vrstica NI rep R388: {GUARD[:80]!r}")
if src.count(GUARD) != 1:
    sys.exit(f"FAILOVEDANO: guard ×{src.count(GUARD)} ≠ 1")
if not src.rstrip("\n").endswith(GUARD):
    sys.exit("FAILOVEDANO: guard NI na koncu — abort")

VNOS = """---
Task ID: R389
Agent: Super Z (AI runda, Job 413422, tick 202610031231)
Task: R389 — prva naloga (prod-qa re-run 388 + DVAINŠTIRIDESIJNA era preverba r347–r388 + val 66 POST-deploy verifikacija) + MANDATORY STIL val 67 (LASTNA-PREHOD GLADKOST — property-list nadgradnja, 2 × REPL in-place) + FEATURE PETI STRAŽAR lastna-prehod disciplina GENERALIZACIJA + era veriga utrjena (CHECKPOINT GUARD + ODPADNI CENZUS + kontrole hash-fallback) + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 2ccba6c (R388) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R388 vnos = handover (prebran; njegov 'R389 prva naloga' + 'R389 kandidati' izvedeni dobesedno). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 388` — **ZELEN ob poskusu 1** (23. runda).
- ⭐ **LEKCIJA R389 (1) — Vercel Security Checkpoint onesnaži žetev**: 1. tek era preverbe [r389-era-tek1] — žeteva '60 čankov OK, 0 failov, 0 retry-jev', ampak samo 82/171 need_static ŽIVO + 89 MISS [EXIT=2]; diagnoza: **večina 60 čankov = 403 'Vercel Security Checkpoint' strani** (~33.9KB po velikostni porazdelitvi; natančen števec ni vztrajen — imenik prepisan z naslednjimi teki; dobesedni žig ×14 preživel v prepisani kopiji) — **qa-harvest uspeh = ne-prazno telo, 403 stran JE ne-prazna!**; ročni probe potrdil: HTTP 403 na site root + chunk URL (Vercel bot-challenge — rate limit po intenzivni žetvi 60 + 89 rezolucijskih curl-ov; NOVA transient kategorija, brez precedensa v worklogu); **deterministična pavza ~45s razrešila** (/api/health vrnil izvorni fail-closed 401 = checkpoint dvignjen); → **CHECKPOINT GUARD v r389-era-harvest.sh** [grep po žetevi: 1× 'Vercel Security Checkpoint' = glasni abort z diagnozo '$pol/$n čankov onesnaženih; NEVELJAVNA — NI code-bug, NI pokritostna vrzel' + exit 2] + **era-clone.py GLASNO razširjen** [nov rep() 1b — vsi prihodnji generirani harvesti nosijo guard; POST checks +('CHECKPOINT GUARD',1)+('Vercel Security Checkpoint',2); izoliran test na pravem r388 viru: anchor count 1, guard blok bajtno identičen].
- ⭐ **LEKCIJA R389 (2) — zamrznjen URL seznam iz R339 OPADE**: tek 2 (po guardu) EXIT=0, ampak 'era kontrola R340: MISS' [v R388 še ŽIV] — diagnoza: **5/60 čankov = 'Not Found' telesa** [Vercel počistil 43-rundne stare artefakte; tudi ti so ne-prazna telesa = 'OK' za qa-harvest]; need_static 171/171 je šel SKOZI ker hash-rezolucija fetcha IZ TEKUČEGA deploya [lokalni chunk fd2377174053c378.js obstaja na prod CDN], ampak era-kontrole sekcija je grepa SAMO po žetvi → **ODPADNI CENZUS** [iskren popis: '$odpad/$n čankov iz zamrznjenega URL seznama (R339) = Not Found' — poročilo, NE abort] + **era kontrole dobile hash-rezolucijski fallback** [isti LEKCIJA R354 mehanizem kot need_static: lokalni chunk → prod CDN 200+niz] → R340 kontrola **ŽIV (hash rezolucija fd2377174053c378.js — URL seznam opadel)**; era-clone.py GLASNO razširjen tudi za to [rep na kontrole vrstici, POST checks +('ODPADNI CENZUS',1)+('era kontrola $tag: ŽIV (hash rezolucija',1)].
- PRVA NALOGA (B): **DVAINŠTIRIDESIJNA era preverba** (42.) `r389-era-harvest.sh` [42 registrov r347–r388, ≥171 = 167 + 4, vsota IZ DISKA [per-registr 4+5+8+9+3+8+4+3+3+3+3+3+3+3+3+4+4+4+4+4+4+4+4+4+4+4+4+4+4+4+1+4+4+4+4+5+4+4+4+4+4+4]; generiran prek era-clone.py --src-round 388 --dst-round 389 --expected-total 171 + **VSEH 12 server-probe spec-ov IZRECNO — LEKCIJA R384 (1)**; ERA_BESODE GLASNO razširjena na 42 [DVAINŠTIRIDESIJNA — guard je to zahteval]; COMPANION `r389-era-ruta-map.py` avtomatsko]; **EXIT=0 ×2** (determinizem, utrjeni skripti) — **171/171 ŽIVO** [69 direktno + 102 hash rezolucija v tek 4]; must_miss ×42 čisto; era kontrole R340 [hash rezolucija]/R341/R343/R345 ŽIVE → **val 66 deploy POTRJEN** (4 needleji r388 razrešeni ob R388 pushu).
- PRVA NALOGA (C): **val 66 POST-deploy spot** `r389-qa-spot.sh` (spot-r171/29; ZERO-MUTACIJA — NIČ klikov na revoke/izvoz/odjavo/obvestilne vrstice/označi prebrano; setup bootstrapa NIKOLI ne sprožimo): (A) /setup javna stran PRED prijavo → N1 <Link> CTA (L100) **iskreno 0** — POGOJNA resnica [CTA renderan SAMO v 'done' stanju po uspešnem bootstrapu/obnovi — ZERO-MUTACIJA ne sproži bootstrapa; needle ŽIVO v buildu = era need_static]; (B) prijava → dashboard dispatch → N2 Badge navy/15 **MONTIRANO 1×** [celoten span 'text-roksal-ink transition-colors hover:bg-roksal-navy/15' per className split; tokeni LOČENO: text-roksal-ink ×30 / transition-colors ×11 / hover:bg-roksal-navy/15 ×1] + N4 red/20 **MONTIRANO 1×** [span 'text-roksal-red transition-colors hover:bg-roksal-red/20']; (C) measurements → N3 PO anchor photo L2081 **iskreno 0** — POGOJNA [odprta fotografija isPhoto && photoId; NI odpiranja/fabriciranja]; (D) sonde navy 27/27/0 + red 0; kolektor **0**. **SKUPAJ val 66: 2 MONTIRANO + 2 iskreno 0 z razlogom.**
- MANDATORY STIL **val 67 — LASTNA-PREHOD GLADKOST (property-list nadgradnja)**: sveža triaža disk resnica `r389-triaza.py` [element-točna, LEKCIJA R388 (1) kanon; val 66 tarče izključene iz kandidatov]: **handover kandidat 1 = 0 REALnih gapov** [122 že pokritih + 239 ui-kit + 1 transform-konflikt; R388 izključitve VSE potrjene na disku ZERO-TRUST: termini-prikaz COLORS ×4 brez .tsx potrošnika — logistika/projekti-termini-pdf uvažata SAMO STATUSI/LABELS/terminBeseda (rg disk preverjeno) + material-intelligence L459 template literal z bazo L457 transition-colors (pokritost prisotna, finder omejitev)]; **handover kandidat 2 = konfliktna družina TOČNO 2** [sistematični scan transition-(transform|opacity|shadow|none) + (group-)hover barvni žeton na istem elementu čez vse src]: notification L811 [nativni ChevronRight: transition-transform + group-hover:translate-x-0.5 + group-hover:text-roksal-amber — barva SNAP] + safety-tab L254 [ui-kit Button: bg-roksal-navy hover:bg-roksal-navy/90 + transition-transform — **baza transition-all OVERRIDANA s strani elementa**]; ⭐ **kaskadna disk resnica iz zgrajenega CSS** [437bdcb4b4a2e58f.css]: .transition @115150 < **.transition-[color,box-shadow] @115870 (Badge baza!)** < .transition-all @117243 < .transition-colors @117441 < .transition-opacity @117776 < .transition-shadow @117982 < .transition-transform @118190 < .transition-none @118423 — kasnejši ZMAGA → (a) L254 hover:bg SNAP kljub bazi [LEKCIJA R389 (3): cva baza pokritost je NIČNA, če element sam nosi ožjo transition-* utility], (b) val 66 Badge popravki VALIDNI [lastna transition-colors @117441 > baza @115870], (c) aditivni transition-colors na L811 bi OVERIL transform [colors @117441 < transform @118190] → edina iskrena rešitev = property-list nadgradnja]; pre-skan `r389-window-scan.py` [**13. generacija iz r388 — TARGETS spremeni NIČ [notification-center + safety-tab ŽE pokrita]; REG_DO = 388; DEL 4 + notification 969 + safety 759**] delta +8/+30 ×transition-transform: **304 okenskih regexov 0 preozkih + 184 needle pinov 0 mrtvih + 150 slice-oknen + 0 vrstičnih odstopanj — EXIT=0 ×2**; polni-span pre-skan čez tests+scripts+TSV: 0 pinov [r211 konflikt NI] + counter-pin preverba: 'transition-transform' števcev 0, r377 'transition-colors = 23' nespremenjen [val 67 doda arbitrary liste, NE colors]; `r389-val67-apply.py` fail-closed [kontrakt ×2 polna stara vrstica bajtno + **EVOLVED ×3 V ISTI atomski korak** (kanon R368); POST: 969+759 vrstic bajtno, nov žeton ×1, star ×0; idempotenca abort]: **2 × REPL in-place** — notification L811 `transition-transform` → `transition-[transform,color]` [translate-x + color OBA gladka] + safety-tab L254 `transition-transform` → `transition-[transform,background-color,box-shadow]` [bg + focus ring + scale; po buildu arbitrary @116799/@117071 < .transition-all @117742 → zmagovalec baza → VSI gladki — kaskadna hipoteza POTRJENA na svežem CSS e99cf86dc346a3ed.css].
- r389-stil-val67.test.ts **×4 ZELENO** [(A) PARITETA 2 tarči nadgrajena lista + star token ×0, (B) CENZUS preostalih 6 transition-transform vrstic [weather L176, vodja ×3, reference L1551, photo L2177] NISO konfliktni — brez roksal hover barve, (C) EVOLVED žigi R388 testov bajtno, (D) in-place disk resnica 970+760 split(\\n) + žetoni ×1]; prvi tek ujel 3 lastne napake [split('\\n') trailing newline semantika 970≠969, R() pot lib/__tests__, regex \\b NE ujame arbitrary zaključka ']'] → popravljeno v isti rundi.
- **FEATURE PETI STRAŽAR — lastna-prehod disciplina GENERALIZACIJA**: `r389-lasta-uzkost-generalizacija.test.ts` **×5 ZELENO** — (A) globalna kršitev = 0 čez VSE src z **KASKADNO logiko** [zmagovalec = najvišji rang med prisotnimi utilityji (lastne + baza za Button/Badge); **R388 unija vseh matchov je bila lažno pozitivna pri ko-obstoju ožjega in širšega utilityja** — disk preverjeno: 0 elementov z 2+ lastnimi utilityji + hover = nič lažnih pozitivov na trenutnem drevesu]; (B) ui-kit bazi zamrznjeni [Button transition-all + Badge transition-[color,box-shadow] bajtno — shadcn jezik NI mutiran]; (C) it.each ×2: val 67 tarči nosijo nadgrajeno listo + star token ×0; (D) izjeme ×11 + L811/L254 kaskadno pokriti izrecno. KOMPLET PETIH varuhov: r385 (dark FB polovica) + r386 (O2 pairing) + r387 (FB-border istobarvnost) + r388 (transition pokritost) + r389 (kaskadna disciplina).
- EVOLVED V ISTI RUNDI (kanon R368; znotraj r389-val67-apply.py): r388-stil-val66.test.ts (C) [L811 pin 'transition-transform ✓' → 'transition-[transform,color] ✓ + star ×0 + group-hover ohranjen', žig [EVOLVED R389 val 67]] + r388-hover-gladkost-generalizacija.test.ts [L811 IZ ZAMRZNJENIH IZJEM ×12→×11 — pokritost sedaj resnična, stražar jo PREVERJA; glava dokumentira, žig ×2].
- e2e-lib dedup 23. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r389.tsv` [2 need_static: notification L811 najdaljši novi span 'transition-[transform,color] group-hover:translate-x-0.5 group-hover:text-roksal-amber' + safety-tab L254 'transition-[transform,background-color,box-shadow] duration-200'; 0 v HEAD 2ccba6c; TODO-R389 must_miss] prek `r389-register-write.py` fail-closed [TSV točno 3 polja, bajtno ŽIVO v src, 0-v-HEAD, need_static=2 usklajeno z era verigo — naslednja ≥173].
- README: števec 5619/371 → **5628/373** [= R388 baza + mojih +9/+2: r389-stil-val67 ×4 + r389-lasta-uzkost ×5 (A+B+C it.each ×2+D)] + R389 bullet (njegov R388 bullet ohranjen) prek `r389-readme-update.py` fail-closed; **iskrenost popavek**: '46/60' (ocena iz velikostne porazdelitve, predstavljena kot števec) → 'večina (natančen števec ni vztrajen)' v TSV+README — NI fabriciranja.
- VERIFIKACIJA-korekcija: README bullet je bil napisan PRED FULL verifikacijo z napovedanimi števci → **vsi števci PO teku usklajeni z disk resnico** (vsi GREEN — nič korekcij števcev; načelo: bullet sme trditi SAMO to, kar je že teklo, ALI se posodobi po teku).

Stage Summary:
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL `eslint .`) · vitest **5628/5628 (373) FULL GREEN TEK 1** [brez stale counter-pinov — LEKCIJA R388 (1) pre-skan zadel] · build svež rm -rf .next EXIT=0 · qa-round.sh 389 needles EXIT=0 [r389.tsv 2 ŽIVO + TODO-R389 odsoten; UNION r340–r389 + veriga r339→…→R227 VSE ŽIVE] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r389-era-harvest EXIT=0 ×2 [42nd — 171/171 ŽIVO; utrjen: guard + cenZUS + kontrole fallback] · r389-window-scan delta EXIT=0 ×2 [DEL 1–4 čisti] · r359-prod-qa-retry 388 ZELEN ob poskusu 1 · kaskadna pozicija POTRJENA na svežem CSS [e99cf86dc346a3ed.css: arbitrary @116799/@117071 < all @117742] · leak-check čist [ghp_[A-Za-z0-9]{30,} ×0 na src+scripts].
- NOVO: scripts/qa-needles/r389.tsv + skripte [r389-era-harvest.sh (42nd, utrjen) + r389-era-ruta-map.py (COMPANION avtomatsko), r389-qa-spot.sh, r389-triaza.py, r389-val67-apply.py, r389-window-scan.py (13. gen), r389-register-write.py, r389-readme-update.py, r389-worklog-append.py, r389-commit-msg.txt] + r389-stil-val67.test.ts [×4] + r389-lasta-uzkost-generalizacija.test.ts [×5 — FEATURE]; UREJENO: 2 render datoteki [val 67 REPL ×2: notification-center L811, safety-tab L254 — 0 novih vrstic], r388-stil-val66.test.ts [EVOLVED (C) L811 pin], r388-hover-gladkost-generalizacija.test.ts [EVOLVED izjeme ×12→×11], era-clone.py [ERA_BESODE +42 GLASNO + CHECKPOINT GUARD + ODPADNI CENZUS + era kontrole hash-fallback — vsi GLASNO, s POST checks], scripts/qa-needles/r389.tsv + README [iskrenost popavek 46/60→večina], README.
- Kontrakt NIČ (/api/sync — probe je samo fail-closed 401 branje); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 67 = render plast className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (83. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R390 prva naloga = qa-round.sh 389 prod-qa re-run [prek r359-prod-qa-retry.sh 389] + triinštirideseta era preverba r347–r389 [43 registrov, ≥173 = 171 + 2; prek era-clone.py --src-round 389 --expected-total 173 + VSEH 12 spec-ov IZRECNO — LEKCIJA R384 (1); ERA_BESODE GLASNO razširiti na 43 — guard bo zahteval]; pričakuj 173/173 ŽIVO [r389 2 needleja razrešena ob TEM pushu] + val 67 POST-deploy verifikacija [2 needleji r389.tsv; mounted + className LOČENO; notification sheet vrstice se samo MERIJO (ZERO-MUTACIJA); safety-tab 'Kopiraj varnostno poročilo' gumb je mutacija (clipboard) — SAMO className split MERITEV brez klika; POGOJNE resnice iskreno].
- R390 kandidati: 1. stil transition/hover-roksal družina IZČRPANA [val 67 disk resnica: 0 realnih gapov] → sveža triaža NOVE družine ALI iskreno izpuščen val [kanon]; 2. L811/L254 POST-deploy spot + kaskadna disk resnica v R390 svežem buildu [r389 feature test (D) komentar — vrstni red je Tailwind-kanon, absolutne pozicije se spreminjajo]; 3. e2e-lib dedup 23. val [po kanonu — ni novih ×3 ponovitev]. ⭐ LEKCIJE R389: (1) **Security Checkpoint 403 onesnaži žetev — qa-harvest uspeh = ne-prazno telo, 403 stran JE ne-prazna** → glasni CHECKPOINT GUARD + deterministična pavza; transient infra kategorija, NI code-bug; (2) **zamrznjen URL seznam (R339) odpada — Vercel čisti stare artefakte ('Not Found' telesa)** → ODPADNI CENZUS + hash-rezolucijski fallback POVSEK (need_static ŽE, era kontrole ZDAJ tudi); (3) **cva baza pokritost je NIČNA, če element sam nosi ožjo transition-* utility — kaskadni zmagovalec (kasnejši v stylesheetu), NE unija matchov**; arbitrary se vrsti PRED transition-all; (4) iskrenost popavek: ocene NE smejo biti predstavljene kot števci ('46/60' → 'večina; natančen števec ni vztrajen'); (5) split('\\n') šteje trailing newline — canon za vrstične števce v testih je split('\\n').length = realne vrstice + 1. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

nov = src.rstrip("\n") + "\n" + VNOS
if not nov.endswith(VNOS.rstrip("\n") + "\n"):
    sys.exit("FAILOVEDANO: append preverba ni uspela — abort")
W.write_text(nov, encoding="utf-8")
print(f"OK: worklog R389 vnos pripet ({len(VNOS)} bajtov; guard = R388 rep)")
