#!/usr/bin/env python3
# r392-worklog-append.py — R392 worklog vnos (fail-closed, append-only;
# guard: R391 vnos mora biti prisoten; idempotenten: abort če R392 ŽE obstaja).
import pathlib
import sys

REPO = pathlib.Path("/home/z/my-project")
WL = REPO / "worklog.md"

VNOS = """
---

Task ID: R392
Agent: Super Z (AI runda, Job 413422, tick 202610031500)
Task: R392 — prva naloga (prod-qa re-run 391 + ŠTIRIDESIJNA era preverba r347–r390 [KOLIZIJA #25 skip obnovljen] + val 68 POST-deploy verifikacija) + MANDATORY STIL val 69 (HOVER-SENČNA GLADKOST — 2 × REPL) + FEATURE SEDMI STRAŽAR hover-transform + senčna pokritost disciplina + register r392.tsv + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 0238292 (R391) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R391 vnos = handover (prebran celoten; njegov 'R392 prva naloga' + 'R392 kandidati' izvedeni dobesedno). ADOPCIJA ni bila potrebna.
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 391` — **ZELEN ob poskusu 1** (25. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **ŠTIRIDESIJNA era preverba** (44.) — ⭐ **LEKCIJA R392 (2) — KOLIZIJA-skip era veriga**: njihova katalog runda (R390, issue #13) NI generirala harvesta → era-clone --src-round 390 bi bral NEOBSTOJEČ r390-era-harvest.sh; REŠITEV: 43rd harvest (r391-era-harvest.sh) obnovljen na GENERACIJSKO ime r390-era-harvest.sh (notranje oznake r390 — chain-top+1 konvencija: r390 pokriva r347–r389, r391 pokriva r347–r390) + COMPANION r390-era-ruta-map.py; generiranje prek era-clone.py --src-round 390 --dst-round 391 --expected-total 182 --dst-label "R390 issue #13 (R170)" --dst-chain-seg "IN r389.tsv val 67 ×2 IN r390.tsv ×9 na" + 18 server-probe spec-ov; ERA_BESODE GLASNO razširjena na 44 [ŠTIRIDESIJNA — guard zahteval]; COMPANION r391-era-ruta-map.py avtomatsko: **EXIT=0 ×2** (determinizem, normirana loga identična) — **182/182 ŽIVO** [147 direktno + 8 hash + 9 njihovih katalog AR server resolucij + 18 server]; must_miss ×44 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **njihov katalog R390 + moj val 68 deploy POTRJEN**; ⭐ **LEKCIJA R392 (1) — zamrznjeni SERVER_PROBE_SPECS ne sledijo novim rutam**: njihovih 9 katalog needlejev NISMO razrešljivi prek starih 12 spec-ov (REG_AR ni v nobenem) → 6 NOVIH AR spec-ov [/api/catalog, /versions, /compatibility, /supplier-mappings, products/000/applications, products/000/variants — vse 401 fail-closed na produ = njihov deploy ŽIVO]; 1. tek brez AR spec-ov = EXIT=2 z 9 MISS (iskreno dokumentiran, NI code-bug); + prisma migrate deploy + generate na njihovi migraciji 20261008080000_r390_product_catalog (stale client = 34 lažnih TS2339 — LEKCIJA R391 (7) potrjena; .env DATABASE_URL pokvarjen — uporabljen eksplicitni URL, .env NI mutiran).
- PRVA NALOGA (C): **val 68 POST-deploy spot** `r392-qa-spot.sh` (spot-r182/31; ZERO-MUTACIJA): (A) calculator L820 'Nazaj na meritve' **iskreno 0** — POGOJNA resnica (importedFromMeasurement vrata; ZERO-MUTACIJA ne fabricira uvoza; needle ŽIVO v buildu = era need_static); (B) inventory L1562 **MONTIRANO 1×** — 13/13 tokenov LOČENO (tabular-nums→focus-visible šiv + active:scale-[0.96], press-scale ×0 — dvojni mehanizem NE obstaja več na produ); sonde navy 23/23/0 + red 0; kolektor **0**. **SKUPAJ val 68: 1 MONTIRANO + 1 iskreno 0 z razlogom.**
- MANDATORY STIL **val 69 — HOVER-SENČNA GLADKOST**: sveža triaža disk resnica [disabled: družina SEMANTIČNA (cursor-wait=in-flight ×3 vs cursor-not-allowed=nedostopno ×7; opacity 30/40/50/70 resnost; delno mrtev CSS na Button elementih — pointer-events-none) → iskreno ZAMRZNJENO; active:scale heterogenost (0.95–0.99 po velikostnih razredih) → iskreno ZAMRZNJENO (subjektivni kriterij); hover-transform ×16 VSE pokrite]; ⭐ **REALNA družina: hover:shadow-sm SNAP ×2** (element-truth triaža čez roksal+ui+app+viz — edina 2 v CELEM src; 40 ostalih hover:shadow pokritih): material-intelligence L1690+L1980 `transition-colors hover:border-roksal-navy/25 dark:hover:border-roksal-ink/25 hover:shadow-sm` — transition-colors NE pokriva box-shadow (Tailwind v4 definicija) → SNAP; **2 × REPL**: `transition-colors` → `transition-[color,background-color,border-color,text-decoration-color,fill,stroke,box-shadow]` (konzervativna nadgradnja = transition-colors ∪ {box-shadow}; družinski precedens logistics L2360/2466/2659 + roksal-catalog L141 z ožjim seznamom); pre-skan: 0 ogroženih needlejev (r388-qa-spot zadetek = lažno pozitiven token-selector) + counter-pini (r377/r372/r373/r383/r384) NESPREMENJENI; `r392-val69-apply.py` fail-closed + idempotenten [2. tek abort — POST NOVO ×2, star ×0, 0 novih vrstic, senčni SNAP ostanki 0]; `r392-stil-val69.test.ts` **×4 ZELENO** [(A) PARITETA 2 tarči, (B) CENZUS 0 snap čez VSE src, (C) seznam = colors ∪ box-shadow, (D) in-place + precedens, (E) Card baza zamrznjena bajtno].
- **FEATURE SEDMI STRAŽAR — hover-transform + senčna pokritost disciplina GENERALIZACIJA**: `r392-senca-transform-disciplina.test.ts` **×7 ZELENO** [(A) globalna kršitev senca = 0 čez roksal+ui+app+viz; (B) globalna kršitev transform = 0; (C) it.each ×2 val 69 tarče; (D) zamrznjeni števci senca 45 / transform 16; (E) ui-kit baze bajtno — Card NIČ transition (element sam nosi pokritost, LEKCIJA R389 (3)) + Button + Badge]. KOMPLET SEDEM varuhov: r385 (dark FB) + r386 (O2 pairing) + r387 (FB-border) + r388 (hover-barvna pokritost) + r389 (kaskadna disciplina) + r391 (press-scale disciplina) + r392 (hover-transform/senčna disciplina).
- 1 lasten eslint error ujet + popravljen v isti rundi [no-require-imports: require('node:fs') → readdirSync import]; 3 lastne testne napake ujete lokalno PRED FULL tekom [nested it.each prepovedan; ternarna precedence past v assertionih; števci na ŠIRŠEM nizu korenov 45/16 — LEKCIJA R392 (4)].
- e2e-lib dedup 23. val ISKRENO IZPUŠČEN (kanon R368 — ni novih ×3 ponovitev).
- REGISTER `scripts/qa-needles/r392.tsv` [1 need_static **ŠIVNI** needle ×2 pojavitvi (Card sorojenci bajtno identična spana): transition-[color,background-color,border-color,text-decoration-color,fill,stroke,box-shadow] hover:border-roksal-navy/25 dark:hover:border-roksal-ink/25 hover:shadow-sm; 0 v HEAD 0238292 — ⭐ **LEKCIJA R392 (3): družinski precedens z ISTIM seznamom onemogoči 0-v-HEAD** (logistics nosi ožji [border-color,box-shadow] = byte-drugačen ✓ konzervativna nadgradnja da unikaten šiv); TODO-R392] prek `r392-register-write.py` fail-closed [×2 check na render plasti src/components — 1. tek ×3: lasten test .ts zadet; naslednja era ≥183 [45., r347–r391]].
- r392-window-scan.py **15. generacija** [REG_DO 392 — njihov r390 ×9 + moj r391 ×2 + moj r392 ×1 v DEL 2]: **304 okenskih regexov 0 preozkih + 198 needle pinov 0 mrtvih + 150 slice-oknen + 0 vrstičnih odstopanj — EXIT=0**.
- README: števec 5727/379 → **5738/381** [+11/+2: stil val 69 ×4 + SEDMI STRAŽAR ×7] + R392 bullet NAD R391 bulletom (bajtno ohranjen).
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL; 1 lasten error ujet + popravljen) · vitest **5738/5738 (381) FULL GREEN TEK 1** · build svež rm -rf .next EXIT=0 · qa-round.sh 392 needles EXIT=0 [r392.tsv 1 ŽIVO ×2; UNION r340–r392 + veriga r339→…→R227] · smoke EXIT=0 · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN — ZERO-MUTACIJA] · r391-era-harvest EXIT=0 ×2 [44th — 182/182] · r392-window-scan EXIT=0 [DEL 1–4 čisti] · r359-prod-qa-retry 391 ZELEN poskus 1 · leak-check čist [ghp_ ×0].
- NOVO: scripts/qa-needles/r392.tsv + skripte [r391-era-harvest.sh (44th) + r391-era-ruta-map.py (COMPANION), r392-qa-spot.sh, r392-val69-apply.py, r392-window-scan.py (15. gen), r392-register-write.py, r392-readme-update.py (inline), r392-worklog-append.py, r392-commit-msg.txt] + r392-stil-val69.test.ts [×4] + r392-senca-transform-disciplina.test.ts [×7 — FEATURE]; UREJENO: material-intelligence-tab.tsx [val 69 REPL ×2], r390-era-harvest.sh + r390-era-ruta-map.py [obnovljeni generacijski imeni], era-clone.py [ERA_BESODE +44], README.
- Kontrakt NIČ (/api/sync in /api/catalog* probe = samo fail-closed 401 branje, brez pisanja); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 69 = render plast className-only]; OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E; njihova shema = njihova poslovna odločitev].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (85. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R393 prva naloga = qa-round.sh 392 prod-qa re-run [prek r359-prod-qa-retry.sh 392] + petinštirideseta era preverba r347–r391 [45 registrov, ≥183 = 182 + 1; era-clone.py --src-round 391 --dst-round 392 --expected-total 183 + 18 spec-ov (12 zamrznjenih + 6 AR katalog — LEKCIJA R392 (1)); ERA_BESODE 45 PETINŠTIRIDESIJNA GLASNO]; pričakuj 183/183 ŽIVO [r392 šivni needle razrešen ob TEM pushu] + val 69 POST-deploy verifikacija [1 šivni needle r392.tsv ×2; mounted + className LOČENO; ZERO-MUTACIJA].
- R393 kandidati: 1. stil: outline mešanica focus-visible:outline-none (104 roksal) vs outline-hidden (TW v4 ui-kit) [disk triaža; v4 outline-none = outline-style:none — preveriti funkcionalno/vizualno]; 2. stil: duration-* konsistenca Card hover družina [logistics duration-150 vs material brez — privzeto 150ms identično → verjetno iskren zaklep]; 3. e2e-lib dedup 23. val [po kanonu]. ⭐ LEKCIJE R392: (1) zamrznjeni SERVER_PROBE_SPECS ne sledijo novim rutam — nov registr z novimi rutami zahteva NOVE spec-e V ISTI generaciji; (2) KOLIZIJA-skip era veriga: obnova generacijskega imena (chain-top+1) omogoči era-clone nad preskočeno rundo; (3) 0-v-HEAD needle = byte-unikaten — družinski precedens z istim seznamom onemogoči → konzervativna nadgradnja da unikaten šiv; (4) lastni testi imajo hrošče — nested it.each prepovedan, ternarna precedence, števci na širšem nizu korenov; (5) eslint no-require-imports — readdirSync import. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

def main():
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R392" in t:
        sys.exit("FAILOVEDANO: R392 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R391" not in t or "PRESS-SCALE DVOJNI MEHANIZEM" not in t:
        sys.exit("FAILOVEDANO: R391 handover guard ni prepoznan (worklog stale?)")
    nova = t.rstrip("\n") + "\n" + VNOS
    WL.write_text(nova, encoding="utf-8")
    print(f"OK: worklog R392 vnos pripsan ({len(VNOS)} bajtov)")

if __name__ == "__main__":
    main()
