#!/usr/bin/env python3
# r396-worklog-append.py — R396 worklog vnos (fail-closed, kanon
# r381/r383/r384/r391/r392/r394): guard = R394 vnos prisoten (tail fraza);
# idempotenten: abort če R396 ŽE obstaja.
import pathlib
import sys

REPO = pathlib.Path("/home/z/my-project")
WL = REPO / "worklog.md"

VNOS = r"""
---

Task ID: R396 (KOLIZIJA #27 preimenovanje R395→R396; njihova runda R395 [0dd9e12 — §16 SIGNATURE + DOCUMENT CHAIN, njihov r395.tsv ×3 + r395-window-scan.py 17. gen] = pristala resnica OB PUSH-PRIJAVI [fetch: cf71787..0dd9e12]; vsi moji artefakti preimenovani r395-→r396-, njihovi bajtno ohranjeni; README/worklog re-aplicirana na NJIHOVO postavitev)
Agent: Super Z (AI runda, Job 413422, tick 202610031746)
Task: R396 — prva naloga (prod-qa re-run 394 + ŠESTINŠTIRIDESIJNA era preverba r347–r392 + SEDEMINŠTIRIDESIJNA 47. era preverba r347–r393 + val 70 POST-deploy verifikacija) + MANDATORY STIL val 71 (DARK-MODE SCROLLBAR PARITETA — CSS-nivojska) + FEATURE DEVETI STRAŽAR tema-pariteta disciplina + register r396.tsv (PRVI CSS-nivojski needle) + window-scan 18. generacija + qa-round žeteva + .css + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD cf71787 (R394) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R394 vnos = handover (prebran celoten; njegova 'R396 prva naloga' + 'R396 kandidati' izvedeni dobesedno). ⚠️ STALE-SUMMARY opomba #45: seja je podedovala R370 plan iz povzetka — disk resnica = R394 (24+ rund naprej; kanon KOLIZIJE #4/R323) — worklog na disku = edina resnica. Okolje: embedded PG :5433 ŽIVO, vseh 30 migracij applied (20261009080000_r393_engineering_rules vključno), .env DATABASE_URL OBIŠČEN s strani lupine (shell env DATABASE_URL=file:…custom.db preglasi .env — LEKCIJA R392 potrjena; eksplicitni URL, .env NI mutiran).
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 394` — **ZELEN ob poskusu 1** (27. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **ŠESTINŠTIRIDESIJNA era preverba** (46.) — disk resnica prešteta IZ registrov PRED generacijo (LEKCIJA R394 (1) upoštevana): r347–r392 = **185** (r392.tsv 1 need_static) — handover aritmetika tokrat TOČNA; ERA_BESODE GLASNO razširjena na 46 + 47 [ŠESTINŠTIRIDESIJNA / SEDEMINŠTIRIDESIJNA; era-clone.py fail-closed guard bi brez tega ZAVRNIL]; generiranje prek era-clone.py --src-round 392 --dst-round 393 --expected-total 185 --dst-label "R392 val 69" --dst-chain-seg "IN r391.tsv val 68 ×2 IN r392.tsv val 69 ×2 na" + 18 spec-ov; COMPANION r393-era-ruta-map.py avtomatsko [201 needlejev, 58 rut]; **EXIT=0 ×2** (determinizem) — **185/185 ŽIVO**; must_miss ×46 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 69 deploy POTRJEN v celoti**.
- PRVA NALOGA (C): **SEDEMINŠTIRIDESIJNA (47.) era preverba** — disk resnica r347–r393 = **188** = 185 + 3 (njihov r393.tsv engineering needleji); ⭐ **LEKCIJA R396 (1) — zamrznjeni SERVER_PROBE_SPECS NE sledijo novim registrskim plastem (LEKCIJA R392 (1) ponovitev, 2. potrditev)**: 1. tek **EXIT=2** — 38 statičnih MISS [27 razrešenih SERVER-REZOLUCIJO + 8 hash]; **3 r393 engineering needleji NERAZREŠLJIVI** — so SERVER-side (.next/server/chunks/_19dadc72/_25cc2ae1/_cae6cba8), loop zahteva spec, kateri register nosi needle → **noben od 18 spec-ov ne kazalec na REG_AU (AU = 393)**; prod poti ŽIVE (GET /api/engineering-rules → 401, versions/000 → 401 — fail-closed); REŠITEV: regeneracija z **19. spec-om `AU|/api/engineering-rules|401`** [era-clone fail-closed tudi ujel moj poskus lažnega REG_ES — regvar validacija deluje]; era-clone.py --src-round 393 --dst-round 394 --expected-total 188 --dst-label "R393 engineering rules (R171)" --dst-chain-seg "IN r391.tsv val 68 ×2 IN r392.tsv val 69 ×2 IN r393.tsv ×3 na"; COMPANION r394-era-ruta-map.py EXIT=0; **EXIT=0 ×2 BAJTNATO** (determinizem) — **188/188 ŽIVO** [30 server resolucij — njihovi engineering ×3 ŽIVO prek .next/server + prod 401]; must_miss ×47 čisto; konvencija: harvest r{N} pokriva r347–r{N-1}.
- PRVA NALOGA (D): **val 70 POST-deploy verifikacija** `r396-qa-spot.sh` (spot-r185/33; ZERO-MUTACIJA — samo sonde + dispatch; LEKCIJA R365 (4) mounted + className LOČENO): build-layer dokaz NEODVISNO od DOM — **val 70 šivni needle ŽIVO na prod CDN v 9/60 čankov** (grep /tmp/r339-chunkurls.txt iz 27. prod-qa teka; era need_static pokrit v 48. preverbi r347–r394 ≥189 [R397 prva naloga]); MONTIRANO DOM: measurements **fvHiddenMounted 38 + šivni needle (fv_hidden+ring-2+ring-navy/40) 36 + brezNadomestila 0 + stariOutlineNoneOstanek 0**; inventory **34 + 32**; sonde navy **23/23/0** + red **0**; kolektor **0**.
- agent-browser QA + temni pregled `r396-visual-sweep.sh`: dark mode deluje (kalkulator/inventory temni); ⭐ LEKCIJA R396 (4): `agent-browser open localhost:3000` UBIDE sejo (v peskovniku ni dev strežnika — e2e-lib EB_BASE = produ; isti-origin location.reload() edini pravilen preklop teme); viz/product-home izpran naslov v temni temi = **dokumentirana R167 meja** (src/components/viz/** = ZAŠČITENO jedro, namerno svetlo — NIČ).
- MANDATORY STIL **val 71 — DARK-MODE SCROLLBAR PARITETA**: sveža triaža `r396-triaza.py` + `r396-triaza2.py` — **10 družin VSE iskreni zaklepi** (K1 duration-* heterogenost = semantična [ambient 500/1000 vs interaktivna 150/200] + ui-kit FROZEN; K2 goli outline-none vnosna polja ×16 = iskrena meja R394; K3 ring-offset dark vrzel = **0** — R168 remap `.dark * { --tw-ring-offset-color: var(--background) }` že rešuje vseh 282; K4 hover:scale brez pokritosti = **0** po r392; K5 focus ring navy brez ink parice ×218 = FROZEN kanon val 52/70 [navy/40 v OBEH temah]; K6 fence-3d hover-border = **R166 dokumentirana izjema** [namerno svetla 3D platno — navy hover na belem kartici je PRAVILNO]; K7 navy gumbi ×84 = oblikovna odločitev [belo besedilo, kontrast v obeh temah]; K8 text-navy ×19 = blagovne znamke/amer/papir; K9 ring-2 brez offseta ×5 = katalog vnos ×1 [FROZEN izjema #2 val 60 — besedilna polja bajtno] + platno overlay ×4 [namerno tesen ring]; K10 offset brez barve ×282 = R168 remap); hover-SNAP 203 = lažno pozitivni [Button base transition-colors dednost — kanon val 69: edina 2 prava senčna SNAP-a že popravljena]; active:scale heterogenost = ZAMRZNJENO R392; text-[11px] ×427 = brez žetona [text-2xs = 10px ≠ 11px — migracija bi SPREMENILA izris]; bg-white papirnate površine ×21 = namerni „papir" [measurement-studio dokumenti/signature podpis/na slikah]; ⭐ **REALNA družina: scrollbar temna pariteta** — `.scrollbar-thin` **×33 rab** nosi SAMO svetli palec #cbd5e1 v OBEH temah; temna govorica družine ŽE obstaja kot `.scrollbar-thin-dark` (#475569 + hover #334155) — **definirana, a NIKOLI povezana (×0 rab, mrtvi CSS)**; `r396-val71-apply.py` fail-closed + IDEMPOTENTEN [+15 vrstic v globals.css @layer utilities: `.dark .scrollbar-thin::-webkit-scrollbar-thumb { #475569 }` + `:hover { #334155 }` — VREDNOSTI IZ ISTIH ŽETONOV, nič izuma; svetla tema bajtno nespremenjena; 1. tek abort: POST-check substrinški hrošč — `:hover` nosi bazični selector kot PREDPONO → števec 2 ≠ 1; popravljen z zaključnim ' {' — ⭐ LEKCIJA R396 (2): POST-checki morajo šteti z BESEDNIMI MEJAMI; 3. tek abort — idempotenca DOKAZANA]; **CSS-nivojska sprememba = 0 className žetonov → 0 pinov na src**; `r396-stil-val71.test.ts` **×5 ZELENO** [(A) PARITETA točno ×1 + vrednosti, (B) CENZUS svetla bajtno + track transparent, (C) družina -dark ostane, (D) raba ≥30, (E) meje + komentar val 71].
- **FEATURE DEVETI STRAŽAR — tema-pariteta disciplina utilities sloja**: `r396-tema-pariteta.test.ts` **×7 ZELENO** [(A) val 71 anchorji (točno ×1 + vrednosti + svetla bajtno), (B) **HEX CENZUS: utilities sloj nosi TOČNO 7 dokumentiranih vrednosti** (#cbd5e1/#475569/#334155/#1d2b3e/#2a4a7f/#f59e0b/#fbbf24) — „0 novih hex" kanon rund je zdaj STOJIČI stražar [+ komentarje-izključujoč parser, nauček R163], (C) gradient-text ogledalo (svetli navy ↔ .dark amber), (D) card-hover + glass-card .dark counterparta zamrznjena, (E) družina živa ≥30 + -dark vir vrednosti ostane, (F) kompilirani CSS dokaz — **ORDER-DEPENDENCA iskreno rešena**: polna vitest faza teče PRED svežim buildom → zastarel build = iskren SKIP; po svežem buildu re-run dokazal POPOLNOSTI (#475569 v build CSS), (G) reduced-motion in-file kanon zamrznjen (roksalShake + tilePopIn) — kontinuirane zanke (badge-pulse-breathe/pulse-soft/bounce-subtle/shimmer) = dokumentirana P2 meja; 2 lastna testna hrošča ujeta + popravljena PRED FULL tekom [(F) zastarel-build false-fail + (G) spremenljivka blok→steviloGuardov] — LEKCIJA R392 (4); 1 eslint no-require-imports (require → statSync/readdirSync import) — LEKCIJA R392 (5)]. KOMPLET DEVET varuhov: r385 + r386 + r387 + r388 + r389 + r391 + r392 + r394 + r395.
- REGISTER `scripts/qa-needles/r396.tsv` [1 need_static **ŠIVNI** needle — **PRVI CSS-nivojski needle v verigi**: `.dark .scrollbar-thin::-webkit-scrollbar-thumb{background-color:#475569}` minificirani kompilirani selector, ×1 v build CSS chunku (dc370602df67e189.css); 0 v HEAD 0dd9e12; :hover varianta = byte-drugačna (brez lažnega podniza); TODO-R396] prek `r396-register-write.py` fail-closed; era veriga (KOLIZIJA #27): 48. preverba (r347–r394) ≥189; 49. (r347–r395) ≥192 = 189 + njihovih 3; TA needle pokrit v 50. preverbi (r347–r396) ≥193 [R397].
- ⭐ **LEKCIJA R396 (3) — CSS-nivojski needleji živijo v minificiranih čankih**: r396-window-scan.py **18. generacija** [REG_DO 395] — DEL 2 dobi **BUILD-CSS fallback** (src preverba ostane PRVA resnica; build CSS = druga dovoljena plast — r395 needle ŽIVO v build CSS, preostalih 202 src-živih NESPREMENJENI): **304 okenskih regexov 0 preozkih + 203 needle pinov 0 mrtvih + 150 slice-oknen + 0 vrstičnih odstopanj — EXIT=0**; IN `qa-round.sh` žeteva razširjena `\( -name '*.js' -o -name '*.css' \)` (aktiven runner R340-konsolidacija, NI zamrznjena zgodovina — dokumentirano v obeh mestih [find + dry-run opis]; 1. tek brez .css = iskren MISS → popravek → R396 needleji FAIL=0).
- README: števec 5828/387 → **5840/389** [+12/+2: stil val 71 ×5 + DEVETI STRAŽAR ×7] + R396 bullet NAD R394 bulletom (bajtno ohranjen) prek `r396-readme-update.py` fail-closed (idempotenca potrjena).
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL; 1 lasten error ujet + popravljen) · vitest **5840/5840 (389) FULL GREEN** [njihova baza 5828/387 + mojih +12/+2; 147.7 s] · build svež rm -rf .next EXIT=0 [PRVI — pred registerjem, ker šivni needle rabi minificirani CSS] · qa-round.sh 395 needles EXIT=0 [r396.tsv 1 ŽIVO ×1 v .css + UNION r340–r395 + veriga r339→…→R227 — 1074 OK, 113×FAIL=0] · smoke EXIT=0 [standalone :3100: health ok + ovojnice 400 + val-3 meja ŽIVO] · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r393-era-harvest EXIT=0 ×2 [46th — 185/185] · r394-era-harvest EXIT=0 ×2 bajtno [47th — 188/188] · r396-window-scan EXIT=0 [18. gen] · r359-prod-qa-retry 394 ZELEN poskus 1 · guard (F) re-run po buildu — POPOLNOST dokazana · leak-check čist [ghp_ ×0].
- NOVO: scripts/qa-needles/r396.tsv + skripte [r393-era-harvest.sh (46th) + r394-era-harvest.sh (47th) + COMPANION r393-era-ruta-map.py + r394-era-ruta-map.py, r396-qa-spot.sh, r396-visual-sweep.sh, r396-triaza.py, r396-triaza2.py, r396-val71-apply.py, r396-window-scan.py (18. gen), r396-register-write.py, r396-readme-update.py, r396-worklog-append.py] + r396-stil-val71.test.ts [×5] + r396-tema-pariteta.test.ts [×7 — FEATURE]; UREJENO: src/app/globals.css [val 71 +15 vrstic], era-clone.py [ERA_BESODE 46+47], qa-round.sh [žeteva + .css], README.
- Kontrakt NIČ (/api/sync + /api/catalog* + /api/engineering-rules probe = samo fail-closed 401 branje, brez pisanja); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 71 = globals.css utilities-only]; viz/** ZAŠČITENO jedro nič (kanon R167); OgrajaVizija nič; 0 novih hex [utilities hex cenzus 7 dokumentiranih — zdaj STOJIČI stražar (B)]; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (87. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R397 prva naloga = qa-round.sh 396 prod-qa re-run [prek r359-prod-qa-retry.sh 396] + **OSEMINŠTIRIDESIJNA (48.) era preverba r347–r394** [48 registrov, ≥189 = 188 + 1 (r394.tsv val 70 šivni ×64); era-clone.py --src-round 394 --dst-round 395 --expected-total 189 + 19 spec-ov (12 + 6 AR + AU); ERA_BESODE 48 OSEMINŠTIRIDESIJNA GLASNO] + NEDEVETA (49.) era preverba r347–r395 [49 registrov, ≥192 = 189 + 3 njihovih r395 document-chain needlejev; era-clone.py --src-round 395 --dst-round 396; ERA_BESODE 49 NEDEVETA GLASNO]; pričakuj 192/192 ŽIVO [val 70 needle razrešen ob R394 pushu — prod CDN 9/60 že dokazano v R396 (D); njihovi document-chain ×3 razrešeni ob njihovem pushu 0dd9e12] + val 71 POST-deploy verifikacija [PRVI CSS-nivojski needle r396.tsv ×1 v .css čanku — qa-round žeteva že nosi .css; mounted dokaz: dark-mode screenshot palec #475569 — ZERO-MUTACIJA].
- R397 kandidati: 1. stil: kontinuirane animacije reduced-motion pokritost [badge-pulse-breathe/pulse-soft/bounce-subtle/shimmer — P2 meja iz (G); @media (prefers-reduced-motion: reduce) bloki ×4 — realna a11y družina]; 2. stil: roksal-catalog iskalni vnos focus-visible:ring-offset-2 [×1 — FROZEN izjema #2 val 60 zahteva EVOLVED pin r381 (D) — previdno]; 3. e2e-lib dedup [po kanonu — ni novih ×3]. ⭐ LEKCIJE R396: (1) zamrznjeni SERVER_PROBE_SPECS ne sledijo NOVIM REGISTROM — nov registr s server-side needleji zahteva NOV spec (REGVAR|ruta|status) V ISTI generaciji [2. potrditev LEKCIJE R392 (1); era-clone regvar validacija ujela lažni REG_ES]; (2) POST-checki štejejo z BESEDNIMI MEJAMI — ':hover'/'[id]' nosijo bazo kot predpono podniza (števec lažno ×2); (3) CSS-nivojski needle = minificiran kompilirani selector — src pretty ≠ minificirano; window-scan DEL 2 dobi build-CSS fallback, qa-round žeteva + '*.css'; (4) agent-browser open na localhost v peskovniku UBIDE sejo — samo isti-origin reload; (5) triaža PRED val: 10 družin lahko VSE zaklepajo iskreno — browser dark-sweep najde realno družino, ki statična analiza ne vidi (scrollbar palec); (6) štetje need_static IZ registrov (disk resnica) PRED era-clone generacijo — tokrat handover aritmetika točna, vendar disk preverba ostane kanon; (7) .next build pred register-write, če je needle CSS-nivojski [minificirani šiv]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

def main():
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R396" in t:
        sys.exit("FAILOVEDANO: R396 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R395" not in t or "SIGNATURE + DOCUMENT CHAIN" not in t:
        sys.exit("FAILOVEDANO: njihov R395 (KOLIZIJA #27) handover guard ni prepoznan (worklog stale?)")
    if not t.endswith("\n"):
        t += "\n"
    nova = t + VNOS
    WL.write_text(nova, encoding="utf-8")
    print(f"OK: worklog R396 vnos pripsan ({len(VNOS)} bajtov)")

if __name__ == "__main__":
    main()
