#!/usr/bin/env python3
# r397-worklog-append.py — R397 worklog vnos (fail-closed, kanon
# r381/r383/r384/r391/r392/r394/r396): guard = R396 vnos prisoten (tail
# fraza "AGENT STARTUP RULE: razvoj > QA]."); idempotenten: abort če R397
# ŽE obstaja.
import pathlib
import sys

REPO = pathlib.Path("/home/z/my-project")
WL = REPO / "worklog.md"

VNOS = r"""
---

Task ID: R397 (KOLIZIJE: brez — fetch-first origin/main == HEAD 9cf275d (R396) ob startu; delovno drevo čisto; worklog R396 vnos = handover, prebran celoten, 'R397 prva naloga' + 'R397 kandidati' izvedeni dobesedno [kandidat 1 = val 72; kandidat 2 (katalog focus-offset) = NE — FROZEN izjema #2 zahteva EVOLVED pin, previdnost kanon; kandidat 3 (e2e-lib dedup) = ISKRENO IZPUŠČEN, po kanonu ni novih ×3]. ⚠️ STALE-SUMMARY opomba #46: seja je podedovala R370 plan iz povzetka — disk resnica = R396 (26+ rund naprej; kanon KOLIZIJE #4/R323) — worklog na disku = edina resnica. Okolje: embedded PG :5433 ŽIVO, 32/32 migracij applied [30 + njihovi 2 document_chain]; shell env DATABASE_URL=file:… preglasi .env — eksplicitni URL, .env NI mutiran.)
Agent: Super Z (AI runda, Job 413422, tick 202610031930)
Task: R397 — prva naloga (prod-qa re-run 396 + OSEMINŠTIRIDESIJNA 48. era preverba r347–r394 + DEVETINŠTIRIDESIJNA 49. era preverba r347–r395 + val 71 POST-deploy verifikacija + PETDESIJNA 50. era preverba r347–r396) + MANDATORY STIL val 72 (REDUCED-MOTION PARITETA — CSS-nivojska) + FEATURE DESETI STRAŽAR gibanje-pariteta disciplina + register r397.tsv (zliti selector list šivni) + window-scan 19. generacija + worklog + push

Work Log:
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 396` — **ZELEN ob poskusu 1** (28. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **OSEMINŠTIRIDESIJNA era preverba** (48.) — disk resnica prešteta IZ registrov PRED generacijo (LEKCIJA R394 (1) / R396 (6) kanon): r347–r394 = **189** (r394.tsv val 70 šivni ×1) — handover aritmetika TOČNA; ERA_BESODE GLASNO razširjena na 48 + 49 + 50 [OSEMINŠTIRIDESIJNA / DEVETINŠTIRIDESIJNA / PETDESIJNA; era-clone.py fail-closed guard bi brez tega ZAVRNIL]; generiranje prek era-clone.py --src-round 394 --dst-round 395 --expected-total 189 --dst-label "R394 val 70" --dst-chain-seg "IN r393.tsv ×3 IN r394.tsv val 70 šivni ×64 na" + 19 spec-ov (12 + 6 AR + AU); COMPANION r395-era-ruta-map.py avtomatsko; **EXIT=0 ×2** (determinizem) — **189/189 ŽIVO**; must_miss ×48 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 70 deploy POTRJEN v celoti**.
- PRVA NALOGA (C): **DEVETINŠTIRIDESIJNA (49.) era preverba** — disk resnica r347–r395 = **192** = 189 + 3 (njihov r395 document-chain needleji); ⭐ **LEKCIJA R397 (1) — spec regvar MORA kazati na registr, ki NOSI needle (3. potrditev LEKCIJE R392 (1)/R396 (1))**: 1. tek **EXIT=2** — 41 statičnih MISS [38 hash-rezolucija]; 3 r395 needleji NERAZREŠLJIVI — SERVER-side (.next/server/chunks node_modules templates + root-of-the-server); moj 1. poskus spec `AV|…` = NAPAČEN register (AV = reg_var(394) = r394.tsv, NE r395!) → še vedno EXIT=2 [regvar validacija generatorja preveri samo OBSTOJ var, ne semantiko — nosilec preveri z grep -qF needle REG_DATOTEKA]; **pravilno `AW|/api/quotes/000/pdf|401`** (20. spec; GET prod probe → 401 fail-closed, deterministično; vsi 3 needleji ŽIVO v .next/server) → era-clone.py --src-round 395 --dst-round 396 --expected-total 192 --dst-label "R395 signature + document chain (R172)" [auto-label bi lažno izračunal "val 71" — r394 nosi val, r395 je poslovna runda; R172 konvencija kot R171] --dst-chain-seg "IN r394.tsv val 70 šivni ×64 IN r395.tsv ×3 na"; COMPANION r396-era-ruta-map.py; **EXIT=0 ×2 BAJTNATO** — **192/192 ŽIVO** [41 resolucij — njihovi document-chain ×3 ŽIVO prek .next/server + prod /api/quotes/000/pdf 401]; must_miss ×49 čisto.
- PRVA NALOGA (D): **val 71 POST-deploy verifikacija** (ZERO-MUTACIJA — samo sonde + screenshot): **prod CDN needle ×1** — .css URL-ji iz živega prod HTML (login), curl grep: `.dark .scrollbar-thin::-webkit-scrollbar-thumb{background-color:#475569}` **×1 v 5fc36b66bd1b4dfb.css** (241 KB glavni čank) + `:hover{background-color:#334155}` ×1; prvi čank (34d933785a17edf3.css, 3.6 KB) čist — registr točen; **MONTIRANI dokaz** `r397-val71-mounted.sh`: ⭐ **LEKCIJA R397 (4) — CSSOM probe MORA rekurzirati v layer/media bloke**: pravilo val 71 živi V `@layer utilities` (CSSLayerBlockRule) — 1. probe z vrhovno iteracijo document.styleSheets = **lažno 0** (selectorText je samo na listih!); rekurzivni walk: **2 pravili pod root > utilities** — `.dark .scrollbar-thin::-webkit-scrollbar-thumb { background-color: rgb(71, 85, 105) }` (= #475569; ::-webkit-scrollbar-thumb NI berljiv prek getComputedStyle — pravilo-v-styleSheets + prod CDN bajti + screenshot = popolna veriga, brez izuma); dark QA sweep `r397-visual-sweep.sh` (htmlClass=dark, bodyBg rgb(15,23,36) = slate-900; kalkulator/inventar temni — LEKCIJA R396 (4) upoštevana: samo isti-origin reload).
- PRVA NALOGA (E): **PETDESIJNA (50.) era preverba** — disk resnica r347–r396 = **193** = 192 + 1 (r396 val 71 CSS needle); era-clone.py --src-round 396 --dst-round 397 --expected-total 193 --dst-label "R396 val 71" --dst-chain-seg "IN r395.tsv ×3 IN r396.tsv val 71 CSS ×1 na" (specs dedovani ×20); ⭐ **LEKCIJA R397 (5) — prod .css URL-i MORAJA biti ABSOLUTNI v žetvenem seznamu**: qa-harvest.sh curla URL DIREKTNO (brez BASE-prepend) — relativni `/_next/...css` padejo po 3 retryih (OPOMBA vrstica, žetev 60/62); popravljeno na absolutni https://… (živ prod HTML, GLASNO; backup /tmp/r339-chunkurls.txt.bak-r397; žetev 62/62) → **EXIT=0 ×2** — **193/193 ŽIVO** [val 71 needle ŽIVO direktno v žeti čank_061 = 5fc36b66….css]; must_miss ×50 čisto; COMPANION r397-era-ruta-map.py.
- MANDATORY STIL **val 72 — REDUCED-MOTION PARITETA** (kandidat 1 iz handoverja — P2 meja iz R396 (G)): triaža PRED val (LEKCIJA R396 (5)): **4 kontinuirane (infinite) zanke BREZ pokritosti** — `.badge-pulse` (badge-pulse-breathe 2s infinite; ×1 raba dashboard-tab) + `.shine-effect::after` (shine 3s infinite; ×1 top-bar) + `.animate-pulse-soft` (pulse-soft 2s infinite; ×2) + `.shimmer` (shimmer 1.5s infinite; ×0 TSX rab — slovar) + `.animate-bounce-subtle` (enojni 0.3s izski; ×0 rab — pokrit za popolnost družine; handover ga je navedel med kontinuiranimi — disk resnica: enojni, GLASNO dokumentirano); obstoječa pokritost: roksalShake + tilePopIn guarda ŽE (r396 (G) kanon); enojni fadeInUp/slideInRight = iskreno dokumentirana meja (WCAG 2.3.3 ne zahteva; forwards končno stanje identično); `globals.css` **+26 vrstic** — EN `@media (prefers-reduced-motion: reduce)` blok z 5× `animation: none` (skupaj 3 media guardi); **0 className žetonov → 0 pinov na src; 0 novih hex** — vrednosti se ne dotikamo, samo ustavimo gibanje; svetla/temna tema bajtno.
- **FEATURE DESETI STRAŽAR — gibanje-pariteta disciplina**: `r397-gibanje-pariteta.test.ts` **×7 ZELENO** [(A) val 72 anchorji — vsi 5 selektorjev točno ×1 znotraj val 72 bloka + skupaj 3 media guardi, (B) besedišče/keyframes + infinite govorica ostane (ustavimo gibanje, ne brišemo slovarja), (C) HEX CENZUS 7 dokumentiranih vrednosti — stoječi stražar r396 prevzet, (D) enojni in-file kanon (shake/tile) bajtno ×1, (E) **disk resnica rabe** — badge-pulse ×1 / shine-effect ×1 / pulse-soft ×2 / shimmer ×0 / bounce-subtle ×0 (slovarska para, iskreno — nič tihega), (F) kompilirani CSS dokaz — **LEKCIJA R397 (2): mtime-staleness** (BUILD_ID < globals.css = zastarel build → iskren SKIP; val 72 NI edini vir reduced-motion guardov — prisotnost 'prefers-reduced-motion' NE razloči), (G) med-stražarski roki val 71 × val 72 (scrollbar pariteta ostane ×1 + #475569); 2 lastna testna hrošča ujeta + popravljena PRED FULL tekom [(E) napačne pragove iz rg-cenzusa, ki je štel globals.css samega + (F) prisotnost-guard false-fail na zastarelem buildu] — LEKCIJA R392 (4)]. KOMPLET DESET varuhov: r385 + r386 + r387 + r388 + r389 + r391 + r392 + r394 + r395 + r396 + r397.
- REGISTER `scripts/qa-needles/r397.tsv` [1 need_static **ŠIVNI** needle — ⭐ **LEKCIJA R397 (3): lightningcss ZLIJE media-guard selektorje v ENO pravilo**: src pretty 5 ločenih blokov → build zliti selector list `.badge-pulse,.shine-effect:after,.animate-pulse-soft,.shimmer,.animate-bounce-subtle{animation:none}` (pseudo-element ::after normaliziran v :after; nadgradnja LEKCIJE R396 (3)) — ×1 v build CSS chunku (698a1900a928a5e6.css); 0 v HEAD 9cf275d (git grep); 0 v src; TODO-R397] prek `r397-register-write.py` fail-closed [build PREJ pred register-write — LEKCIJA R396 (7)]; era veriga: 48. (r347–r394) 189/189; 49. (r347–r395) 192/192; 50. (r347–r396) 193/193 [TA runda]; TA needle pokrit v 51. preverbi (r347–r397) ≥194 [R398].
- `r397-window-scan.py` **19. generacija** [naslednik r396-window-scan.py, ki ga NIKOLI ne mutira; REG_DO 397; val 72 = globals-only → TARGETS nespremenjeni, 0 novih src pinov; DEL 2 build-CSS fallback kanon]: **EXIT=0** (0 preozkih okenskih + 0 mrtvih pinov + 150 slice-oknen + 0 vrstičnih odstopanj — disk resnica, brez mutacij).
- README: števec 5857/390 → **5864/391** [+7/+1: val 72 (del r397-gibanje-pariteta ×7) + DESETI STRAŽAR ×7] + R397 bullet NAD R396 bulletom (bajtno ohranjen) + R398 naloga/kandidati prek `r397-readme-update.py` fail-closed (idempotenca potrjena — 2. tek OPOMBA). ⚠️ OPOMBA o knjigovodstvu: R396 worklog zapis je nosil "vitest 5840/5840 (389)", medtem ko README/disk resnica = 5857/390 — moja meritev baze = disk (kanon R396 (6)); odmik GLASNO dokumentiran, nič tihega.
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL) · vitest **5864/5864 (391) FULL GREEN** [baza 5857/390 + mojih +7/+1; 148.7 s] · build svež rm -rf .next EXIT=0 [PRVI — pred registerjem, LEKCIJA R396 (7)] · qa-round.sh 397 needles EXIT=0 [r397.tsv 1 ŽIVO v .css + UNION r340–r397 + veriga r339→…→R227] · smoke EXIT=0 [standalone :3100: health ok + ovojnice 400 + val-3 meja ŽIVO] · e2e EXIT=0 [r339-e2e-browser fallback — regresijska pokritost, iskren banner; ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r395-era-harvest EXIT=0 ×2 [48th — 189/189] · r396-era-harvest EXIT=0 ×2 bajtno [49th — 192/192] · r397-era-harvest EXIT=0 ×2 bajtno [50th — 193/193] · r397-window-scan EXIT=0 [19. gen] · r359-prod-qa-retry 396 ZELEN poskus 1 · guard re-run po buildu — 19/19 ZELENO, (F) POPOLNOST dokazana · leak-check čist [ghp_ ×0].
- NOVO: scripts/qa-needles/r397.tsv + skripte [r395-era-harvest.sh (48th) + r396-era-harvest.sh (49th) + r397-era-harvest.sh (50th) + COMPANION r395/r396/r397-era-ruta-map.py, r397-visual-sweep.sh, r397-val71-mounted.sh, r397-window-scan.py (19. gen), r397-register-write.py, r397-readme-update.py, r397-worklog-append.py] + r397-gibanje-pariteta.test.ts [×7 — FEATURE]; UREJENO: src/app/globals.css [val 72 +26 vrstic], era-clone.py [ERA_BESODE 48+49+50], README.
- Kontrakt NIČ (/api/quotes/000/pdf probe = samo fail-closed 401 branje, brez pisanja); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 72 = globals.css-only]; viz/** ZAŠČITENO jedro nič (kanon R167); OgrajaVizija nič; 0 novih hex [utilities hex cenzus 7 dokumentiranih — stoječi stražar (C)]; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (88. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R398 prva naloga = qa-round.sh 397 prod-qa re-run [prek r359-prod-qa-retry.sh 397] + **ENAINPETDESETA (51.) era preverba r347–r397** [51 registrov, ≥194 = 193 + 1 (r397.tsv val 72 zliti šivni); era-clone.py --src-round 397 --dst-round 398 --expected-total 194; ERA_BESODE 51 ENAINPETDESETA GLASNO; pričakuj ŽIVO ob pushu — val 72 needle je CSS-nivojski, razreši se ob R397 deployu; prod .css URL-i ostanejo ABSOLUTNI v žetvi — LEKCIJA R397 (5)] + val 72 POST-deploy verifikacija [CSS needle v .css čanku + MONTIRANI dokaz: rekurzivni CSSOM walk `.badge-pulse` + `animation:none` pod prefers-reduced-motion — vzorec r397-val71-mounted.sh; ZERO-MUTACIJA].
- R398 kandidati: 1. stil: enojni vstopni animaciji fadeInUp/slideInRight — reduced-motion odločitev za 100 % pokritost gibanja [trenutno iskreno dokumentirana meja v (A)/(B); WCAG 2.3.3 ne zahteva; previdno]; 2. slovarska para shimmer/bounce-subtle (×0 klicnih mest): uporabiti v UI (loading skeleti) ALI iskreno označiti kot mrtvi CSS — odločitev z lastnikom; 3. e2e-lib dedup [po kanonu — ni novih ×3]. ⭐ LEKCIJE R397: (1) spec regvar MORA kazati na registr, ki NOSI needle — regvar validacija generatorja preveri samo OBSTOJ var, ne semantiko [AV=r394 ≠ AW=r395; 3. potrditev LEKCIJE R392/R396 (1)]; (2) mtime-staleness za kompilirane-CSS guard teste, ko pretekli guardi ŽE obstajajo [prisotnost 'prefers-reduced-motion' NE razloči zastarele gradnje]; (3) lightningcss ZLIJE media-guard selektorje v ENO pravilo — needle = zliti selector list, ::after → :after normalizacija [nadgradnja LEKCIJE R396 (3)]; (4) CSSOM probe MORA rekurzirati v layer/media bloke — @layer utilities = CSSLayerBlockRule, vrhovna iteracija = lažno 0; (5) prod .css URL-i ABSOLUTNI v žetvenem seznamu — qa-harvest curla direktno brez BASE-prepend, relativni padejo po 3 retryih (OPOMBA vrstica); (6) handover žeton "NEDEVETA" za 49. NE sledi vzorcu ERA_BESODE (…INŠTIRIDESIJNA) — vzorcem zvesta oblika DEVETINŠTIRIDESIJNA, odmik GLASNO. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""

def main():
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R397" in t:
        sys.exit("FAILOVEDANO: R397 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R396" not in t:
        sys.exit("FAILOVEDANO: R396 handover guard ni prepoznan (worklog stale?)")
    tail = "AGENT STARTUP RULE: razvoj > QA]."
    if not t.rstrip().endswith(tail):
        sys.exit(f"FAILOVEDANO: worklog rep ni R396 tail (guard: ...{tail!r})")
    if not t.endswith("\n"):
        t += "\n"
    nova = t + VNOS
    WL.write_text(nova, encoding="utf-8")
    print(f"OK: worklog R397 vnos pripsan ({len(VNOS)} bajtov)")

if __name__ == "__main__":
    main()
