#!/usr/bin/env python3
# r398-worklog-append.py — R398 worklog vnos (fail-closed, kanon
# r381/r383/r384/r391/r392/r394/r396/r397): guard = R397 vnos prisoten
# (tail fraza "AGENT STARTUP RULE: razvoj > QA]."); idempotenten: abort
# če R398 ŽE obstaja.
import pathlib
import sys

REPO = pathlib.Path("/home/z/my-project")
WL = REPO / "worklog.md"

VNOS = r"""
---

Task ID: R398 (KOLIZIJE: brez — fetch-first origin/main == HEAD d8dc884 (R397) ob startu; delovno drevo čisto; worklog R397 vnos = handover, prebran celoten, 'R398 prva naloga' + 'R398 kandidati' izvedeni dobesedno [kandidat 1 = val 73 izveden; kandidat 2 (slovarska para shimmer/bounce-subtle uporaba) = ODLOŽENO — odločitev z lastnikom, GLASNO dokumentirano; kandidat 3 (e2e-lib dedup) = po kanonu ni novih ×3]. ⚠️ STALE-SUMMARY opomba #47: seja je podedovala R370 plan iz povzetka — disk resnica = R397 (27+ rund naprej; kanon KOLIZIJE #4/R323) — worklog na disku = edina resnica. Okolje: embedded PG :5433 ŽIVO, 32/32 migracij applied; shell env DATABASE_URL=file:… preglasi .env — eksplicitni URL, .env NI mutiran.)
Agent: Super Z (AI runda, Job 413422, tick 202610032016)
Task: R398 — prva naloga (prod-qa re-run 397 + ENAINPETDESETA 51. era preverba r347–r397 + val 72 POST-deploy verifikacija) + MANDATORY STIL val 73 (VSTOPNE ANIMACIJE reduced-motion zaključek — CSS-nivojska) + FEATURE ENAJSTI STRAŽAR gibanje-pariteta zaključek + register r398.tsv (zliti vstopni guard šivni) + window-scan 20. generacija + worklog + push

Work Log:
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 397` — **ZELEN ob poskusu 1** (29. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA).
- PRVA NALOGA (B): **ENAINPETDESETA era preverba** (51.) — disk resnica prešteta IZ registrov PRED generaciji (LEKCIJA R394 (1) / R396 (6) kanon): r347–r397 = **194** (r397.tsv val 72 zliti šivni ×1) — handover aritmetika TOČNA; ERA_BESODE GLASNO razširjena na 51 [ENAINPETDESETA; handover vzorec zvest]; generiranje prek era-clone.py --src-round 397 --dst-round 398 --expected-total 194 + **ekspliciten --dst-chain-seg** "IN r395.tsv ×3 IN r396.tsv val 71 CSS ×1 IN r397.tsv val 72 ×1 na" [auto-vzorec 'IN r{src-1}.tsv val {src_val} ×4 na' = 0 ujem na mešanem repu — fail-closed ujel, kanon R379 (9)]; auto-label točno izračunal "R397 val 72" (×1); COMPANION r398-era-ruta-map.py avtomatsko; **1. + 2. tek EXIT=2** [⭐ LEKCIJA R398 (3): `cmd | tail; echo $?` meri EXIT od tail, NE skripte — prvi "EXIT=0" je bil lažni; popravljen merilni postopek]; diagnoza: 2 CSS needleja (val 71 + val 72) MISS — **⭐ LEKCIJA R398 (1): CSS content-hash čanki NISO deterministični čez build okolja** — lokalni build čanek 698a1900a928a5e6.css na prod CDN = **404**, prod servisira f6eba6f080fd091b.css z ISTO vsebino (needle ×1 potrjen direktno) — 'enako ime = enaka vsebina' (LEKCIJA R354) velja za .js čanke, NE za .css (Vercel build ≠ lokalni build); **⭐ LEKCIJA R398 (2): /tmp žetveni seznam je Ephemeren čez seje** — /tmp/r339-chunkurls.txt nazaj na 60 JS-only URL-jev (R397 +2 .css IZGUBLJENI); popravljeno po LEKCIJI R397 (5): +2 ABSOLUTNA .css URL-ja iz živega prod HTML (GLASNO; backup /tmp/r339-chunkurls.txt.bak-r398; žetev 62/62) → **EXIT=0 ×2 BAJTNATO** — **194/194 ŽIVO** [33 SERVER-REZOLUCIJA ŽIVO prek 20 dedovanih specov + 2 CSS needleja prek žive žetve f6eba6f080fd091b.css]; must_miss ×51 čisto; era kontrole R340/R341/R343/R345 ŽIVE → **val 70/71/72 deployi POTRJENI v celoti**.
- PRVA NALOGA (C): **val 72 POST-deploy verifikacija** (ZERO-MUTACIJA — samo sonde + screenshot): **prod CDN needle ×1** — .css URL-ji iz živega prod HTML (login), curl grep: `.badge-pulse,.shine-effect:after,.animate-pulse-soft,.shimmer,.animate-bounce-subtle{animation:none}` **×1 v f6eba6f080fd091b.css** (nov glavni čank po R397 deployu); prvi čank (34d933785a17edf3.css) čist — registr točen; **MONTIRANI dokaz** `r398-val72-mounted.sh` (vzorec r397-val71-mounted.sh; LEKCIJA R397 (4) upoštevana — rekurzivni CSSOM walk): **2 pravili z badge-pulse** — zliti guard pod `root > components > CSSMediaRule[prefers-reduced-motion: reduce]` (animation:none) + slovarski original pod `root > utilities` (2s infinite badge-pulse-breathe); media-guard pot ×1 točna; .badge-pulse element na plošči ni montiran na trenutnem pogledu (raba ×1 pogojna — disk resnica (E) ostaja; CSS pravilo MONTIRANO = bistvo prova); screenshot /tmp/r398-val72-mounted.png.
- MANDATORY STIL **val 73 — VSTOPNE ANIMACIJE reduced-motion zaključek** (kandidat 1 iz handoverja — iskreno dokumentirana meja iz R397 (A)/(B)): triaža PRED val (LEKCIJA R396 (5)): **3 vstopne animacije BREZ pokritosti** — `.animate-fade-in-up` (fadeInUp 0.3s forwards; **×55 TSX rab**) + `.slide-in-right` (slideInRight 300ms forwards; **×14 rab**) + `.stagger-children > *` (fadeInUp forwards + **STATIČNO opacity: 0**; ×0 rab — slovarska para, iskreno); ⭐ varnostna analiza: forwards končno stanje (opacity 1 / translate 0) = statično stanje → animation:none VARNENO za .animate-fade-in-up/.slide-in-right; .stagger-children > * bi ob animation:none ostal NEVIDEN (statično opacity:0) → **opacity: 1 spremljevalec OBVEZEN** (isti vzorec kot .more-tile guard); interaktivna družina (.btn-shine:hover::after btn-shine-sweep) = kanon val 69 meja — uporabniško sproženo, NI samodejnega gibanja, ostaja dokumentirana (GLASNO); `globals.css` **+25 vrstic znotraj OBSTOJEČEGA .more-tile media guard bloka** — media guardov ostane **TOČNO 3** (zamrznjen kanon r397 (A): ×1 globalno) in val 72 blok ostane bajtno nedotaknjen (5× animation:none — r397 (A) invariant); **0 className žetonov → 0 pinov na src; 0 novih hex**; svetla/temna tema bajtno.
- **FEATURE ENAJSTI STRAŽAR — gibanje-pariteta zaključek**: `r398-gibanje-zakljucek.test.ts` **×7 ZELENO** [(A) val 73 anchorji — .more-tile + 3 vstopni anchorji točno ×1 v vstopnem bloku + .stagger-children opacity:1 spremljevalec + skupaj 3 media guardi zamrznjeno, (B) **ZAKLJUČEK strukturiran dokaz** — vsaka ne-interakcijska `animation:` deklaracija izven guardov ima guard UJEMNEGA selektorja v prefers-reduced-motion bloku (≥11 nosilcev; :hover/:active = interaktivna družina val 69 dovoljeni izjemi; CSS parser: media bloki razrezani, komentarji odstranjeni), (C) HEX CENZUS 7 dokumentiranih vrednosti — stoječi stražar r396/r397 prevzet, (D) **disk resnica rabe** — animate-fade-in-up ×55 / slide-in-right ×14 / stagger-children ×0 (slovarska para, iskreno — nič tihega), (E) kompilirani CSS dokaz z mtime-staleness SKIP (LEKCIJA R397 (2)) — val 73 zliti guard ×1 + .stagger-children ×1 + **val 72 guard bajtno ×1** (era veriga se ne sme prelomiti), (F) med-stražarski roki val 71 × val 72 × val 73 (val 72 blok 5 selektorjev ×1 + 5× animation:none + scrollbar pariteta #475569), (G) interaktivna meja dokumentirana (btn-shine-sweep :hover bajtno + val 73 komentar) + keyframes slovar cel (7 keyframes); 1 lasten testni hrošč ujet + popravljen PRED FULL tekom [(E) napovedana minificirana oblika .stagger-children napačen VRSTNI RED deklaracij — disk resnica iz builda] — LEKCIJA R392 (4)]. KOMPLET ENAJST varuhov: r385 + r386 + r387 + r388 + r389 + r391 + r392 + r394 + r395 + r396 + r397 + r398.
- REGISTER `scripts/qa-needles/r398.tsv` [1 need_static **ŠIVNI** needle — zliti vstopni guard `.animate-fade-in-up,.slide-in-right{animation:none}` (lightningcss zlije sosede z enakimi deklaracijami; .stagger-children ima drugačne deklaracije → SAMOSTOJNO pravilo) — ×1 v build CSS chunku (0d49a822af6ff8bf.css); 0 v HEAD d8dc884 (git grep); 0 v src; TODO-R398] prek `r398-register-write.py` fail-closed [build PREJ pred register-write — LEKCIJA R396 (7); NOVA varovalka: preverba da val 72 needle ostane bajtno ×1 v build CSS]; ⭐ **LEKCIJA R398 (4): lightningcss SERIALIZIRA deklaracije v kanoničnem redu** (opacity PRED animation) — src `animation: none; opacity: 1` → build `{opacity:1;animation:none}`; minificirana oblika se NIKOLI ne ugiba — prebere se iz builda (nadgradnja LEKCIJE R397 (3)); era veriga: 51. (r347–r397) 194/194 [TA runda]; TA needle pokrit v 52. preverbi (r347–r398) ≥195 [R399].
- `r398-window-scan.py` **20. generacija** [naslednik r397-window-scan.py, ki ga NIKOLI ne mutira; REG_DO 398; val 73 = globals-only → TARGETS nespremenjeni, 0 novih src pinov; DEL 2 build-CSS fallback kanon]: **EXIT=0** (304 okenskih regexov 0 preozkih + 208 needle pinov 0 mrtvih + 150 slice-oknen + 0 vrstičnih odstopanj — disk resnica, brez mutacij).
- val 73 **LOKALNI MONTIRANI dokaz** `r398-val73-mounted.sh` (ZERO-MUTACIJA; prod verifikacija sledi ob R399 — kanon: CSS needle se razreši ob R398 deployu): lokalni standalone :3100 (env kanon r339-e2e: DATABASE_URL roksal_dev + SESSION_SECRET + .env/static kopiji; `setsid` pod `(…)` za preživetje čez tool klice — goli `&` ga pobere) + rekurzivni CSSOM walk: **zliti vstopni guard + .stagger-children spremljevalec ŽIVO pod media[prefers-reduced-motion]** + val 72 rok (badge-pulse ×2 pravila) — screenshot /tmp/r398-val73-mounted.png.
- README: števec 5864/391 → **5871/392** [+7/+1: val 73 (del r398-gibanje-zakljucek ×7) + ENAJSTI STRAŽAR ×7] + R398 bullet NAD R397 bulletom (bajtno ohranjen) + R399 naloga/kandidati prek `r398-readme-update.py` fail-closed (idempotenca potrjena — 2. tek OPOMBA).
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL) · vitest **5871/5871 (392) FULL GREEN** [baza 5864/391 + mojih +7/+1] · build svež rm -rf .next EXIT=0 [PRVI — pred registerjem, LEKCIJA R396 (7)] · qa-round.sh 398 needles EXIT=0 [r398.tsv 1 ŽIVO v .css + UNION r340–r398 + veriga r339→…→R227] · smoke EXIT=0 [standalone :3100: health ok + ovojnice 400 + val-3 meja ŽIVO] · e2e EXIT=0 [r339-e2e-browser fallback — regresijska pokritost, iskren banner; ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · r398-era-harvest EXIT=0 ×2 bajtno [51st — 194/194] · r398-window-scan EXIT=0 [20. gen] · r359-prod-qa-retry 397 ZELEN poskus 1 · leak-check čist [ghp_ ×0].
- NOVO: scripts/qa-needles/r398.tsv + skripte [r398-era-harvest.sh (51st) + COMPANION r398-era-ruta-map.py, r398-val72-mounted.sh, r398-val73-mounted.sh, r398-window-scan.py (20. gen), r398-register-write.py, r398-readme-update.py, r398-worklog-append.py] + r398-gibanje-zakljucek.test.ts [×7 — FEATURE]; UREJENO: src/app/globals.css [val 73 +25 vrstic], era-clone.py [ERA_BESODE 51], README.
- Kontrakt NIČ (/api/quotes/000/pdf probe = samo fail-closed 401 branje, brez pisanja); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 73 = globals.css-only]; viz/** ZAŠČITENO jedro nič (kanon R167); OgrajaVizija nič; 0 novih hex [utilities hex cenzus 7 dokumentiranih — stoječi stražar (C)]; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (89. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA.
- R399 prva naloga = qa-round.sh 398 prod-qa re-run [prek r359-prod-qa-retry.sh 398] + **DVAINPETDESETA (52.) era preverba r347–r398** [52 registrov, ≥195 = 194 + 1 (r398.tsv val 73 zliti šivni); era-clone.py --src-round 398 --dst-round 399 --expected-total 195; ERA_BESODE 52 DVAINPETDESETA GLASNO; pričakuj ŽIVO ob pushu — val 73 needle je CSS-nivojski, razreši se ob R398 deployu; ⭐ LEKCIJI R398 (1)/(2): prod .css URL-i ABSOLUTNI iz živega HTML + /tmp žetveni seznam preveri PRED tekom (ephemeren čez seje — po potrebi ponovno razširi z backupom)] + val 73 POST-deploy verifikacija [CSS needle v .css čanku + MONTIRANI dokaz: rekurzivni CSSOM walk `.animate-fade-in-up,.slide-in-right` + `animation:none` pod prefers-reduced-motion — vzorec r398-val73-mounted.sh; ZERO-MUTACIJA].
- R399 kandidati: 1. slovarska para shimmer/bounce-subtle (×0 klicnih mest): uporabiti v UI (loading skeleti) ALI iskreno označiti kot mrtvi CSS — odločitev z lastnikom [preneseno iz R398]; 2. interaktivni btn-shine hover sweep reduced-motion odločitev [interaktivna družina kanon val 69 — zahteva EVOLVED pin odločitev z lastnikom, previdno]; 3. e2e-lib dedup [po kanonu — ni novih ×3]. ⭐ LEKCIJE R398: (1) CSS content-hash čanki NISO deterministični čez build okolja — lokalni ≠ Vercel; 'enako ime = enaka vsebina' (R354) velja za .js, NE za .css; CSS needleji se rešujejo prek ŽIVIH prod .css URL-jev iz HTML [nadgradnja LEKCIJE R397 (5)]; (2) /tmp žetveni seznam EPHEMEREN čez seje — R397 razširitve izgubljene; pred vsako era preverbo preveri seznam in po potrebi razširi z backupom [odpadni cenzus poroča iskreno, ne abort]; (3) `cmd | tail; echo $?` meri EXIT od tail, NE skripte — EXIT vedno direktno zajeti [prva dva teka 51. preverbe = EXIT=2, ne 0 — CSS needleja čakala URL-popravek]; (4) lightningcss SERIALIZIRA deklaracije v kanoničnem redu (opacity PRED animation) — minificirana oblika ≠ vrstni red v src; needle iz builda, nikoli napovedan [nadgradnja R397 (3)]; (5) varnostna analiza forwards/končno-stanje OBVEZNA pred reduced-motion razširitvijo — statično opacity:0 (.stagger-children > *) zahteva opacity:1 spremljevalca, sicer element izgine [.more-tile vzorec]. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""


def main():
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R398" in t:
        sys.exit("FAILOVEDANO: R398 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R397" not in t:
        sys.exit("FAILOVEDANO: R397 handover guard ni prepoznan (worklog stale?)")
    tail = "AGENT STARTUP RULE: razvoj > QA]."
    if not t.rstrip().endswith(tail):
        sys.exit(f"FAILOVEDANO: worklog rep ni R397 tail (guard: ...{tail!r})")
    if not t.endswith("\n"):
        t += "\n"
    nova = t + VNOS
    WL.write_text(nova, encoding="utf-8")
    print(f"OK: worklog R398 vnos pripsan ({len(VNOS)} bajtov)")


if __name__ == "__main__":
    main()
