#!/usr/bin/env python3
# r401-worklog-append.py — R401 worklog vnos (fail-closed, kanon
# r381/r383/r384/r391/r392/r394/r396/r397/r398/r400): guard = R400 vnos
# prisoten (tail fraza "AGENT STARTUP RULE: razvoj > QA]."); idempotenten:
# abort če R401 ŽE obstaja.
import pathlib
import sys

REPO = pathlib.Path("/home/z/my-project")
WL = REPO / "worklog.md"

VNOS = r"""
---

Task ID: R401 (⚠️ STALE-SUMMARY opomba #50: seja je podedovala R370 plan iz povzetka — disk resnica = R400 (30+ rund naprej; kanon KOLIZIJE #4/R323) — worklog na disku = edina resnica; R400 handover 'R401 prva naloga' + 'R401 kandidati' izvedeni. Okolje: embedded PG :5433 ŽIVO, 32/32 migracij applied; shell env DATABASE_URL=file:… preglasi .env — eksplicitni URL, .env NI mutiran [LEKCIJA R392 potrjena].)
Agent: Super Z (AI runda, Job 413422, tick 202610032219)
Task: R401 — prva naloga (prod-qa re-run 400 + DVAINPETDESETA 52. era preverba RE-RUN + TRETINPETDESETA 53. era preverba r347–r399 generacija + tek + val 73/74 POST-deploy verifikacija [obe PENDING — deploy ŠE VEDNO rate-limited]) + MANDATORY STIL val 75 (COLOR-SCHEME PARITETA — CSS-nivojska) + FEATURE TRINAJSTI STRAŽAR color-scheme disciplina + LEKCIJA R401 reg_var popravnik + register r401.tsv (×2 CSS needlejev) + window-scan 23. generacija + README + worklog + push

Work Log:
- START: fetch-first origin/main == HEAD 6abd7b1 (R400) — KOLIZIJA: NI ob startu; delovno drevo čisto; worklog R400 vnos = handover (prebran celoten; njegova 'R401 prva naloga' + 'R401 kandidati' izvedeni dobesedno). Okolje: embedded PG :5433 ŽIVO (32/32 migracij), **/api/version stamp sonda** [LEKCIJA R400 (2)]: `{"build":"2026-10-03T12:16:01.361Z"}` x-vercel-cache MISS @ 14:22 UTC — **deploy ŠE VEDNO PENDING** (R398 push 13:02:19 UTC + R400 push — Vercel Hobby rate-limit 24 h poteče šele ~12:16–13:02 UTC 4.10.); agent-browser FOREGROUND QA [kanon]: `agent-browser --help` → prod `/` → redirect /login (auth-gated, pravilno) → snapshot čist (forma E-pošta/Geslo/Prijava + UI nogica **'Zgrajeno 03.10.2026 ob 14:16:01 (Europe/Ljubljana)' = 12:16:01 UTC — STARI build, tretja neodvisna potrditev PENDING**) → console ×0 napak; direktni CDN grepi: val 71 needle ×1 ŽIVO + val 72 needle ×1 ŽIVO v f6eba6f080fd091b.css, val 73 ×0, `shimmer` ×0 v JS čankih — **iskreno stanje starega deploya, nič lažnih ŽIVO**.
- ⭐ **QA ODKRITJE — middleware 401-catch-all**: `/api/storage/reconcile` → **401 na STAREM deployu** (pričakovano 404 — r399 ruta NI deployana!); dodatni probe: `/api/definitely-nonexistent-r401-probe` → **401 z ISTIM body** `{"error":"Neavtoriziran dostop","detail":"Prijava je obvezna."}`, nonexistent page → 307, POST reconcile → 403 — **middleware auth-gate prestreže NEZMANE /api/* poti = |401 probe NI deploy-diskriminator** (isti body za žive in nežive rute); POSLEDICA: r399 'AZ spec /api/storage/reconcile|401' iz R400 handoverja bi dal **false-ŽIVO** takoj po dodaji (tudi brez deploya) — spec NAMERNO NI dodan v 53. preverbo (false-ŽIVO zaščita, kontrakt 'no fabricated data'); 3× r399 needleji ostajajo PENDING do pristanka deploya + odločitve z lastnikom; opomba ne vpliva na obstoječe 33 SERVER-REZOLUCIJ (vse = niz-v-lokalnem-server-čanku + deterministični 401 dokaz 'fail-closed vrata' — uveljavljen kanon, ne spremenjen).
- PRVA NALOGA (A): prod-qa re-run prek `r359-prod-qa-retry.sh 400` — **ZELEN ob poskusu 1** (31. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA); po REDNEM ZAKONU [LEKCIJA R400 (1)]: tek je Prepišal /tmp/r339-chunkurls.txt na 60 JS-only — **+2 ABSOLUTNA .css URL-ja re-dodana z backupom .bak-r401** [62 URL-jev, 2 .css; živi HTML = vir, kanon].
- PRVA NALOGA (B): **52. preverba RE-RUN** [r399-era-harvest.sh — bajtno] → **iskren 194/195 EXIT=2** — edini MISS = val 73 needle `.animate-fade-in-up,.slide-in-right{animation:none}` (deploy PENDING — trojno potrjeno); era kontrole R340/R341/R343/R345 ŽIVE; must_miss ×52 čisto. ⭐ metodična opomba: prvi tail-pipeline poskus je prikazal lažni EXIT=0 (`$?` = tail-ov, NE skripte) — ponovljen z redirect + echo $? = **REAL EXIT=2**; kanon: era EXIT VEDNO brez pipe.
- PRVA NALOGA (C): **TRETINPETDESETA (53.) era preverba generirana + potekla**: disk resnica prešteta IZ registrov PRED generacijo [kanon R394 (1)/R396 (6), metoda `grep -vE '^#'` + need_static filter — LEKCIJA R400 (3) spoštovana]: r347–r399 = **198** (195 + 3 r399.tsv) — handover aritmetika TOČNA; ERA_BESODE **53 TRETINPETDESETA GLASNO** [handover kanon; vzorec mape: triinpetdeset → TRETINPETDESETA, tretji-(ordinalska) oblika kot 51./52.]; ⚠️ **handover odmik GLASNO: '--dst-round 401' v handoverju je neskladen z lastno ordinalnostjo '53.'** — formula stevec = dst-347 bi zahtevala ERA_BESODE[54] (ne obstaja; fail-closed guard bi zavrl); disk-kanon vzorca (52. = r399-era-harvest.sh ↔ ključ 52) zahteva **--dst-round 400** → r400-era-harvest.sh + COMPANION r400-era-ruta-map.py; generiranje: era-clone.py --src-round 399 --dst-round 400 --expected-total 198 --dst-label "R399 object storage reconcile (§18)" --dst-chain-seg "IN r399.tsv ×3 na" [poslovna runda brez val → ekspliciten label, kanon R375]; per-registr vsota 198 ✓; **tek 1 iskren: 194/198 ŽIVO, EXIT=2** — 4 MISS = val 73 needle + 3× r399 storage/reconcile nizi (vsi PENDING na stari deploy; server-čanki NISO javno dostopni — hash-rezolucija ni možna za server nize).
- ⭐ **LEKCIJA R401 — reg_var dvočrkovni popravnik**: 1. generacija 53. preverbe = **pokvarjen bash** (`REG_A[="…"`, line 78 unexpected EOF — fail-closed ujet ob PRVEM poganjanju, ne kasneje); koren: era-clone.py `reg_var()` = `"A" + chr(65 + i - 26)` podpira SAMO A* generacijo (i 26–51); pri i=52 (r399) chr(91) = `[` — neveljaven bash identifikator; **popravljeno splošno**: `chr(65 + (i-26)//26) + chr(65 + (i-26)%26)` → AA=373…AZ=398, BA=399, BB=400, BC=401 ✓ (verificirano prek izpisa); pokvarjeni artefakti GLASNO izbrisani (nikoli uspešno pognani) + regeneracija; dokumentirano v docstringu + worklogu — nič tihega.
- PRVA NALOGA (D): **val 73 + val 74 POST-deploy verifikacija = PENDING** (deploy ŠE VEDNO rate-limited; iskreno; vzorca r398-val73-mounted.sh + MONTIRANI dokaz r396 (4) pripravljena; izvedba R402 ob stamp-gate > 13:02 UTC).
- MANDATORY STIL **val 75 — COLOR-SCHEME PARITETA** (CSS-nivojska; triaža PRED val [kanon LEKCIJA R396 (5)]: `color-scheme` = **×0 v celotnem src drevesu** — prava paritetna vrzel, ne izmišljen žeton; alternativne družine iskreno odrešene: ::selection ×0 = mrtav CSS če bi jo dodal [kanon val 74 — par z ×0 klicnimi mesti NE], checkboxi ×5 ŽE imajo izrecen accent-color [amber ×1 + navy ×4 — ločena plast]); **problem**: UA-nativne površine NE sledijo temni temi — accent-color jih NE doseže (UA-lastno krom): izbira datuma/časa **×10 mest v 5 datotekah** (type="date" ×9: crm-tab ×2 + dashboard-tab ×1 + logistics-tab ×3 + photo-tab ×2 + quote-followup ×1; type="datetime-local" ×1 logistics-tab) [koledar popup + ikona], nativni **select popup ×2** (photo-tab), **range sled ×2** (photo-tab + ar-scanner), **autofill**; brez color-scheme UA odpre SVETEL koledar popup na temni temi; **rešitev (+12 vrstic DODATIVNO v obstoječa bloka, 0 novih pravilnih blokov, 0 mutacij)**: `:root { color-scheme: light; }` = izrecna svetla **100 % determinizem** (nič UA-prislova) + `.dark { color-scheme: dark; }` = temno-nativno krom; **hybridna vrednost „light dark" PREPOVEDANA** (dvoumna — determinizem zahteva eno ključno besedo na blok); **0 novih hex** (ključni besedi, hex cenzus 7 dotaknjen); val 71 scrollbar pariteta (custom ::-webkit-scrollbar) bajtno; svetla tema izrecno OJAČANA (ne spremenjena).
- **FEATURE TRINAJSTI STRAŽAR — color-scheme disciplina**: `r401-color-scheme.test.ts` **×7 ZELENO** [(A) VAL 75 CSS anchorji — `color-scheme: light;` ×1 znotraj :root bloka + `color-scheme: dark;` ×1 znotraj .dark bloka (0 novih blokov), (B) PARITETA POPOLNOST — točno 2 razglasitvi v celotnem CSS + .dark PO :root [kaskadni vrstni red] + nič hybridne „light dark" dvoumnosti, (C) HEX CENZUS 7 dokumentiranih vrednosti — stoječi stražar prevzet (r396–r400 → r401), (D) EFEKTNE POVRŠINE ŽIVE disk resnica — type="date" ×9 per-datoteka (2/1/3/2/1) + datetime-local ×1 + select ×2 + range ×2 + **meja**: checkboxi ×5 z izrecnim accentom (amber ×1 + navy ×4) ostanejo ločena plast, (E) KOMPILIRANI CSS dokaz z mtime-staleness iskren SKIP → po svežem buildu POPOLNOST — color-scheme:light ×1 + color-scheme:dark ×1 v build CSS + val 72 guard bajtno ×1 + val 73 guard bajtno ×1 (era veriga se ne sme prelomiti), (F) MED-STRAŽARSKI roki val 72 × val 73 × val 71 bajtno (5 selektorjev + 5× animation:none + 4 anchorji + media guardov TOČNO 3 + scrollbar #475569), (G) MEJE dokumentirane — val 75 komentar (accent-color NE doseže + determinizem) + val 69 interaktivna meja bajtno + keyframes slovar cel (9 keyframes)]. KOMPLET TRINAJST varuhov: r385 + r386 + r387 + r388 + r389 + r391 + r392 + r394 + r395 + r396 + r397 + r398 + r399 + r400 + r401.
- REGISTER `scripts/qa-needles/r401.tsv` [**2 need_static CSS-nivojska needleja** — `color-scheme:dark` ×1 + `color-scheme:light` ×1 v build CSS čankih (vzorec val 71/r396: globals.css pravilo → minificirani kompilirani žeton; števca IZ BUILDA, nikoli napovedana — LEKCIJA R398 (4); **×0 v build JS = čista CSS plast** — varovalka v r401-register-write.py; 0 v HEAD 6abd7b1 git grep ×2; TODO-R401] prek `r401-register-write.py` fail-closed [build svež rm -rf .next PRVI pred register-write — LEKCIJA R396 (7); varovalki: **val 72 needle bajtno ×1 + val 73 needle bajtno ×1 v build CSS**]; ⭐ opažanje (iskreno, NI mutirano): r400.tsv nosi **TODO-R399** must_miss label [njihov copy slip iz r399-register-write vzorca] — ostane bajtno, pristala resnica; moj TODO-R401 po konvenciji; era veriga: TA registra sta v **55. preverbi (r347–r401) ≥201 = 198 + 1 (r400.tsv val 74) + 2 [R402]**; 54. preverba (r347–r400) ≥199 vmes.
- `r401-window-scan.py` **23. generacija** [naslednik r400-window-scan.py (22. gen, bajtno ohranjen); REG_DO 401 — r401.tsv ×2 CSS needlejev v DEL 2 rešena prek **BUILD-CSS fallbacka** (src pretty `color-scheme: dark;` ≠ minificirani needle `color-scheme:dark` — ista plast kot val 71); val 75 = dodativni vrstici v globals.css [NI render tarča] → TARGETS + PRIČAKOVANE_VRSTICE nespremenjene]: **EXIT=0** (304 okenskih 0 preozkih + 214 needle pinov 0 mrtvih + 150 slice-oknen + 0 vrstičnih odstopanj — disk resnica, brez mutacij).
- README prek `r401-readme-update.py` fail-closed: števec 5895/394 → **5902/395** [+7/+1: val 75 + TRINAJSTI STRAŽAR ×7] + R401 bullet NAD R400 bulletom (bajtno ohranjen) + R401 naloga/kandidati vrstici (iz R400 handoverja, izvedene) zamenjani z R402 naloga/kandidati; zgodovinski 5895/5895 v R400 bulletu ostanejo bajtno (njihova landska verifikacija).
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL) · vitest **5902/5902 (395) FULL GREEN** [R400 baza 5895/394 + mojih +7/+1; guardian (E) po svežem buildu POKRIT — nič SKIP] · build svež rm -rf .next EXIT=0 [PRVI — pred registerjem, LEKCIJA R396 (7)] · qa-round.sh 401 needles EXIT=0 [r401.tsv ×2 ŽIVO v build CSS + r400.tsv ×1 ŽIVO + r399.tsv ×3 ŽIVO [lokalni build vsebuje njihovo merged plast] + UNION r340–r401 + veriga r339→…→R227] · smoke EXIT=0 [standalone :3100: health ok + ovojnice 400 + val-3 meja ŽIVO] · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · era 52. RE-RUN iskren 194/195 EXIT=2 + era 53. tek iskren 194/198 EXIT=2 [obe PENDING — re-run ×2 do EXIT=0 = R402 ob stamp-gate] · window-scan EXIT=0 [23. gen] · r359-prod-qa-retry 400 ZELEN poskus 1 · leak-check čist [ghp_[A-Za-z0-9]{36} ×0].
- Kontrakt NIČ (era probes = samo fail-closed branje, brez pisanja); SDK/BOM/pricing/geometry core NIČ; measurement jedro NIČ [val 75 = globals.css dodativni vrstici + komentar]; viz/** ZAŠČITENO jedro nič (kanon R167); OgrajaVizija nič; 0 novih hex [utilities hex cenzus 7 dokumentiranih — stoječi stražar (C)]; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E].
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (92. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA. ⚠️ **Vercel Hobby kvota RATE-LIMITED** (še vedno aktiven; stamp 12:16:01 tudi ~2 h po R400 pushu) — val 73/74/75 + r399 needleji se NE razrešijo na produ do pristanka; R402: /api/version stamp PRED vsakim era tekom [LEKCIJA R400 (2)].
- R402 prva naloga = **STAMP-GATE najprej** (/api/version stamp > 13:02 UTC 3.10. = NOV deploy; če ŠE rate-limited: iskren PENDING — LEKCIJA R400 (2)) + ob pristanku: val 73 POST-deploy verifikacija [prod CDN needle ×1 v NOVEM .css čanku + rekurzivni CSSOM walk — vzorec r398-val73-mounted.sh; ZERO-MUTACIJA] + val 74 POST-deploy verifikacija [`shimmer rounded` ×7 v build JS čankih + MONTIRANI dokaz getComputedStyle animationName = shimmer — agent-browser produ, isti-origin reload, kanon R396 (4)] + val 75 POST-deploy verifikacija [`color-scheme:dark` ×1 v NOVEM .css čanku + MONTIRANI dokaz getComputedStyle(document.documentElement).colorScheme = 'dark' v temni temi] + r399 needleji ×3 v 53. RE-RUN [r400-era-harvest.sh bajtno; ⚠️ |401 probe NI dodan — middleware 401-catch-all bi dal false-ŽIVO; odločitev z lastnikom] + qa-round 401 prod-qa re-run [r359-prod-qa-retry.sh 401; REDNI ZAKON: prod-qa PRVI → .css razširitev → era] + **ŠTIRINPETDESETA (54.) era preverba r347–r400** [era-clone.py --src-round 400 --dst-round 401 --expected-total 199; ERA_BESODE 54 ŠTIRINPETDESETA GLASNO] + **PETINPETDESETA (55.) era preverba r347–r401** [--src-round 401 --dst-round 402 --expected-total 201; ERA_BESODE 55 PETINPETDESETA GLASNO; pokrije r401.tsv ×2].
- R402 kandidati: 1. merge-chunkurls.py hardening — UNIJA ohrani .css vnose (prod-qa re-run jih briše; kanon: hardening V NOVI skripti, zamrznjen R297 NI mutiran — odločitev z lastnikom); 2. interaktivni btn-shine hover sweep reduced-motion odločitev [interaktivna družina kanon val 69 — zahteva EVOLVED pin odločitev z lastnikom, previdno]; 3. e2e-lib dedup [po kanonu — ni novih ×3]; 4. era-clone.py reg_var enotski test [reg_var(347…420) znani nizi vs. izpeljava — prepreči ponovitev LEKCIJE R401 REG_A[]. ⭐ LEKCIJE R401: (1) **reg_var dvočrkovna generacija** — '"A"+chr(65+i-26)' podpira samo A* (i 26–51); BA+ zahteva splošno (i-26)//26+(i-26)%26; pokvarjen izhod ujet ob PRVEM poganjanju (fail-closed delo skript), popravilo GLASNO + docstring; (2) **handover ordinalnost: '--dst-round 401' + '53.' je bilo interno neskladno** — stevec = dst-347 zahteva dst=400 za 53.; disk-kanon vzorca je resnica; fail-closed guard (ERA_BESODE[54] ne obstaja) bi 401 zavrl; (3) **middleware 401-catch-all** — /api/* nezmane poti = ISTI 401 body kot žive rute → |401 API-status probe NI deploy-diskriminator na tej app; deploy-dokaz za server rute = SAMO klient-vidni čanki [val 73 stil] ALI auth-razločevalen odgovor; storage/reconcile spec odločitev z lastnikom; (4) **era EXIT brez pipe** — `bash script | tail; $?` da tail-ov exit; redirect + standalone echo $? = realni EXIT [iskren 194/195 EXIT=2, ne lažni 0]; (5) val 75 = prvi val z DODATIVNIMA vrsticama v :root/.dark bloka (0 novih blokov) — anchor testiranje 'znotraj bloka' [slice :root{→\n}] namesto 'cel blok bajtno' [bloka sta ŽE histórijsko rasla — R162 komentari]; (6) TODO-label slip opažanje [r400.tsv nosi TODO-R399] — iskreno dokumentirano, pristala resnica bajtno, NI mutirano. ISSUE #1: vsa sprejemna merila ✓; ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""


def main():
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R401" in t:
        sys.exit("FAILOVEDANO: R401 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R400" not in t:
        sys.exit("FAILOVEDANO: R400 handover guard ni prepoznan (worklog stale?)")
    tail = "AGENT STARTUP RULE: razvoj > QA]."
    if not t.rstrip().endswith(tail):
        sys.exit(f"FAILOVEDANO: worklog rep ni R400 tail (guard: ...{tail!r})")
    if not t.endswith("\n"):
        t += "\n"
    nova = t + VNOS
    WL.write_text(nova, encoding="utf-8")
    print(f"OK: R401 vnos dodan ({len(VNOS)} bajtov; worklog {len(nova)} bajtov)")


if __name__ == "__main__":
    main()
