#!/usr/bin/env python3
# r402-worklog-append.py — R402 worklog vnos (fail-closed, kanon
# r381/…/r401-worklog-append.py): guard = R401 vnos prisoten (tail fraza
# "AGENT STARTUP RULE: razvoj > QA]."); idempotenten: abort če R402 ŽE
# obstaja.
import pathlib
import sys

REPO = pathlib.Path("/home/z/repo-analysis")
WL = REPO / "worklog.md"

VNOS = r"""
---

Task ID: R402 (⚠️ STALE-SUMMARY opomba #51: prejšnja seja je zmanjkala konteksta SREDI R402 — worktree je nosil ~80 % §19 dela (nezaveščeno) + QA artefakte brez vnosa; TA seja = NADALJEVALNA inkarnacija: delo rekonstruirano, preverjeno, dopolnjeno in zavezščeno. KOLIZIJE #31–#33: NJIHOVE QA runde R400 [6abd7b1 val 74 slovar-raba + r400.tsv ×1 + r400-window-scan 22. gen] + R401 [35e6f12 val 75 color-scheme + r401.tsv ×2 + r400-era-harvest 53. preverba] + dopolnilo [8275bfe r400-commit-msg artefakt] pristale med delom prejšnje seje → kanon KOLIZIJE #4/R323/#13–#30: NJIHOVE runde = pristala resnica, MOJA preimenovana R400→R402 [register r402.tsv, testi r402-*, migraciji r402_*, window-scan 24. gen, žigi v virih]. Okolje: embedded PG :5433 ŽIVO, 34/34 migracij applied [32 + 2 r402]; shell env DATABASE_URL eksplicitni URL, .env NI mutiran.)
Agent: main-agent (Z.ai Code, lastnoročno — nadaljevalna seja po prekinitvi)
Task: R402 — issue #13 korak R170 iz §19 (INVOICE → PAYMENT → RECONCILIATION) [poslovna runda: statusni stroj + transakcijska plast + 3 API rute + 2 migraciji + UI + 43 testov] + R401 handover QA naloge [STAMP-GATE + val 73/74/75 POST-deploy MONTIRANI dokazi + era 52. RE-RUN + 53. RE-RUN + 54. + 55. preverba + prod-qa re-run 401] + register r402.tsv (×3 strežniških needlejev) + window-scan 24. gen + README + worklog + push

Work Log:
- START (nadaljevalna seja): fetch-first origin/main == HEAD 8275bfe (R401 dopolnilo) — KOLIZIJA: NI ob startu; delovno drevo = nezaveščeno §19 delo prejšnje prekinjene seje [22 mutiranih + 19 novih datotek; brez vnosa v worklog]; rekonstrukcija stanja: prebrani R401 vnos (handover) + vsi r402 artefakti; odkrite 3 NEDOKONČANE naloge: (1) žigi v virih nosijo R400 (preimenovanje nezaključeno), (2) register r402.tsv zapisan s PRESLEDKI ne TAB, (3) _prisma_migrations nosi DUPLIKATE (stara r400 imena + nova r402 imena = 36 zapisov za 34 migracij).
- ⭐ ČIŠČENJE _prisma_migrations (kanon R393/R395 precedens — preimenovanje zapisov v OBEH bazah): preverjeno, da so NOVI r402 zapisi checksum-USKLAJENI s trenutnimi migracijskimi datotekami (sha256) in da DDL resnično obstaja v obeh bazah [Payment + PaymentAllocation tabele + invoice_status_allowed CHECK + Invoice.poslanoAt]; stara r400 duplikat zapisa GLASNO zbrisana iz roksal_dev IN roksal_test [36 → 34 zapisov]; `prisma migrate status` = "Database schema is up to date!" ✓. Backfill vrstic = 0 (roksal_dev nima legacy PLACAN brez allocacij — iskreno).
- ŽIGI (preimenovanje zaključek): schema.prisma 7× R400→R402 [§19 blok komentari]; test fixture 2026-R400A→2026-R402A; r402.tsv deskriptorji R400 vrata→R402 vrata + BACKFIL-R400-LEGACY tipka→BACKFILL-R402-LEGACY [migracija sama nosi R402 — prebrano, potrjeno]; opaženo tudi: tsv deskriptorji nosijo izvorni "korak R170 iz §19" — PREVERJENO proti issue #13 "Priporočen vrstni red" tabeli [GitHub API]: **R170 = Invoice → Payment → Reconciliation ✓ PRAVILNO** (drseče oznake starejših rund — r390.tsv "R170 iz §14", R399 "R173 iz §18" — so pristala resnica, bajtno, nič mutirano; issue tabela = kanon).
- §19 IMPLEMENTACIJA (delo prejšnje seje, re-verificirano v tej): [A] FINANČNI STATUSNI STROJ src/lib/invoice-lifecycle.ts ×185 vrstic — 9 statusov [plačilna OSNUTEK→IZDAN→POSLAN→DELNO_PLACAN→PLACAN + izterjevalna IZDAN/POSLAN→ZAPADLO→OPOZORILO→IZTERJAVA]; DELNO_PLACAN/PLACAN IZPELJANA iz plačil (ročni PATCH → 409 z navodilom na /api/payments — "Ni UI-only status rules" §21); izpeljava v centih (FP varnost 0,1+0,2); povratni status po prekinitvi determinističen iz diska. [B] TRANSAKCIJSKA PLAST src/lib/payments.ts ×673 vrstic — zabeleziPlaciloVTx [plačilo + allocacije + izpeljava + auditi VSE ATOMSKO; vrata: osnutek/storno 409, prečni projekt 409, NADPLACILO 409, vsota allocacij > plačilo 400, EUR-only 400, podvojen par 400] + prekiniPlaciloVTx [PREKINJENO z razlogom — pravna sled, NE briše; PONOVNA izpeljava iz KNJIZENO ostanka; dvojna 409] + uskladiPlacila [samo-bralno poročilo + 8 anomalij — poroča, NE popravlja; kanon object-reconciliation R399]. [C] API 3 rute: POST/GET /api/payments [invoices.issue/read + resource-plast + rate-limit + Idempotency-Key exactly-once — bančni promet se NE podvoji ob retry; API ključ ZAVRNJEN — kanon R126] + GET/PATCH /api/payments/[id] [prekinitev {action:'prekini',razlog}] + GET /api/payments/reconciliation [GET-samo brez rate-limit — kanon R390]; GET /api/invoices nosi strežniško placiloZnesek. [D] BAZA 2 migraciji: Payment + PaymentAllocation [@@unique(paymentId,invoiceId)] + Invoice.poslanoAt + BACKFILL legacy PLACAN [referenca BACKFILL-R402-LEGACY, createdBy NULL — spec §33 korak 6] + CHECK invoice_status_allowed na 9 statusov [ločena migracija — precedens R395]. [E] UI invoice-manager [9-statusni STATUS_META, ZABELEŽI PLAČILO prek /api/payments, gumb Poslan, Doplata, povzetek šteje placiloZnesek] + prihodki-pdf [9 statusov + placiloZnesek + zapadlost VSA neplačena].
- ⭐ LEKCIJA R402 (1) — REGISTER STRUKTURA IZ PREKINJENE SEJE: r402.tsv je bil zapisan s PRESLEDKI namesto TAB ločili — qa-round.sh Z-STRUCT-REG varuh parse FS="\t" → presledčna oblika bi dala NAPAČEN needle (celotna vrstica) in tiho napačno verifikacijo. r402-register-write.py [fail-closed, REPO=/home/z/repo-analysis — popravek NJIOVE zastarele konstante /home/z/my-project iz r401 skripte]: deterministična rekonstrukcija vrstic (needle STRINGI morajo obstajati v trenutni vsebini — sicer abort; nič tihih zamenjav) + števca IZ svežega BUILDA [LEKCIJA R398 (4)] + 0-v-HEAD [git grep d8a76c5] + med-stražarski roki [val 72 ×1 CSS, val 73 ×1 CSS, val 74 ×7 js_client, val 75 dark/light ×1/×1 CSS] + TODO-R402 must_miss ×0. ⭐ pod-lekcija: val 74 "shimmer rounded" kanon = KLIENT čanki [.next/static/chunks ×7 v 5 datotekah — RSC strežniški dvojniki (+3 v .next/server) NE štejejo]; ločena plast js_client v pojavi(). ⭐ pod-lekcija: 2 lastni tipkarski napaki ujeti s fail-closed ("pravice"↔"pravico" v needle konstantah — needle mora biti BESEEDEN iz izvorne kode, ne iz spomina).
- REGISTER r402.tsv FINALNO: 3 need_static strežniški needleji [Beleženje plačil zahteva pravico invoices.issue. ×1 v payments app-route čanku; Prekinitev plačila zahteva pravico invoices.issue. ×1; se izpelje iz plačil — zabeleži plačilo prek /api/payments ×1 v invoices čanku] + TODO-R402 must_miss; TAB ločila + končna nova vrstica; AZ spec izpuščen NAMERNO [false-ŽIVO zaščita — NJIOVA QA ugotovitev R401: middleware 401-catch-all]; era ≥204 = 201 + mojih 3 [56. preverba = R403].
- 🎉 **STAMP-GATE: DEPLOY PRISTAL** (R401 handover prva naloga): /api/version `{"build":"2026-10-03T14:57:03.428Z"}` x-vercel-cache MISS @ 16:17 UTC — **> 13:02 UTC = NOV deploy** (Vercel Hobby kvota pretekla; R401 build 8275bfe ŽIV); NOVI .css čanki na produ: 34d933785a17edf3 + caab1e523b39b9f6 (stari f6eba6f080fd091b zamenjan) — vse pending QA naloge_odklenjene.
- PRVA NALOGA (A) — **val 73/74/75 POST-deploy MONTIRANI dokazi VSI ZELENI** [r402-val73-75-mounted.sh — agent-browser produ s prijavo, ZERO-MUTACIJA sonde + screenshot /tmp/r402-val-mounted/r402-val73-75-prod.png]: val 73 — media[prefers-reduced-motion] nosi .animate-fade-in-up,.slide-in-right {animation:...none} MONTIRAN ×1 (CSSOM walk); val 74 — .shimmer + .animate-bounce-subtle pravila MONTIRANA ×3 + badge-pulse zliti ×2 bajtno (val 72 guard); val 75 — korenColorScheme 'light' + :root{color-scheme:light} + .dark{color-scheme:dark} MONTIRANA + hibrid false (nikjer "light dark").
- PRVA NALOGA (B) — **era 52. RE-RUN EXIT=0 — 195/195 ŽIVO** [r399-era-harvest.sh bajtno]: val 73 needle `.animate-fade-in-up,.slide-in-right{animation:none}` ŽIV v NOVEM .css čanku; era kontrole R340/R341/R343/R345 ŽIVE; must_miss ×52 čisto. LEKCIJA R400 (2) stamp-gate PRED tekom spoštovana.
- PRVA NALOGA (C) — prod-qa re-run prek `r359-prod-qa-retry.sh 401` [BAŠ_ENV cd-shim kanon R376/R393(3) — zamrznjena skripta hardkodira cd /home/z/my-project = TUJA mapa] — **ZELEN ob poskusu 1** (32. runda zapored); Z2 needleji ŽIVO + Z3 v99 sync gate ŽIVO (ZERO-MUTACIJA); po REDNEM ZAKONU [LEKCIJA R400 (1)]: tek je prepisal /tmp/r339-chunkurls.txt na 60 JS-only — **+2 ABSOLUTNA .css URL-ja re-dodana z backupom .bak-r402** [62 URL-jev; NOVA .css čanka iz živega HTML — kanon].
- PRVA NALOGA (D) — **era 53. RE-RUN [r400-era-harvest.sh] iskren 195/198 EXIT=2** (44 MISS vrstice − 41 hash/server resolucij = 3 končni MISS = 3× r399 storage/reconcile needleji — AZ spec izpuščen NAMERNO, odločitev z lastnikom; iskreno PENDING, nič lažnih ŽIVO); **era 54. [r401-era-harvest.sh — ŠTIRINPETDESETA, generirana prejšnjo sejo z era-clone ERA_BESODE 54] iskren 196/199 EXIT=2** (isti 3 PENDING); **era 55. [r402-era-harvest.sh — PETINPETDESETA, ERA_BESODE 55] iskren 198/201 EXIT=2** (isti 3 PENDING; **r400.tsv val 74 shimmer ŽIV + r401.tsv color-scheme:dark/light ŽIVA na produ** ✓). ⭐ era-clone.py ERA_BESODE razširitev 54/55 [STIRIINPETDESETA/PETINPETDESETA — prejšnja seja; reg_var LEKCIJA R401 popravljena splošno (i-26)//26+(i-26)%26].
- ⭐ **DOPOLNILNI AUTH-DOKAZ ZA 3× r399 PENDING** (R401 lekcija (3) — "auth-razločevalen odgovor"): prijavljen same-origin probe GET /api/storage/reconcile → **HTTP 403 (NE 401!)** + body `{"error":"Spravo shrambe urejajo uporabniki z vodstveno vlogo"}` — **r399 needle N1 BESEEDNO v telesu**; middleware 401-catch-all bi dal 401 z DRUGAČNIM telesom ("Neavtoriziran dostop") → 403+sporočilo lahko vrne SAMO deployana ruta → **/api/storage/reconcile DOKAZANO deployana** (N1 neposredno; N2/N3 = isti route/store čank — lokalno verificirani qa-round 399, deploy sklepnjen iz N1 + iskerno označen kot sklep, ne direktna sonda). Vzorec ponudjen R403 kandidatu 1 (AZ spec kanonizacija — odločitev z lastnikom).
- VERIFIKACIJA (celotna, FOREGROUND): tsc 0 · eslint 0 (FULL) · vitest **5945/5945 (398 datotek) FULL GREEN prek 3 foreground shardov** [2219 + 2133 + 1593; R401 baza 5902/395 + mojih +43/+3 = r402-invoice-lifecycle ×20 + r402-payments-api ×12 + r402-payments-store ×11; PIN shifts ×17 starih datotek] · build svež rm -rf .next EXIT=0 [PRVI — pred registerjem, LEKCIJA R396 (7)] · qa-round.sh 402 needles **EXIT=0** [BASH_ENV cd-shim /tmp/r402-legacy-cd-shim.sh; UNION r340–r402 + veriga r339→…→R227 VSE ŽIVE — 1095 OK; brez shima: legacy veriga pade "r324-build-needles.sh No such file" — LEKCIJA R393 (3) potrjena] · smoke EXIT=0 [standalone :3100: health + login 200 + PWA + CSRF 403] · e2e EXIT=0 [ODTIS BAJTNATO IDENTIČEN pre==post r276+r281+r283+r287 — ZERO-MUTACIJA] · era 52. EXIT=0 + era 53./54./55. iskreni EXIT=2 [3× r399 PENDING — dokumentirano z AUTH-DOKAZOM] · window-scan 24. gen EXIT=0 [304 okenskih 0 preozkih + 217 needle pinov 0 mrtvih + 150 slice + 0 vrstičnih] · prod-qa re-run 401 ZELEN poskus 1 · leak-check čist [ghp_/vcp_ ×0 v virih IN v diffu].
- README prek r402-readme-update.py fail-closed: števec 5902/395 → **5945/398** [+43/+3] + R402 bullet NAD R401 bulletom (bajtno ohranjen) + R402 naloga/kandidati vrstici zamenjani z R403 naloga/kandidati.
- Kontrakt: era probes = samo fail-closed branje (ZERO-MUTACIJA); SDK/BOM/pricing/geometry core NIČ mutirano; measurement jedro NIČ; viz/** ZAŠČITENO jedro nič (kanon R167); OgrajaVizija nič; 0 novih hex; NIČ novih FNV soli; brez sheme s strani QA [ZERO-MUTACIJA E2E]; §19 delo = poslovna runda (issue #13 kanon pooblašča mutacije v poslovni domeni).
- ⏰ roksal-fallback-db POTEČE 2026-10-25 (~3 tedne) — obvestiti lastnika (93. zapis). ⚠️ žetona (GitHub + Vercel) uporabljena — priporočena ROTACIJA. ⚠️ Vercel Hobby kvota: MOJ R402 push sproži NOV deploy — če rate-limit okno (24 h od 14:57 UTC 3.10.) ŠE drži, deploy pristane ~14:57 UTC 4.10.; r402.tsv needleji so na produ ŠELE po njem (56. preverba = R403 ob stamp-gate > 14:57:03).
- R403 prva naloga = STAMP-GATE (/api/version > 14:57:03 UTC = NOV deploy z R402 plačili) + prod-qa re-run 402 [r359-prod-qa-retry.sh 402; REDNI ZAKON: prod-qa PRVI → +2 .css URL z backupom .bak-r403 → era] + ŠESTINPETDESETA (56.) era preverba r347–r402 [era-clone.py --src-round 402 --dst-round 403 --expected-total 204; ERA_BESODE 56 GLASNO; pokrije r402.tsv ×3 — ⚠️ strežniški needleji: klient-čank resolucija NE pokriva strežniške plasti → pričakovan iskren MISS + AUTH-probe vzorec (403 body) kot dopolnilni dokaz — odkrito R402] + era 53./54./55. RE-RUN [3× r399 PENDING — odkriti stanje; AZ spec odločitev z lastnikom] + val 73/74/75 + r399 + r402 needleji POST-deploy verifikacija.
- R403 kandidati: 1. AZ spec kanonizacija — auth-razločevalni probe (403 body needle) kot deploy-dokaz za strežniške needleje [r399 ×3 + r402 ×3; |401 ostaja PREPOVEDAN — false-ŽIVO; odločitev z lastnikom]; 2. merge-chunkurls.py hardening — UNIJA ohrani .css vnose (odločitev z lastnikom; zamrznjen R297 NI mutiran); 3. era-clone.py reg_var enotski test (prepreči REG_A[ ponovitev); 4. e2e-lib dedup [ni novih ×3]. ⭐ LEKCIJE R402: (1) register iz prekinjene seje = PRESLEDKI ne TAB → Z-STRUCT-REG bi tiho napačno verifikacijo — rekonstrukcija mora biti DETERMINISTIČNA (needle stringi besedeno iz izvorne kode; fail-closed ob vsakem odstopanju); (2) _prisma_migrations po preimenovanju migracij: resolve-marked novi zapisi + stari duplikati = 36 zapisov — čiščenje starih v OBEH bazah (checksum usklajenost najprej!); (3) val 74 klient-kanon: .next/static/chunks ×7 — RSC dvojniki v .next/server NE štejejo; (4) era EXIT vedno brez pipe (R398 (3)/R401 (4) potrjena dvakrat); (5) tipkarske napake v needle konstantah ujame SAMO fail-closed preverjava proti izvorni kodi (nikoli zaupaj spominu za besedilne needle). ISSUE #1: ostaja odprt, owner 'Razvoj > QA' [AGENT STARTUP RULE: razvoj > QA].
"""


def main() -> None:
    t = WL.read_text(encoding="utf-8")
    if "Task ID: R402" in t:
        sys.exit("FAILOVEDANO: R402 vnos ŽE obstaja (idempotenca)")
    if "Task ID: R401" not in t:
        sys.exit("FAILOVEDANO: R401 handover guard ni prepoznan (worklog stale?)")
    tail = "AGENT STARTUP RULE: razvoj > QA]."
    if not t.rstrip().endswith(tail):
        sys.exit(f"FAILOVEDANO: worklog rep ni R401 tail (guard: ...{tail!r})")
    if not t.endswith("\n"):
        t += "\n"
    WL.write_text(t + VNOS.lstrip("\n"), encoding="utf-8")
    print(f"OK: {WL} R402 vnos dodan ({len(VNOS)} znakov)")


if __name__ == "__main__":
    main()
